### PR TITLE
OrderedImportsFixer - PHP 7 group imports support

### PR DESCRIPTION
**Pull request by SpacePossum**

### CODE REVIEW

**Comment by SpacePossum** [comment]
replaces https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2235

**Comment by keradus** [comment]
@SpacePossum , please fix what this PR replaces, as it's linking itself ;)

**Comment by SpacePossum** [comment]
>please fix what this PR replaces, as it's linking itself ;)

: D

**Comment by keradus** [comment]
Still WIP ?

**Comment by SpacePossum** [comment]
yes, I've fixed the sort of elements within a group, but not the other bug :(

**Comment by SpacePossum** [comment]
ready for review

**Comment by keradus** [comment]
Thank you @SpacePossum.

**Pull request closed without merging**
