### PR TITLE
HeredocToNowdocFixer - works with CRLF line ending

### PR DESCRIPTION
**Pull request by dg**

### CODE REVIEW

**Comment by SpacePossum** [comment]
thanks for the PR :)
:+1:

**Comment by SpacePossum** [comment]
could you change the target of your PR to 2.2, as this is a bug fix it would be nice to have it on the lowest supported release branch

**Comment by dg** [comment]
@SpacePossum done

**Comment by SpacePossum** [comment]
thank you! :)

**Comment by keradus** [comment]
Thank you @dg.

**Pull request merged**
