### PR TITLE
PhpdocTypesOrderFixer - Improve nested types support

### LINKED ISSUE #5850: PhpdocTypesOrderFixer false positive
## Bug report

PHP version: 7.4.16
PHP CS Fixer version: 3.0.2
the command used to run PHP CS Fixer: `vendor/bin/ecs check` (using symplify/easy-coding-standard)
the configuration (file) you used: configured by ECS but it's not relevant in this case

### Code snippet that reproduces the problem

before running PHP CS Fixer:

```php
	/**
	 * @return Generator<int, Promise<mixed>, mixed, Identity>
	 */
	private function getEntranceId(RealtyRegistrationProcessId $processId): Generator
```

unexpected change made by PHP CS Fixer:

```php
	/**
	 * @return Generator<int, Promise<mixed>|, mixed, Identity>
	 */
	private function getEntranceId(RealtyRegistrationProcessId $processId): Generator
```

expected result: no change

### PR DESCRIPTION
**Pull request by julienfalque**
Fixes #5850, #5921 and replaces #5919. It also improves nested union types support.

### CODE REVIEW

**Comment by drupol** [comment]
I tested this branch on a project and I can't wait for this to be merged.

What's left to do ? I might dedicate some time to get this in asap! Thanks

**Comment by julienfalque** [comment]
Maybe more review would be nice to be more confident this won't break things, any help is welcome :)

@keradus did you review this fully?

**Comment by keradus** [comment]
unfortunately not at all, was focusing on PHP8.1/Symfony6 reviews. maybe someone else can give this PR a try?

**Comment by julienfalque** [comment]
@kubawerlos already did. Given that several people reported the changes in this PR fixed the issue for them, I consider this can be merged.

**Comment by SpacePossum** [comment]
@julienfalque please resolve the conflict, squash and than tag this PR RTM when the tests are green, thanks :+1:  : )

**Comment by SpacePossum** [comment]
Thank you @ruudk.

**Pull request merged**
