### PR TITLE
playground

### PR DESCRIPTION
**Pull request by keradus**

### CODE REVIEW

**Comment by keradus** [comment]
wow
> https://travis-ci.org/FriendsOfPHP/PHP-CS-Fixer/builds/262021366#L514
> Failed to clone the git@github.com:keradus/php-coveralls.git repository, try running in interactive mode so that you can enter your GitHub credentials

**Comment by julienfalque** [comment]
What's the status of this PR?

**Comment by julienfalque** [comment]
ping @keradus

**Comment by SpacePossum** [comment]
I'm closing this one as I think it is out dated, if there is anything left please re-open or create a new PR :)

**Pull request closed without merging**
