### PR TITLE
.gitignore - add cache file

### PR DESCRIPTION
**Pull request by gharlan**

### CODE REVIEW

**Comment by keradus** [comment]
When you run `php php-cs-fixer fix` no `.php_cs.cache` would be created!

**Comment by GrahamCampbell** [comment]
It would on the master branch though. This is missing only on the master branch, right?

**Comment by SpacePossum** [comment]
:+1: 

https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1017 ;)

**Comment by gharlan** [comment]
> When you run php php-cs-fixer fix no .php_cs.cache would be created!

Hmm, you're right, we are not using cache in this project.
The file was created by a misconfigured php-cs-fixer "tool" in my IDE.

**Pull request closed without merging**
