### PR TITLE
boost .travis.yml file

### PR DESCRIPTION
**Pull request by keradus**
Beceause nobody likes slow CI...

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Hmmm, though PHP 5.4 has different execution paths to 5.6 in some places, which is why coverage was running on every vesion, because we have version specific execution paths.

**Comment by keradus** [comment]
We execute more path on newer and newer versions.
Do we indeed do sth only in old versions?

**Comment by GrahamCampbell** [comment]
Well some paths are only executed on old versions?

**Comment by keradus** [comment]
like?

**Comment by GrahamCampbell** [comment]
```
        if (
            '' === $old
            || !$fileCacheManager->needFixing($this->getFileRelativePathname($file), $old)
            // PHP 5.3 has a broken implementation of token_get_all when the file uses __halt_compiler() starting in 5.3.6
            || (PHP_VERSION_ID >= 50306 && PHP_VERSION_ID < 50400 && false !== stripos($old, '__halt_compiler()'))
        ) {
            if ($this->eventDispatcher) {
                $this->eventDispatcher->dispatch(
                    FixerFileProcessedEvent::NAME,
                    FixerFileProcessedEvent::create()->setStatus(FixerFileProcessedEvent::STATUS_SKIPPED)
                );
            }

            return;
        }
```

**Comment by keradus** [comment]
Then, 5.3, 5.6 and hhvm should be enought?

**Comment by GrahamCampbell** [comment]
Yes, though do we actually have coverage for that anyway? if not, then we don't need 5.3.

**Comment by keradus** [comment]
For now we have. Question is do we want to collect 5.3 (or 5.5) coverage on Travis.
For now we do not collect it for php7 (no support fod xdebug)

**Comment by GrahamCampbell** [comment]
> For now we do not collect it for php7 (no support fod xdebug)

You don't need xdebug. On php 7, you can collect coverage using phpdbg and phpunit 5.

**Comment by GrahamCampbell** [comment]
Travis only has an old vesion of phpunit though, and I don't think phpdbg is available - I've never tried.

**Comment by keradus** [comment]
updated to run coverage on every available php versions, but still a bit faster ;)

**Comment by GrahamCampbell** [comment]
:+1:

**Pull request closed without merging**
