### PR TITLE
Add SingleLineThrowFixer

### PR DESCRIPTION
**Pull request by kubawerlos**
Resolves https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/3988

@nicolas-grekas should we have this as part of `@Symfony` ruleset?

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
It don't the rules of the project regarding updating existing rulesets, but we would definitely enable this one the Symfony repo. Thanks for working on it!

**Comment by julienfalque** [comment]
:+1: for adding the rule to the `@Symfony` ruleset.

**Comment by SpacePossum** [comment]
can you add these test case:

```php
<?php throw new Exception( // 0
                "Foo", // 1
                0 // 2
            ); //3
```

```php
<?php throw new Exception(  0 /*
1
2
3
*/
  /*4*/              "Foo", /*5*/
/*6*/0 /*7*/);
```

**Comment by keradus** [comment]
(rebased + fix small issues causing CI to fail)

**Comment by keradus** [comment]
Thank you @kubawerlos.

**Pull request merged**
