### PR TITLE
NoUnneededControlParenthesesFixer - Remove useless braces after case and default

### PR DESCRIPTION
**Pull request by SpacePossum**
closes https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/2798
closes https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/1540

not sure we want to add a configuration option to enable this behavior?

ping @nazarhussain

### CODE REVIEW

**Comment by julienfalque** [comment]
I think this behavior was not expected from initial version of the fixer, so I would consider this a new feature which would require a configuration option. The option may be enabled by default in 3.0 though.

Would it be hard to support removing these unneeded braces anywhere in the code (instead of in `case`s only) like mentioned in https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/1540#issuecomment-300417299 ?

**Comment by nazarhussain** [comment]
@SpacePossum @juliendufresne May be I am wrong, but the configuration option already exists `no_unneeded_control_parentheses`. Is it not good enough for this feature?

**Comment by SpacePossum** [comment]
@nazarhussain the current option is used for `case (1): ` to `case 1:` fixing. We could reuse the option for the new fixing as well. 

>I think this behavior was not expected from initial version of the fixer, so I would consider this a new feature which would require a configuration option. The option may be enabled by default in 3.0 though.

fine and fine by me

>Would it be hard to support removing these unneeded braces anywhere in the code (instead of in cases only) like mentioned in #1540 (comment) ?

that is a bit of work because;
- `{` can mean a lot of things in PHP (like `$a{1}`, `$a{$a}`, `if (){}`, etc.)
- not all useless `{` should be removed, for example in the following code the `{` pair is useless but a lot people like them anyway ;)
  ```php
      if ($a){echo 2;} 
      echo 1;`
  ```

**Comment by julienfalque** [comment]
> not all useless { should be removed, for example in the following code the { pair is useless but a lot people like them anyway ;)
> ```php
>    if ($a){echo 2;} 
>    echo 1;`
> ```

Of course :p

Maybe detecting whether the `{` is preceded by a control structure (or part of a variable variable, e.g. `${$a}`) should be enough? If not done in this PR, would this be considered a bugfix or a new feature?

**Comment by SpacePossum** [comment]
I would say new feature, but not a BC breaking one so on 2.x line ;)

**Comment by keradus** [comment]
1. fixer is suppose to remove useless parenthesis. those are `(`, not `{`. why to remove later?
2. this is behaviour change of existing fixer, for that it's bc breaker.

either it's a new fixer or new, disabled by default, option for existing fixer.
imo, new fixer.

**Comment by SpacePossum** [comment]
new fixer could work;
so we want a black or white list for tokens before `{`?

Blacklist is prop. easiest;
* `{`
* `;`
* `<?php`

not sure this will be safe if the code being fixed is used as an include though

**Comment by keradus** [comment]
> not sure this will be safe if the code being fixed is used as an include though

what does it change? result of php file is same regardless it's executed directly or included.

**Comment by keradus** [comment]
@SpacePossum ? was that intentional close ?

**Pull request closed without merging**
