### PR TITLE
Fix URL to Doctrine Annotations documentation

### PR DESCRIPTION
**Pull request by astehlik**

### CODE REVIEW

**Comment by SpacePossum** [comment]
Hi and thanks for taking the time to propose this improvement!

Currently the documentation gets generated from the various source files. For this case, please also update this file:
>https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.1.0/src/RuleSet/Sets/DoctrineAnnotationSet.php#L40

after that we'll run the tests/CI and if all green will merge it :+1:

**Comment by astehlik** [comment]
Thank you for the hint :)

I have updated the URL in the DoctrineAnnotationSet source now, too.

**Comment by SpacePossum** [comment]
thanks so much! :)
can I ask you one more thing, can you maybe rebase and squash the commits?

**Comment by astehlik** [comment]
No problem at all. The branch is now rebased and the commits were sqashed.

**Comment by SpacePossum** [comment]
Thank you @astehlik.

**Pull request merged**
