### PR TITLE
NoUselessSprintfFixer - Introduction

### PR DESCRIPTION
**Pull request by SpacePossum**

### CODE REVIEW

**Review by kubawerlos — CHANGES_REQUESTED** [review]
See failing testes in: https://github.com/kubawerlos/php-cs-fixer-custom-fixers/pull/426

WDYT about test case as this:
```

        yield [
            '<?php
                $foo = "Foo";',
            '<?php
                $foo = sprintf(
                    "Foo"
                );',
        ];
```

**Comment by SpacePossum** [comment]
I think fixer should've on responsibility, in this case dealing with the useless `sprintf`. There can be other fixers dealing with the spacing and I think the priorities work for that.
Having a generic way of remove a complete line sounds good to me, but that is it.
After spending a lot of time checking all the fixers for PHP8 I feel some have to much logic which makes it hard to maintain and support.

**Comment by kubawerlos** [comment]
Fair enough, then just please fix the non-whitespace related e.g. by adding a case:
```php

        yield 'very simple' => [
            '<?php foo";',
            '<?php sprintf("foo");',
        ];
```
and this is RTM for me.

**Comment by SpacePossum** [comment]
is that different than https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5280/files#diff-e75b6e307967808e190ad48750412d99b02fa732653680f902c6dd8834a8c0e6R37 ?

**Comment by SpacePossum** [comment]
good catch, tests added :+1:

**Review by kubawerlos — APPROVED** [review]

**Pull request merged**
