### PR TITLE
PHIVE: save phar.io key and skip keyserver

### PR DESCRIPTION
**Pull request by Slamdunk**
This is getting annoying:

immagine

### CODE REVIEW

**Comment by Slamdunk** [comment]
Ping @ktomk

**Comment by ktomk** [comment]
Last summary I collected about keyservers went into this comment:

https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4615#issuecomment-548171321

having two references. The first one has a bash fragment:

	for server in ha.pool.sks-keyservers.net \
				  hkp://p80.pool.sks-keyservers.net:80 \
				  keyserver.ubuntu.com \
				  hkp://keyserver.ubuntu.com:80 \
				  pgp.mit.edu; do
		gpg --keyserver "$server" --recv-keys \
			B42F6819007F00F88E364FD4036A9C25BF357DD4 \
			&& break || echo "Trying new server..."
	done

there are also other bash examples in that first one.

The other reference is to a list of keyservers in the Phive utility which also does rotate as it runs into the same problem:

    'hkps.pool.sks-keyservers.net',
    'keys.fedoraproject.org',
    'keyserver.ubuntu.com'

So that is the data gathered that time. Having a shell script fragment like the first one should do it, if not even `gpg` supports having multiple key-server hostnames via CLI args (I think this would be worth to clarify before making use of a for-loop in the shell script).

Annoying ... I can understand that, last time when we had this, `travis_retry` was sufficient and I just realized tonight by the ping from 31th of January 4 days ago that this is an ongoing issue.

@Slamdunk Have you considered multiple keyservers as an alternative way to address this?

**Comment by Slamdunk** [comment]
@ktomk thank you very much for your effort to detect an effective solution.

At the cost of sounding not much worried about security, I would like to ask: do we really really really really really need to fetch the key from a keyserver?

I mean, suppose everything goes wrong:

1. We download the tool+asc from a compromised website
1. The key this PR saved is compromised
1. We download a compromised version of `composer-normalize` and `composer-require-checker`

Very unlikely scenario, but then... so? What could go wrong? These are build stages in a short-lived public disposable containters for a MIT licensed FOSS. Maybe someone could leak [this](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.16/.travis.yml#L149) key? What else?

Don't get me wrong, PHIVE addresses an important goal in PHP ecosystem, but in my point of view, in this particular case, reliable and quick builds are more useful than perfectly secured ones.

Relying on external resources in builds is a paint-in-the-***, I've seen too many builds (hence: developers hours and electricity) wasted for timing-out resources.

In my experience, gpg keyservers are one of the least reliable external resources ever, sadly :\

**Comment by ktomk** [comment]
@Slamdunk So I guess the answer to my question about if you considered it an alternative is a no (or towards it), so for me not seeming lazy I provided it now. I couldn't find an issue report, so have re-used this pull-request number instead to reference the problem.

For me this is more about reproducibility and to secure the process. Especially with `phive` this would break the whole supply chain.

Also it's worth to keep in mind that the script can be run supervised, and that most likely is on some other users system which is not a throw-away system.

This is just my 2 cents, there was yet no discussion by the project on how this should be addressed AFAIK.

**Comment by keradus** [comment]
Thank you for all the work @Slamdunk !
I like the discussion that happen here and in #4784 and I decided to merge the later.

I do not have a stron opionion about which PR is better, but definitely not-merging anything is worse than merging any of them.

Big thanks for working on the topic!

**Pull request closed without merging**
