### PR TITLE
TokenizerLintingResult - expose line number of parsing error

### LINKED ISSUE #2075: New linter doesn't show the line number
The php 7 tokenizer linter doesn't show the line number it occurred on.

### PR DESCRIPTION
**Pull request by keradus**
closes #2075

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
That doesn't work?

**Comment by GrahamCampbell** [comment]
That gives you the line in our code that threw the error.

**Comment by keradus** [comment]
I don't think so. Code proves the other way

**Comment by GrahamCampbell** [comment]
Oh, cool. I guess I was a bit drunk when I tested this then. That was the reason I closed my last PR.

**Comment by GrahamCampbell** [comment]
👍 then to the idea, but I'd prefer it if we slightly matched PHP's format more closely - doesn't have to be exactly the same tho. :P

**Comment by GrahamCampbell** [comment]
How about this?

```php
throw new LintingException(
    sprintf('%s on line %d.', $this->error->getMessage(), $this->error->getLine()),
    $this->error->getCode(),
    $this->error
);
```

**Comment by keradus** [comment]
doesn't matter...

**Comment by SpacePossum** [comment]
:+1:  looking good :)

**Comment by GrahamCampbell** [comment]
> doesn't matter...

Definitely does. The message you have there is horrible IMO.

**Comment by keradus** [comment]
it's copy-pasted from `php -l file` on php7

**Pull request merged**
