### PR TITLE
Drop php-cs-fixer/accessible-object dependency

### PR DESCRIPTION
**Pull request by keradus**

### CODE REVIEW

**Review by kubawerlos — APPROVED** [review]

**Comment by keradus** [comment]
issue with different packages providing some kind of PHPUnit polyfill with some kind of different autoloading issue? can't tell, yet:

using v1.x of composer/semver - crashing:
```
ker@dus:~/github/PHP-CS-Fixer λ git du
diff --git a/composer.json b/composer.json
index f84930da8..df2a4cd29 100644
--- a/composer.json
+++ b/composer.json
@@ -17,7 +17,7 @@
         "php": "^5.6 || ^7.0",
         "ext-json": "*",
         "ext-tokenizer": "*",
-        "composer/semver": "^1.4 || ^2.0 || ^3.0",
+        "composer/semver": "^1.7.1 || ^2.0 || ^3.0",
         "composer/xdebug-handler": "^1.2",
         "doctrine/annotations": "^1.2",
         "php-cs-fixer/diff": "^1.3",
@@ -52,7 +52,10 @@
         "symfony/polyfill-mbstring": "When enabling `ext-mbstring` is not possible."
     },
     "config": {
-        "sort-packages": true
+        "sort-packages": true,
+        "platform": {
+            "php": "5.6.40"
+        }
     },
     "autoload": {
         "psr-4": {
ker@dus:~/github/PHP-CS-Fixer λ composer update --prefer-lowest -q
ker@dus:~/github/PHP-CS-Fixer λ vendor/bin/phpunit 
PHP Warning:  Cannot declare class \PHPUnit\Framework\Error\Warning, because the name is already in use in /home/d.ruminski/github/PHP-CS-Fixer/vendor/symfony/phpunit-bridge/bootstrap.php on line 96
PHP Warning:  Cannot declare class \PHPUnit\Framework\ExpectationFailedException, because the name is already in use in /home/d.ruminski/github/PHP-CS-Fixer/vendor/symfony/phpunit-bridge/bootstrap.php on line 96
PHP Warning:  Cannot declare class \PHPUnit\Framework\TestCase, because the name is already in use in /home/d.ruminski/github/PHP-CS-Fixer/vendor/symfony/phpunit-bridge/bootstrap.php on line 96
PHP Warning:  Cannot declare class \PHPUnit\Runner\Version, because the name is already in use in /home/d.ruminski/github/PHP-CS-Fixer/vendor/symfony/phpunit-bridge/bootstrap.php on line 96
^C
```

using v3.x of composer/semver - all good:
```
ker@dus:~/github/PHP-CS-Fixer λ git du
diff --git a/composer.json b/composer.json
index f84930da8..59cbc7047 100644
--- a/composer.json
+++ b/composer.json
@@ -17,7 +17,7 @@
         "php": "^5.6 || ^7.0",
         "ext-json": "*",
         "ext-tokenizer": "*",
-        "composer/semver": "^1.4 || ^2.0 || ^3.0",
+        "composer/semver": "^3.0",
         "composer/xdebug-handler": "^1.2",
         "doctrine/annotations": "^1.2",
         "php-cs-fixer/diff": "^1.3",
@@ -52,7 +52,10 @@
         "symfony/polyfill-mbstring": "When enabling `ext-mbstring` is not possible."
     },
     "config": {
-        "sort-packages": true
+        "sort-packages": true,
+        "platform": {
+            "php": "5.6.40"
+        }
     },
     "autoload": {
         "psr-4": {
ker@dus:~/github/PHP-CS-Fixer λ composer update --prefer-lowest -q
ker@dus:~/github/PHP-CS-Fixer λ vendor/bin/phpunit 
PHPUnit 5.7.27 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.4.3
Configuration: /home/d.ruminski/github/PHP-CS-Fixer/phpunit.xml.dist

Testing 
.............................................................
```

**Review by GrahamCampbell — APPROVED** [review]

**Comment by GrahamCampbell** [comment]
What is the status of this after a rebase?

**Comment by keradus** [comment]
let's see

**Comment by GrahamCampbell** [comment]
Gah. Could just drop PHP 5.6. :trollface:

**Comment by GrahamCampbell** [comment]
Looks like basically nobody is using PHP 5.6 and 7.0:

image

image

image

**Comment by GrahamCampbell** [comment]
So we could just drop PHP 5.6 and 7.0 on master, and re-target this PR at master?

**Comment by keradus** [comment]
change of php support was already discussed and is not planned for 2.15

moving the PR to draft mode to recover it at proper stage.

**Pull request closed without merging**
