### PR TITLE
Added a fixer to add a New Line before phpdoc (black list). 

### PR DESCRIPTION
**Pull request by daiglej**
Added a fixer to add a New Line before phpdoc. 

Will not add a new line before:
- File level doc-block.
- First doc-block inside curly brackets.
- Consecutive Inline @var

Example of consecutive inline @var :

```
<?php

/** @var SomeClass $foo */
/** @var ComeOtherClass $bar */
list($foo, $bar) = SomeWeird::factory($input);
```

### CODE REVIEW

**Comment by keradus** [comment]
For first to minutes it looks overcomplicated.
Why not add missing new line if the character before docblock is `;` ?

**Comment by daiglej** [comment]
Sorry for the long answer, it's been a very busy week.
Yes I think that should do it, I will post an update soon.

**Comment by daiglej** [comment]
So I created an alternate version here : https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2263

In ended up being not that much simpler, since I soon realized I wanted a blank line between the file doc and the class doc, but not between 2 consecutive inline @var

**Comment by keradus** [comment]
Closing in fav. of #2263

**Pull request closed without merging**
