### PR TITLE
CombineConsecutiveIssetsFixer - Improve description

### PR DESCRIPTION
**Pull request by kubawerlos**
This will make descriptions unified and more readable

### CODE REVIEW

**Comment by keradus** [comment]
shouldn't any of this go to 2.2 ?

**Comment by kubawerlos** [comment]
it could, not sure if should, as it's clean up I was thinking about it to be in the default branch

**Comment by keradus** [comment]
all possible bugfixes/docs/refactoring/cleanups shall go to oldest supported branch, which is 2.2

**Comment by kubawerlos** [comment]
ok, so I've extracted [this](https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3408) and changed this to point ot 2.9.

**Comment by keradus** [comment]
please rebase

**Comment by GrahamCampbell** [comment]
Technically, this title should read `Improving fixers' descriptions` with an apostrophe. :P

**Comment by keradus** [comment]
Thank you @kubawerlos.

**Pull request merged**
