### PR TITLE
DocBlock\Tag - keep the case of tags

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Tags should be case sensitive. This was my bad when I wrote this stuff originally. Sorry.

This PR will also be a prerequisite for a risky contrib level fixer that will look for things like `@Param` and fix to `@param`.

### CODE REVIEW

**Comment by keradus** [comment]
:+1:

**Comment by gharlan** [comment]
:+1:

**Comment by keradus** [comment]
BTW, what do you think @GrahamCampbell about using external docblock parser like `phpDocumentor\Reflection\DocBlock` or `Sami\ParserDocBlockParser` (build on first one) ?
Then we won't need to maintain all crazy variants of phpdocs ourselves

**Comment by GrahamCampbell** [comment]
Because external parsers don't offer the things we want, and implement a load of things we don't need. That's why I didn't use them originally.

**Comment by stof** [comment]
@keradus the issue is that PHP-CS-Fixer actually needs info about formatting, to be able to fix it.

**Comment by keradus** [comment]
OK, just the thought to reduce possible bugs. Thank you both for quick answer ;)

**Comment by keradus** [comment]
Thank you @GrahamCampbell.

**Pull request closed without merging**
