### PR TITLE
YodaStyleFixer - handling equals empty array

### PR DESCRIPTION
**Pull request by kubawerlos**
@SpacePossum is this bug?

### CODE REVIEW

**Comment by SpacePossum** [comment]
I would say so yeah :)

**Comment by SpacePossum** [comment]
@kubawerlos 

please add these test (these pass btw :+1:)

```
            [
                '<?php return [ [ [ ] ] ] === $array;',
                '<?php return $array === [ [ [ ] ] ];',
            ],
            [
                '<?php return array(/* foo */) === $array;',
                '<?php return $array === array(/* foo */);',
            ],
            [
                '<?php return [
                    // 1
                ] === $array;',
                '<?php return $array === [
                    // 1
                ];',
            ],
```

**Comment by kubawerlos** [comment]
Let's merge https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4934 first and I will update this one, so we have no conflicts.

**Comment by SpacePossum** [comment]
:+1:  I've merged it @kubawerlos

**Comment by kubawerlos** [comment]
@SpacePossum updated, but I've added only 2 of your 3 tests, without this one:
```php
          [
                '<?php return [ [ [ ] ] ] === $array;',
                '<?php return $array === [ [ [ ] ] ];',
          ],
```
but I've added these:
```php

            ['<?php return $p == array(array());'],
            ['<?php return $p == [[]];'],
```

Isn't this more consistent with these:
```php

            ['<?php return $p == array(2);'],
            ['<?php return $p == array("2");'],
            ['<?php return $p == array(TWO);'],
```

WDYT?

**Comment by SpacePossum** [comment]
@kubawerlos yeah looks good to me, nice to see the `[[]]` edge case handled as well :)

**Comment by SpacePossum** [comment]
Thank you @kubawerlos.

**Pull request merged**
