### PR TITLE
NoSuperfluousPhpdocTagsFixer - Remove for typed properties (PHP 7.4)

### PR DESCRIPTION
**Pull request by ruudk**
See https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4713

This one targets 2.15. I hope I did it correctly. If not, then https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4713 still has the 2.16 version.

### CODE REVIEW

**Comment by ruudk** [comment]
Honestly, I don't understand why you try to support 2 versions. Look at all the work we had to go through to get here. Target master, target 2.16, target 2.15.

**Comment by SpacePossum** [comment]
Thank you @ruudk.

**Comment by SpacePossum** [comment]
I know it was a struggle and you got the worst of our support chain. Having a LTS with bug fixes releases and other supported versions with new features sometimes causing all this work as the branches start to differ a lot... 

Thanks for doing all the work, it is much appreciated!

**Comment by ruudk** [comment]
Thanks for merging!

**Comment by mssimi** [comment]
Excuse me, why isn't this feature in 2.16?

**Comment by SpacePossum** [comment]
Hi @mssimi ,
The changes are merged upstream, you can see these here on 2.16.4 for example;
https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.16.4/src/Fixer/Phpdoc/NoSuperfluousPhpdocTagsFixer.php

If it doesn't work for you can you maybe make a new issue/bug report here? Thanks!

**Pull request merged**
