### PR TITLE
Make some more classes final

### PR DESCRIPTION
**Pull request by ntzm**
Not Config and Finder as they are extension points.

### CODE REVIEW

**Comment by keradus** [comment]
-0
+1 when we will have nice rule for that

**Comment by kubawerlos** [comment]
Rule or AutoReview test that all classes must be final, except listed ones?

**Comment by keradus** [comment]
Rule > AutoReview
all except listed one is too demanding, nice reasoning is good to have, i won't provide full spec now, but Doctrine ORM classes shall not be final

**Comment by ntzm** [comment]
#3923

**Comment by SpacePossum** [comment]
I think this is RTM TBH

**Comment by SpacePossum** [comment]
Thank you @ntzm.

**Comment by ntzm** [comment]
Thanks! I'll be contributing again soon hopefully :crossed_fingers:

**Pull request merged**
