### PR TITLE
PhpUnitDedicateAssertFixer - fix typos in is_numeric and is_resource

### PR DESCRIPTION
**Pull request by ivan1986**
fix is_*e2808b*

### CODE REVIEW

**Comment by keradus** [comment]
nice
how did you found it ?

**Comment by ivan1986** [comment]
@keradus bitbucket diff and colleague like write all options in config and not use default

**Comment by julienfalque** [comment]
Github diff shows words replaced by the same words, what changed exactly?

**Comment by ivan1986** [comment]
screenshot_20170316_114049
in gitk

**Comment by ivan1986** [comment]
`
0x00000160: 20747275 652C0A2D 20202020 20202020      true,.-
0x00000170: 2769735F E2808B6E 756D6572 69632720     'is_...numeric'
0x00000180: 3D3E2074 7275652C 0A2B2020 20202020     => true,.+
0x00000190: 20202769 735F6E75 6D657269 6327203D       'is_numeric' =
`

E2808B

**Comment by julienfalque** [comment]
Yay, invisible zero width spaces 😑.

**Comment by SpacePossum** [comment]
nice find! :) 
I wonder how it got in there in the first place

**Comment by julienfalque** [comment]
I already faced similar issues. These zero width spaces are rarely (never?) intended and often the result of an odd keyboard combination. Would a fixer that removes them make sense?

**Comment by keradus** [comment]
Please create dedicated PR/issue.

**Comment by keradus** [comment]
Thank you @ivan1986.

**Comment by keradus** [comment]
merged into 2.1 instead of 2.2

**Comment by SpacePossum** [comment]
:+1: thanks @ivan1986 :)

**Pull request closed without merging**
