### PR TITLE
Bug with duplicating header comment

### PR DESCRIPTION
**Pull request by kubawerlos**
Fix for https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/2590 and https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/3467.

### CODE REVIEW

**Comment by julienfalque** [comment]
At first glance, this looks like a partial implementation of what @BackEndTea proposed in #3468, right? If so, do you want to go further here?

**Comment by julienfalque** [comment]
ping @kubawerlos :)

**Comment by kubawerlos** [comment]
It might help in https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3468 yet this focuses only on HeaderCommentFixer - the header placing will need further discussion if we want also add third location.

**Comment by keradus** [comment]
if it fixes 2590, shouldn't we add integration test for `declare_strict_types and header_comment` (it may be `misc` itest, not necessary `priority` one) ?

**Comment by kubawerlos** [comment]
@keradus not sure about integration test as this only makes sure comment won't be duplicated. Best case I created is:
```
--TEST--
Integration of fixers: declare_strict_types,header_comment.
--RULESET--
{"declare_strict_types": true, "header_comment": {"header": "Foo header"}}
--REQUIREMENTS--
{"php": 70000}
--EXPECT--
<?php



declare(strict_types=1);

/*
 * Foo header
 */

namespace Bar;

class Baz
{
}

--INPUT--
<?php

/*
 * Foo header
 */

declare(strict_types=1);

namespace Bar;

class Baz
{
}

```

It looks like "declare_strict_types" is not used there.

**Pull request closed without merging**
