### PR TITLE
Use lowercase mikey179/vfsStream in composer.json

### LINKED ISSUE #4324: Composer mumbles about mixed case mikey179/vfsStream
$ composer --version
Deprecation warning: require-dev.mikey179/vfsStream is invalid, it should not contain uppercase characters. Please use mikey179/vfsstream instead. Make sure you fix this as Composer 2.0 will error.
Composer version 1.8.4 2019-02-11 10:52:10

### PR DESCRIPTION
**Pull request by lolli42**
fixes #4324

### CODE REVIEW

**Comment by kubawerlos** [comment]
Can you point to `2.12` branch?

**Comment by prisis** [comment]
But this https://github.com/mikey179/vfsStream/pull/174/files should be merged first and packagist should be updated

**Comment by GrahamCampbell** [comment]
> But this mikey179/vfsStream/pull/174/files should be merged first and packagist should be updated

This is actually not necessary. This is evident because composer succeeded on travis...

This PR should be merged straight away.

**Comment by kubawerlos** [comment]
> composer succeeded on travis...

This can be used as well as argument to not merge it yet.

**Comment by GrahamCampbell** [comment]
> This can be used as well as argument to not merge it yet.

I don't see how? Composer succeeding on travis means that there is no 3rd party blocker.

**Comment by kubawerlos** [comment]
Because composer is succeeding on travis without this change.

**Comment by GrahamCampbell** [comment]
Composer 2.0 would be failing though.

**Comment by kubawerlos** [comment]
Yeah, in [2021](https://github.com/composer/composer/milestones/2.0) ;)

No need to hurry with this one, they will rename repo sooner than Composer 2.0 will be released.

**Comment by SpacePossum** [comment]
@lolli42 can you rebase this PR on 2.12? if not we can proceed merging https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4367 as alternative I think

**Comment by GrahamCampbell** [comment]
> No need to hurry with this one, they will rename repo sooner than Composer 2.0 will be released.

My point is that they don't need to rename the repo. The name is already lowercase, regardless of what they named it in their composer.json. The packagist registry considers is lowercase. This is exactly why there was never a third-party blocker here.

**Comment by SpacePossum** [comment]
Thank you @lolli42.

**Pull request merged**
