### PR TITLE
Added more header comment tests

### PR DESCRIPTION
**Pull request by GrahamCampbell**
The first two are failing.

### CODE REVIEW

**Comment by keradus** [comment]
Shouldn't the doc be injected between `<?php` and `namespace` ?

**Comment by GrahamCampbell** [comment]
No.

**Comment by GrahamCampbell** [comment]
I also tried with those as a test case too, and that failed.

**Comment by GrahamCampbell** [comment]
It put newlines in the wrong place.

**Comment by GrahamCampbell** [comment]
If someone wants to put the namespace decoration on the same line as the opening php tag, then we should allow them to do that. That freedom is just as important as being able to choose to use `/*` or `/**`.

**Comment by keradus** [comment]
any chances to have that finished?

**Comment by GrahamCampbell** [comment]
Sorry, got no time today.

**Comment by keradus** [comment]
ping @GrahamCampbell

**Comment by keradus** [comment]
ping @GrahamCampbell

**Comment by keradus** [comment]
ping @GrahamCampbell

**Comment by GrahamCampbell** [comment]
It might be an idea for someone else to take over fixing this since I don't have the time right not.

**Comment by keradus** [comment]
Closing due to merge of #1949

**Comment by GrahamCampbell** [comment]
Can we add these tests too please?

**Comment by keradus** [comment]
as it was refactored on 2.x, check if those tests are there, if not - feel free to send a PR for master branch

**Pull request closed without merging**
