### PR TITLE
EspaceImplicitBackslashesFixer - Fix escaping multiple backslashes

### PR DESCRIPTION
**Pull request by julienfalque**
/cc @Slamdunk

### CODE REVIEW

**Comment by julienfalque** [comment]
Actually I find these ones pretty simple, but I don't worry about that: I know we would have @keradus to the rescue if needed ;)

**Comment by keradus** [comment]
give me the spec via unit tests, and I will make regex for you ;)

**Comment by julienfalque** [comment]
Rebased.

**Comment by SpacePossum** [comment]
I like to request @keradus as reviewer here as the regex is a bit out of my regex-understanding-capabilities;)

**Comment by julienfalque** [comment]
@SpacePossum When I have difficulties understanding regular expressions, I use https://regex101.com. It is very helpful so I would recommand you try it :)

**Comment by SpacePossum** [comment]
please resolve the conflict @julienfalque

**Comment by julienfalque** [comment]
PR rebased.

**Comment by keradus** [comment]
Thank you @julienfalque.

**Pull request merged**
