### PR TITLE
Fix header comment in php files

### PR DESCRIPTION
**Pull request by ajgarlag**
This PR is the result of running the new HeaderCommentFixer, implemented in #1002

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
:+1:

**Comment by keradus** [comment]
IMO... This changes license header and should not be voted but discussed with creator.

Any thoughts @fabpot ?

**Comment by keradus** [comment]
Then @ajgarlag please leave original header and just fix the deformations.

**Comment by ajgarlag** [comment]
The license header was changed by @fabpot in 926ad7d

**Comment by GrahamCampbell** [comment]
:+1:

**Comment by keradus** [comment]
Wow, then we have various header depending on file? :/
Nice catch then, thanks for pointing it out!

:+1:

**Comment by keradus** [comment]
Thank you @ajgarlag.

**Pull request merged**
