### PR TITLE
Runner - No need to determine relative file name twice

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] determines the relative pathname for a file once only

Somewhat related to #1998.

### CODE REVIEW

**Comment by keradus** [comment]
It could be from some 1.12 merge conflict.
Or it appears duplicated on 1.12 as well ?

**Comment by localheinz** [comment]
@keradus 

Nope, only in `master`.

**Comment by keradus** [comment]
thanks for checking

**Comment by keradus** [comment]
Thank you @localheinz.

**Pull request merged**
