### PR TITLE
[WIP] proof for issue#1506

### PR DESCRIPTION
**Pull request by SpacePossum**
@ see https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/1506

### CODE REVIEW

**Comment by keradus** [comment]
any chances for a fix?

**Comment by SpacePossum** [comment]
>any chances for a fix?

not really :(

**Comment by keradus** [comment]
no need to close it then ;)

**Comment by keradus** [comment]
Closing due to #1559 
Thanks @SpacePossum !

**Comment by SpacePossum** [comment]
thanks @keradus :)

**Pull request closed without merging**
