### PR TITLE
PhpdocAddMissingParamAnnotation: fix and extend

### PR DESCRIPTION
**Pull request by WinterSilence**
1.Fixes:
~~~php
/**
 * Doc header
 * ADDS TAG HERE
 */
/**
 * Function description.
 */
function fixMe($id = null) {
}
~~~
~~~php
  /**
   * Function description.
   * @param ?int $id SET INVALID TYPE
   */
  function test2(?int $id) {
  }
  /**
   * Function description.
   * @param null|mixed $id SET INVALID TYPE
   */
  function test3($id = null) {
  }
~~~
2. Optional ignore one-line PhpDoc's (option `skip_inline_phpdocs`)
3. Fix  arrow/closure PhpDoc's,  in case as  `/** ... */ return fn($a)`, it's better than nothing :)
4. Fix skip structures "without" methods (exceptions, interfaces and etc.)

### CODE REVIEW

**Comment by julienfalque** [comment]
Please do not mix different changesets in the same PR. You should at least have 2 PRs:
* one for bugfixes that targets the lowest branch where the bugs exist (likely 2.18);
* one for new features that target next minor version branch (master).

Also, please add test cases to prove the changes are working as expected and to prevent future regressions.

**Comment by WinterSilence** [comment]
@julienfalque you right, but it doesn't make sense in v3 - that's should be rewritten using more analyzers, for example:
~~~php
$commentsAnalyzer = new CommentsAnalyzer();
...
if (
    $commentsAnalyzer->isHeaderComment($tokens, $index)
    || !$commentsAnalyzer->isBeforeStructuralElement($tokens, $index)
) {
    continue;
}
~~~

**Comment by WinterSilence** [comment]
@julienfalque also, current tests failed because they are faked and invalid: `@param ?array $foo` ans `@param null|mixed $foo` are invalid PhpDoc types, `null|array` same to `array|null`. 
I can fix current tests and add test for new config option. ok?

**Comment by keradus** [comment]
Please, extract the new feature part to separated PR.

> you right, but it doesn't make sense in future(v3.*) - that's should be rewritten using analyzers, for example:

if that's the case, please create the feature PR for `3.0` line instead of `master`

**Pull request closed without merging**
