### PR TITLE
Do not replace mt_rand to random_int - seed is ignored

### PR DESCRIPTION
**Pull request by mvorisek**
`mt_rand` function is semantically different than `random_int`

- `mt_rand` is seedable random number generator
- `random_int` is cryptographically secure random number generator and can not seeded [1]

because of this, I belive this is a bug and replacing `mt_rand` to `random_int` should never be done by default

[1]  - https://stackoverflow.com/questions/39352599/php-random-int-seeding#61375549

### CODE REVIEW

**Review by sanmai — APPROVED** [review]

**Comment by SpacePossum** [comment]
Hi and thanks for the PR!

The functions are indeed semantically different, however I think we've made this the default because of people actually not knowing about this behavior of `mt_rand` and mistaken it for a true RNG (suitable for cryptographically).
As such I'm kind of +0 for this change because I think there are more applications that don't need seeds than there are with it, however that is just IMHO ; )

**Comment by sanmai** [comment]
Though I left a positive review, I tend to agree with @SpacePossum. If someone is using `mt_rand` as seedable rng, they will most definitely notice their tests are broken. There's no evil here.

**Comment by GrahamCampbell** [comment]
👎 For this change. This fixer is marked as risky, and will do the right thing for most people wanting to migrate to the better functions. For those who don't want this change, the fixer is configurable already.

**Comment by keradus** [comment]
for majority of user, the change brings benefits.
I agree about your case, @mvorisek , but that's the beauty of most of "risky" fixers. eg `== / ===` fixer is changing the behaviour, and we should encourage to use later, while there can be a valid case to use only `==`. For those folks, explicitly disabling the rule is a way to go.

But I agree also about need of visibility and understanding what is the tricky part here.
Can I ask you to extend the documentation of the fixer, please?
current one:
```
Fixer applying this rule is risky.
Risky when the configured functions are overridden.
```

**Pull request closed without merging**
