### PR TITLE
Replace --config by --config-file

### PR DESCRIPTION
**Pull request by j0k3r**

### CODE REVIEW

**Comment by j0k3r** [comment]
Wow, the README file is actually tested :face_with_thermometer:

**Comment by SpacePossum** [comment]
Hi,
For master / 2.x line the argument is actually called `config` and no longer `config-file` (as it was on the 1.x line), this is documented in [UPGRADE.md](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.0.0/UPGRADE.md#cli-options).

**Comment by j0k3r** [comment]
Woops sorry, I was testing with my php-cs-fixer globaly (which run the 1.x) instead of locally.
So sorry :disappointed:

**Comment by SpacePossum** [comment]
no worries! :+1:  :)

**Pull request closed without merging**
