### PR TITLE
Added UnalignDoubleArrowFixer

### LINKED ISSUE #882: [Proposal] Array Un-Align Fixer
Does the reverse of our array align fixer, and makes sure array elements are not aligned up.

I'd be happy to write this for the contrib level to hopefully go into 1.5.

### PR DESCRIPTION
**Pull request by keradus**
Closes #882

### CODE REVIEW

**Comment by sstok** [comment]
You need to run the fixer to fix the project itself ;)

**Comment by stof** [comment]
:+1: 

this should also be added in the list of conflicting fixers in #1033

**Comment by gharlan** [comment]
:+1: 

(there shouldn't be problems, but maybe add a test case with `yield $x => $y` syntax.)

**Comment by keradus** [comment]
List of conflicted fixers updated, thanks @stof ;)

**Pull request closed without merging**
