### PR TITLE
docs: [DateTimeCreateFromFormatCallFixer] Fix typos in the code sample

### PR DESCRIPTION
**Pull request by elementaire**
Just a fix for typos in the code sample of DateTimeCreateFromFormatCallFixer.

### CODE REVIEW

**Review by jrmajor — CHANGES_REQUESTED** [review]
Thanks! You need to run `php dev-tools/doc.php` to update the documentation.

**Comment by elementaire** [comment]
Done.

**Review by keradus — APPROVED** [review]

**Review by jrmajor — APPROVED** [review]
Thank you :)

**Comment by keradus** [comment]
Thanks!

**Pull request merged**
