### PR TITLE
SingleClassElementPerStatementFixer - fix array handling

### LINKED ISSUE #2046: [bug] single_class_element_per_statement - handle arrays
The fixer doesn't detect the statements correctly when a statement is an array, so it will break the array into pieces.

Input:
```php
<?php
class Test {
    private static $content = array(
        "     * @param string \$hello\n",
        "     * @param bool \$test Description\n     *        extends over many lines\n",
        "     * @param adkjbadjasbdand \$asdnjkasd\n",
        "     * @throws \Exception asdnjkasd\n     *\n     * asdasdasdasdasdasdasdasd\n     * kasdkasdkbasdasdasdjhbasdhbasjdbjasbdjhb\n",
        "     * @return void\n",
    );
}
```

Output:
```diff
1) PhpCsFixer\Tests\Fixer\ClassNotation\SingleClassElementPerStatementFixerTest::testFix with data set #0 ('<?php\nclass Test {\n    /**\n  ...}    \n')
Code build on expected code must not change.
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
     private static $content = array(
-        "     * @param string \$hello\n",
-        "     * @param bool \$test Description\n     *        extends over many lines\n",
-        "     * @param adkjbadjasbdand \$asdnjkasd\n",
-        "     * @throws \Exception asdnjkasd\n     *\n     * asdasdasdasdasdasdasdasd\n     * kasdkasdkbasdasdasdjhbasdhbasjdbjasbdjhb\n",
-        "     * @return void\n",
-    );
+        "     * @param string \$hello\n";
+    private static "     * @param bool \$test Description\n     *        extends over many lines\n";
+    private static "     * @param adkjbadjasbdand \$asdnjkasd\n";
+    private static "     * @throws \Exception asdnjkasd\n     *\n     * asdasdasdasdasdasdasdasd\n     * kasdkasdkbasdasdasdjhbasdhbasjdbjasbdjhb\n";
+    private static "     * @return void\n";
+    private static );
 }

```

master only, tested on:
possum@LandOfOz:~/work/PHP-CS-Fixer$ php -v
PHP 7.0.4-7ubuntu2.1 (cli) ( NTS )

### PR DESCRIPTION
**Pull request by keradus**
Fixes #2046

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
We should probably add a short array syntax test just for completeness too.

**Comment by GrahamCampbell** [comment]
When was this bug introduced btw?

**Comment by keradus** [comment]
2.x line, dunno when, for sure it's not ready to merge PR, but it proves the bug.
If you have time please deal with it.

**Comment by keradus** [comment]
changed

**Comment by SpacePossum** [comment]
>When was this bug introduced btw?

on merge of the fixer on master https://github.com/FriendsOfPHP/PHP-CS-Fixer/commit/92d7f83737a8cdbe5b82f5c6b30804082e1760fe

thanks for fixing this @keradus !

**Pull request merged**
