### PR TITLE
PhpCsFixer\Config::getFinder() can return PhpCsFixer\Finder

### PR DESCRIPTION
**Pull request by SignpostMarv**
since `PhpCsFixer\Config::getFinder()` will return an instance of `PhpCsFixer\Finder` by default, it'd be beneficial to type-hint in the docblock that this is the case :)

### CODE REVIEW

**Comment by SpacePossum** [comment]
Hi and thank you for your PR!

~~The additional type hint you suggest here seems overcomplete to me.
As `Finder` extends [`\IteratorAggregate`](https://github.com/symfony/finder/blob/2.0/Finder.php#L29) which extends [`Traversable`](http://php.net/manual/en/class.iteratoraggregate.php) which is what is now hinted as return type. I think the current type hinting is correct as we don't want to rely on the `Finder` implementation~~ (, besides if should hint `Finder` we would've to do it as FQCN or import it).

I just read up on the issue over @ phpstan, isn't this resolved at their end with https://github.com/phpstan/phpstan/pull/650 ?

**Comment by SignpostMarv** [comment]
@SpacePossum phpstan/phpstan#650 only resolves the issue when Finder is explicitly listed as a return/param type.

**Comment by SignpostMarv** [comment]
p.s. this came up because of the [php-cs-fixer config package I use](https://github.com/SignpostMarv/PHP-CS-Fixer-Config/blob/e9d86b06fab9ad6af47ea223083192cf156ff976/src/Config.php#L101), where I'm calling `Config::setFinder()` after passing `$finder->ignoreUnreadableDirs()` through `array_reduce()`

**Comment by SpacePossum** [comment]
alrighty than, I'm leaning to +1 here,
however the type hint should still ref. the namespace of Finder, therefore I would pref. importing the Finder with its namespace.

**Comment by SignpostMarv** [comment]
closing this one in favour of #3301 since I'm using 2.8 myself.

**Pull request closed without merging**
