### PR TITLE
AlignDoubleArrowFixer - fix handling of nested arrays

### LINKED ISSUE #1450: align_double_arrow looks weird
Since the last update ``align_double_arrow``looks weird

```bash
oskar.stark:/Volumes/development/workspaces/SonataBlockBundle (master)$ make cs
./vendor/bin/php-cs-fixer fix --verbose
Loaded config from "/Volumes/development/workspaces/SonataBlockBundle/.php_cs"
.................FF...........................................................................................
Legend: ?-unknown, I-invalid file syntax, file ignored, .-no changes, F-fixed, E-error
   1) Block/Service/MenuBlockService.php (align_double_arrow)
   2) Block/Service/RssBlockService.php (align_double_arrow)
Fixed all files in 23.432 seconds, 9.500 MB memory used
make: *** [cs] Error 1
oskar.stark:/Volumes/development/workspaces/SonataBlockBundle (master)$ git diff
diff --git a/Block/Service/MenuBlockService.php b/Block/Service/MenuBlockService.php
index 6cd0965..2c88923 100644
--- a/Block/Service/MenuBlockService.php
+++ b/Block/Service/MenuBlockService.php
@@ -133,16 +133,16 @@ class MenuBlockService extends BaseBlockService
     protected function getFormSettingsKeys()
     {
         return array(
-            array('title', 'text', array('required' => false)),
-            array('cache_policy', 'choice', array('choices' => array('public', 'private'))),
-            array('menu_name', 'choice', array('choices' => $this->menus, 'required' => false)),
+            array('title', 'text', array('required'           => false)),
+            array('cache_policy', 'choice', array('choices'   => array('public', 'private'))),
+            array('menu_name', 'choice', array('choices'      => $this->menus, 'required' => false)),
             array('safe_labels', 'checkbox', array('required' => false)),
-            array('current_class', 'text', array('required' => false)),
-            array('first_class', 'text', array('required' => false)),
-            array('last_class', 'text', array('required' => false)),
-            array('menu_class', 'text', array('required' => false)),
-            array('children_class', 'text', array('required' => false)),
-            array('menu_template', 'text', array('required' => false)),
+            array('current_class', 'text', array('required'   => false)),
+            array('first_class', 'text', array('required'     => false)),
+            array('last_class', 'text', array('required'      => false)),
+            array('menu_class', 'text', array('required'      => false)),
+            array('children_class', 'text', array('required'  => false)),
+            array('menu_template', 'text', array('required'   => false)),
         );
     }

diff --git a/Block/Service/RssBlockService.php b/Block/Service/RssBlockService.php
index 80e906e..be76f09 100644
--- a/Block/Service/RssBlockService.php
+++ b/Block/Service/RssBlockService.php
@@ -51,7 +51,7 @@ class RssBlockService extends BaseBlockService
     {
         $formMapper->add('settings', 'sonata_type_immutable_array', array(
             'keys' => array(
-                array('url', 'url', array('required' => false)),
+                array('url', 'url', array('required'    => false)),
                 array('title', 'text', array('required' => false)),
             ),
         ));
oskar.stark:/Volumes/development/workspaces/SonataBlockBundle (master)$ vendor/bin/php-cs-fixer --version
PHP CS Fixer version 1.10.1 by Fabien Potencier
oskar.stark:/Volumes/development/workspaces/SonataBlockBundle (master)$
```

### PR DESCRIPTION
**Pull request by keradus**
Fixes #1450.
Replaces #1455.

### CODE REVIEW

**Comment by keradus** [comment]
@SpacePossum @Soullivaneuh 
Please, could you take a look on fix?

**Comment by SpacePossum** [comment]
Looks good to me :+1: 

If I understand/read you code correctly you won't insert any place holders for the spacing of double arrows for nested arrays if such an an array is on one line, correct?
So a small future improvement could be removing extra white space around an double arrow if found in an nested array (for example in something like this:

```php
<?php
$formMapper->add(1, 2, array(
    "keys" => array(
        array(5, 123, array(10   => array(12 => false))),
)));
```
)

**Comment by keradus** [comment]
Yeah, your solution was to detect nested array, I add a check if nested array is single-line.

The fixer does not remove extra spaces, so I would keep it that way. If one want to remove extra spaces around `=>` he has separated fixer for that ;)

Thanks for approval ! Fixer is quite tricky.

**Comment by SpacePossum** [comment]
:+1: 
 nice one, I'm out of town so I couldn't help out, thanks for picking this up!

**Comment by keradus** [comment]
Thank you @Soullivaneuh.

**Comment by Soullivaneuh** [comment]
Thank you for the fix @keradus!

Seems to works, nice catch. :+1:

**Pull request merged**
