### PR TITLE
YodaStyleFixer - fix for assignment operators

### PR DESCRIPTION
**Pull request by kubawerlos**
Reference: https://github.com/drush-ops/drush/blob/10.4.3/src/internal-forks/Config/Yaml/Unescaper.php#L130

### CODE REVIEW

**Comment by julienfalque** [comment]
Is this correct? `<` and `>` have a greater precedence than `+=`.

**Comment by kubawerlos** [comment]
Good point 😄 

Yet, the problem exists as the referenced code breaks PHP syntax.

**Comment by julienfalque** [comment]
Not sure what you mean. The referenced code and the code in your tests in valid syntax-wise. Some code may be broken logically, but is it related to PHP CS Fixer?

**Comment by kubawerlos** [comment]
@julienfalque when you try to fix:
```
if (0x80 > $c %= 0x200000) {
    return chr($c);
}
```
with
```
'yoda_style' => [
    'equal' => false,
    'identical' => false,
    'less_and_greater' => false,
],
```
there is a syntax error.

**Review by SpacePossum — APPROVED** [review]

**Comment by keradus** [comment]
@kubawerlos can you rebase to solve conflict, pls?

**Comment by keradus** [comment]
Thank you @kubawerlos.

**Pull request merged**
