### PR TITLE
Add "phpt" as a valid extension

### PR DESCRIPTION
**Pull request by henriquemoody**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This is breaking so should go to master imo.

**Comment by stof** [comment]
Why adding this ? ``.phpt`` is the extension used by test files for the PHPT tool used in PHP itself and in most extensions, and these files are not valid PHP files (sections in it are, but it is very common to omit the closing PHP tag in sections)

**Comment by henriquemoody** [comment]
PHPUnit also runs PHPT files and uses it to test its own code.

It's really not a PHP file, by definition, but it contains valid PHP code.

Also, it's not common to omit the closing PHP tag in the sections, it's a [recomendation to close them](https://qa.php.net/write-test.php), because doing that you can run the file with `php` command.

**Comment by stof** [comment]
hmm, indeed. Looks like I had no luck when choosing some of the PHP tests themselves at first...

**Comment by keradus** [comment]
any other opinions ?

**Comment by henriquemoody** [comment]
@keradus, do you have intent to merge it?

**Comment by keradus** [comment]
I am not against this PR, but before merge I would like to see some :+1: here

**Comment by gharlan** [comment]
:+1:

**Comment by GrahamCampbell** [comment]
:+1: here, but for merging to master.

**Comment by keradus** [comment]
Thank you @henriquemoody.

**Pull request closed without merging**
