### PR TITLE
Feature add sort by depth algorithm for OrderedClassElementsFixer

### PR DESCRIPTION
**Pull request by sidux**
This adds the possibility the sort class methods by depth meaning called methods will be placed after the caller like in the option "Keep dependent methods together depth-first-order" of PhpStorm.

### CODE REVIEW

**Comment by sidux** [comment]
The `sort_algorithm` was only string before i made it array and kept string (backward compatibility) so that we can use something like `['alpha', 'depth']` or 'alpha' as a `sort_algorithm` and that's the result on the `README.rst`

**Comment by SpacePossum** [comment]
Thanks @sidux for the PR, looks promising (based on the unit test samples)! Need some more time to review it properly though

(and I've to check what is up with that README generation indeed)

**Comment by sidux** [comment]
I'm closing this, since it doesn't seem that requested.

**Comment by sidux** [comment]
I'm closing this, since it doesn't seem that requested.

**Pull request closed without merging**
