### PR TITLE
Made all tests internal

### PR DESCRIPTION
**Pull request by keradus**
Continuation of #1387

### CODE REVIEW

**Comment by keradus** [comment]
fabbot.io fails as always :(

**Comment by stof** [comment]
@keradus what do you think about moving them to a separate ``tests`` folder at the root, which would not be autoloadable at runtime ?
This would cleanly separate the testsuite from the library, avoiding the need to mark anything as internal in the testsuite (as it would not be accessible at all anymore)

**Comment by GrahamCampbell** [comment]
> @keradus what do you think about moving them to a separate tests folder at the root, which would not be autoloadable at runtime ?

I suggested this before, and @fabpot rejected the idea.

**Comment by keradus** [comment]
> This would cleanly separate the testsuite from the library, avoiding the need to mark anything as internal in the testsuite (as it would not be accessible at all anymore)

**Comment by keradus** [comment]
> This would cleanly separate the testsuite from the library, avoiding the need to mark anything as internal in the testsuite (as it would not be accessible at all anymore)

I can include classes from tests dir myself and use it, extend it ect. So marking them internal/final isn't pointless.

**Comment by stof** [comment]
@keradus if you have to include them yourselves rather than relying on the autoloading, it is clear you are doing weird thing (and that you would ignore an ``@internal`` phpdoc anyway, which is harder to see than an autoloading failure)

**Comment by keradus** [comment]
I' not saying here should we move tests or not, just saying that marking tests as final/internal is still gr8

**Comment by keradus** [comment]
I agree that one should not include files from vendor himself, but if we mark tests as internal we won't lose anything

**Pull request merged**
