### PR TITLE
minor: extract NoMultipleStatementsPerLineFixer from BracesFixer

### PR DESCRIPTION
**Pull request by julienfalque**
Extracted from #4884.

### CODE REVIEW

**Comment by mvorisek** [comment]
why there is no code removed from BracesFixer?

**Comment by julienfalque** [comment]
I made some cleanup :)

**Comment by julienfalque** [comment]
Now I remember why: some integration tests fail when removing this code. This requires more work from #4884.

**Comment by SpacePossum** [comment]
looking good, please consider https://github.com/julienfalque/PHP-CS-Fixer/pull/12

**Pull request merged**
