### PR TITLE
Removed phpstorm plugin link in favor of gist link

### PR DESCRIPTION
**Pull request by tiemevanveen**
Link to _PhpStorm plugin is broken. 
I can't find any plugins online, is it gone?

You could go for this gist? It helped me :)

### CODE REVIEW

**Comment by keradus** [comment]
Link to php storm is not broken

**Comment by tiemevanveen** [comment]
Oh apparently this is the live version of the page, including a link to http://arnolog.net/.... 

https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/1.7/README.rst

**Comment by keradus** [comment]
1.7 is so old, link was changed on 1.9, the latest stable is 1.10.
no new version need to be released

**Comment by stof** [comment]
@keradus the issue is that http://cs.sensiolabs.org/ displays an outdated version of the readme.

@fabpot please either update http://cs.sensiolabs.org/ (making it update automatically on new releases would be the best as you are not the one doing releases anymore), or shutdown this website and make it redirect to the github repo.

**Comment by keradus** [comment]
That's odd. I remember that site was already autogenerated after releases.

**Pull request closed without merging**
