### PR TITLE
Fixed project name in xdebug warning

### PR DESCRIPTION
**Pull request by gharlan**

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
Copy paste spotted! :-P

**Comment by SpacePossum** [comment]
>following composer who warns it users about the impact of xdebug this will warn users in a similar way.

(https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1552#issue-119223739)
bit to similar ;)

:+1:

**Comment by GrahamCampbell** [comment]
:hatched_chick:

**Comment by keradus** [comment]
Thank you @gharlan.

**Comment by SpacePossum** [comment]
:+1: thanks @gharlan

**Pull request merged**
