### PR TITLE
Broken simple_lambda_call case

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
@SpacePossum 

> if you want it changed make a PR, don't act like you don't know how FOSS works or why things are merged, thanks

My complaint was that despite the original PR being known to not work properly, you merged it anyway.

**Comment by GrahamCampbell** [comment]
> again, please let us know if you found a bug using the issue template, I don't know why you don't

Your issue template is kinda hard to use. It's much faster to send a PR showing broken tests!

**Comment by SpacePossum** [comment]
can you look at the test that are failing, I cannot merge this following your own complaint

**Comment by GrahamCampbell** [comment]
I propose the original PR is reverted in the meanwhile. I'm unlikely to fix this issue myself in the next few weeks, since I don't plan to ever use this fixer myself.

**Comment by SpacePossum** [comment]
closing in favor of https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4752

**Pull request closed without merging**
