### PR TITLE
Introduce CT_ARRAY_INDEX_CURLY_BRACE_OPEN and CT_ARRAY_INDEX_CURLY_BRACE_CLOSE

### LINKED ISSUE #1909: wrong linebreak
```patch
@@ -49,7 +49,8 @@ class LivestreamControllerTest extends WebTestCase
         $this->assertSame('application/json', $response->headers->get('Content-Type'));

         $content = json_decode($response->getContent());
-        $embeddedRelations = (array) $content->_embedded->items{0}->_embedded;
+        $embeddedRelations = (array) $content->_embedded->items{0}
+        ->_embedded;

         /*
          * Assert that channel is embedded
```

Using:
`PHP CS Fixer version 1.11.1 by Fabien Potencier`

### PR DESCRIPTION
**Pull request by keradus**
Also, fixes #1909

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
:+1:

**Comment by keradus** [comment]
I extended detection by cases discovered during #1958

**Comment by GrahamCampbell** [comment]
:ship:

**Comment by keradus** [comment]
I would like to do that only after #1958 would be ready to merge as well ;)

**Comment by SpacePossum** [comment]
:+1:   :ship:  :)

**Pull request merged**
