### PR TITLE
Fixed typo in suggest for ext-mbstring

### PR DESCRIPTION
**Pull request by pascal-hofmann**

### CODE REVIEW

**Comment by keradus** [comment]
wow, we just released this, thanks !

**Comment by GrahamCampbell** [comment]
👍

**Comment by GrahamCampbell** [comment]
> fabbot.io — The rules contain unknown fixers (non_printable_character).

Does this mean fabbot.io is executing our .php_cs file? If so, that's definitely a bad idea, since someone can send a PR and execute arbitrary code on their servers.

**Comment by keradus** [comment]
it's ok as fabbot runs it in virtualized sandbox
in the end, it's not up to me or you, but up to fabbot.

**Comment by GrahamCampbell** [comment]
What sort of information could be leaked from the sandbox is the real question I guess.

**Comment by keradus** [comment]
It's up to the infrastructure and fabbot.io decided they are prepared enough to do this.
If you want, raise a concern directly to them, not here.

**Comment by keradus** [comment]
Thank you @pascal-hofmann.

**Pull request merged**
