### PR TITLE
Fix equals alignement with too high level sign

### PR DESCRIPTION
**Pull request by Soullivaneuh**
Replace #1273

Could anyone check if my modified test seems legit?

### CODE REVIEW

**Comment by keradus** [comment]
tests are broken

**Comment by keradus** [comment]
ping @Soullivaneuh

**Comment by Soullivaneuh** [comment]
Actually not having the time for that. Will look at this ASAP.

**Comment by SpacePossum** [comment]
ping @Soullivaneuh love to see this one fixed :)

**Comment by Soullivaneuh** [comment]
I look at the test.

To be honest, right now I don't know how to fix it and I don't have such of time to investigate more on it.

This seems to be because of sub arrays:

```php
<?php
    $data = [
        "foo"  => "Bar",
        "main" => array(
            [
                "baz" => "Test",
                "bazaa" => $a->{"Test"},
                "bazaa" => $a["Test"],
                "bazaaaa" => b("Test"),
            ]
        ),
        "bar"  => array(),
    ];',
```

If anybody have a suggestion, I'll be glad to apply it and rebase the branch against 1.12. :+1: 

Or simply cherry-pick my commit and modify it. :wink:

**Comment by keradus** [comment]
Closes due to merge of #2573

**Pull request closed without merging**
