### PR TITLE
DuplicateSemicolonFixer - ignore duplicated semicolons inside T_FOR

### PR DESCRIPTION
**Pull request by keradus**
bug from #992

### CODE REVIEW

**Comment by keradus** [comment]
PR has been merged.

**Comment by dzgrief** [comment]
```
php-cs-fixer --version
PHP CS Fixer version 2.0-DEV by Fabien Potencier
```

```
php-cs-fixer fix  Application/
Files that were not fixed due to internal error:
   1) Admin/Controller/AdminController.class.php
   2) Admin/Controller/AttributeController.class.php
   3) Admin/Controller/CategoryController.class.php
```

**Comment by keradus** [comment]
This mean some problem occured somewhere inside.
This may or may not be connected with duplicate semicolons. Please provide your files content to replicate the error.

**Comment by dzgrief** [comment]
##### For example: this file is called [FileController.class.php]
```
<?php

namespace Api\Controller;
use Common\Controller\FileCommonController;

class FileController extends FileCommonController
{
    
    /**
     * upload file
     * @return [array] [description]
     */
    public function upload_post() {
        parent::upload();
    }

    /**
     * delete file
     * @return [array] [description]
     */
    public function delete_post() {
    	parent::delete();
    }

}
```
##### If you change the file name to [FileController.php] can be carried out smoothly.


*Run fail:*
```
php-cs-fixer fix FileController.class.php 
Fixed all files in 0.289 seconds, 4.500 MB memory used

Files that were not fixed due to internal error:
   1) /home/wwwroot/booking2/FileController.class.php
```

*Run success:*
```
php-cs-fixer fix FileController.php 
   1) /home/wwwroot/booking2/FileController.php
Fixed all files in 0.098 seconds, 4.500 MB memory used
```

**Pull request closed without merging**
