### PR TITLE
Rename simplified_null_return,no_useless_return,no_whitespace_in_blan…

### PR DESCRIPTION
**Pull request by Bolaxax**
…k_line,blank_line_before_return,no_extra_consecutive_blank_lines.test to simplified_null_return - no_useless_return - no_whitespace_in_blank_line - blank_line_before_return - no_extra_consecutive_blank_lines.test

The name of file with , cause problems in composer

### CODE REVIEW

**Comment by keradus** [comment]
What problems ? Why comma ?

**Comment by Bolaxax** [comment]
[ErrorException]
  ZipArchive::extractTo(C:\xampp\htdocs\yii2/_protected/vendor/composer
  /a9e282ba/FriendsOfPHP-PHP-CS-Fixer-9704c5d\tests\Fixtures\Integration\misc
  /simplified_null_return,no_useless_return,no_whitespace_in_blank_line,blank
  _line_before_return,no_extra_consecutive_blank_lines.test): failed to open
  stream: Invalid argument

i belive this is caused by the file name

**Comment by keradus** [comment]
> i belive this is caused by the file name

Please verify 


also,
https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/2098#issuecomment-235510771

**Comment by keradus** [comment]
?

**Comment by keradus** [comment]
Closing due to #2098

**Pull request closed without merging**
