### PR TITLE
Simplify Transformers

### LINKED ISSUE #987: Transfomers are performance bottleneck - Suggested Fix
Hello,

Few weeks ago, I made a research about fundamental flaws in PHP-CS-Fixer. I have made extensive changes into PHP-CS-Fixer code - but I decided not PR them as I would not have time to battle all the energy and time consuming review process you guys have here.

Among all problems, transformers were heaviest part - single transformations took place in several loops. I changed that. Now there are only two loops, and all transformations happen inside them. 

It should be straightforward for any maintainer to take this [gist](https://gist.github.com/dericofilho/7460e435b2193a2f20cb) and incorporate these changes.

The transformers are still atomic - they just happen in less loops.

I hope it helps you guys.

### PR DESCRIPTION
**Pull request by keradus**
Resolve #987

I keep everything in separated classes to not create one god class that do all transformations.

Also, I was able to pack everything into one iteration over tokens collection.

@dericofilho, could you give an opinion ?

### CODE REVIEW

**Comment by dericofilho** [comment]
Except by the broken test at HHVM, LGTM.

One loop only through the tokens is an enormous improvement.

**Comment by keradus** [comment]
> One loop only through the tokens is an enormous improvement.

I'm still a bit sad about that loop over all Transformers ;(

**Comment by dericofilho** [comment]
> I'm still a bit sad about that loop over all Transformers ;(

That's what I tried to avoid in my implementation but I know I did not managed it. You are already early exiting them, so I believe there is little to improve on that - the two options left is to come with a more complex algorithm that transforms everything at once; or loop unrolling.

Loop unrolling comes with a price, though. You will have to abdicate from dynamic loading of Transformers.

**Comment by keradus** [comment]
IMO both solutions isn't worth it as they (especially creating one god-like Transformer) make it harder to maintain.

Thank you for your assistance !

**Comment by sstok** [comment]
How about generation? You collect all the custom tokens and content of each process from all the files store this in a big class with no loop what so ever. The transformers are still in there own class, but are collected once for better speed.

You choose to keep the generated class in the repository, system temp-folder, and for the phar version keep it with the archive.

**Comment by dericofilho** [comment]
@sstok that's what I implicitly suggested by loop unrolling.

**Comment by sstok** [comment]
Hihi, I never heard of that word :)

**Comment by keradus** [comment]
To be honest I don't like generating code and have no experience with it :(

**Comment by keradus** [comment]
PR has been merged.

**Pull request closed without merging**
