### PR TITLE
Add NoWhileAsForLoopFixer.

### PR DESCRIPTION
**Pull request by SpacePossum**
Expected
```php
                <?php
                    while($a > 1) {
                        echo $a;
                    }
```

Input

```php
                <?php
                    for(;$a > 1;) {
                        echo $a;
                    }
```

### CODE REVIEW

**Comment by gharlan** [comment]
`for (;;)` is valid, but `while ()` is not.

**Comment by SpacePossum** [comment]
good catch :+1: 
updated in https://github.com/SpacePossum/PHP-CS-Fixer/commit/cf9ed85437eac7c4215419e7b0d20f336018ea59

Expected
```php
<?php
    while(true) {
        echo 1;
        break;
    }
```

Input
```php
<?php
    for(;;) {
        echo 1;
        break;
    }
```

**Comment by SpacePossum** [comment]
maybe to rare of case to the code base?

**Comment by gharlan** [comment]
> maybe to rare of case to the code base?

I wanted to add my ":+1:" just this moment. But maybe you're right.

**Comment by gharlan** [comment]
And btw: thanks for all your work!!
But I think we should not add fixers with very rare use cases.

**Comment by SpacePossum** [comment]
>And btw: thanks for all your work!!

Thanks! :)
I'll create a new public MIT repo with some rare fixers, just in case someone finds a need for those one day (other than me ^-^).

Thanks for reviewing!

**Pull request closed without merging**
