### PR TITLE
Readme - Add spaces around PHP-CS-Fixer headers

### PR DESCRIPTION
**Pull request by Soullivaneuh**
Because it's not really standard compliant AFAIK. :-)

### CODE REVIEW

**Comment by sstok** [comment]
:+1:

**Comment by GrahamCampbell** [comment]
:-1: This was done on purpose otherwise if you're using a fixer that removes the spacing, you end up with things getting double fixed.

**Comment by GrahamCampbell** [comment]
Oh wow, just read the diff... Ignore me. :+1:

**Comment by keradus** [comment]
Thank you @Soullivaneuh.

**Pull request merged**
