### PR TITLE
minor: extract BlankLinesInsideBlockFixer from BracesFixer

### PR DESCRIPTION
**Pull request by julienfalque**
Extracted from #4884.

### CODE REVIEW

**Comment by SpacePossum** [comment]
Does this new rule add anything new/else over `no_extra_blank_lines` with `curly_brace_block` ?

**Comment by julienfalque** [comment]
If I replace `blank_lines_inside_block` with `no_extra_blank_lines`, some tests fail. For now I would keep `blank_lines_inside_block` but it would make sense to merge those rules at some point.

**Comment by SpacePossum** [comment]
happy to look into those cases, I think we should not introduce a new rule if we think we can do without it

**Comment by keradus** [comment]
the failing cases would be in BracesFixerTest, or somewhere else?

**Comment by julienfalque** [comment]
In BracesFixerTest. It seems it can be fixed easily, working on it.

**Comment by julienfalque** [comment]
I updated #4884 to use `no_extra_blank_lines` and dropped `blank_lines_inside_block`. IMO #4884 is small enough to be reviewed directly now so I'm closing here. Let me know if you still want me to extract things.

**Pull request closed without merging**
