### PR TITLE
PrintToEchoFixer - add to symfony rule set

### PR DESCRIPTION
**Pull request by gharlan**

### CODE REVIEW

**Comment by keradus** [comment]
Good one.
Please, as you extend `@Symfony` set, could you extend `symfony` integration test as well?

**Comment by gharlan** [comment]
Hmm, at the moment there is only a symfony integration test without any modification: https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/Symfony/CS/Tests/Fixtures/Integration/symfony.test

I'm not sure how I should add test for PrintToEchoFixer

**Comment by keradus** [comment]
add expect part ;)

**Comment by gharlan** [comment]
This way?

**Comment by keradus** [comment]
:+1:

**Comment by SpacePossum** [comment]
:+1:

**Comment by keradus** [comment]
Thank you @gharlan.

**Pull request merged**
