### PR TITLE
PhpdocAlignFixer - unicode characters support

### PR DESCRIPTION
**Pull request by SpacePossum**
closes https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/2387

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
👍

**Comment by keradus** [comment]
fabbot.io is finally green !
http://fabbot.io/report/FriendsOfPHP/PHP-CS-Fixer/2388/2d18886a3c68a70982837991a699ef5f0087a46a
vs
http://fabbot.io/report/FriendsOfPHP/PHP-CS-Fixer/2388/8f5cab45fe5afa15114ea8ae953b5af208830ff1

thank you @fabpot !

**Comment by SpacePossum** [comment]
Ha nice, thanks! : D

**Comment by keradus** [comment]
Thank you @SpacePossum.

**Pull request merged**
