### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by SpacePossum**
Just some typos, missing doc entries and unused `use` cases.

### CODE REVIEW

**Comment by SpacePossum** [comment]
hope it worked, looks a bit odd in github.. hmm..

**Comment by GrahamCampbell** [comment]
Doesn't some of this need fixing on an earlier branch?

**Comment by SpacePossum** [comment]
@GrahamCampbell woundn't hurt. How is the flow for fixes over versions? Symfony like; lowest only and the collaborators merge it upstream? Or PRs on all effected versions?

**Comment by stof** [comment]
@SpacePossum same than Symfony. Maintainers are merging older branches into newer ones regularly

**Comment by SpacePossum** [comment]
Thanks @stof :+1:  I'll figure out what branch to target and send in a new PR.

**Pull request closed without merging**
