### PR TITLE
README.rst - fix wrong value in example

### PR DESCRIPTION
**Pull request by mleko**

### CODE REVIEW

**Comment by SpacePossum** [comment]
Hi!

Thanks for this PR, this is indeed a typo in the docs, well spotted!
Currently on the stable release branch 2.2 this has been corrected by https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2677 , however it seems that fix was not applied to the master branch.
(ping @keradus , would you want to merge 2.2 -> master, or take a new PR for master?)

**Comment by mleko** [comment]
This PR and #2677 fix typos in different places.

I checked and it seems #2677 is merged to master

**Comment by SpacePossum** [comment]
You are absolutely right! 
Can't believe I missed the typo again  :|

Nice fix, thanks again :)

**Comment by keradus** [comment]
Thank you @mleko.

**Pull request closed without merging**
