### PR TITLE
PhpdocTypesFixer - fix recognizing callable

### PR DESCRIPTION
**Pull request by kubawerlos**

### CODE REVIEW

**Review by SpacePossum — APPROVED** [review]

**Review by GrahamCampbell — APPROVED** [review]

**Comment by SpacePossum** [comment]
Thank you @kubawerlos.

**Comment by SpacePossum** [comment]
Thank you @kubawerlos.

**Comment by SpacePossum** [comment]
```
  The command "git push origin "master" refs/notes/github-comments" failed.                       
                                                                                                  
  Exit Code: 1(General error)                                                                     
                                                                                                  
  Working directory: /home/possum/work/master/PHP-CS-Fixer                                        
                                                                                                  
  Output:                                                                                         
  ================                                                                                
                                                                                                  
                                                                                                  
  Error Output:                                                                                   
  ================                                                                                
  remote: error: GH006: Protected branch update failed for refs/heads/master.                     
  remote: error: At least 1 approving review is required by reviewers with write access.          
  To github.com:FriendsOfPHP/PHP-CS-Fixer.git                                                     
     db0eb49f9..138157281  refs/notes/github-comments -> refs/notes/github-comments               
   ! [remote rejected]     master -> master (protected branch hook declined)                      
  error: failed to push some refs to 'git@github.com:FriendsOfPHP/PHP-CS-Fixer.git'               
                                                                                        
```

@keradus I can no longer merge because of the new rules, so someone else has to take over

**Comment by keradus** [comment]
can you try again, @SpacePossum ?

yet another strong point to finalise getting out of `gh` tool, imho

**Comment by SpacePossum** [comment]
Thank you @kubawerlos.

**Comment by SpacePossum** [comment]
and thanks @keradus , merge went all fine now :+1:

**Pull request closed without merging**
