### PR TITLE
Added missing internal annotation

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Ping @keradus. This one's an easy merge. ;)

**Comment by gharlan** [comment]
:+1: ;)

**Comment by SpacePossum** [comment]
:+1: ;)

**Comment by keradus** [comment]
:+1:

(I have my hardware broken, I cannot do much things now, will merge it at late evening.
Thanks you all for keeping the repo running, sending PRs, make reviews, discuss on your own, all of you are awesome!)

**Comment by GrahamCampbell** [comment]
You're awesome too @keradus. ;)

**Comment by SpacePossum** [comment]
good luck with the hardware @keradus, you're awesome  :)

**Comment by keradus** [comment]
Thank you @GrahamCampbell.

**Pull request merged**
