### PR TITLE
Double arrow align failed on sub array proof

### PR DESCRIPTION
**Pull request by Soullivaneuh**
Related to #1377.

### CODE REVIEW

**Comment by SpacePossum** [comment]
@Soullivaneuh I think this is fixed, can you commit something to the branch to trigger Travis again :)

**Comment by keradus** [comment]
I have restarted the build for Travis

**Comment by GrahamCampbell** [comment]
Still failing.

**Comment by SpacePossum** [comment]
thanks @keradus for the restart!

I don't get it, I'll look more into this very soon
: (

**Comment by Soullivaneuh** [comment]
> @Soullivaneuh I think this is fixed, can you commit something to the branch to trigger Travis again :)

I rebased the PR from 1.10, let's see.

Can you please tell me where this is fixed? Thanks.

**Comment by keradus** [comment]
ref #1417

**Comment by Soullivaneuh** [comment]
Rebased this PR to see if tests passes.

This could be merged too for new tests.

**Comment by Soullivaneuh** [comment]
Indeed, seems it's working now. Great work! \o/

**Comment by SpacePossum** [comment]
good to hear :)

>This could be merged too for new tests.

I've added the test at:
https://github.com/Soullivaneuh/PHP-CS-Fixer/blob/align-sub-array-proof/Symfony/CS/Tests/Fixer/Contrib/AlignDoubleArrowFixerTest.php#L72

sorry I didn't pick your commit correctly on my fix branch

**Comment by Soullivaneuh** [comment]
> sorry I didn't pick your commit correctly on my fix branch

No problem. Indeed tests are the same, closing this one so. :+1:

**Pull request closed without merging**
