### PR TITLE
NoBreakCommentFixer - Fix handling comment text with PCRE characters

### PR DESCRIPTION
**Pull request by julienfalque**
Ref: https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3155#discussion_r151517076.

### CODE REVIEW

**Comment by SpacePossum** [comment]
nice catch :+1: 

maybe we could also test if `$this->configuration['comment_text']` (through configuration definition setup) doesn't contain `\\` itself so we don't insert an invalid comment token that way?

**Comment by Slamdunk** [comment]
What about other special chars like pipe?

**Comment by julienfalque** [comment]
> maybe we could also test if `$this->configuration['comment_text']` (through configuration definition setup) doesn't contain `\n\s*[^\\]{2}` itself so we don't insert an invalid comment token that way?

Indeed, shall we throw an exception in such case or just strip unwanted characters?

> What about other special chars like pipe?

They are all handled by `preg_quote` already, the point of the new test is to prove this call was missing, not that *all* characters are escaped one by one.

**Comment by Slamdunk** [comment]
> They are all handled by preg_quote already, the point of the new test is to prove this call was missing, not that all characters are escaped one by one.

My fault sorry, I read bad the manual. 👍

**Comment by SpacePossum** [comment]
I would throw an exception if the configured-content would not create one valid comment token, just IMHO of course :)

**Comment by julienfalque** [comment]
I added the exception when comment text contains newlines and `rtrim` to prevent inserting trailing whitespaces.

**Comment by SpacePossum** [comment]
thanks! looks all great to me! :)

**Comment by SpacePossum** [comment]
grrrr sorry :(
phone acting against me...

**Comment by keradus** [comment]
Thank you @julienfalque.

**Pull request closed without merging**
