### PR TITLE
DeclareStrictTypesFixer - prove bug

### PR DESCRIPTION
**Pull request by keradus**
I see no reason why we remove that empty line...

### CODE REVIEW

**Comment by keradus** [comment]
any thoughts @Seldaek @SpacePossum ?

**Comment by Seldaek** [comment]
Nope I don't see why it would need to touch that space.

**Comment by keradus** [comment]
awesome ! (especially as it conflicting with other rules).

could you prepare a fix for fixer using my utests please?

**Comment by Seldaek** [comment]
Eh I really can't at the moment I only have my phone next few days. If
someone else can great :)

**Comment by keradus** [comment]
I see.
@SpacePossum , would you be able to play with it please?

**Comment by SpacePossum** [comment]
I played around with a bit, but is harder than expected because of the line break attached to the open tag... I would say lets park this one until we figured out; https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/2062
(to prevent wasting dev. time on doing the same thing twice)

**Comment by keradus** [comment]
replaced by #3597

**Pull request closed without merging**
