### PR TITLE
PhpdocAnnotationWithoutDotFixer - add failing cases

### PR DESCRIPTION
**Pull request by keradus**
introduced in #3882

ref https://github.com/symfony/symfony/pull/28814
ref https://github.com/symfony/symfony/pull/28817

### CODE REVIEW

**Comment by keradus** [comment]
@kubawerlos , can you take a look on this one, please ?

**Comment by kubawerlos** [comment]
I see no simple solution for this - the actually broken PHPDoc (with missing `*`) handled in https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3882 IMHO should not be handled in the fixer, but in `DocBlock`/`Tag` class - as all broken PHPDocs should, like the `@return` added in this PR (the content of tag - returned by `Tag` class - is the first line only, so here fixer behaves correctly).

What do you think about reverting #3882 for now, then updating `DocBlock`/`Tag` to allow missing `*` and then getting back to the cases with broken PHPDoc?

**Comment by keradus** [comment]
Changing DocBLock\* has unpredictable consequences :(

**Comment by kubawerlos** [comment]
We could give it a try... or assume that PHPDocs with gaps in asterisk are not handles as its have asterisk where missing => remove both test cases with missing asterisk and revert #3882 "fix".

**Comment by keradus** [comment]
indeed, when asterisks are missing, phpdoc is malformed and let not modify it

**Comment by keradus** [comment]
can you take a look, @kubawerlos ?

**Comment by SpacePossum** [comment]
Thanks @keradus.

**Comment by SpacePossum** [comment]
(not sure why GH doens't state this PR as `merged` but as `closed`)

**Comment by keradus** [comment]
(as I see squashed commit went to target branch, but PR was not updated with squashed commit)

**Pull request closed without merging**
