### PR TITLE
Fixed deployments

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Surely this'll fix it?

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Seems box broke this in their 2.7.3 update when they dropped support for php 5.3 and 5.4.

**Comment by keradus** [comment]
it's not fixing anything... before deploy we install deps once again without prefer lowest but with platform.

**Comment by keradus** [comment]
again, they didn't.
https://github.com/box-project/box2/issues/151
they just wrongly build phar file, installation via composer on 5.3 works fine

**Comment by GrahamCampbell** [comment]
Yeh. I didn't read the first error properly. I understand now what's going on. Even thgen, I'd still recommend this PR even though it doesn't fix this per say.

**Comment by GrahamCampbell** [comment]
> they just wrongly build phar file, installation via composer on 5.3 works fine

They intentionally built it like that according to their release notes.

**Comment by keradus** [comment]
Then it would only add new job to build matrix, pointless

**Comment by GrahamCampbell** [comment]
No, it means our phar doesn't use old dependencies?

**Comment by keradus** [comment]
our phar use as new deps as possible that will still works on 5.3.6

**Comment by GrahamCampbell** [comment]
No it doesn't. It uses prefer lowest, use uses symfony 2.3.0? Am i going crazy?

**Comment by keradus** [comment]
Yes it does. It uses 2.6.x

**Comment by keradus** [comment]
if you don't believe just unpack .phar file and see the files.

**Comment by GrahamCampbell** [comment]
2.6.0?

**Comment by GrahamCampbell** [comment]
I'll take a closer look later. For now, I'll trust that you're right. I have no reason to assume otherwise really. :)

**Comment by keradus** [comment]
depends what is the newest 2.6 during phar creation.

**Pull request closed without merging**
