### PR TITLE
added some failing tests for the Yoda fixer

### PR DESCRIPTION
**Pull request by fabpot**

### CODE REVIEW

**Comment by theofidry** [comment]
@keradus any update regarding this? I share pretty much the opinion of @bgotink (cf. [comment](https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/693#discussion_r20051509)).

The Symfony policy is currently an hybrid between Yoda and non-Yoda conditions. Personally I don't care much that's the policy chosen and that's it. But the current Yoda fixer only support non-yoda conditions and Symfony "hybrid" yoda conditions, no fixer is available for true yoda condtions.

**Comment by Soullivaneuh** [comment]
Personally, I'm :+1: for hybrid Yoda conditions only.

But, we can imagines such fixers:

* [Symfony] hybrid_yoda_condition
* [Contrib] yoda_condition
* [Contrib] reverse_yoda_condition (for people who doesn't want yoda condition at all)

**Comment by theofidry** [comment]
>Personally, I'm :+1: for hybrid Yoda conditions only.

As I said it's not a question of personal opinion, but to give the choice to the user. If Symfony want to use an hybrid fine, but it doesn't have to impose its version to everyone.

>But, we can imagines such fixers:
[Symfony] hybrid_yoda_condition
[Contrib] yoda_condition
[Contrib] reverse_yoda_condition (for people who doesn't want yoda condition at all)

:+1:

**Comment by Soullivaneuh** [comment]
@keradus What do you think about https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/693#issuecomment-146558548?

**Comment by keradus** [comment]
actually today it should be single fixer with bunch of options for each possible revert of order

**Pull request closed without merging**
