### PR TITLE
performance improvement

### PR DESCRIPTION
**Pull request by gharlan**
refs #1604

Here is the comparison for fixing this project itself (using given config, no cache, php 5.6):

https://blackfire.io/profiles/compare/e5a3a321-e328-426c-8a30-bde631dd70cf/graph

Before:

screenshot 2015-12-18 01 34 28

After:

screenshot 2015-12-18 01 33 11

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Pretty sexy/ :+1:

**Comment by sstok** [comment]
:+1: :clap:

**Comment by gharlan** [comment]
Made another improvement. What do you think? The feature was not used anywhere.

New comparison to current master:
https://blackfire.io/profiles/compare/b518187a-1e7a-4274-9c84-c644ab47f290/graph

**Comment by GrahamCampbell** [comment]
Unfortunately, those stats are massively inflated on the reality though. I find that blackfire generally slows down all function calls by a fixed cost, so low cost functions have their call time inflated by blackfire. If you run this code without blackfire, you'll see the difference is much less, but still pretty decent. I found this out while trying to improve the performance of Laravel.

**Comment by gharlan** [comment]
hmm, yes, you're right. Without blackfire the performance gain is much lower.

**Comment by gharlan** [comment]
At the moment the performance gain on my machine is round about 12%.
(without blackfire, fixing project itself, php 5.6 and 7.0)

**Comment by GrahamCampbell** [comment]
Yeh, still a very nice improvement though. :+1: :ship: :rocket:

**Comment by SpacePossum** [comment]
:+1: :shipit: :)

**Comment by keradus** [comment]
Thank you @gharlan.

**Pull request closed without merging**
