### PR TITLE
PhpUnitConstructFixer: handle static calls

### PR DESCRIPTION
**Pull request by Slamdunk**

### CODE REVIEW

**Comment by julienfalque** [comment]
I would merge this as a new feature.

**Comment by Slamdunk** [comment]
> I would merge this as a new feature.

I would not :\\
Let's listen what others say.

**Comment by Slamdunk** [comment]
Rebased to master as per https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3478#issuecomment-365404119

**Comment by keradus** [comment]
Thank you @Slamdunk.

**Pull request merged**
