### PR TITLE
Abstract blank line above fixer.

### PR DESCRIPTION
**Pull request by lucasmichot**
Add an abstract blank line above fixer.
See : https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1696#issuecomment-174186567

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
?

**Comment by lucasmichot** [comment]
?

**Comment by GrahamCampbell** [comment]
PHP-CS-Fixer tends not to accept PRs like this. Only PRs that also include an actual use of it.

**Comment by keradus** [comment]
Closing due to https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1696#issuecomment-182134399

**Pull request closed without merging**
