### PR TITLE
[docs] cookbook - update to current version

### PR DESCRIPTION
**Pull request by TomasVotruba**
- `Symfony/CS` => `src`
- `Symfony/CS/Tests` => `tests`
- Contrib/PSR-2/Symfony are not determined by directory anymore

### CODE REVIEW

**Comment by SpacePossum** [comment]
thanks for picking this up!

closes https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/2404

(hope I can review later)

**Comment by julienfalque** [comment]
This PR should target 2.2 instead of master.

**Comment by TomasVotruba** [comment]
@SpacePossum Thanks. I'm just reading it and getting lost. It's way too long for intro.
So any help to orientate what should be changed is appreciated.

@julienfalque Sure. I switched it. Could you resolve it with the button please?

**Comment by julienfalque** [comment]
@TomasVotruba You need to rebase your branch onto the `2.2` branch.

**Comment by TomasVotruba** [comment]
@juliendufresne That would be too much work for me, doing this from browser. I think you as a merger have "Resolve conflict" button there.

Can send new PR if needed.

**Comment by julienfalque** [comment]
@TomasVotruba There is no "Resolve conflict" button as there is no conflict. But I can handle the rebase if you want.

**Comment by TomasVotruba** [comment]
@juliendufresne Well, maybe that's on merge button. 

No need, I took care of it :) here is new PR:
https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2750

**Comment by keradus** [comment]
> Sure. I switched it. Could you resolve it with the button please?

@TomasVotruba , when you do change a base branch backwards (like here, from 2.3 line into 2.2 line), you PR will contain **all** commits that were available on your branch since it was created on 2.3 line.
When you lower base branch, you need to manually rebase the branch on lower branch. It's not possible via github web interface.

**Comment by TomasVotruba** [comment]
I see, thanks for explainin. 
I did something I write about, not for branch swtiching, but for new commits in target branch. I probably mixed that.

**Pull request closed without merging**
