### PR TITLE
Grammar fix

### PR DESCRIPTION
**Pull request by driesvints**
Just a small grammar fix here.

### CODE REVIEW

**Comment by driesvints** [comment]
Lol whut? Why did this trigger all those failures? 😅

**Comment by kubawerlos** [comment]
@driesvints see the message from failing test.

Did you really expected that such REAMDE is to be updated manually? That it is manually updated with all the new fixers and new options?

**Comment by driesvints** [comment]
@kubawerlos there's a 108 failing tests in the CircleCI test alone and yes I did expect I could simple edit a README of a repo without breaking the entire test suite 😅

**Comment by driesvints** [comment]
Nvm, I just saw the contributing guide. Sorry for not reading that earlier!

**Comment by kubawerlos** [comment]
@driesvints 108? Take a second look:

> FAILURES!
Tests: 19682, Assertions: 452708, Failures: 1, Skipped: 108, Incomplete: 41.

You broke exactly one test, which in its message explains what went wrong:

> 1) PhpCsFixer\Tests\Console\Command\ReadmeCommandTest::testIfReadmeFileIsCorrect
README.rst file is not up to date! Do not modify it manually! Regenerate readme with command: `php php-cs-fixer readme > README.rst`.

**Comment by julienfalque** [comment]
See #4944.

**Pull request closed without merging**
