### PR TITLE
BracesFixer - fix next case

### LINKED ISSUE #1439: Minor cosmetic issue
I just stumbled about a cosmetic issue that I think should be looked after (if it's not caused by my configuration, see below).

**This is the code before running php-cs-fixer:**

```php
class MyClass {
    public function myFunction($foo, $bar)
    {
        return another\package\YourClass::{$foo}($bar);
    }
}
```

**This is after:**

```php
class MyClass {
    public function myFunction($foo, $bar)
    {
        return another\package\YourClass::{$foo}
        ($bar);
    }
}
```

It inserted an additional line-break where, from my understanding, shouldn't be any. This is a cosmetic issue only though; the code is still valid.

**My `.php_cs` config file:**

```php
<?php

$finder = Symfony\CS\Finder\DefaultFinder::create()
    ->files()
    ->name('*.php')
    ->exclude('vendor')
    ->in(__DIR__);

return Symfony\CS\Config\Config::create()
    ->level(Symfony\CS\FixerInterface::PSR2_LEVEL)
    ->fixers(array(
        'psr0',
        'psr1',
        'psr2',
        'duplicate_semicolon',
        'empty_return',
        'multiline_array_trailing_comma',
        'namespace_no_leading_whitespace',
        'new_with_braces',
        'phpdoc_params',
        'remove_leading_slash_use',
        'remove_lines_between_uses',
        'return',
        'single_array_no_trailing_comma',
        'spaces_cast',
        'standardize_not_equal',
        'ternary_spaces',
        'unused_use',
        'whitespacy_lines',
        'align_double_arrow',
        'concat_with_spaces',
        'short_array_syntax',
    ))
    ->finder($finder);
```

### PR DESCRIPTION
**Pull request by keradus**
Fix #1439

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
`continuous-integration/appveyor` should be removed from the required checks on 1.10.

**Comment by keradus** [comment]
I'm curious what's going on with AppVeyor...
Only 1.10 is broken? Why?

**Comment by GrahamCampbell** [comment]
It's not broken. It's not even running, because there is no config file on 1.10.

**Comment by GrahamCampbell** [comment]
You've just missconfigured github's required status stuff on the 1.10 branch.

**Comment by keradus** [comment]
hahahahaha, mea culpa ;D

**Comment by keradus** [comment]
done

**Comment by GrahamCampbell** [comment]
:+1:

**Pull request closed without merging**
