### PR TITLE
BinaryOperatorSpacesFixer - better handling of Arrow Functions 

### PR DESCRIPTION
**Pull request by SpacePossum**
closes https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/6223
closes https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/6220
closes https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/5667
depends on https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6333

### CODE REVIEW

**Comment by keradus** [comment]
> depends on https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6333

6333 got merged

**Comment by SpacePossum** [comment]
thanks, rebased

**Review by GrahamCampbell — APPROVED** [review]

**Comment by SpacePossum** [comment]
Can someone merge this? what is the wait?

**Comment by keradus** [comment]
i was having very limited availability due to personal life topics.
can you reopen @SpacePossum ? I would love to merge it.

let's aim to have a call to see why you cannot merge anymore and let's have it fixed.

**Pull request closed without merging**
