### PR TITLE
Finder - do not search for .xml and .yml files

### PR DESCRIPTION
**Pull request by keradus**
We do not fix that files, they tend to fail on pre-linting, and we should not modify them as they aren't PHP files.

### CODE REVIEW

**Comment by localheinz** [comment]
@keradus 

:+1:

**Comment by localheinz** [comment]
Related to https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1179, see https://github.com/localheinz/PHP-CS-Fixer/commit/cbea63102db1e3ef48f7f19b324f6fddc531aaed.

@keradus 

Happy to rebase my PR once this PR has been merged!

**Comment by keradus** [comment]
Yeah, that was why I send this PR ;)

**Comment by localheinz** [comment]
:rocket:

**Comment by GrahamCampbell** [comment]
:ship:

**Pull request merged**
