### PR TITLE
CI: Fix AppVeyor integration

### PR DESCRIPTION
**Pull request by keradus**

### CODE REVIEW

**Comment by keradus** [comment]
fyi @kubawerlos

**Comment by kubawerlos** [comment]
@keradus weird, `copy` from line 25 was fine and this was failing?

**Comment by keradus** [comment]
copy was not fine, it was working only due to cache on base branch, apparently this one is not optimal also - ref #4916

**Comment by keradus** [comment]
this was the problem i tried to fix here: https://ci.appveyor.com/project/keradus/php-cs-fixer/builds/32097519/job/fh4v254mmxss8r2a#L24

**Pull request merged**
