### PR TITLE
PhpdocAlignFixer - Fix linebreak inconsistency

### LINKED ISSUE #2983: PhpdocAlignFixer - Unix - Windows inconsistency
The following code requires no change on windows and fails on linux:

Windows 10, PHP v. 5.6.25, php-cs-fixer v. 2.4.0
```php
	/**
	 * Desc here
	 *
	 * @param array $xyz Desc here
	 *
	 * @return array Array of data.
	 * [
	 *      [
	 *           'id'          => 1,
	 *           'qty_ordered' => 2,
	 *           'Product' => [
	 *                'id'   => 1,
	 *                'name' => 'xxxx',
	 *            ],
	 *      ],
	 * ]
	 */
	function foo(array $xyz)
	{
		//
	}
```

On linux (several flavors) it does this ugly fix:
Amazon Linux AMI release 2016.09, PHP v. 5.6.29, php-cs-fixer v. 2.4.0
```php
	/**
	 * Desc here
	 *
	 * @param array $xyz Desc here
	 *
	 * @return array Array of data.
	 *               [
	 *               [
	 *               'id'          => 1,
	 *               'qty_ordered' => 2,
	 *               'BaseProduct' => [
	 *               'id'   => 1,
	 *               'name' => 'xxxx',
	 *               ],
	 *               ],
	 *               ]
	 */
	function foo(array $xyz)
	{
		//
	}
```

Ran the fixer using `vendors/bin/php-cs-fixer fix <filename>`

My configuration:
```
return PhpCsFixer\Config::create()
	->setIndent("\t")
	->setLineEnding(PHP_EOL)
	->setUsingCache(false)
	->setRules([
		'array_syntax'                                => ['syntax' => 'short'],
		'binary_operator_spaces'                      => ['align_double_arrow' => true, 'align_equals' => true],
		'blank_line_after_namespace'                  => true,
		'blank_line_before_return'                    => true,
		// 'braces'                                      => true,
		// 'combine_consecutive_unsets'                  => true,
		'concat_space'                                => ['spacing' => 'one'],
		'elseif'                                      => true,
		'full_opening_tag'                            => true,
		'function_typehint_space'                     => true,
		'hash_to_slash_comment'                       => true,
		'line_ending'                                 => true,
		'lowercase_cast'                              => true,
		'lowercase_keywords'                          => true,
		'method_argument_space'                       => true,
		// 'method_separation'                           => true,
		'native_function_casing'                      => true,
		// 'new_with_braces'                             => true,
		'no_blank_lines_after_phpdoc'                 => true,
		'no_blank_lines_before_namespace'             => true,
		'no_closing_tag'                              => true,
		'no_empty_comment'                            => true,
		'no_empty_phpdoc'                             => true,
		'no_empty_statement'                          => true,
		'no_extra_consecutive_blank_lines'            => true,
		'no_leading_import_slash'                     => true,
		'no_leading_namespace_whitespace'             => true,
		'no_multiline_whitespace_around_double_arrow' => true,
		'no_multiline_whitespace_before_semicolons'   => true,
		'no_short_echo_tag'                           => true,
		'no_singleline_whitespace_before_semicolons'  => true,
		'no_spaces_after_function_name'               => true,
		'no_spaces_inside_parenthesis'                => true,
		'no_trailing_comma_in_list_call'              => true,
		'no_trailing_whitespace'                      => true,
		'no_trailing_whitespace_in_comment'           => true,
		// 'no_useless_else'                             => true,
		'no_whitespace_before_comma_in_array'         => true,
		'no_whitespace_in_blank_line'                 => true,
		// 'ordered_class_elements'                      => true,
		'ordered_imports'                             => true,
		// 'phpdoc_add_missing_param_annotation'         => true,
		'phpdoc_align'                               => true,
		'phpdoc_indent'                               => true,
		'phpdoc_no_access'                            => true,
		'phpdoc_order'                                => true,
		'phpdoc_separation'                           => true,
		'phpdoc_trim'                                 => true,
		'phpdoc_types'                                => true,
		'single_class_element_per_statement'          => true,
		'standardize_not_equals'                      => true,
		'trim_array_spaces'                           => true,
		'visibility_required'                         => true,
	])
	->setFinder($finder)
;
```

### PR DESCRIPTION
**Pull request by SpacePossum**
Fixes #2983

### CODE REVIEW

**Comment by keradus** [comment]
any chances to fix tests ?

**Comment by SpacePossum** [comment]
I don't think I've the time needed to fix this soon, as it will take me a long time as I find the fixer hard. Sorry about that.

**Comment by keradus** [comment]
Sure, just asking about state, so we know what we stay on ;)

**Comment by SpacePossum** [comment]
I took out the other failing test because it is a different issue that should be handled in another PR.
This PR should fix the problem with "\n" vs. "\r\n" endings

**Comment by SpacePossum** [comment]
rebased and sqaushed

**Comment by keradus** [comment]
Thank you @SpacePossum.

**Pull request merged**
