### PR TITLE
Renamed whitespacy_lines to no_whitespace_in_blank_lines

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by keradus** [comment]
Oh, and then - `no_whitespace_in_blank_lines` or `no_whitespace_in_blank_line` ?

**Comment by GrahamCampbell** [comment]
> no_whitespace_in_blank_lines

I prefer that and it's more consistent with our other fixer names.

**Comment by keradus** [comment]
OK, let us wait for CI and good to go

**Comment by keradus** [comment]
Thank you @GrahamCampbell.

**Pull request merged**
