### PR TITLE
semicolon_after_instruction,no_unneeded_control_parentheses prio issue

### PR DESCRIPTION
**Pull request by SpacePossum**
expect test to fail and become green again after:
https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2193#issuecomment-248859106

### CODE REVIEW

**Comment by keradus** [comment]
@SpacePossum please always provide information why closing ;)

**Comment by SpacePossum** [comment]
The test is overcomplete, it proves itself as not being needed ^-^

**Comment by keradus** [comment]
it was tricky to figure out that problem. what about keeping the test but moving it to `misc` dir ?

**Comment by SpacePossum** [comment]
good idea, moved :)

**Comment by keradus** [comment]
:+1:

**Comment by keradus** [comment]
Thank you @SpacePossum.

**Comment by SpacePossum** [comment]
thanks @keradus : D

**Pull request merged**
