### PR TITLE
[7.3] PhpUnitDedicateAssertFixer - support PHP 7.3

### PR DESCRIPTION
**Pull request by kubawerlos**

### CODE REVIEW

**Comment by SpacePossum** [comment]
please see https://github.com/SpacePossum/PHP-CS-Fixer/commit/3d7875c3e04329e23b34be8e3f0f0b1430f28c32 as well

**Comment by SpacePossum** [comment]
please add:

```
             [
                 '<?php $this->assertInternalType(\'array\', $a,);',
                 '<?php $this->assertTrue(is_array($a,),);',
             ],
```

as these are fixed through a different path

**Comment by kubawerlos** [comment]
@SpacePossum I've added your test cases

**Comment by keradus** [comment]
Thank you @kubawerlos.

**Pull request merged**
