### PR TITLE
Added TrimArraySpacesFixer

### PR DESCRIPTION
**Pull request by keradus**
Replaces #1039

### CODE REVIEW

**Comment by jaredh159** [comment]
thanks. I was having trouble sorting out the mess I made.

**Comment by keradus** [comment]
no problem, glad to be helpful

**Comment by GrahamCampbell** [comment]
Travis failing due to bad cs in php-cs-fixer, lol. :)

**Comment by keradus** [comment]
fixing itself show error of this new fixer, new testcase have been already added

**Comment by keradus** [comment]
fixed

**Comment by GrahamCampbell** [comment]
:+1:

**Comment by keradus** [comment]
Thank you @jaredh159.

**Pull request merged**
