### PR TITLE
PhpdocToParamTypeFixer - fix for void as param

### PR DESCRIPTION
**Pull request by kubawerlos**
Is the test correct?

### CODE REVIEW

**Comment by SpacePossum** [comment]
`Fatal error: void cannot be used as a parameter type in`

maybe this fixer needs the syntax-checker you wrote as well?

**Comment by kubawerlos** [comment]
For that it will help, but not for the error you can see in Travis:
```
1) PhpCsFixer\Tests\Fixer\FunctionNotation\PhpdocToParamTypeFixerTest::testFix with data set "void as type" ('<?php /** @param void $bar */...ar) {}', '<?php /** @param void $bar */...ar) {}')
The token at index 7 must be:
{
    "id": 319,
    "name": "T_STRING",
    "content": "void",
    "isArray": true,
    "changed": false
},
got:
{
    "id": null,
    "name": null,
    "content": "void",
    "isArray": false,
    "changed": false
}.
Failed asserting that false is true.
```

**Comment by SpacePossum** [comment]
but the fixer should not never try to put `void` as type right?

**Comment by keradus** [comment]
Thank you @kubawerlos.

**Pull request merged**
