### PR TITLE
Remove trailing whitespace from comments

### PR DESCRIPTION
**Pull request by simoheinonen**

### CODE REVIEW

**Comment by SpacePossum** [comment]
Hi,
Are you sure the `no_trailing_whitespace_in_comment` isn't doing the same thing?

**Comment by GrahamCampbell** [comment]
> Remove trailing whitespace from comments

This change doesn't work in multiline comments.

**Comment by GrahamCampbell** [comment]
> Are you sure the no_trailing_whitespace_in_comment isn't doing the same thing?

Yes, this should be closed.

**Comment by GrahamCampbell** [comment]
This change also cannot be allowed into this fixer anyway because it is not in PSR2, and this fixer is a strictly PSR-2 only fixer.

**Comment by simoheinonen** [comment]
Hmm, yes that looks like what I'm after for. For some reason one comment wasn't fixed when I ran the fixer. I'll look more into it why that happened.

**Comment by simoheinonen** [comment]
PSR2 2.3. Lines

> There MUST NOT be trailing whitespace at the end of non-blank lines.

**Comment by GrahamCampbell** [comment]
PSR2 is referring to actual whitespace tokens. The whitespace at the end of comments is actually included as a comment, as it not treated as whitespace by PHP's parser.

**Comment by SpacePossum** [comment]
thanks for reporting back @simoheinonen , good to hear you found the issue and a solution :)

**Pull request closed without merging**
