### PR TITLE
Fixed a few file headers

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
fabbot.io isn't happy with ShortTagFixerTest.php. Not sure what we can do about this. Both are false positives.

**Comment by keradus** [comment]
wow, how? it works here: #1015

**Comment by GrahamCampbell** [comment]
fabbot.io only analyses changed files I assume. :)

**Comment by keradus** [comment]
yeah, indeed, forgot that ;)

**Comment by keradus** [comment]
Thank you @GrahamCampbell.

**Pull request merged**
