### PR TITLE
[WIP] Add ReturnAssignmentFixer

### PR DESCRIPTION
**Pull request by SpacePossum**
Taking this fixer for a run by Travis.
It is still WIP, however please state if you do or do not want this fixer to be added to the fixer project (after it would be finished of course).
Target is master because I need the fixed `Token:equals`.
There are hits on SF in 16 files (2.3 current).

Fixes var assignments that are return directly, for example:

Expected:
```php
<?php
return 1;
```

Input:
```php
<?php
$a = 1;
return $a;
```

TODO;
- [ ] integration tests and priority fixing
- [ ] only fix within functions/methods and do not touch `static` or `global` variables

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Does this case fail?

```php
<?php

function foo ($bar)
{
    $a = 123;
    if ($bar)
        $a = 12345;
    return $a;
}
```

**Comment by rob006** [comment]
You can't do that for any global var - `$a` can be used in other files and removing assignment can change behavior of code.

**Comment by SpacePossum** [comment]
>Does this case fail?

nope, I've added your code to the utest https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1853/files#diff-92916bea59cd94be6dfa75d1d7d22ec9R133 thanks for pointing it out :)

>You can't do that for any global var - $a can be used in other files and removing assignment can change behavior of code.

Thanks for reporting, I going to look into it :+1:

**Comment by GrahamCampbell** [comment]
I'd say global variables should NEVER be used, so this is fine. Maybe we could just mark the fixer as risky and say that crappy code may be modified incorrectly.

**Comment by keradus** [comment]
We could easily detect if the variable is imported from globals

**Comment by rob006** [comment]
> I'd say global variables should NEVER be used, so this is fine

You almost always have some global variables, because when you create file like
```php
<?php
$config = require __DIR__ . '/config.php';
App::run($config);
```
you have global var `$config`.

**Comment by keradus** [comment]
I think we are already having some fixers that touch code only inside functions/methods

**Comment by gharlan** [comment]
another "nice" test case (reference parameter):

```php
function foo(&$a)
{
    $a = 1;
    return $a;
}
```

**Comment by SpacePossum** [comment]
thanks all for looking, I'll re-open after I've reworked this one (might take a while...)

**Pull request closed without merging**
