### PR TITLE
Fix CS in cookbook

### PR DESCRIPTION
**Pull request by ntzm**

### CODE REVIEW

**Comment by keradus** [comment]
it was there on purpose with later request to call fixer itself to fix all the work

**Comment by ntzm** [comment]
Ah, that makes sense. Sorry!

**Comment by SpacePossum** [comment]
@ntzm thanks for PR'ing, I thought the same until @keradus pointed it out, no need for sorries here :D

**Comment by keradus** [comment]
remember, CS we use are changing during time, no need to always update sample code, if we could just ask to run the tool and it will fix not only empty skeleton of fixer, but also whole user-added logic

**Pull request closed without merging**
