### PR TITLE
Update README.rst

### PR DESCRIPTION
**Pull request by fitzel**
needs an Update, took me a while to figure out that the autoloader was not actually broken ;)

### CODE REVIEW

**Comment by SpacePossum** [comment]
Thanks for reporting. It seems the README is indeed not correct, not for 1.x and not for master as well.
Could you change the code that generates the README on 1.x?
(around https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/1.12/Symfony/CS/Console/Command/FixCommand.php#L192) 

and than regenerate the README;
```
php php-cs-fixer readme > README.rs
```
(https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/1.12/CONTRIBUTING.md)

**Comment by keradus** [comment]
Why it's not correct?

**Comment by gharlan** [comment]
@fitzel I guess you are using 1.11.x, so you should look to that branch: https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/1.11/README.rst

1.12 is not yet released, but there are new classes for config and finder, and the old ones are deprecated.
So the 1.12 readme is correct for 1.12.

**Comment by GrahamCampbell** [comment]
Yeh, this PR isn't right.

**Comment by keradus** [comment]
Thank you @fitzel, please follow @gharlan solution ;)

**Comment by fitzel** [comment]
yep, thats my bad, sry guys! shouldve seen the version diff

**Pull request closed without merging**
