### PR TITLE
NoBreakCommentFixer - fix edge case

### PR DESCRIPTION
**Pull request by keradus**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Perhapse a better way to write this fixer is to find the end of switch blocks, then backward iterate them?

**Comment by GrahamCampbell** [comment]
Unrelated to this PR ish, but what about this test case:

```php
<?php

$foo = 1;

switch ($foo) {
    case 1:
?>
<?php
    default:
        echo 'lol';
}
```

**Comment by keradus** [comment]
don't know, tbh don't care, we don't test such cases at all.
if you care and if it's failing - open a PR.
from my perspective - we could skip files containing multiple php code mixed with html

**Comment by julienfalque** [comment]
Actually the test case suggested by @GrahamCampbell was failing so I added it.

**Comment by keradus** [comment]
Thank you @julienfalque.

**Pull request merged**
