### PR TITLE
DX: Use "yield from" in tests

### PR DESCRIPTION
**Pull request by kubawerlos**
The scenario is almost always the same, huge array `$tests` and the `foreach` with `yield` and some `if` after:
```php
        $tests = [/** ... */];

        foreach ($tests as $index => $test) {
            yield $index => $test;
        }

        if (\PHP_VERSION_ID < 80000) {
```

### CODE REVIEW

**Review by julienfalque — APPROVED** [review]
I would argue we should extract conditional cases into dedicated providers with `@require` annotations, but this can be done later.

**Comment by kubawerlos** [comment]
> I would argue we should extract conditional cases into dedicated providers with `@require` annotations, but this can be done later.

I'd like to discuss it, so we have some order in tests/providers, so when bumping lowest PHP version we have [this](https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5902), not [this](https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5906).

**Comment by keradus** [comment]
i'm open to discuss how to have conditional tests existing, but IMHO it's good value to see some tests were skipped due to missing requirements.

it;s different to say " 100 / 100 tests passed" vs "100 / 150 tests passed and 50 could not be executed due to not fulfilled requirements"

**Review by keradus — APPROVED** [review]
anyway, good cleanup

**Comment by keradus** [comment]
Thank you @kubawerlos.

**Comment by kubawerlos** [comment]
> it;s different to say " 100 / 100 tests passed" vs "100 / 150 tests passed and 50 could not be executed due to not fulfilled requirements"

what I would REALLY like is to have a way to get reported tests that are skipped in every PHP version we support (like the removed one with `@requires PHP <7.0` from https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5902).

**Pull request merged**
