### PR TITLE
minor: prevent BC break in ErrorOutput

### PR DESCRIPTION
**Pull request by keradus**
https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6581/files#r969271629

### CODE REVIEW

**Comment by keradus** [comment]
cc @jrmajor

**Review by SpacePossum — APPROVED** [review]

**Comment by jrmajor** [comment]
> https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6581#discussion_r969271629: we don't know that function is actually present. 

@keradus I've derived these types from the PHPStan stubs (https://github.com/phpstan/phpstan-src/blob/da5db91da8893569117a94dffcb30c9b91de7c63/stubs/Exception.stub#L29-L33), as I've written in https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6581#discussion_r955073289.

I know PHPStan isn't the source of truth, so I've dived deeper and found the function responsible for generating backtraces: https://github.com/php/php-src/blob/7dbefe2cebf2461503e6a6260f8c348cb57ad997/Zend/zend_builtin_functions.c#L1704. The `function` key is added inside a conditional, but both `if` and `else` paths end up adding the `function` key, on lines 1794 and 1880 respectively.

We don't have to be concerned about users passing an array without the `function` key too, as this method is private and we only call it with frames from `Throwable::getTrace()`.

**Comment by keradus** [comment]
> We don't have to be concerned about users passing an array without the `function` key too, as this method is private and we only call it with frames from `Throwable::getTrace()`.

I will take extreme here - it is _now_ the case. But code will change. And one day, someone will pass an argument that is not coming directly from `getTrace()`. Until `getTrace()` is returning strongly-typed result on language level, that we can use to type input parameter for `outputTrace()`, we are stucked with `array` type. And with this, it may have any keys inside and I will prefer to validate the input, rather than assuming it on phpdoc level.

**Comment by jrmajor** [comment]
> And one day, someone will pass an argument that is not coming directly from `getTrace()`. 

The whole point of using PHPStan is so that it can warn us in such cases.

**Comment by keradus** [comment]
So we use it for that ;) yet, it's not possible yet to crash during compilation or execution time of given code itself, it's only a side tool. Maybe one day ;)

**Comment by SpacePossum** [comment]
Yeah I think the intentions, research and all efforts into the change were and are very good, no question about it :+1: 

However, taking the more defense programming route from @keradus here seems reasonable to me. The cost of it, extra `isset` checks, is so minimal that keeping it for more future proof (or other VM proof) outweighs the SCA trigger for me.

Hope in the future the PHP API itself will return some DTO and not some (array) hash so we can be more strict about it without relying on checking the internal code and such.

Still like the involvement very much, nice and important to keep a clean code base :)

**Pull request merged**
