### PR TITLE
Specified line endings in .gitattributes.

### PR DESCRIPTION
**Pull request by adawolfa**
I suggest specifing line endings into `.gitattributes` file, otherwise hundreds of tests don't pass.

### CODE REVIEW

**Comment by keradus** [comment]
https://github.com/composer/composer/blob/master/.gitattributes

**Comment by keradus** [comment]
?

**Comment by adawolfa** [comment]
I have overlooked the link target, I'm sorry! Aren't those lines sufficient?

**Comment by keradus** [comment]
Currently the control of white characters are checked by fixer itself.
If we want to go with git as well - why not use more advanced checks?

**Comment by adawolfa** [comment]
Well, I think those additional options don't make any difference when checking out files. Line ending option does. When I switched EOL to LF via git config, I had to re-checkout all files. Then all tests passed.

**Comment by keradus** [comment]
it disallows you to add the file with tabs, for example

**Comment by SpacePossum** [comment]
if we start with `.gitattributes` I'm :+1: for making it as complete as possible, so adding the other lines as well

**Comment by keradus** [comment]
@adawolfa
could you update ?

**Comment by SpacePossum** [comment]
btw. if take
```
*.yml   text eol=lf whitespace=blank-at-eol,blank-at-eof,space-before-tab,tab-in-indent,tabwidth=2
```

we should update;
https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/1.12/.travis.yml
https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/1.12/appveyor.yml

as these are indented with 4 and not 2 spaces

**Comment by keradus** [comment]
```diff
-*.yml   text eol=lf whitespace=blank-at-eol,blank-at-eof,space-before-tab,tab-in-indent,tabwidth=2
+*.yml   text eol=lf whitespace=blank-at-eol,blank-at-eof,space-before-tab,tab-in-indent,tabwidth=4
```

magic ;)

**Comment by keradus** [comment]
Replaced by #2188

**Pull request closed without merging**
