### PR TITLE
Create @Symfony:risky ruleset

### PR DESCRIPTION
**Pull request by keradus**
ref #2118

### CODE REVIEW

**Comment by SpacePossum** [comment]
:+1:

**Comment by SpacePossum** [comment]
Do we need an overall integration test for this ruleset?

**Comment by keradus** [comment]
Symfony integration tests was created on 1.x line with the following reasoning:
- oh boy, we have so many fixers, some of them may conflicts one another ! or have priority issues ! we don't know
- we have priority tests, but only for those we know that should be in given order
- let us create a big integration tests with a lot of fixers
- oh, most of the fixers are inside Symfony ruleset, let us use it!

So the reasoning was to test most fixers, not to test Symfony ruleset.

Here, the case is different - only 3 rules

**Comment by SpacePossum** [comment]
Thanks! :)

**Pull request merged**
