### PR TITLE
Introduce @PhpCsFixer ruleset

### PR DESCRIPTION
**Pull request by keradus**

### CODE REVIEW

**Comment by keradus** [comment]
does it make sense ?

**Comment by GrahamCampbell** [comment]
Err, no?

**Comment by GrahamCampbell** [comment]
The ruleset of this tool is not one other people are going to want to use I imagine?

**Comment by SpacePossum** [comment]
looking at my own projects (I use with just a few minor changes) I'm +1,
but I'm not sure about how much others use it.

**Comment by keradus** [comment]
I also use it in every single project.
Our ruleset is basically: Symfony hard rules (so `@Symfony`), Symfony soft rules (applied only in new codebase, not in whole repo, due to merging issues) and strict fixers

**Comment by SpacePossum** [comment]
please rebase and :ship: :)

**Comment by teohhanhui** [comment]
This will only create more confusion for the users. :smile:

**Comment by julienfalque** [comment]
I'm not sure I want this feature.

The name suggests that the ruleset is internal, or at least it does not really give a clue about the rules one can expect from it.

It enables the `array_syntax` rule with `long` syntax while most recent projects will use the `short` syntax so they will still need to override this rule.

Creating this ruleset will require to maintain BC on it afterwards. This mean we won't be able to change anything in it except adding new rules. So if we want to change the way we fix the project itself, we will have to override some rules in our config file instead of tweaking the ruleset, defeating its purpose.

**Comment by SpacePossum** [comment]
@keradus sorry man, gonna close this one after discussion. Lets see if we can get up with another way to make it easy to share this ruleset as I do like/use it : )

**Pull request closed without merging**
