### PR TITLE
Align @property PHPDoc tags

### PR DESCRIPTION
**Pull request by ntzm**
See #1492

### CODE REVIEW

**Comment by keradus** [comment]
I'm afraid this changes the behaviour and for that shall be optional

**Comment by ntzm** [comment]
I'd say it fixes behaviour, this is how I'd expect it to work

**Comment by julienfalque** [comment]
`@property` is not listed in the current description and it was never documented as supported by the fixer so it's a new feature, not a bugfix. But I agree it would make sense to enable it by default anyway. Is there a specific reason it was not implemented before?

**Comment by ntzm** [comment]
Maybe we could make this fixer configurable and allow the user to decide which tags they want to align?

**Comment by SpacePossum** [comment]
>Maybe we could make this fixer configurable and allow the user to decide which tags they want to align?

I think that is what @keradus meant :)  

> Is there a specific reason it was not implemented before?

AFAIK no, prop, no one find time to make it

**Comment by ntzm** [comment]
I'll have a go at making it configurable tonight. In terms of backwards compatibility, if no options are passed should it behave like it currently does (all but `@property`)?

**Comment by keradus** [comment]
Default config should be like current behaviour. It can be changed in future on 3.x line.
Just please, don't make `include_property` or sth like this config key. Keys should be as much generic as possible, like `[tags => return, var, ...]` or sth

**Comment by ntzm** [comment]
Gonna close this and open up a new one tonight 👍

**Comment by keradus** [comment]
ping @ntzm

**Comment by ntzm** [comment]
Got a bit stuck on stuff last night, is there a place I can ask noob questions?

**Comment by SpacePossum** [comment]
You can find us on gitter; fixer channel:
https://gitter.im/FriendsOfPHP/PHP-CS-Fixer
but you can send also direct messages to people.
I try to be there a bit today :)

**Pull request closed without merging**
