### PR TITLE
CS

### PR DESCRIPTION
**Pull request by SpacePossum**

### CODE REVIEW

**Review by kubawerlos — CHANGES_REQUESTED** [review]
Hold on, let's fix the fixer that should add it.

**Comment by SpacePossum** [comment]
the fixer is fine, I forgot to running the tool when merging upstream from 2.19

**Review by kubawerlos — COMMENTED** [review]
Oh, I see

**Review by kubawerlos — APPROVED** [review]

**Comment by keradus** [comment]
I found more cases by psalm - PR replaced by #5739. thanks for spotting the issue!

**Comment by kubawerlos** [comment]
@keradus this raises a question why not introduce psalm to every build? On `3.0` branch type coverage is 97.2463%, so not far from fully typed codebase.

**Comment by keradus** [comment]
on my setup i see plenty of psalm changes i don't actually l like to have, I do not have a time to work to polish that.

**Pull request closed without merging**
