### PR TITLE
DX: update composer-normalize

### PR DESCRIPTION
**Pull request by keradus**

### CODE REVIEW

**Review by SpacePossum — APPROVED** [review]

**Comment by SpacePossum** [comment]
Thank you @keradus.

**Comment by keradus** [comment]
extra note: looks like PRs started failing on new normaliser version. Was this change expected, @localheinz ?

**Comment by localheinz** [comment]
@keradus 

Apologies for the delay, I have quite busy these last months. 

Thanks to some reordering of the original Schema as provided by `composer/composer`, these changes are expected. 

See https://github.com/ergebnis/composer-normalize/issues/779.

**Comment by keradus** [comment]
delay? what delay? you are way faster than me ;)

thanks for context!

**Pull request merged**
