### PR TITLE
[WIP] Add CombineConsecutiveImportsFixer.

### PR DESCRIPTION
**Pull request by SpacePossum**
Expected
```php
<?php
    global $a, $b;
```

Input
```php
<?php
    global $a;
   global $b;
```

TODO: priority checks and integration tests

### CODE REVIEW

**Comment by keradus** [comment]
:-1: for touching globals at all.

**Comment by SpacePossum** [comment]
could you explain why?

**Comment by keradus** [comment]
Globals should not be used at all. 
I don't like fixers that support bad practices.

**Comment by GrahamCampbell** [comment]
I agree with @keradus.

**Comment by SpacePossum** [comment]
What about short tags, we support those?

I would like it in, because I deal with a lot of legacy code which contains globals.
Anyway, the fixer is at contrib so I see no issue, however if no one else see a use in than lets drop it.

**Comment by keradus** [comment]
short tags fixer is different. short tags fixer say "ok, so I will recognize your ugly short tag and fix it with full tag".

fixer in this PR is "ok, so I will recognize your ugly globals and keep them ugly"

**Comment by SpacePossum** [comment]
>"ok, so I will recognize your ugly globals and keep them ugly"

"ok, so I will recognize your ugly globals and make them less ugly."

I'm not writting globals (here, and the fixer isn't neither), I just have to deal with those. The fixer is part of Friends Of PHP, globals are part of PHP. I really don't see why you are stonewalling this on contrib level,

**Comment by keradus** [comment]
And then some less experienced developer, after having fun with globals and asked to stop doing it will say "but I saw that other use them too, there are even rules how you should write them!".
Really, I had situations like this few times.

You want to introduce coding style rule "combine your globals", while rule should be "don't use globals".

------------------------------------------------------------------------------------------------------------------------------------------

In the end remember that this tool is driven by community. There were few situations where I, personally, didn't like the PR but community does so we merge it. If the community will want it we will have it. For now there are just 3 opinions.

**Comment by GrahamCampbell** [comment]
We should make some troll fixer for april 1st that just delete all global variables, and all variables that are snake_case. :P

**Comment by SpacePossum** [comment]
Alright, I like to ask the community about 2 other rules as well before PR-ing it.

First;
Expected
```php
<?php
global $a, $b;
```
Input
```php
<?php
global $a,      $b   ;
```

Second;
Expected
```php
function test()
{
    global $t, $t1, $t2;

    return $t + $t1 + $t2;
}
```

Input:
```php
function test()
{
    global $t, $t1;
    return $t + $t1 + $t2;
}
```

**Comment by keradus** [comment]
first one: 0
second one: :-1: (cmon, `$t2` is not global, don't create new one!)

**Comment by SpacePossum** [comment]
update the case, I did not meant to create the new global; the fix is about having an empty line after the global at the start of a function

**Comment by Slamdunk** [comment]
:-1:

**Comment by gharlan** [comment]
:-1: for adding fixers related to `global`.

**Comment by SpacePossum** [comment]
thanks all for your input :+1:

**Comment by Slamdunk** [comment]
@SpacePossum to waste your hard work, you can reuse this code for [`static`](http://php.net/manual/it/language.variables.scope.php#language.variables.scope.static), which is totally acceptable :wink:

**Comment by keradus** [comment]
:+1: for static

**Pull request closed without merging**
