### PR TITLE
Clarify error message and how to fix

### PR DESCRIPTION
**Pull request by josephzidell**
The current error message about risky behavior is a bit unclear about passing a `yes|no` value. This clarifies it

### CODE REVIEW

**Comment by SpacePossum** [comment]
Looks like a nice clarification to me, thanks :)

**Comment by keradus** [comment]
shall be 2.12, also, please run `php php-cs-fixer readme > README.rst`

**Comment by SpacePossum** [comment]
sorry, tried to be clever but changing the base branch didn't work out

**Comment by keradus** [comment]
using github UI only to change base branch to older branch won't bring anything good, you will also need to rebase the commits on top of new target branch

**Comment by josephzidell** [comment]
I can create a new PR for `2.12`

**Comment by josephzidell** [comment]
I can create an new PR for `2.12`, but will need to close this one first.

**Pull request closed without merging**
