### PR TITLE
[WIP] remove HHVM hacks

### PR DESCRIPTION
**Pull request by keradus**

### CODE REVIEW

**Comment by stof** [comment]
Looks like these HHVM checks are still necessary.

**Comment by keradus** [comment]
Yeah, when the current hhvm-dev will become stable I will update min HHVM version and remove WIP flag

**Comment by keradus** [comment]
http://docs.travis-ci.com/user/build-environment-updates/2015-04-09/
> Schedule 2015-04-27 15:00 UTC
> HHVM 3.5.0 → 3.6.1

**Comment by stof** [comment]
@keradus this environment update has been canceled

**Comment by keradus** [comment]
Replaced by #1465

**Pull request closed without merging**
