### PR TITLE
DX: php_unit_test_case_static_method_calls - use default config

### PR DESCRIPTION
**Pull request by keradus**
ref https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3476/files#r176360233

please vote

### CODE REVIEW

**Comment by keradus** [comment]
ping @FriendsOfPHP/php-cs-fixer

**Comment by SpacePossum** [comment]
:-1:  as most of the ((F)OSS) project I work on use `$this->`, I also like the current style better. All in all a matter of taste I think ;)

**Comment by keradus** [comment]
so, let me remind what I referenced into:
1. we are already using self:: and static::, eg in our custom assertions, in which we can't use `$this->`, as our methods are static
2. SCA tools got confused by calling static method on `$this`

**Comment by SpacePossum** [comment]
@keradus you've the majority of the voted, congrats!  :D 
can you prepare this PR again so it can be merged? thanks!

**Comment by keradus** [comment]
would you want it to target `master` or LTS branch ?

**Comment by SpacePossum** [comment]
I would vote LTS as to have least number of differences between the branches

**Comment by keradus** [comment]
done

**Comment by kubawerlos** [comment]
Thank you @keradus

**Pull request merged**
