### PR TITLE
[Feature, 1.11] Add 'for' semicolon fixer.

### PR DESCRIPTION
**Pull request by SpacePossum**
Add fixer for spacing around semicolons in a `for` loop

 @ see https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/1564

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
It'll end up in 1.12 btw. ;)

**Comment by keradus** [comment]
as stated [here](https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/1564#issuecomment-161709858), there should be two fixers: one that remove spaces before `;`, one that add spaces after `;`, and both should not care is there is an `for` or not..

**Comment by SpacePossum** [comment]
>one that add spaces after `;`, and `[...]` should not care is there is an for or not..

that one will create a lot of trailing whitespace.....

**Comment by gharlan** [comment]
> one that remove spaces before `;`

https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/1.12/Symfony/CS/Fixer/Symfony/SpacesBeforeSemicolonFixer.php

> one that add spaces after `;`

that one is missing

> that one will create a lot of trailing whitespace.....

Add single space if there is no whitespace.

**Pull request closed without merging**
