### PR TITLE
Changes in 3.0: stop exporting files from tests folder in distributions

### PR DESCRIPTION
**Pull request by hannesvdvreken**
Follow up of #5079

### CODE REVIEW

**Comment by hannesvdvreken** [comment]
TBH that's the most rude and uninclusive response a maintainer ever replied to me. 

You're never seeing me here again...

**Comment by kubawerlos** [comment]
> most rude and uninclusive response a maintainer ever replied to me

@hannesvdvreken I'm not a maintainer - just a guy who spams a lot of pull request (with passing checks). I'd call my comment honest and definitely less arrogant than the one from your  [initial](https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5079) pull request.

I simply wonder what were you thinking when you saw these complicated exclude rules? Was it "haha, idiots, they must have done it without a reason, I will show them how to make it right"? Because I can't find other explanation.

> You're never seeing me here again...

So we won't have any more pull request with random changes and failing checks? I can't say I will cray about it ;)

**Comment by hannesvdvreken** [comment]
> "haha, idiots, they must have done it without a reason, I will show them how to make it right"

Not at all. Was simply interested to know why and if there was a plan to simplify it. Afaik tests are not/never for public use. I could have sent a simple issue but that's more likely to get ignored.

> So we won't have any more pull request with random changes and failing checks? I can't say I will cray about it ;)

Your parents must be proud to have raised such a charitable person like yourself. Congratulations.

**Comment by kubawerlos** [comment]
> Was simply interested to know why

And creating pull request is the best way to find out? You could have clone the repo, make the changes and run tests locally. Then track the failing test to the [PR](https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4262) to learn the reason.

> tests are not/never for public use

Julien already explained the reason: https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5079#issuecomment-667210023

> Your parents must be proud to have raised such a charismatic person like yourself.

Yep, they must...

**Pull request closed without merging**
