### PR TITLE
type hinting that \PhpCsFixer\Config::getFinder() can return \PhpCsFi…

### PR DESCRIPTION
**Pull request by SignpostMarv**
type hinting that \PhpCsFixer\Config::getFinder() can return \PhpCsFixer\Fixer

### CODE REVIEW

**Comment by SpacePossum** [comment]
The SCA failure on Travis seems unrelated to this PR. Could you rebase your branch to the latest of 2.8 to see if it helps?

**Comment by keradus** [comment]
it was for 2.8 : https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3301 
I aksed for 2.2, as if we would accept this change, then only for 2.2 target branch

**Comment by SignpostMarv** [comment]
Does this still need rebasing?

**Comment by keradus** [comment]
Don't bother with rebases here.
What is needed here is not to fix docblock to match fuzzy logic of phpstan, but to actually investigate the code do we really support both, collection of SplFileInfo and strings equally or not, and if so why, maybe with possibility to improve it.

**Comment by SignpostMarv** [comment]
@keradus tl:dr; "is finder overkill?" ?

**Comment by keradus** [comment]
finder is wrapper for iterable and adding finder here is solving an issue just for fuzzy phpstan logic due to issues fully discussed in referred issue.

SplFileInfo vs string case could be a thing that needs investigation indeed, and side effect of it could be solving in-place confusion of phpstan as well.

**Comment by SignpostMarv** [comment]
@keradus in faffing around with my package trying to get a workaround, have discovered that 2.9 doesn't support `string[]` as per documentation of `PhpCsFixer\ConfigInterface::setFinder()`, but does support `SplFileInfo[]`

**Comment by keradus** [comment]
yet, `string[]` might be supported if one provides a pure array, not Finder instance.
as said, I need to take deeper look to know shall we merge your docs update or drop string in first place -
 it's one of oldest code in out project.

I must admit it's not a prio for me on end-of-the-year time. Please be patient.
no need for further actions from your side here (like merges/rebases)

**Comment by SignpostMarv** [comment]
@keradus When providing the pure `string[]` array. `FileFilterIterator` line 56 assumes `SplFileInfo[]`, leading to a fatal error.

**Comment by keradus** [comment]
Thanks for checking @SignpostMarv . Removal of wrong `string[]` in docs has been done in #3415, thus I'm closing this PR.

**Pull request closed without merging**
