### PR TITLE
bug: Fix 3 weird behavior about BinaryOperatorSpacesFixer

### PR DESCRIPTION
**Pull request by VincentLanglet**
Solve https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6444#issuecomment-1167578049
and https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6445#discussion_r907618897

cc @SpacePossum and @julienfalque

### CODE REVIEW

**Comment by SpacePossum** [comment]
can we please look into the other 2 merged PR's first before this one? If not, than it is fine by me, but at the same time I'm just saying I'm not likely to prioritize this anytime soon.

**Comment by VincentLanglet** [comment]
> can we please look into the other 2 merged PR's first before this one? If not, than it is fine by me, but at the same time I'm just saying I'm not likely to prioritize this anytime soon.

Dunno why you're trying to blackmail about my PR like this.

I proposed two bug fixes with tests. They were merged.
- One of them discovered an existing bug
- The other introduced a bug, because there was no test about it.
With this PR both of them are solved and there is now tests about those situations.
All I see overall is an improvement of this fixer with a total of 4 bug fixes.

**Comment by VincentLanglet** [comment]
BTW:
https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6444 solved
- https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/3986

https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6445 solved
- The example 2 and 3 of https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/6379

I just introduced a similar fix for double arrow (only checking the first double arrow of a line) and it solves: 
- https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/6351
- https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/5020
- https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/5667

I assume the same king of fix I introduced here (by using a currentLevel when opening an array) could be used  to solve 
- https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/5648
- https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/6379 (the example 1)
- https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/5896
- https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/6223
- https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/5980
but I prefer to do it on another PR to avoid too much changes.

**Comment by VincentLanglet** [comment]
> lets call it a day, we see things different

Sorry for not following your reasoning. I do appreciate your interventions and I was pretty sure you would find use case for the code I modified. I had in mind to fix those, that's why I do it here, even if the previous PR is merged.

> good luck with the people who can merge 👍

Thanks

**Comment by VincentLanglet** [comment]
@keradus @julienfalque I saw you release https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/tag/v3.9.1

I would have hope this PR to be merged before, because it fixes possible bugs reported as
https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6444#issuecomment-1167578049
https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6445#discussion_r907618897

**Review by julienfalque — APPROVED** [review]

**Comment by julienfalque** [comment]
Thank you @VincentLanglet.

**Comment by VincentLanglet** [comment]
You're welcome. I'll see if I can solve

- https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/6220
- https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/5648
- https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/6379
- https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/5896
- https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/6223
- https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/5980

now

**Comment by VincentLanglet** [comment]
I opened https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6515 for four of them

**Pull request merged**
