### PR TITLE
DX: ProjectCodeTest - shall not depends on xdebug/phpdbg anymore

### PR DESCRIPTION
**Pull request by keradus**
shall not be needed anymore after #3789 and #3791

### CODE REVIEW

**Comment by keradus** [comment]
Thank you @SpacePossum.

**Comment by SpacePossum** [comment]
thank you @keradus , I think the merge script is off since I didn't do anything here ;)

**Comment by keradus** [comment]
you did "master to PR merge" via gh interface, then `gh` decided to squash the commits, pick first author that was not the merger, thus... you ;P

**Comment by SpacePossum** [comment]
haha nice case : D

**Pull request merged**
