### PR TITLE
Bug-fix for is_null() edge cases

### PR DESCRIPTION
**Pull request by kalessil**

### CODE REVIEW

**Comment by keradus** [comment]
Thanks for picking this up.
Could you please squash all commits of yours ?

**Comment by SpacePossum** [comment]
ref.: https://github.com/kalessil/PHP-CS-Fixer/pull/1

**Comment by kalessil** [comment]
@keradus : when you merge a PR, you can squash it right in GitHub interface.

@SpacePossum: will merge your PR in the evening, I totally forgot about the AbstractFunctionReferenceFixer class, thanks!

**Comment by SpacePossum** [comment]
>when you merge a PR, you can squash it right in GitHub interface.

yes, but it doesn't allow for more controlled squashing, like keeping one commit for each author :)

**Comment by kalessil** [comment]
Hm, if I squash then it'll be also just 1 commit authored by me.
Do you mean that it's possible to squash commits grouping bu author?

**Comment by SpacePossum** [comment]
From the command line using git you can squash the commits the way you want, making groupings based on authors or some other grouping.
For example if you checkout this branch and use `git rebase HEAD~10 -i` you can squash only the last 8 commits into the second comment and leave the first one what it is.

**Comment by kalessil** [comment]
Ok, I thought there is another way to do it.

**Comment by keradus** [comment]
@kalessil, merging via github interface with squashing will squash all commits into first one (so here, it would be @localheinz). I asked to squash all commit of yours, so 1st commit will still be authored by @localheinz , then one commit of yours, then maybe one of @SpacePossum (related sub-PR).
If not, then I will do it manually during merging.

**Comment by keradus** [comment]
Replaced by #2653

**Pull request closed without merging**
