### PR TITLE
travis: remove cs check

### PR DESCRIPTION
**Pull request by gharlan**
Codings standards are checked by fabbot..

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
No they're not. It only checks modified files and uses an older version of php-cs-fixer. Basically, it's no use on its own.

**Comment by GrahamCampbell** [comment]
Also checking itself increases code coverage. More test cases can never be bad.

**Comment by gharlan** [comment]
Ok, makes sense.

**Comment by keradus** [comment]
For your information - fabbot.io has PHP CS Fixer under the hood ;)

**Comment by GrahamCampbell** [comment]
> For your information - fabbot.io has PHP CS Fixer under the hood ;)

Yeh, but not the current version, and it doesn't check any files by default, making it useless.

**Comment by keradus** [comment]
yes, you have already said it, so i didn't need to repeat it ;p

**Pull request closed without merging**
