### PR TITLE
DX: enable no_superfluous_phpdoc_tags rule

### PR DESCRIPTION
**Pull request by keradus**
What do you prefer guys ? shall we use `no_superfluous_phpdoc_tags` ?
Please vote ;)

### CODE REVIEW

**Comment by keradus** [comment]
cc @SpacePossum @julienfalque @localheinz

**Comment by SpacePossum** [comment]
If it makes a PHPDoc completely empty I'm :+1: , if not I like complete listings better, so in its current form I'm not in favor of the changes.

**Comment by julienfalque** [comment]
:+1: even with partial removing :)

**Comment by Slamdunk** [comment]
I don't know if I can vote.
To me partial docs look so misunderstanding / confusing

**Comment by localheinz** [comment]
I agree with @Slamdunk and @SpacePossum.

**Comment by ntzm** [comment]
I'm 👍for this PR, I think some devs are used to the PHPDoc with all the information, but IMO it's completely useless if it doesn't add anything.

**Comment by keradus** [comment]
for now, there is no config option that would allow to drop position only if all params/return would be dropped.
if one would raise such PR, it would be highly appreciated ;)

for now, closing without mergin

**Pull request closed without merging**
