### PR TITLE
Psr0Fixer - move to contrib level

### LINKED ISSUE #117: Make the class name leading in the "file name vs class name" fix in the PSR-0 fixer
Currently the filename is considered leading in the "fix" to make the class name match the file name. However I think this is incorrect behavior. I believe that file's are often (mistakingly) incorrectly named, but classes rarely are. Especially when using IDE's with check-style detection, etc.

- https://github.com/Seldaek/PHP-CS-Fixer/blob/psr0/Symfony/CS/Fixer/Psr0Fixer.php#L60

Consider the following scenario:

$foo = new \Foo;

The autoloader loads the incorrectly named file: `foo.php`, which has the class declaration `class Foo ..`. Everything keeps working, until we deploy to an environment with a case-sensitive filesystem.

Consider the second scenario, after running the current psr-0 fixer implementation:

$foo = new \Foo;

The autoloader loads the incorrectly named file: `foo.php`, which now has the class declaration `class foo ..`. Everything keeps working (until PHP finally decides to make class names case-sensitive...) but now the class name is perhaps no longer conform the CamelCase standard, so what happens when we run the fixer again? Quite possibly the class name is corrected, since now it might be incorrect casing.

### LINKED ISSUE #282: Class with underscore are renamed and fixer complain about wrong path...
My class is declared like this 

```php
namespace XtoY\Reader;
class XLS_Reader extends Optionnable implements ReaderInterface {

 }
```
and is placed in file src/XtoY/Reader/XLS/Reader.php according to PSR0 this seems right. 

but when using php-cs-fixer the class is renamed Reader (corresponding to filename ) and the the path is wrong.

### LINKED ISSUE #858: Question: PSR0
I suggest to turn off PSR0 fixer from cascading PSR group (currently using PSR2 uses PSR1 and PSR0 as well). PSR0 was deprecated and in fact when using PSR4 I must disable PSR0 fixer.

This should be done after #857.

What do you think guys ?

### LINKED ISSUE #867: Improve speed: FixerInterface change
Currently:
`FixerInterface::fix(SplFileInfo $file, $content)`

I would made it:
`FixerInterface::fix(SplFileInfo $file, Tokens $tokens)`

Yes, it is a BC breaker for 2.0.

What happens now - file content is passed into next and next fixer - each of them receive full code as string and create Tokens from it - it is quite ok due to internal Tokens::$cache.
But at end of work of single fixer - the code it transformed back into string to compare if strings changed - and if yes then the PHP CS Fixer know that the file was changed by fixer.
That means we regenerate full content for each fixer.

Proposed change will release us of that performance lack, but then we will need to observe Tokens to detect if whole collection or just one collection element changed.

What do you think ?

//cc @dericofilho

### PR DESCRIPTION
**Pull request by gharlan**
closes #867 
closes #858 
closes #282 
closes #117 

I guess there will be some :-1: but I want to try it anyway. ;)

### CODE REVIEW

**Comment by stof** [comment]
:+1: for the removal. This fixer is a risky one, fixing things the wrong way in most cases, and breaking things for people using PSR-4 because it is enabled by default.

However, from a git history PoV, you should split the changes in 2 commits IMO (maybe even 2 separate PRs):
- one removing this fixer
- another one changing the FixerInterface

these are 2 different changes (and it would be valid to remove the PSR-0 fixer without changing the interface btw)

**Comment by gharlan** [comment]
Ok, I've split the commits.

**Comment by GrahamCampbell** [comment]
:-1: for removing the file parameters. Makes it impossible to write a psr4 fixer.

**Comment by GrahamCampbell** [comment]
And breaks customer fixers other people might have.

**Comment by stof** [comment]
@GrahamCampbell a PSR-4 fixer would suffer exactly from the same issue than a PSR-0 one: renaming the class is the wrong way to fix it (changing class names is a BC break) so it is entirely risky. In many cases, the right fix is actually to rename the file, and this is not possible in a fixer.
so I would also vote -1 on a PSR-4 fixer as we cannot get it right (thus, it would be hard to write it without knowing where the PSR-4 path is starting)

**Comment by GrahamCampbell** [comment]
@stof My point was it prevents me writing my own fixer because I'm not allowed to know the filename.

**Comment by GrahamCampbell** [comment]
And it breaks all other custom fixers that need to know the filename.

**Comment by GrahamCampbell** [comment]
Someone might have a fixer to check migration file names for example.

**Comment by stof** [comment]
@GrahamCampbell but in this case, the same applies: if you want to fix it, you would always have to assume that the file name is right and the content is wrong, because the opposite is not possible. and it might be wrong.

**Comment by keradus** [comment]
> And breaks custom fixers other people might have.

That is why this is a BC breaker, so no big deal about that one point

**Comment by GrahamCampbell** [comment]
It's a massive deal. It's making php-cs-fixer significantly less attractive for people and will ultimately drive people to phpcs.

**Comment by keradus** [comment]
@gharlan, @stof,
What are the benefits of removing `\SplFileInfo` from `fix` method signature ?

**Comment by gharlan** [comment]
To be honest there is no big advantage. In my opinion the parameter is useless. No Fixer is using it (except the faulty Psr0Fixer), I didn't see any custom fixer using it until now.
Fixing class names by using filename is a bad idea. But changing filenames would not be better in my opinion, because we should only fix the content of files.
So I can not imagine a "good" fixer using this parameter.

Note: It is still possible to decide if a fixer supports a file, because the method `supports(\SplFileInfo $file)` is still there.

**Comment by GrahamCampbell** [comment]
> I didn't see any custom fixer using it until now.

I do. I know of fixers in private code bases using that.

**Comment by stof** [comment]
@keradus you were the one mentionning it in the first place

**Comment by SpacePossum** [comment]
:+1: for removing the PSR-0 fixer, also for remove the SplFileInfo from the interface (we are bumping a major release version...). However I've no strong opinion on the interface change.

**Comment by GrahamCampbell** [comment]
>  also for remove the SplFileInfo from the interface (we are bumping a major release version...).

It's not the fact that it's a breaking change that bothers me. I don't care about that. I care because I need access to the file name.

**Comment by keradus** [comment]
I would agree in some cases knowing info about file may be useful (Even UnusedUseFixer uses it, but in different way).
I would also agree that someone would like to use PSR0 fixer, even if it is so risky.

To keep everyone happy I would suggest keeping SplFileInfo as parameter and move PSR0 fixer into contrib level, marked as risky.

**Comment by GrahamCampbell** [comment]
> To keep everyone happy I would suggest keeping SplFileInfo as parameter and move PSR0 fixer into contrib level, marked as risky.

:+1:

**Comment by GrahamCampbell** [comment]
I think we also need a psr4 fixer too though.

**Comment by GrahamCampbell** [comment]
Consider the following code:

Location on disk: app/Foo.php
```
<?php

namespace App;

Class Bar
{
}
```

I'd expect the filename to be changed only, but the namespace in the code is changed from App to app. A psr4 fixer shouldn't change the namespace like that.

**Comment by keradus** [comment]
PSR4 is different discussion, even if I would be happy to see it.
Just try to keep this discussion concise to finally finish it.

**Comment by GrahamCampbell** [comment]
Sure. I like your proposal. It would be good to get that done asap. :)

**Comment by gharlan** [comment]
> To keep everyone happy I would suggest keeping SplFileInfo as parameter and move PSR0 fixer into contrib level, marked as risky.

done

**Comment by GrahamCampbell** [comment]
:+1: :ship:

**Comment by SpacePossum** [comment]
:+1:

**Comment by keradus** [comment]
Thank you @gharlan.

**Pull request merged**
