### PR TITLE
Added PhpdocInlineTagFixer

### PR DESCRIPTION
**Pull request by keradus**
Backported from 2.x line (ref #1275)
Requested by fabbot.io (ref #1208, fabbot.io will fail)

### CODE REVIEW

**Comment by keradus** [comment]
Thank you @SpacePossum.

**Comment by stof** [comment]
Actually, PSR-5 defines a non-inline inheritdoc tag (which is better suited for the usage done in Symfony btw, as we are currently abusing the inline tag because there was no other way at the time we made the decision)

**Comment by keradus** [comment]
Could you elaborate please?
[Here](https://github.com/php-fig/fig-standards/pull/169/files) I can not see non-inline inheritdoc tag, just `{@inheritdoc}`

**Comment by stof** [comment]
ah, looks like phpDocumentor has implemented this tag (see http://phpdoc.org/docs/latest/guides/inheritance.html#the-inheritdoc-tag) but not yet included it in their PSR-5 proposal

**Comment by stof** [comment]
@mvriel are you planning to include the non-inline tag in PSR-5 ?

**Comment by mvriel** [comment]
@stof yes I am, I have a draft on my machine with the full text for it

**Comment by SpacePossum** [comment]
Maybe we should remove the `fixing` part of the `{@inheritdoc}` from the fixer to make the fixer atomic (before version 2 is released because removing it after would be a BC).
Then we could create a new fixer for this and deprecate the fixer when the PSR-5 change makes it and create a new fixer that will change `{@inheritdoc}` to `@inheritdoc` if this is the only content (+/- white space) of a PHPDoc.

**Pull request merged**
