### PR TITLE
Fix rule sets overwriting rules defined independently

### PR DESCRIPTION
**Pull request by pilgerone**
Fixing the issue described in https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/2543 and https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/2680.
Rewritten the resolveSet() method to be more concise by using recursion.

### CODE REVIEW

**Comment by SpacePossum** [comment]
Thanks for your PR!
However this is duplicate to https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2545 and same issue as https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/2543. Both are still discussed so lets see where the discussion ends before we start reviewing solutions.

**Comment by pilgerone** [comment]
You're right. Sorry about this. Kinda new to this collaboration thing. :confused:

I've pinpointed the problem in the code. It's a bit hard to explain exactly what its doing, but it's definitely overwriting the rules set further below on the configuration file in some cases.

I'll read the other PR thread thoroughly and see if I can come up with a test to show what I mean.

**Comment by keradus** [comment]
I think we got what your issue is and I confirm that it is a bug.
The thing is that we need to decide how we want to fix more general bug, having your case in mind.

**Comment by pilgerone** [comment]
If I understood correctly, the problem is how to treat overwriting rules that contain arrays (e.g.: `rule = ['a','b','c']`) being overwritten (e.g.: by something like `rule = ['a']`).  Is that right?

**Comment by keradus** [comment]
no, it's about disabling/enabling rule, changing config is slightly other thing. let us not spread discussion about 1 thing into 2 threads

**Comment by keradus** [comment]
@pilgerone , @SpacePossum 
is there something left here after merge of #2545 ?

**Comment by SpacePossum** [comment]
I think @pilgerone and I thought the same thing as this PR and mine (https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2545) seem to work in a similar way :)
However, I would very much like to see this confirmed.

**Comment by pilgerone** [comment]
Yeap. All good after the latest release.

I guess we can safely discard this one in favor to @SpacePossum 's.  :+1:

**Comment by SpacePossum** [comment]
Thanks @pilgerone for this PR, your thoughts (and comments) on my PR and testing/reporting back on this one. 
Happy to see this is resolved, thanks!

**Pull request closed without merging**
