### PR TITLE
Add apostrophe to possessive "team's"

### PR DESCRIPTION
**Pull request by ChandlerSwift**

### CODE REVIEW

**Comment by ChandlerSwift** [comment]
Oops! Didn't catch the memo about not modifying README.rst manually.

**Comment by julienfalque** [comment]
Reopening as the change looks valid.

**Comment by ChandlerSwift** [comment]
I committed the change to README.rst, which is autogenerated from the readme command. I'm writing up a proper patch now. (plus I PR'd to the wrong branch -- d'oh! Probably helps to read the contribution guidelines first)

**Comment by ChandlerSwift** [comment]
That should do it, I'd think.

**Comment by julienfalque** [comment]
> I PR'd to the wrong branch

You can edit the PR with the dedicated button next to the title to switch the target branch. Note that you'll need to rebase your chnges to drop commits from 2.15 branch.

**Comment by SpacePossum** [comment]
Thank you @ChandlerSwift.

**Pull request merged**
