### PR TITLE
OrderedTraitsFixer - introduction

### PR DESCRIPTION
**Pull request by julienfalque**
Implements #1334.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Surely this should be a risky fixer?

**Comment by SpacePossum** [comment]
can you provide an example of such risky fix, conflict resolution for traits has to be done explicit already and that order does not matter

**Comment by GrahamCampbell** [comment]
Ah, right. I see.

**Comment by SpacePossum** [comment]
Thank you @julienfalque.

**Pull request merged**
