### PR TITLE
Partial revert of #1422

### LINKED ISSUE #1450: align_double_arrow looks weird
Since the last update ``align_double_arrow``looks weird

```bash
oskar.stark:/Volumes/development/workspaces/SonataBlockBundle (master)$ make cs
./vendor/bin/php-cs-fixer fix --verbose
Loaded config from "/Volumes/development/workspaces/SonataBlockBundle/.php_cs"
.................FF...........................................................................................
Legend: ?-unknown, I-invalid file syntax, file ignored, .-no changes, F-fixed, E-error
   1) Block/Service/MenuBlockService.php (align_double_arrow)
   2) Block/Service/RssBlockService.php (align_double_arrow)
Fixed all files in 23.432 seconds, 9.500 MB memory used
make: *** [cs] Error 1
oskar.stark:/Volumes/development/workspaces/SonataBlockBundle (master)$ git diff
diff --git a/Block/Service/MenuBlockService.php b/Block/Service/MenuBlockService.php
index 6cd0965..2c88923 100644
--- a/Block/Service/MenuBlockService.php
+++ b/Block/Service/MenuBlockService.php
@@ -133,16 +133,16 @@ class MenuBlockService extends BaseBlockService
     protected function getFormSettingsKeys()
     {
         return array(
-            array('title', 'text', array('required' => false)),
-            array('cache_policy', 'choice', array('choices' => array('public', 'private'))),
-            array('menu_name', 'choice', array('choices' => $this->menus, 'required' => false)),
+            array('title', 'text', array('required'           => false)),
+            array('cache_policy', 'choice', array('choices'   => array('public', 'private'))),
+            array('menu_name', 'choice', array('choices'      => $this->menus, 'required' => false)),
             array('safe_labels', 'checkbox', array('required' => false)),
-            array('current_class', 'text', array('required' => false)),
-            array('first_class', 'text', array('required' => false)),
-            array('last_class', 'text', array('required' => false)),
-            array('menu_class', 'text', array('required' => false)),
-            array('children_class', 'text', array('required' => false)),
-            array('menu_template', 'text', array('required' => false)),
+            array('current_class', 'text', array('required'   => false)),
+            array('first_class', 'text', array('required'     => false)),
+            array('last_class', 'text', array('required'      => false)),
+            array('menu_class', 'text', array('required'      => false)),
+            array('children_class', 'text', array('required'  => false)),
+            array('menu_template', 'text', array('required'   => false)),
         );
     }

diff --git a/Block/Service/RssBlockService.php b/Block/Service/RssBlockService.php
index 80e906e..be76f09 100644
--- a/Block/Service/RssBlockService.php
+++ b/Block/Service/RssBlockService.php
@@ -51,7 +51,7 @@ class RssBlockService extends BaseBlockService
     {
         $formMapper->add('settings', 'sonata_type_immutable_array', array(
             'keys' => array(
-                array('url', 'url', array('required' => false)),
+                array('url', 'url', array('required'    => false)),
                 array('title', 'text', array('required' => false)),
             ),
         ));
oskar.stark:/Volumes/development/workspaces/SonataBlockBundle (master)$ vendor/bin/php-cs-fixer --version
PHP CS Fixer version 1.10.1 by Fabien Potencier
oskar.stark:/Volumes/development/workspaces/SonataBlockBundle (master)$
```

### PR DESCRIPTION
**Pull request by Soullivaneuh**
Fixes #1450.

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
@keradus I revert the buggy part. I had to remove tests of @SpacePossum because this cancel his improvement.

@SpacePossum, if you have a fix now, please ping here. If not, could you please merge this one and bump a new patch version @keradus?

Thanks.

**Comment by Soullivaneuh** [comment]
ping @keradus @SpacePossum.

Could you please merge it in waiting for a correct fix of @SpacePossum? This is an important issue IMHO.

**Comment by keradus** [comment]
I would not like to lose #1422 :(
Please check this out: #1460

**Comment by keradus** [comment]
Closing due to merge of #1460

**Pull request closed without merging**
