### PR TITLE
Allow running if installed as project specific

### PR DESCRIPTION
**Pull request by SpacePossum**
closes https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/4468

replaces https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4469

### CODE REVIEW

**Comment by keradus** [comment]
I thought we already closed #446. what happen we need to fix it again ?

**Comment by kubawerlos** [comment]
I believe @SpacePossum meant #4468 (which replaced #4469 was fixing).

BTW what was wrong with #4469?

**Comment by SpacePossum** [comment]
wrongly copy paste indeed, I tried to merge/squash the other one, didn't work out, opened this one but run out of time of merging, will merge later

**Comment by quarties** [comment]
@SpacePossum any news on this? I had a similar issue like in #4468 and it looks like your PR would fix that.

**Comment by SpacePossum** [comment]
Thank you @ticktackk.

**Pull request merged**
