### PR TITLE
Added Atom package

### PR DESCRIPTION
**Pull request by pfefferle**

### CODE REVIEW

**Comment by keradus** [comment]
Please, follow CONTRIBUTING guide.

**Comment by pfefferle** [comment]
Sorry, will send another request following the CONTRIBUTING guide. Is a request to the master OK or is it a feature for the latest version branch?

**Comment by keradus** [comment]
Just follow the guide in this PR ;) I may change the destiny branch during merging ;)

**Comment by pfefferle** [comment]
new pull request https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1173

**Pull request closed without merging**
