### PR TITLE
ExplicitStringVariableFixer - handle binary strings

### PR DESCRIPTION
**Pull request by ntzm**

### CODE REVIEW

**Comment by keradus** [comment]
just wondering - did you encounter `b`-strings in real code ?

**Comment by ntzm** [comment]
Yes, looks like someone was preparing for PHP 6 a bit too far in advance 😆

**Comment by keradus** [comment]
hehe. don't worry, I still know few hostings that are proud to support php6 !

**Comment by keradus** [comment]
Thank you @ntzm.

**Pull request merged**
