### PR TITLE
ordered_use_by_length fixer added

### PR DESCRIPTION
**Pull request by pbkyriak**

### CODE REVIEW

**Comment by keradus** [comment]
Please see #1801

**Comment by GrahamCampbell** [comment]
The following test case will fail:

```php
<?php

use Acme;
use Foo;
use Bar;
```

The output should be:

```php
<?php

use Bar;
use Foo;
use Acme;
```

**Comment by GrahamCampbell** [comment]
I think. We should add it all the same. ;)

**Comment by pbkyriak** [comment]
sorry missed that spot. can i try do the sorting option of the ordered_use fixer?

**Comment by keradus** [comment]
Indeed, this should not be new fixer but option for existing one.

**Comment by GrahamCampbell** [comment]
@keradus This should be closed then?

**Comment by GrahamCampbell** [comment]
Any news here?

**Comment by keradus** [comment]
Closing due to wrong approach and lack of authors interest

**Comment by powelski** [comment]
@pbkyriak I'm cheering you up, this awesome feature is highly awaited :)

**Pull request closed without merging**
