### PR TITLE
DiffConsoleFormatter - fix output escaping

### PR DESCRIPTION
**Pull request by SpacePossum**
for ref: https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3290#issuecomment-348929490

cc @Slamdunk thanks for reporting!

TODO:
- [x] Add utest
- [x] Target lowest branch

(tested local using the linked fixer)

### CODE REVIEW

**Comment by keradus** [comment]
how do we know that this one works ?

**Comment by keradus** [comment]
Windows is sad :(

**Comment by SpacePossum** [comment]
Windows is happy again ;)

**Comment by Slamdunk** [comment]
I would like to implement github-like/diff-so-fancy colouring (https://github.com/so-fancy/diff-so-fancy#screenshot), but I need this PR for `DiffConsoleFormatterTest`.
Please ping me when merged @SpacePossum

**Comment by keradus** [comment]
you started observing the thread by posting in it, you will be pinged automatically for any activity here ;P

**Comment by Slamdunk** [comment]
😄 

I'm so used to unsubscribe notifications that I forgot they can be useful sometimes 🐳

**Comment by keradus** [comment]
Thank you @SpacePossum.

**Pull request merged**
