### PR TITLE
LineEndingFixer - BracesFixer - Priority

### PR DESCRIPTION
**Pull request by dmvdbrugge**
Separated the `line_ending`/`braces`-priority relation and some comments from #4085

### CODE REVIEW

**Comment by SpacePossum** [comment]
Thanks for all the proviling!
I didn't catch up on all the bigger PR's and comments, but I wander; can't avoid this conflict if the `braces` uses the line ending that `line_ending` enforces? Just curious :)

**Comment by dmvdbrugge** [comment]
I just checked, braces never _inserts_ hardcoded newlines, they come from the whitespace config. It does do some string-magic with `\n`s though, however at the moment I wouldn't know how to actually fix that (without spending hours for deeply understanding `braces`).

**Comment by SpacePossum** [comment]
note to self, 7.3 failures are not related to this PR

**Comment by SpacePossum** [comment]
Thank you @dmvdbrugge.

**Pull request merged**
