### PR TITLE
Corrected method visibility

### PR DESCRIPTION
**Pull request by GrahamCampbell**
I'm not sure if this is what you had in mind?

### CODE REVIEW

**Comment by SpacePossum** [comment]
sure, shipit :)
the goal is to have all those method removed anyway ;)

**Comment by GrahamCampbell** [comment]
Maybe we should also add an internal test to check the visibility of this method?

**Comment by keradus** [comment]
no need for doing that:
- they are outside the interface, if one uses them it is his risk
- with time, we will remove all of them

**Comment by GrahamCampbell** [comment]
Makes sense. :)

**Comment by keradus** [comment]
Thank you @GrahamCampbell.

**Pull request closed without merging**
