### PR TITLE
[PSR-2] Switch case parentheses fixer

### PR DESCRIPTION
**Pull request by Soullivaneuh**
#1539 for switch cases.

Related PSR-2 rule: http://www.php-fig.org/psr/psr-2/#5-2-switch-case

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
Ready for review.

**Comment by Soullivaneuh** [comment]
AppVeyor failing not related to this PR.

**Comment by gharlan** [comment]
:+1:

**Comment by keradus** [comment]
Closing in favour of #1550

**Pull request closed without merging**
