### PR TITLE
move fixer classes from level subdirs to thematic subdirs

### PR DESCRIPTION
**Pull request by gharlan**
Do we want to remove the level subdirs (contrib/psr1/psr2/symfony)?

### CODE REVIEW

**Comment by keradus** [comment]
:-1:
I don't want to have 100 fixers on one level.

Instead of it I would prefer to have dirs per type of changes, like dir for PhpDoc fixers, dir for phpunit fixers and so on.

**Comment by gharlan** [comment]
> Instead of it I would prefer to have dirs per type of changes, like dir for PhpDoc fixers, dir for phpunit fixers and so on.

:+1:

**Comment by GrahamCampbell** [comment]
:-1: for this as is

**Comment by gharlan** [comment]
current state: https://github.com/gharlan/PHP-CS-Fixer/tree/remove-level-subdirs/src/Fixer
is this the right direction?

**Comment by keradus** [comment]
I assume that `*_` are not-moved-yet fixers.
I like that direction.

**Comment by keradus** [comment]
Also, at the end, I would move `FixerInterface` and `Abstract*Fixer` into `Fixer` dir as well.

**Comment by gharlan** [comment]
> I assume that *_ are not-moved-yet fixers.

yes

**Comment by gharlan** [comment]
all classes are moved now: https://github.com/gharlan/PHP-CS-Fixer/tree/remove-level-subdirs/src/Fixer
please discuss.. :)

**Comment by GrahamCampbell** [comment]
Can we not get away with `Return` rather than `ReturnNotation` since php surely only reserves the class `Return`, not the namespace?

**Comment by GrahamCampbell** [comment]
Same for the others, like `Array`.

**Comment by GrahamCampbell** [comment]
Could we move the abstract phpdoc fixers into the phpdoc namespace?

**Comment by GrahamCampbell** [comment]
I'm :+1: on the way this PR is moving btw.

**Comment by gharlan** [comment]
> Can we not get away with Return rather than ReturnNotation since php surely only reserves the class Return, not the namespace?

https://3v4l.org/1RWsD

**Comment by GrahamCampbell** [comment]
Sigh. I guess I didn't think about how tokenization would work.

**Comment by keradus** [comment]
Maybe some new namespace like `BlankLine`, with:
- NoBlankLinesAfterPhpdocFixer (ReturnNotation)
- BlankLineBeforeReturnFixer.php (ReturnNotation)
?

Also, 3 of 4 Fixers from `Semicolon` are more about whitespaces, not semicolon.

**Comment by keradus** [comment]
:+1:

**Comment by keradus** [comment]
Thank you @gharlan.

**Comment by SpacePossum** [comment]
:+1:  very nice :)

**Pull request merged**
