### PR TITLE
Add PhpdocToCommentFixer

### PR DESCRIPTION
**Pull request by keradus**
> MARK FOR MERGE INTO 2.0 by @keradus
> Remove `$token->getLine()` !

Replaces #969

### CODE REVIEW

**Comment by keradus** [comment]
Thank you @ceeram.

**Comment by pyrech** [comment]
Just found a small issue with this fixer: it also converts phpdoc used in a foreach block to describe the type of the collection item:

```php
foreach ($myCollection as $item) {
    /** @var Item item */
    ...
}
```

will be converted to:

```php
foreach ($myCollection as $item) {
    /* @var Item item */
    ...
}
```

**Comment by ceeram** [comment]
This would ont happen if you defined it like:
```
foreach ($myCollection as $item) {
    /** @var Item $item */
    ...
}
```

**Comment by pyrech** [comment]
Sorry typo in the issue, the variable is of course well named in our code but was altered by php-cs-fixer

**Comment by ceeram** [comment]
There are tests that prove it wont change them, can you provide the exact
code please?

2015-02-27 15:34 GMT+01:00 Loïck Piera <notifications@github.com>:

**Comment by ceeram** [comment]
Ow i see what is going on, phpdoc needs to be before the declaration. you have it within the foreach, tests have it before the foreach. I am not sure if this is desired to be changed, thoughts @keradus ?

**Comment by pyrech** [comment]
Yeah, I just saw that. I was pretty convinced that phpdoc should be placed inside foreach but indeed, even the upcoming PSR-5 recommends to place it before the declaration. So not any issue here, keep it working as it is.
Thanks :)

**Comment by ceeram** [comment]
OK, this can be closed then

**Pull request merged**
