### PR TITLE
WhitespacyLinesFixer - stop changing non-whitespacy tokens

### PR DESCRIPTION
**Pull request by keradus**
Replaces: #1226
Ref: #923

### CODE REVIEW

**Comment by keradus** [comment]
PHP7 fails due to #1278

**Comment by keradus** [comment]
cc @SpacePossum

**Comment by keradus** [comment]
Thank you @SpacePossum.

**Comment by keradus** [comment]
Thank you @SamBurns-awin

**Comment by SpacePossum** [comment]
:+1:  @keradus thanks!

**Pull request merged**
