### PR TITLE
Add ControlStructuresParenthesesWhitespacesFixer

### PR DESCRIPTION
**Pull request by denplatov**

### CODE REVIEW

**Comment by keradus** [comment]
Hi !

There are 2 authors. Please use same author.
Eg  rebase to get rid of merge commit

**Comment by denplatov** [comment]
Rebase is done!

**Comment by keradus** [comment]
All functionality of this fixer is already inside `braces` fixer.

If you just need this functionality just use other fixer. If you need it to be separated from `braces` fixer - that's totally fine, but please remote that functionality from `braces` fixer.

**Comment by SpacePossum** [comment]
I suggest to close this as the fixer add no new value, i.e. the `braces`-fixer already handles all cases.

**Comment by keradus** [comment]
@denplatov , as stated, are you willing to extract that logic from `braces` fixer to not have 2 fixers doing the same?
If not, I will sadly close this PR as @SpacePossum suggested

**Pull request closed without merging**
