### PR TITLE
CurlyBraceTransformer - count T_CURLY_OPEN itself as level as well

### PR DESCRIPTION
**Pull request by SpacePossum**
closes https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/5983

### CODE REVIEW

**Comment by SpacePossum** [comment]
missing utest

also, wondering if it wouldn't be better to "just" check on the _content_ `{` / `}` and not the token (ct) types...

**Comment by GrahamCampbell** [comment]
Looks good to me, but I think it would be a good idea to regression test this on symfony/symfony and laravel/framework first before merging, just to be sure we're not making things worse. I can do this, tomorrow morning.

**Comment by SpacePossum** [comment]
thanks @GrahamCampbell , just run it on SF without issues, please let me know if you run into something on laravel

**Comment by GrahamCampbell** [comment]
Yep, works. :shipit:

**Pull request merged**
