### PR TITLE
SilencedDeprecationErrorFixer - adjust level

### PR DESCRIPTION
**Pull request by keradus**
ref #2078
no risky fixers should be enabled by default

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
👍

**Comment by HeahDude** [comment]
Hey, we discussed this with Fabien, and from his pov, not changing the code in that specific case is a bug that should be fixed by this fixer, so it should not be risky at all.

**Comment by GrahamCampbell** [comment]
This is definitely risky. The fact that it fixes a "bug" by definition means it's changed the behaviour.

**Comment by HeahDude** [comment]
But changing the behavior is not risky when you expect to fix a bug, right?

**Comment by GrahamCampbell** [comment]
Yes it is. Anything other than a cs fix is risky. A bug fix is risky.

**Comment by HeahDude** [comment]
I understand your rules, but life, sometimes, is not binary. Concretely what is risky here?

**Comment by GrahamCampbell** [comment]
That is the definition of risky here. This is a code style fixing tool, not a static analyzer.

**Comment by keradus** [comment]
For Symfony not-silenced deprecation error is a bug, fixer do the job and Symfony is happy. Awesome.
We do the same - for use comparing with `==` is a bug, `===` should be used. We have a fixer that does that. Awesome.

But in both cases - sb else may not consider this as bugs, and since this is changing the behaviour we need to warn user about that.

**Comment by HeahDude** [comment]
@keradus so the new ruleset you are adding (#2119) is the only way to get it running on the symfony repo easily?

**Comment by keradus** [comment]
no, one could also use CLI `rules` arg or define ruleset in config file ;)
But I thought it would be easier if that ready to use ruleset would exists.

**Comment by HeahDude** [comment]
Thanks ;)

**Pull request merged**
