### PR TITLE
Added ProtectedToPrivateFixer

### PR DESCRIPTION
**Pull request by keradus**
Replaces #2084
Same content, just squashed commits and rebased

### CODE REVIEW

**Comment by keradus** [comment]
Thank you @Slamdunk.

**Comment by Slamdunk** [comment]
Wouldn't you have been able to do it in the original PR?

Not complaining about what you have done (thanks for merging), just thinking that in the long term this way you could lose some informations and references of the original PR, if project maintainers don't repeat exactly all your steps when they have to do the same.

**Comment by Slamdunk** [comment]
Thinking about you to change the base branch, and adding something like `waiting author squash + rebase` label easily readable from "Pull requests" personal summary

**Comment by keradus** [comment]
> Wouldn't you have been able to do it in the original PR?

not without access to your private fork


> just thinking that in the long term this way you could lose some informations and references of the original PR

that's why I have linked them, for me it's enough. authorship of commits were not modified as well.


> if project maintainers don't repeat exactly all your steps when they have to do the same

They (so... me?) don't have to. at all.


> Thinking about you to change the base branch, and adding something like `waiting author squash + rebase` label easily readable from "Pull requests" personal summary

For you it's could be easy and fast, but it;s not always like that. not all know how to rebase, how to squash without losing authorship where there are more authors. from experience - it could take up to whole week.
And since merging 1.x -> 2.x tooks a lot of time, which I actually had the time I decided to merge this PR, it was better for me to squash on my side and merge to 2.x than suspend it for up to 2 weeks (waiting for squashing and waiting for me to have new opportunity to merge 1->2).

It's very edge case to have PR with multiple authors, so that case is not happaning usually. I don't see big deal here ;)

**Comment by Slamdunk** [comment]
:+1:

**Pull request merged**
