### PR TITLE
Alphabetically sort entries in .gitignore

### PR DESCRIPTION
**Pull request by GrahamCampbell**
This has been pissing me off for a while, lol.

### CODE REVIEW

**Comment by keradus** [comment]
Thank you @GrahamCampbell.

**Comment by Soullivaneuh** [comment]
@GrahamCampbell, the gitignore nazi! :-)

**Comment by GrahamCampbell** [comment]
:P

**Comment by keradus** [comment]
tbh I like it sorted too ;P

**Comment by Soullivaneuh** [comment]
I have to confess... I like it too. :-P

**Comment by keradus** [comment]
folks, maybe we should write a git-fixer tool, that will fix things like this? :D

**Comment by Soullivaneuh** [comment]
IMO, we should create a FriendsOfCS group. :-)

**Comment by keradus** [comment]
and incorporate front-end tools :D oh now, they are at war between them :D

**Comment by Soullivaneuh** [comment]
> oh now, they are at war between them :D

Don't touch front-end! It's a special and magic world.

What? We are not friday? :trollface:

**Comment by keradus** [comment]
Actually I was a front-end guy for last few years ;P

**Comment by Soullivaneuh** [comment]
image

**Pull request merged**
