### PR TITLE
Rename php-cs-fixer to php-cs-fixer.phar

### PR DESCRIPTION
**Pull request by drazisil**
Appears to be missing extension, as the install instructions on README.md do not work.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
It's not a phar file though?

**Comment by GrahamCampbell** [comment]
The docs on the readme refer to if you downloaded the phar.

**Comment by drazisil** [comment]
Oh, sorry. I can't find the .phar, thought it was this. I get 404 on your commands. I'll open an issue then.

**Comment by GrahamCampbell** [comment]
If you swap out https with http, it should work. This is a known temporary issue. :)

**Comment by GrahamCampbell** [comment]
Oh, yeh, the phar build for 1.11.7 failed. Just use 1.11.6. :)

**Pull request closed without merging**
