### PR TITLE
[CS] Clean up extra lines from documentation

### PR DESCRIPTION
**Pull request by carusogabriel**
I've removed all extra lines from our documentation :smile:

### CODE REVIEW

**Comment by keradus** [comment]
Hi ;)
Please change target branch to 2.2 (you will also need to rebase your branch and push it with force)

**Comment by carusogabriel** [comment]
Sure, rebasing in a minute :man_technologist:

**Comment by SpacePossum** [comment]
ey what happened?

**Comment by carusogabriel** [comment]
After rebase, docs were clean :smile:

**Comment by SpacePossum** [comment]
ah ok :D :+1:

**Comment by keradus** [comment]
weird.
or maybe it was fine on 2.2 and the issue was introduced on 2.9  ?

**Pull request closed without merging**
