### PR TITLE
Tokens - fix iterator used with foreach by reference

### PR DESCRIPTION
**Pull request by keradus**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
:+1:

**Comment by kalessil** [comment]
@keradus :+1: , can you share details please? Php version, project?

**Comment by gharlan** [comment]
@kalessil it is independent of php version and project: http://3v4l.org/rNI1u

**Comment by kalessil** [comment]
@gharlan : thank you.

@keradus : the rest changes operates on arrays, so no other issues with the construction

**Pull request merged**
