### PR TITLE
Add option to sort within import groups

### PR DESCRIPTION
**Pull request by miken32**
Within the Ordered Imports fixer, import groups such as this are left unsorted:

```php
use Foo\{Baz, Bar};
```

This PR adds an option to alphabetically sort elements inside groups.

### CODE REVIEW

**Review by kubawerlos — CHANGES_REQUESTED** [review]
I wonder if this should be an option or simply the part of behaviour - if one wants to sort imports then let's sort the one within a group too.

Also, some test would be more than appreciated.

**Comment by miken32** [comment]
I always err on the side of caution when it comes to changing defaults, so I left it as an option. But it makes sense to me that one would want this as an always-on thing.

**Comment by SpacePossum** [comment]
Hi and thanks for your PR!

During tested on 2.15 and master I noticed that for both the added test and the code sample already get fixed by the current fixer and as such the configuration value of the new option didn't effect the way the code gets fixed. Can you maybe provide a tests that fails to pass on the current setup?

**Comment by miken32** [comment]
LOL well that's rather embarrassing! I agree I can't seem to reproduce the issue that got me here in the first place. I suspect I may have forgotten to add a rule or something to the run I was doing when I noticed the "problem."

**Comment by SpacePossum** [comment]
good to hear it is resolved, thanks for reporting and your time :+1:

**Pull request closed without merging**
