### PR TITLE
OrderedTrait - Move Phpdoc with trait import

### PR DESCRIPTION
**Pull request by VincentLanglet**
Closes https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/6352

### CODE REVIEW

**Comment by VincentLanglet** [comment]
Friendly ping @SpacePossum :)

**Review by SpacePossum — APPROVED** [review]

**Comment by SpacePossum** [comment]
thanks for the wait @VincentLanglet , looks good to me, I cannot merge at the moment so we'll have to wait for the team :+1:

**Comment by VincentLanglet** [comment]
> thanks for the wait @VincentLanglet , looks good to me, I cannot merge at the moment so we'll have to wait for the team 👍

thanks for the update.

**Comment by VincentLanglet** [comment]
@julienfalque @keradus Do you have some time to merge this ? :)

**Comment by VincentLanglet** [comment]
Thanks a lot

**Pull request merged**
