### PR TITLE
More candidates for config file

### PR DESCRIPTION
**Pull request by gharlan**
proposal for #1068

### CODE REVIEW

**Comment by keradus** [comment]
:-1: for #1068 itself.

**Comment by GrahamCampbell** [comment]
:-1:

**Comment by gharlan** [comment]
@keradus @GrahamCampbell I'v removed the config file in home directory. What do you think about this pr now?

**Comment by GrahamCampbell** [comment]
I still don't like the idea anyway.

**Comment by gharlan** [comment]
But when I execute `php php-cs-fixer fix Symfony/CS/Fixer` shouldn't be used the config file of this project? why not?

**Comment by keradus** [comment]
cwd may have sense to not forsing to fix whole project or pass config file.
any other thoughts?

**Comment by keradus** [comment]
Really? No other thoughts ?

**Comment by keradus** [comment]
Closing due to lack of interest :(

**Comment by gharlan** [comment]
:(

**Comment by keradus** [comment]
Could reopen it after any positive opinion ;)

**Comment by GrahamCampbell** [comment]
:-1: from me :P

**Comment by gharlan** [comment]
@GrahamCampbell can you explain the reason for your _no_?

> But when I execute `php php-cs-fixer fix Symfony/CS/Fixer` shouldn't be used the config file of this project? **why not?**

**Comment by GrahamCampbell** [comment]
I just don't like the whole concept of searching about for a config file. I think there should be one in a defined place, and that should be it (yes I know we support .dist too ;P).

**Comment by gharlan** [comment]
Ok.

> I think there should be one in a defined place, and that should be it

This PR does not add more places, it only changes the fixer to also use the one config file when fixing parts of a project.

**Pull request closed without merging**
