### PR TITLE
Add get_required_files and user_error aliases

### PR DESCRIPTION
**Pull request by ntzm**

### CODE REVIEW

**Comment by kubawerlos** [comment]
Although, shouldn't branch `2.12` be the target?

**Comment by ntzm** [comment]
I think I see this as a new feature rather than a bug fix

**Comment by dmvdbrugge** [comment]
> I think I see this as a new feature rather than a bug fix

In which case it should target master, and get milestone 2.14
It seems however, @SpacePossum disagrees with you

**Comment by dmvdbrugge** [comment]
(And I submitted too fast...)

I think I agree with the feature not bug fix approach, also taking into account how some of my previous things were "classified".

**Comment by SpacePossum** [comment]
it is not exact science,  I'm happy with 2.12, 2.13 and master here TBH

**Comment by ntzm** [comment]
I think I will target `master` instead, forgot 2.13 was the stable

**Comment by kubawerlos** [comment]
> SpacePossum added `feature` `RTM` labels
> SpacePossum added this to the `2.13.1` milestone

@SpacePossum both agrees and disagrees this to be feature :)

**Comment by SpacePossum** [comment]
haha, true, what to say, I like this to be in that is all, I'll leave the details to the specialists :)

**Comment by SpacePossum** [comment]
Thank you @ntzm.

**Pull request merged**
