### PR TITLE
Drop CircleCI and AppVeyor

### PR DESCRIPTION
**Pull request by keradus**

### CODE REVIEW

**Review by GrahamCampbell — APPROVED** [review]

**Comment by GrahamCampbell** [comment]
Could just only run the auto-review tests on Linux. Who cares why they are broken on Windows. There are better things to spend time on. ;)

**Comment by keradus** [comment]
@GrahamCampbell I see Windows build green

**Comment by GrahamCampbell** [comment]
Odd. It was red before. The last build, 5 hours ago has it green.

**Comment by GrahamCampbell** [comment]
I guess this is good to go, then.

**Review by kubawerlos — APPROVED** [review]

**Pull request merged**
