### PR TITLE
DX: enable native_function_invocation

### PR DESCRIPTION
**Pull request by keradus**
please vote

### CODE REVIEW

**Comment by keradus** [comment]
ping @FriendsOfPHP/php-cs-fixer

**Comment by ntzm** [comment]
What are the before and after benchmarks?

**Comment by kubawerlos** [comment]
Why not all native functions?

**Comment by keradus** [comment]
@ntzm , minimal compared to fun with tokenizer
@kubawerlos , see discussion at #3048

**Pull request merged**
