### PR TITLE
Fixer - Fix ordering of fixer when both level and custom fixers are used

### PR DESCRIPTION
**Pull request by SpacePossum**
closes https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/1746

### CODE REVIEW

**Comment by keradus** [comment]
what was the problem?

**Comment by SpacePossum** [comment]
Inside the Fixer there is a lot of juggling with the fixers it should use, i.e. `$this->fixers` vs. `$fixers` from the configuration etc. I would suggest to make it more clean, i.e. use `$this->fixers` everywhere.
Because of this currently when you configure a level (on > master) and add some fixers, the fixers from the level are sorted but the complete set (level + added fixers) is not. This caused the fixers to be ran in the wrong order.

**Comment by keradus** [comment]
Then please, could you make a utest to cover that?
I had strong feeling that it would need to be rewritten on 2.x line...

**Comment by SpacePossum** [comment]
That test should cover the `FixCommand`, `Configuration(Resolver)` and `Fixer` because the provided fail-case did work as integration test, proving even more the complex interaction between the listed 3 parts.
I might find some time to prove the failure and fix by utest later this week or maybe next.

**Comment by keradus** [comment]
I'm just afraid that if we merge it without utest and then merge 1.12 into 2.x line, which has completely different way preparing fixers (own Factory class), we could lost the fix.

**Comment by keradus** [comment]
Tests would indeed be tricky and even not unit. Could you check if that error is already resolved on 2.x line ?

**Comment by keradus** [comment]
Could you check if that error is already resolved on 2.x line ?

**Comment by keradus** [comment]
ping @SpacePossum

**Comment by SpacePossum** [comment]
Sorry about letting you wait.
Running the Fixer on master on the sample code provided with;
```
s1@possum:/home/possum/work/PHP-CS-Fixer# php php-cs-fixer fix test.php --rules=@Symfony,phpdoc_order
```

works as expected. So your factory class seems to work fine :)

**Comment by keradus** [comment]
Cool. Knowing this is very important for merging 1.x->2.x

**Comment by keradus** [comment]
Thank you @SpacePossum.

**Pull request merged**
