### PR TITLE
Install and update locally by composer

### PR DESCRIPTION
**Pull request by danielspk**
Edit README.

Add info for install and update locally by composer.

### CODE REVIEW

**Comment by keradus** [comment]
@julienfalque , we are giving the options here, it's up to end user. you consider it wrong, one considers it's great, as he doesn't need to have global tools/multiple composer files/multiple package managers . both can use whatever we prefer. simply, let's document the option and that it. it's up to end user which one he will take.

**Comment by keradus** [comment]
@danielspk , please take a look at README paragraph
https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.15/CONTRIBUTING.md#quick-guide

**Comment by SpacePossum** [comment]
>it's not npm, that's how composer works.

This true by itself so not much an argument to go on :)  In order words, just because composer acts this way and npm does not, doesn't mean it is a good idea to use composer for that use case (some might think so but I don't).

I agree with @julienfalque here and as such I think we should not document this way, we cannot document all possible ways to install so I think it would be best to only document ways we think is the best or "good" way.

**Comment by julienfalque** [comment]
IMO #4608 is the exact reason why we should suggest *not* to install the tool as a dev dependency in the main `composer.json`: every two years, upgrading PHP CS Fixer to next Symfony major version suddenly becomes the top priority because it's installed in a lot of projects this way, so it prevents those projects from using the new Symfony version until PHP CS Fixer does.

This is wrong, the version of Symfony components used by PHP CS Fixer should remain an internal detail, we should be able to upgrade whenever we want/need it, not immediatly when a new Symfony major version is released.

**Comment by keradus** [comment]
I like your reasoning, @julienfalque . but how to bind which PHP CS Fixer version should be used by given project? doing a global installation can do more harm.
what if i have 3 projects?
- project A using 2.12
- project B using 2.16
- project C using 1.12

let say that i had installed 2.12 globally.
the result of executing the tool will not be stable
- processing project A will pass
- processing project B will fail due to configured rules from 2.16
- processing project C will crash due to heavy bc breaks.

we need to provide a way to bind which PHP CS Fixer should be used for given project by having any kind of lock.
for that and completeness of having both, global and local installation steps , i like having the option described in readme.

**Comment by julienfalque** [comment]
I'm not talking about installing PHP CS Fixer globally. It brings other issues indeed. I'm talking about installing it via a dedicated `composer.json` (e.g. `tools/php-cs-fixer/composer.json`). Nothing prevents this `composer.json` from having its own `composer.lock`.

The `require-dev` section should be for packages that are actually needed by the project to run in a non-prod environment. For example `symfony/debug` for a Symfony application. PHP CS Fixer is *not* required by the application to run, it is an external tool.

**Comment by SpacePossum** [comment]
closing following https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/4496#issuecomment-571927585

**Pull request closed without merging**
