### PR TITLE
ArrayIndentationFixer - Fix indentation in HTML

### LINKED ISSUE #3631: ArrayIndentationFixer unexpected changes with HTML attributes
When reporting an issue (bug) please provide the following information:

#### The PHP version you are using (`$ php -v`):
=> 7.2.3

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> 2.11.0

#### The command you use to run PHP CS Fixer:
=> `vendor/bin/php-cs-fixer fix`

#### The configuration file you are using, if any:
```php
<?php

declare(strict_types=1);

$finder = PhpCsFixer\Finder::create()
    ->in(__DIR__)
    ->exclude('vendor');

return PhpCsFixer\Config::create()
    ->setFinder($finder)
    ->setRules([
        'array_indentation' => true,
    ]);
```

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
<div>
    <a
        class="link"
        href="<?= Url::to([
            '/site/page',
            'id' => 123,
        ]); ?>"
    >
        Link text
    </a>
</div>
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
<div>
    <a
        class="link"
        href="<?= Url::to([
    '/site/page',
    'id' => 123,
]); ?>"
    >
        Link text
    </a>
</div>
```

 * with the changes you expected instead:
Expected no changes

### PR DESCRIPTION
**Pull request by julienfalque**
Fixes #3631.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
👍

**Comment by julienfalque** [comment]
Rebased.

**Comment by SpacePossum** [comment]
please kick appveyor ;)

**Comment by keradus** [comment]
Thank you @julienfalque.

**Pull request merged**
