### PR TITLE
Longer explanation of how to use blacklist

### PR DESCRIPTION
**Pull request by bmitch**
Was originally confused on how this worked. Thought a slightly more involved explanation might help.

### CODE REVIEW

**Comment by keradus** [comment]
I like that.
Please, could you also applied it here: https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/1.5/Symfony/CS/Console/Command/FixCommand.php#L139 ?

**Comment by bmitch** [comment]
:+1: How's this? Let me know if there's anything else. Thanks.

**Comment by keradus** [comment]
The text need to match one another. That is why the Travis failed.
README.rst is autogenerated.
Please see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/1.5/CONTRIBUTING.md

**Comment by bmitch** [comment]
Oh sorry, I'll fix that up.

**Comment by keradus** [comment]
Thank you @bmitch.

**Comment by bmitch** [comment]
:+1:

**Pull request merged**
