### PR TITLE
Allow Symfony 4

### PR DESCRIPTION
**Pull request by garak**
See #3124

### CODE REVIEW

**Comment by SpacePossum** [comment]
SF 4 is not published yet on packagist.org so it will not be used in the CI suit with the `composer.json` in your PR.

**Comment by keradus** [comment]
also, shall go for 2.2

**Comment by keradus** [comment]
> "minimum-stability": "dev",

1. no
2. it doen't make Travis install 4.x: https://travis-ci.org/FriendsOfPHP/PHP-CS-Fixer/jobs/283234906#L550

**Comment by garak** [comment]
I don't know how to force 4.x then

**Comment by garak** [comment]
I removed the stability flag and tried to force the Symfony version in travis, I'm not sure if it's working tho

**Comment by SpacePossum** [comment]
You can check if it works by looking at the output of Travis, for example:
https://travis-ci.org/FriendsOfPHP/PHP-CS-Fixer/jobs/284272226#L545
this show that for PHP 7.2 SF3 components are installed by composer. On PHP 7.1 it is the same.

**Comment by keradus** [comment]
please change target branch to 2.2 line

**Comment by garak** [comment]
It looks like basing on 2.2 is causing a mess. I close this PR and will open a new one

**Comment by julienfalque** [comment]
This is because your branch includes your commits but also all commits from 2.6 that are not in 2.2. You need to rebase your branch onto 2.2 to get rid of these commits and keep only the ones you added.

**Comment by garak** [comment]
See #3134

**Pull request closed without merging**
