### PR TITLE
ShortArraySyntaxFixer/LongArraySyntaxFixer - Merge conflicting fixers

### PR DESCRIPTION
**Pull request by SpacePossum**

### CODE REVIEW

**Comment by keradus** [comment]
nice so far ;)
(btw, please check gitter)

**Comment by SpacePossum** [comment]
problem here is that the integration test will resolve the fixers _and_ configure those before checking the requirements set in the test.

**Comment by keradus** [comment]
Why it is a problem ?

**Comment by SpacePossum** [comment]
I check if the configuration of the fixer makes sense based on the env., so this will fail:
https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2274/files#diff-00016b9c4b10354d36ed225366173552R58

even if I set the requirements of the test on 5.4

**Comment by keradus** [comment]
then why not simply check requirements before creating fixers? (what actually makes perfect sense)

**Comment by SpacePossum** [comment]
>then why not simply check requirements before creating fixers? (what actually makes perfect sense)

thats the plan :)   :+1:

**Comment by SpacePossum** [comment]
This PR also fixes using `setFormat()` in a configuration file as it was not used by the Fixer (i.e. it would always run with the value given on commandline or fall back on 'txt').

**Comment by keradus** [comment]
could we separated that fix? PR getting bigger and bigger already, and that bugfix is not directly related

**Comment by SpacePossum** [comment]
Expect Travis PHP5.3 to fail because of https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2285

**Comment by keradus** [comment]
rebased

**Comment by keradus** [comment]
Thank you @SpacePossum.

**Pull request closed without merging**
