### PR TITLE
Support property, property-read and property-write tags

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Takes the basic stuff from https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1487.

### CODE REVIEW

**Comment by keradus** [comment]
:+1: if Travis passes

**Comment by keradus** [comment]
I see that php7 crash on Travis :/
https://travis-ci.org/FriendsOfPHP/PHP-CS-Fixer/jobs/91932810

**Comment by GrahamCampbell** [comment]
> I see that php7 crashes on Travis :/

LOL. Not again.

**Comment by GrahamCampbell** [comment]
I can confirm the tests pass on PHP 7 though. I've got PHP 7 installed on a VM on my laptop.

**Comment by keradus** [comment]
php7 on my Windows passes too.
I'm not saying the tests fail, just feel bad about Travis :(

**Comment by SpacePossum** [comment]
(poor Travis : (  )
:+1:

**Comment by keradus** [comment]
done
:+1:

**Comment by GrahamCampbell** [comment]
https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1519 now includes the bugfix part of this for the tag class, targeted at 1.10.

**Comment by keradus** [comment]
Thank you @GrahamCampbell.

**Comment by GrahamCampbell** [comment]
:)

**Pull request closed without merging**
