### PR TITLE
Docs: Add link to a VS Code extension in readme

### PR DESCRIPTION
**Pull request by jakebathman**
This PR adds a link to a VS Code extension for PHP CS to the readme.

Please let me know if there are any questions. Thanks!

### CODE REVIEW

**Comment by kubawerlos** [comment]
@jakebathman I have a question: can you close this PR?

This is PHP CS Fixer and the extension is for PHP_CodeSniffer - completely different tool.

**Comment by jakebathman** [comment]
Wow, I pasted the wrong GitHub URL and didn't even realize. Pushed a fix @kubawerlos

**Comment by jakebathman** [comment]
@keradus Good points and suggestions. Updated to change the URL and actually use it in the readme this time.

**Comment by keradus** [comment]
Thank you @jakebathman.

**Comment by keradus** [comment]
note: merged to 2.12, not 2.13

**Pull request merged**
