### PR TITLE
AppVeyor/Travis - use GITHUB_OAUTH_TOKEN

### PR DESCRIPTION
**Pull request by keradus**

### CODE REVIEW

**Comment by stof** [comment]
should it check whether the variable is defined ?

**Comment by keradus** [comment]
I think it is not needed as it is defined directly in Travis configuration (not the file)

**Comment by stof** [comment]
Well, if it is a secure env variable, it will not be available in PRs sent from a fork (to avoid allowing a PR to be sent which would dump the value of the env variable and so leak it)

**Comment by keradus** [comment]
So... let us use the raw, readable format to allow all PRs use it ?

**Comment by stof** [comment]
@keradus well, this can be discussed though. PRs will still benefit from the existing cache (as they reuse the cache of the target branch, which will have been populated by builds using the token), so they may not need the token.

**Comment by keradus** [comment]
Indeed, in most cases PRs will use cache, but not always

**Comment by keradus** [comment]
BTW, added token to AppVeyor as well

**Comment by stof** [comment]
@keradus there is still a fallback to the slower clone then. the question is whether you want to have a github token available publicly (even though a token with no scope is not a big issue, it still allows people to make read requests on your behalf)

**Comment by stof** [comment]
why have you cancelled the AppVeyor build ? you should let the build run as you changed the config file

**Comment by keradus** [comment]
> there is still a fallback to the slower clone then.

So, when possible use cache, when not use dist with oauth (5000 limit), and clone is the last hope.
Isn't it nice?

> the question is whether you want to have a github token available publicly (even though a token with no scope is not a big issue, it still allows people to make read requests on your behalf)

I have no problem with that. That dummy token can be created for dummy account and always changed, right?

---------------

> why have you cancelled the AppVeyor build ?

I will restart it if we agreed to merge the PR.
For now I'm fighting with non-working AppVeyor on another PRs and AppVeyor is busy today (and I don't want to wait an hour to get my job done)

**Comment by GrahamCampbell** [comment]
> For now I'm fighting with non-working AppVeyor on another PRs and AppVeyor is busy today (and I don't want to wait an hour to get my job done)

Is there not something else better out there? AppVeyor is always slow as hell.

**Comment by keradus** [comment]
Feel free to find any ;)

**Comment by GrahamCampbell** [comment]
> Feel free to find any ;)

Haha. Might be faster to just write one. :P

**Comment by GrahamCampbell** [comment]
TBH, that's not too crazy a thought, lol.

**Comment by keradus** [comment]
OK, then please focus on main topic of this PR ;)

**Comment by keradus** [comment]
So...
:+1: ? ;)

**Comment by stof** [comment]
:+1: from me

**Comment by sstok** [comment]
> Is there not something else better out there? AppVeyor is always slow as hell.

Windows, with a 32bit php version (that needs to be reinstalled every time) what do you expect :)
At least it's free in price.

**Pull request merged**
