### PR TITLE
Upgrade php-cs-fixer/accessible-object

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Follow-up to https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5188 and pre-req to https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5183.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Looks like that failure is unrelated, and will also be solved by #5183.

**Comment by keradus** [comment]
To be honest, I was always wondering about need of PRs like those. we don't have lock file, we don't rely on newest version. what's the benefit?
if someone would install ^1.0, he will get newest 1.1 anyway. and requiring ^1.1 would be saying that 1.0 doesn't work anymore for the project - from code perspective, it's not right. from requirements perspective, composer will install the version that is matching the PHP requirement.

With that, i don't see benefit behind this PR

**Comment by SpacePossum** [comment]
after https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5216 we might not need this package anymore

**Comment by GrahamCampbell** [comment]
I guess we can merge this until that is ready. Maybe that PR will only end up in 2.16.

**Comment by keradus** [comment]
or we don't merge it at all and whoever installing PHP CS Fixer via composer will get 1.1 thanks to already in-place ^1.0 requirement

**Comment by keradus** [comment]
I decided to close the PR due to discussion and fact we can drop the dependency in first place (#5242)

**Pull request closed without merging**
