### PR TITLE
NativeFunctionInvocationFixe - fix buggy config validation

### PR DESCRIPTION
**Pull request by keradus**

### CODE REVIEW

**Comment by SpacePossum** [comment]
nice catch :)
I've update the test to be even more strict, feel free to drop that commit if you thing it is to much.

**Comment by keradus** [comment]
I will keep it (but squash during merge)

**Comment by keradus** [comment]
Thank you @SpacePossum.

**Comment by SpacePossum** [comment]
thanks @keradus !

**Pull request merged**
