### PR TITLE
Do not distribute documentation

### PR DESCRIPTION
**Pull request by szepeviktor**
With Packagist and GitHub

### CODE REVIEW

**Comment by SpacePossum** [comment]
Thanks for the suggestion!

I think shipping the docs could be handy for people so would like to keep those in. These could be excluded from the `phar` release, but I'm not sure these are in there.

**Comment by szepeviktor** [comment]
> I think shipping the docs could be handy for people

Your right. But those could take up 0.1% of downloads.
e.g. production installations do not need that for sure

I leave it up to you.

**Comment by keradus** [comment]
docs are out of phar. i would move them away from composer export too.
if one looks for docs, they can go to repo/page/run `describe` command

and docs are like 1.3MB

so, it's 1:1 between core team for now.
@julienfalque @kubawerlos @localheinz , any opinion?

**Comment by SpacePossum** [comment]
I'm +0, happy to go either direction

**Comment by szepeviktor** [comment]
I'm glad that you are not -0

**Comment by kubawerlos** [comment]
I'm for removing the docs from dist, but isn't breaking links in `README.rst` a problem?

**Comment by keradus** [comment]
I'm eager to take that risk and see how many folks would complain, if any

**Comment by keradus** [comment]
I prepared https://github.com/PHP-CS-Fixer/PHP-CS-Fixer.github.io/pull/5 to unblock this PR

**Comment by keradus** [comment]
Thank you @szepeviktor.

**Comment by szepeviktor** [comment]
You're welcome.

**Pull request merged**
