### PR TITLE
Travis - switch to trusty

### PR DESCRIPTION
**Pull request by keradus**
Before:
> Elapsed time 8 min 6 sec
> Total time for 28 min 17 sec

After:
> Elapsed time 6 min 43 sec
> Total time for 25 min

-------------------------------------------

Before:
> HipHop VM 3.5.0 (rel)

After:
> HipHop VM 3.6.6 (rel)

### CODE REVIEW

**Comment by stof** [comment]
?

**Comment by keradus** [comment]
Please, just ignore the test PR ;)

**Comment by keradus** [comment]
pnig @stof

**Comment by keradus** [comment]
ref #1465

**Comment by Soullivaneuh** [comment]
You learn me something, I didn't know we can choose the linux distribution.

Do you have related doc link?

**Comment by GrahamCampbell** [comment]
I think using the newer linux distro, you don't get the container architecture though?

**Comment by keradus** [comment]
Why you woudnt? If I get it right - you can use sudo, but you don't need to.

@Soullivaneuh actually you could just use "default" 12.x or upcoming 14.x, which after some time replace 12.

**Comment by keradus** [comment]
Any thoughts?

**Pull request merged**
