### PR TITLE
bug: BinaryOperatorSpacesFixer: Solve issues with scoped arrow and equal alignments

### PR DESCRIPTION
**Pull request by VincentLanglet**
The PR https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6384 was valid and close:
Closes https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/6220
Closes https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/6223
Closes https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/5896

For the discussion, https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6384#discussion_r927633989
it was solved by https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6450

I also added a fix for
Closes https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/5980

cc @julienfalque 

Edit:
Closes https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/6510
Closes https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/6514
Closes https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/5648

Edit2:
Closes https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/6379
Closes https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/6348

### CODE REVIEW

**Comment by VincentLanglet** [comment]
Just added one commit to fix
- https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/6510
- https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/6514
- https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/5648

**Comment by VincentLanglet** [comment]
And the last commit fixes https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/6379

**Comment by VincentLanglet** [comment]
This is ready to be reviewed @keradus @julienfalque

**Comment by VincentLanglet** [comment]
The main idea of this PR is to rely more on the currentLevel and always scoped the `=`/`=>` replaced.
An opened `(` or `{` is adding on to the current level, when `)` and `}` is removing one.

For instance
```
$obj = new class() extends SomeClass {
    public $someProperty = null;
};
$fabricator->setOverrides(["first" => "Bobby"], $persist = false);
$bobbyUser = $fabricator->make();
if (
     $foo = 1
) {
}
```
was becoming
```
$obj PLACEHOLDER_0 new class() extends SomeClass {
    public $someProperty PLACEHOLDER_1 null;
};
$fabricator->setOverrides(["first" => "Bobby"], $persist = false); // Not touched because not multi-line
$bobbyUser PLACEHOLDER_0 $fabricator->make();
if (
    $foo PLACEHOLDER_1 1
) {
}
```

But I found an issue with 
```
$fabricator->setOverrides(
["first" => "Bobby"], $persist = false);
$fabricator->setOverrides(["first" => "Bobby"], $persist = false
);
```
which became
```
$fabricator->setOverrides(
["first" => "Bobby"], $persist PLACEHOLDER_1 false);
$fabricator->setOverrides(["first" => "Bobby"], $persist PLACEHOLDER_1 false
);
```
so different scope were aligned.

I changed the currentLevel strategy to the following, each scope has a different current level. So now we have
```
$obj PLACEHOLDER_0 new class() extends SomeClass {
    public $someProperty PLACEHOLDER_1 null;
};
$fabricator->setOverrides(["first" => "Bobby"], $persist = false); // Not touched because not multi-line
$bobbyUser PLACEHOLDER_0 $fabricator->make(); // Still in scope 0 when the scope 1 is finished.
if (
    $foo PLACEHOLDER_2 1 // New scope
) {
}
```
and
```
$fabricator->setOverrides(
["first" => "Bobby"], $persist PLACEHOLDER_1 false);
$fabricator->setOverrides(["first" => "Bobby"], $persist PLACEHOLDER_2 false
);
```

**Comment by VincentLanglet** [comment]
Feel free to ask if you want more non-regression tests @julienfalque @keradus :)

**Comment by julienfalque** [comment]
I think there is no test related to #6220 and #6348 cases, can you add some?

**Comment by VincentLanglet** [comment]
> I think there is no test related to #6220 and #6348 cases, can you add some?

Sure, I added one test for the two issues @julienfalque

**Comment by edvordo** [comment]
This worked fine for the issue of multiple consecutive `->method(fn() => value)` statements (`=>` are not aligned), but also did this

```diff
             if (
-                false === is_null($variable)
+                false             === is_null($variable)
                 && $otherVariable === 1
             ) {
```

which I'm not entirely okay with ..

**Comment by VincentLanglet** [comment]
> This worked fine for the issue of multiple consecutive `->method(fn() => value)` statements (`=>` are not aligned), but also did this
> 
> ```diff
>              if (
> -                false === is_null($variable)
> +                false             === is_null($variable)
>                  && $otherVariable === 1
>              ) {
> ```
> 
> which I'm not entirely okay with ..

I introduced this change for arrows to solve the issue https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/5980 by allowing to align `=>` inside the if. I don't really see why this should not be done for other operator, since it aligns them in any other situation. So I assumed this was also ignored because scope alignment wasn't supported so
```
$a = 1;
if ($b = $foo->isTrue()) {}
```
were aligned. 

Why are you not okay with ? I would say it's the purpose of passing 
`'===' => 'align'` in the config. If you don't want to align `===` you should update the config. Or am I missing something ?

**Comment by edvordo** [comment]
Fair enough, updated config to not align `===`, works like a charm!

Any idea of if and when this can be merged?

**Comment by VincentLanglet** [comment]
> Fair enough, updated config to not align `===`, works like a charm!
> 
> Any idea if and when this can be merged?

I'm just a contributor, so it will be when @keradus @julienfalque will have time ;)

**Review by julienfalque — APPROVED** [review]

**Comment by julienfalque** [comment]
Thank you @VincentLanglet.

**Pull request merged**
