### PR TITLE
MethodArgumentSpaceFixer - handle misplaced )

### PR DESCRIPTION
**Pull request by keradus**

### CODE REVIEW

**Comment by keradus** [comment]
ping @SpacePossum , @brendt can you take a look?

@brendt, can you also test it manually before we would merge it?

**Comment by SpacePossum** [comment]
Looking good. I was wondering, can this fixing been done when not using the configuration option `ensure_fully_multiline` ? 
This way it would always fix;
```php
<?php
if (true) {
    execute(
        $foo,
        $bar
        );
}
```

**Comment by brendt** [comment]
I tested this PR, and it seems to work as intended. Any idea when this will be merged and tagged?

**Comment by drupol** [comment]
Seems to be working fine on my side as weel, however, this needs a rebase.

**Comment by SpacePossum** [comment]
Thank you @keradus.

**Comment by drupol** [comment]
Next release is gonna be great!

**Pull request merged**
