### PR TITLE
companion to FriendsOfPHP/PHP-CS-Fixer#3297, type hinting that \PhpCs…

### PR DESCRIPTION
**Pull request by SignpostMarv**
companion to FriendsOfPHP/PHP-CS-Fixer#3297, type hinting that \PhpCsFixer\Config::getFinder() can return \PhpCsFixer\Fixer

### CODE REVIEW

**Comment by keradus** [comment]
duplicate is not needed. close one, and for other one set oldest supported branch

**Comment by SignpostMarv** [comment]
@keradus wasn't aware of that- thanks :)

**Comment by keradus** [comment]
please change target branch to 2.2

**Comment by SignpostMarv** [comment]
@keradus as per your request: #3305

**Comment by keradus** [comment]
ok, as you basically opened same PR against 3 different branches, take a look on this:
https://github.com/blog/2224-change-the-base-branch-of-a-pull-request 
;)

**Comment by SignpostMarv** [comment]
@keradus wasn't aware of that, thanks :D

**Pull request closed without merging**
