### PR TITLE
Add `invoke` option to `ordered_class_elements`

### PR DESCRIPTION
**Pull request by driftingly**
This PR adds an `invoke` option to `OrderedClassElementsFixer`.

When creating invokable controllers in Laravel I typically want the `__invoke()` method listed before any helper methods.
Adding this option will allow specifying in which order the `__invoke()` method appears.

### CODE REVIEW

**Comment by keradus** [comment]
hey @driftingly and thanks for the PR!
can you share if this is some kind-of well established standard for any open source community?

**Comment by SpacePossum** [comment]
isn't `__invoke()` already be covered by config option `magic`  anyways?

**Comment by driftingly** [comment]
> hey @driftingly and thanks for the PR! can you share if this is some kind-of well established standard for any open source community?

In Laravel you can create [single-action controllers ](https://laravel.com/docs/8.x/controllers#single-action-controllers).

```php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Models\User;

class ProvisionServer extends Controller
{
    public function __invoke()
    {
        // ...
    }
}
```

When these invokable methods have any helpers ideally these would be listed below the `invoke()` method.  In this capacity `invoke()` similar to the `__contstruct()` method.  

```php
class ProvisionServer extends Controller
{
    public function __invoke()
    {
        $result = $this->helperMethod();
    }

    private function helperMethod()
    {
        return $result;
    }
}
```

This doesn't appear to be an established Laravel standard but it is [the preference at the agency I work at](https://github.com/tighten/tlint/pull/232).


> isn't `__invoke()` already be covered by config option `magic` anyways?

It is covered by `magic`, but in the same way ` __construct()` is, adding a separate option for `__invoke()` allows greater control in which order it appears.

**Comment by bakerkretzmar** [comment]
+1 for this, `__invoke` is often used as a "handler" method for single action controllers as @driftingly mentioned, and also for things like jobs, event listeners, and actions.

It's similar to `__construct` and I would always want it at the top of a class (right after `__construct` if present). Would love to be able to configure that with this PR!

**Comment by SpacePossum** [comment]
does this not work if you use `magic` ? and if not, can somebody share an example of that?

**Comment by SpacePossum** [comment]
```
Using magic puts them all at the top, including __call, __callStatic, __get, etc. Those I generally still want last, it's specifically __invoke I would want at the top.
```

That shouldn't be the case, using `magic` should puts al_ `magic` methods at the place where you configure these, not just all at the top. I cannot reproduce this either, so an example to reproduce would be needed.

I know however that currently you cannot configure putting `invoke` in a different location than the other magic methods,
This I don't consider an issue as I know of no standard that recommends this exception of `invoke` over the other magic methods.

**Comment by bakerkretzmar** [comment]
Sorry, yes, that's what I meant—not necessarily at the top but all together. So if you wanted `__invoke` at the top, the only way to do that currently would be to to put `magic` at the top, which puts them all there.

You're right, there is no standard that enforces placing `__invoke` at the top of the class. It's a convention in the Laravel ecosystem, and it's something that we would like to be able to use PHP-CS-Fixer for at work, rather than doing manually. Lots of other existing rules and options aren't standards either but are still very useful. This PR adds support for one more existing formatting convention/preference, which I think is a valuable addition to the tool ☺️

**Comment by driftingly** [comment]
What @bakerkretzmar is saying is correct.  We would like to treat the `__invoke()` method similar to the `__construct()` method and specify the order outside of it being included with the other `magic` methods.

With configuration: 

```
['order' => [
    'constant_public',
    'construct',
    'invoke',
    'method_public',
    'magic',
    ]
]
```

---

Before:

```php
<?php

class Example
{
    public const EXAMPLE = true;

    public function helperFunction(){}

    public function __invoke(){}
}
```

After:

```php
<?php

class Example
{
    public const EXAMPLE = true;

    public function __invoke(){}

    public function helperFunction(){}
}
```

---

Before:

```php
<?php

class Example
{
    public const EXAMPLE = true;

    public function __toString(){}

    public function someMethod(){}

    public function __construct(){}
}
```

After:

```php
<?php

class Example
{
    public const EXAMPLE = true;

    public function __construct(){}

    public function someMethod(){}

    public function __toString(){}
}
```

**Comment by SpacePossum** [comment]
Thanks for all the details and work so far. IIUC this is only an issue if you have multiple magic methods in your project and you want `__invoke` at some other location than the other magic methods, yet care for all magic methods.

I'm +0 on it as I don't see a wide use for it, however I see the Laravel use case (cc @GrahamCampbell :)  ).
 
I would like to see unit tests for using both `magic` and `invoke` to see the behavior when using both and another utest when using only this new option.
I assume that `invoke` as a more detailed option is honored over the more generic `magic` case.

But lets see if other members and/or maintainers have more ideas on this first :+1:

**Comment by gharlan** [comment]
I think it is too specific. Don't use `magic` in your order, then you can place these methods where you want (but it will not be enforced).

Maybe we could introduce a more general solution to place methods by name. Like:

```
['order' => [
    'constant_public',
    'construct',
    ['method', '__invoke'],
    ['method', 'myOtherSpecialMethod'],
    'method_public',
    'magic',
]]
```

**Comment by SpacePossum** [comment]
I prefer the more generic solution proposed :+1:

**Comment by driftingly** [comment]
Same, generic solution would provide a lot more functionality.

**Pull request closed without merging**
