### PR TITLE
UnusedUseFixer - prove bugs

### PR DESCRIPTION
**Pull request by keradus**

### CODE REVIEW

**Comment by keradus** [comment]
Looks green, could anyone take a look please?

**Comment by SpacePossum** [comment]
Looks good :)  
Is removing the `i` so effective? 

The only case I can think of not covered by the tests is using the imported class in a static way. For example: 
```php
use my\test\Foo;

$a = 1;

// @see \my\test\Foo::ellow();

$a += Foo::ellow();
``` 

or something simular.

Nice fix! :+1:

**Comment by keradus** [comment]
Thank you. Added ;)

**Comment by gharlan** [comment]
Hmm, class names are case insensitive, so the change looks wrong to me.

```php

use Foo\Bar;

new bar();
```

**Comment by GrahamCampbell** [comment]
I agree this is wrong.

**Comment by keradus** [comment]
Thank you both for catching that! :)
I always write class case-sensitive and didn't think about that in this PR.

Are annotations case insensitive too?
Would sth like that works?
```php
use Doctrine\ORM\Mapping as ORM;

class Foo
{
    /**
     * @orm\Id
     * @orm\GeneratedValue
     * @orm\Column(type="integer")
     */
    private $id;
}
```

Maybe we could keep case-insensitive for code and reject it for comments?

**Comment by GrahamCampbell** [comment]
> Maybe we could keep case-insensitive for code and reject it for comments?

We can't really reject it for phpdoc, but we should reject it for descriptions inside phpdoc. I don't think people should be referencing classes inside written descriptions.

**Comment by GrahamCampbell** [comment]
@keradus How about just making it optional to enable case sensitive mode? We can easily do this via fixer configuration.

**Comment by keradus** [comment]
I think we shouldn't support classes with diferent char case

**Comment by GrahamCampbell** [comment]
Hmmm. Well, it would be good to get this resolved. For me, personally, either way makes no difference, so I'm not massively fussed either way.

**Comment by GrahamCampbell** [comment]
It would be good to get this into the next release.

**Comment by keradus** [comment]
Then good to go or some changes required?

**Comment by gharlan** [comment]
> @keradus How about just making it optional to enable case sensitive mode? We can easily do this via fixer configuration.

:+1:

**Comment by keradus** [comment]
In that case it would be great if someone hijack this PR. I squashed it for convenience.

someone really need insensitive mode? why? :/

**Comment by GrahamCampbell** [comment]
Can we just merge this as is into 1.12 and treat it as a new feature?

**Comment by gharlan** [comment]
it would made the fixer risky, that's the reason why I'm against the change.

**Comment by keradus** [comment]
Closing due to discussion.

**Pull request closed without merging**
