### PR TITLE
Made all test classes final

### PR DESCRIPTION
**Pull request by keradus**
Just a thought... shouldn't all tests be final?

### CODE REVIEW

**Comment by keradus** [comment]
fabbot.io still fails on PHPUnit Optimizations

**Comment by GrahamCampbell** [comment]
Hmmmm, in this context, probably, but I guess it's normally not bothered with because tests are normally in autoload-dev in other projects, but here, they're not separated like that.

**Comment by keradus** [comment]
Whatever they are autoloaded or not one can still import it himself ;)

**Comment by GrahamCampbell** [comment]
> Whatever they are autoloaded or not one can still import them himself ;)

Not out of the box though. Someone would have to go out of their way to get that done.

**Comment by keradus** [comment]
therefore, :+1: ?

**Comment by GrahamCampbell** [comment]
I can't decide. I guess I'm :+1:, but would prefer us to move to a src` `tests` structure at the top.

**Comment by keradus** [comment]
step by step @GrahamCampbell , step by step ;)

**Comment by GrahamCampbell** [comment]
;)

**Comment by SpacePossum** [comment]
nice :+1:

**Comment by SpacePossum** [comment]
@keradus  nice to have this, thanks :)

**Comment by keradus** [comment]
at your service!

**Comment by GrahamCampbell** [comment]
Does add more stuff to remember to change on merge to 2.x though.

**Comment by keradus** [comment]
I do not understand. Does what? more stuff like? where?
It's on master already

**Comment by GrahamCampbell** [comment]
If you merge a PR to 1.11, you need to remember to make its tests final when you to a 1.11->master merge.

**Comment by keradus** [comment]
I have treated changing non-final classes into final as BC break (yeah, even while they are only tests), and merge it directly to 2.x line, see milestone or target branch

**Comment by GrahamCampbell** [comment]
Yeh, I know. I'm talking about future stuff reaching this branch needs making final each time.

**Pull request merged**
