### PR TITLE
NoAliasFunctionsFixer: add die => exit

### PR DESCRIPTION
**Pull request by Slamdunk**
https://secure.php.net/manual/en/function.die.php

### CODE REVIEW

**Comment by Slamdunk** [comment]
Mmm, didn't expect tests to fail 😮

**Comment by Slamdunk** [comment]
Ah yea, die end exit are not functions, but language constructs, so dynamic generated test cases can never happen. Will fix tests soon, with dedicated test case for die.

**Comment by SpacePossum** [comment]
good idea :+1:  but it should not be part of this fixer IMHO

maybe something of value is still in this issue;
https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/1692#issuecomment-173545467

**Comment by julienfalque** [comment]
It's not a function but it's kinda used like one, adding it to this fixer is fine IMO, but I would be ok with a separate fixer as well.

**Comment by carusogabriel** [comment]
Here's a list of all PHP aliases https://secure.php.net/manual/en/aliases.php#aliases. Maybe can help you :smile:

**Comment by Slamdunk** [comment]
The fact that it is a language contruct and not a funtion break `NoAliasFunctionsFixer` algorithm. I'll open a new PR with dedicated fixer.

**Pull request closed without merging**
