### PR TITLE
BracesFixer - Do not pull close tag onto same line as a comment

### PR DESCRIPTION
**Pull request by SpacePossum**
replaces https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4094

this stops the fixer changing:

```php
<?php if ($a) { //
?>
```

into

```php
<?php if ($a) { // ?>
```

### CODE REVIEW

**Comment by dmvdbrugge** [comment]
I disagree with the premise, I think it should pull it up.

**Comment by dmvdbrugge** [comment]
What, no discussion?

**Comment by SpacePossum** [comment]
There was between 3 people of 8 days?

**Comment by dmvdbrugge** [comment]
Kubawerlos only commented on the code, I disagreed with the idea behind the PR. My comment got no reply from you. I don't call that a discussion.

**Comment by SpacePossum** [comment]
I'm not sure what more there is to discuss, some people like this form `<?php if($a) { // ?>` and others don't. I didn't find that form in a major project FOSS project either.

**Comment by dmvdbrugge** [comment]
Ok, so there's the discussion, thanks. Not much I can counter with, if it boils down to stylistic choice only.

Would've been nice to have had that comment earlier though, instead of ignoring me for a week and then just merging, especially since I was the bug reporter and even submitted a PR for it.

**Comment by SpacePossum** [comment]
sorry about that, I just picked of all the RTM PR's without looking into it much more, I'll try to pay more attention next time

**Pull request merged**
