### PR TITLE
PhpdocSeparationFixerTest - Add nested separation fixer tests

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Not passing yet. Needs fixing.

### CODE REVIEW

**Comment by SpacePossum** [comment]
:+1:  thanks for picking this one up :)

**Comment by GrahamCampbell** [comment]
Easy for me to notice since I broke it. :P

**Comment by keradus** [comment]
Any chances for a fix too? :D

**Comment by GrahamCampbell** [comment]
> Any chances for a fix too? :D

Sure. I'll fix this at some point in the near future. Just no time to sit down and work through it right now.

**Comment by GrahamCampbell** [comment]
This fix I have in mind is non-trivial, and I'll be adding more cases to other fixers too, because I'm pretty sure the fixer that changes the order of annotations is totally broken if these kind of annotations are floating around.

**Comment by keradus** [comment]
@ping @GrahamCampbell

**Comment by GrahamCampbell** [comment]
Crap. Forgot about this one. I'll see what time I have to sort it. I'll probably do the PSR4 stuff first since it's going to be more straight foward.

**Comment by keradus** [comment]
OK, whichever issue will be first it's great to have your help!

**Comment by keradus** [comment]
ping @GrahamCampbell

**Comment by GrahamCampbell** [comment]
This is going to take a serious amount of time to actually fix, and I don't have that time just now.

**Comment by keradus** [comment]
ping @GrahamCampbell

**Comment by GrahamCampbell** [comment]
This is going to have to wait until my summer break I'm afraid. It is going to take some serious time.

**Comment by keradus** [comment]
ping @GrahamCampbell

**Comment by keradus** [comment]
ping @GrahamCampbell

**Comment by GrahamCampbell** [comment]
Sorry, won't have time this Month. Super duper busy.

**Comment by keradus** [comment]
The same as last 7 months...

**Comment by GrahamCampbell** [comment]
Lol, well, this month is particularly busy. I'm only "home" for 5 days.

**Comment by SpacePossum** [comment]
>This is going to have to wait until my summer break I'm afraid. It is going to take some serious time.

I hope that is summer 2017 ^_^
On a more serious note, I would really like to see this fixed, so please let us know if you plan on working this :)

**Comment by GrahamCampbell** [comment]
I do plan to tackle this. However, the fix is non-trivial. I basically need a clear day to deal with it.

**Comment by keradus** [comment]
Actually, is this style supported by anyone? IIRC it was removed from phpdoc and psr-5 proposal

**Comment by SpacePossum** [comment]
Closing after almost a year of no activity. Secondly the support would be for a form not widely used.
Feel free to reopen when new development on this has been done together with a ref. to usage of the form, will review then.

**Comment by julienfalque** [comment]
> Actually, is this style supported by anyone? IIRC it was removed from phpdoc and psr-5 proposal

It's still in [PSR-5 draft](https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc.md#examples-12).

**Pull request closed without merging**
