### PR TITLE
Add PhpdocOpeningClosingFixer

### PR DESCRIPTION
**Pull request by Slamdunk**
```diff
-/******
+/*
  * Multiline comment with arbitrary asterisks count
- ******/
+ */

-/**\
+/*\
  * Multiline comment that seems a DocBlock
  */

 /**
  * DocBlock with arbitrary asterisk count at the end
- **/
+ */
```

This fixer fixes both multiline comments and docblock: I've namespaced it under Phpdoc because the main purpose here is to ease the reading and understanding of comments that aren't docblock but can be misundestood as a docblock, like `/*** C */` and `/**\ C */`.

### CODE REVIEW

**Comment by Slamdunk** [comment]
@SpacePossum the backslash in the code sample seems be broking the colouring:
```
$ php php-cs-fixer describe phpdoc_opening_closing
Description of phpdoc_opening_closing rule.
DocBlocks must start with two asterisks, multiline comments must start with a single asterisk, after the opening slash. Both must end with a single asterisk before the closing slash.

Fixing examples:
 * Example #1.
   ---------- begin diff ----------
   --- Original
   +++ New
   @@ -1,13 +1,13 @@
    <?php

   -/******
   +/*
     * Multiline comment with arbitrary asterisks count
   - ******/
   + */

   -/**</fg=red>
   +/*</fg=green>
     * Multiline comment that seems a DocBlock
     */

    /**
     * DocBlock with arbitrary asterisk count at the end
   - **/
   + */
   ----------- end diff -----------
```

**Comment by julienfalque** [comment]
:+1: 

> I've namespaced it under Phpdoc because the main purpose here is to ease the reading and understanding of comments that aren't docblock but can be misundestood as a docblock

I would still move this fixer to the `Comment` namespace as it does not only deal with PhpDoc comments.

**Comment by Slamdunk** [comment]
> I would still move this fixer to the Comment namespace as it does not only deal with PhpDoc comments.

It deals also with PhpDoc comments:
```diff
 /**
  * DocBlock with arbitrary asterisk count at the end
- **/
+ */
```

**Comment by julienfalque** [comment]
That's what I meant :p

Happy to hear more opinions about it though.

**Comment by keradus** [comment]
shall be in `Comment` namespace indeed

**Comment by Slamdunk** [comment]
- [x] `Phpdoc` -> `Comment`
- [x] `PhpdocOpeningClosingFixer` -> `MultilineCommentOpeningClosingFixer`

**Comment by julienfalque** [comment]
Shall we add it to the project config?

**Comment by keradus** [comment]
Thank you @Slamdunk.

**Pull request closed without merging**
