### PR TITLE
WhitespacesAwareFixerInterface clean up

### PR DESCRIPTION
**Pull request by Slamdunk**
Tests pass and `$this->whitespacesConfig` is never called

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
It's a bug that it's not called. It should be.

**Comment by Slamdunk** [comment]
https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.3.2/src/DocBlock/Line.php#L134

**Comment by julienfalque** [comment]
Looks good to me but this should target 2.2.

**Comment by Slamdunk** [comment]
Target changed to `2.2` and rebased

**Comment by SpacePossum** [comment]
@GrahamCampbell can you elaborate on your comment, I wonder about this as well.

**Comment by Slamdunk** [comment]
@SpacePossum it's easy: the whitespace configuration was used, but now the only functionalities that interact with new-lines are:

1. https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.3.2/src/Fixer/Phpdoc/PhpdocSeparationFixer.php#L104
1. https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.3.2/src/Fixer/Phpdoc/PhpdocSeparationFixer.php#L170

A method that find itself the newline style:

https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.3.2/src/DocBlock/Line.php#L134

So everything is ok

**Comment by SpacePossum** [comment]
thanks @Slamdunk :)

**Comment by keradus** [comment]
Thank you @Slamdunk.

**Pull request merged**
