### PR TITLE
Do not update Composer twice

### PR DESCRIPTION
**Pull request by sanmai**
This is done already at the start of the build:
https://travis-ci.com/github/FriendsOfPHP/PHP-CS-Fixer/jobs/434729269#L182-L183

(It wasn't before.)

### CODE REVIEW

**Comment by SpacePossum** [comment]
Hi and thanks for your PR!

I think this is happening on 2.15 as well, maybe you can target that branch? You removed both the self-update statements, do we not need one?

**Comment by sanmai** [comment]
Sure thing! Should I retarget #5262 to 2.15 too?

**Comment by SpacePossum** [comment]
nice, thanks for the rebase and info :+1:

**Comment by sanmai** [comment]
No prob. It wasn't a mistake when this was added initially, just for the record. At that time Travis CI wouldn't update to Composer v2 because it wasn't released yet.

**Comment by SpacePossum** [comment]
Thank you @sanmai.

**Pull request merged**
