### PR TITLE
Removed unneeded brackets

### PR DESCRIPTION
**Pull request by GrahamCampbell**
:trollface:

### CODE REVIEW

**Comment by keradus** [comment]
Closing due to #1867

**Comment by GrahamCampbell** [comment]
k :P

**Comment by TomasVotruba** [comment]
Is there some fixer to remove unneded brackes? I recall I saw it somewhere, but could not find it here.

```diff
-(echo  "hi");
+echo  "hi";
```

**Comment by SpacePossum** [comment]
I think you are looking for `no_unneeded_control_parentheses` (for the `echo` case)

**Comment by TomasVotruba** [comment]
Thanks for the guide. I actually need it for:

```diff
 function test()
 {
-    (yield 5);
+    yield 5;
 }
```

I tried the `PhpCsFixer\Fixer\ControlStructure\NoUnneededControlParenthesesFixer` but it doesn't cover this.

**Comment by keradus** [comment]
Sadly, we do not have such rule.
I see value of it as well, could you propose a PR ?

**Comment by TomasVotruba** [comment]
I actually resolved it in the place of origin: https://github.com/rectorphp/rector/pull/421/files

**Pull request closed without merging**
