### PR TITLE
Fix typos in changelog

### PR DESCRIPTION
**Pull request by mnabialek**

### CODE REVIEW

**Comment by keradus** [comment]
and now I'm wondering.... changelog is autogenerated :D

**Comment by mnabialek** [comment]
@keradus All those typos were also in commits/pull requests :) Just found one today when looking for something so I fixed also others I found

**Comment by keradus** [comment]
yeah, I understand that. I am just wondering how to not drop your fixes next time I would regenerate the readme (which is using, basically, `git log` under the hood)

**Comment by SpacePossum** [comment]
Thanks @mnabialek.

**Pull request merged**
