### PR TITLE
PhpdocAnnotationWithoutDotFixer - Handle multibyte chars

### PR DESCRIPTION
**Pull request by WinterSilence**
Fix for multibyte charsets, current version breake first letter)
изображение

### CODE REVIEW

**Comment by SpacePossum** [comment]
Hi @WinterSilence ,

Thanks for the PR! Since it is a bug fix could you maybe target 2.15 as that is the lowest supported branch. That way your fix will be shipped to as many people as possible.
Could you maybe update the unit test for this fixer so in the future this bug won't happen again, thanks :)

**Comment by WinterSilence** [comment]
@SpacePossum Ok, I'm try some later. But my fix it's only little part of this trouble. 50% fixes without  regex  `/u` + 90% fixes not use 'mb_' functions at change text.

**Comment by kubawerlos** [comment]
@WinterSilence can you show a place where there is a regex without `/u` run?

**Comment by WinterSilence** [comment]
@kubawerlos my mistake based on regexes as [this](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/src/Fixer/Phpdoc/PhpdocAnnotationWithoutDotFixer.php#L101) (:

**Pull request closed without merging**
