### PR TITLE
Tokens - improve block end lookup

### PR DESCRIPTION
**Pull request by keradus**
Before:
> Fixed all files in 17.040 seconds, 14.000 MB memory used
> Fixed all files in 17.615 seconds, 14.000 MB memory used
> Fixed all files in 17.188 seconds, 14.000 MB memory used

After:
> Fixed all files in 16.581 seconds, 14.000 MB memory used
> Fixed all files in 16.579 seconds, 14.000 MB memory used
> Fixed all files in 16.456 seconds, 14.000 MB memory used

few % improved

### CODE REVIEW

**Comment by keradus** [comment]
@SpacePossum , we had a small talk about it ages ago. take a look ;)

**Comment by SpacePossum** [comment]
awesome :)

**Comment by SpacePossum** [comment]
One question,
if `$isLegacyMode` is `true` the cache might be outdated if tokens are changed using `Token::override` / `Tokens::overrideAt` I think, maybe best not to use the cache if in legacy mode?

**Comment by keradus** [comment]
very good point

**Comment by keradus** [comment]
done

**Comment by SpacePossum** [comment]
thanks, looks good to me :+1:

**Pull request closed without merging**
