### PR TITLE
SemicolonAfterInstructionFixer - Fix case where block ends with an opening curly brace

### PR DESCRIPTION
**Pull request by ntzm**
`<?php if ($x) { ?>` was turned into `<?php if ($x) {; ?>`

### CODE REVIEW

**Comment by julienfalque** [comment]
👍 (AppVeyor failures unrelated, probably due to recent Symfony releases).

**Comment by SpacePossum** [comment]
Nice catch;
however this should still be fixed:

```php
<?php function A(){  } ?>
```

so I think the code needs to be updated.

**Comment by ntzm** [comment]
You're right @SpacePossum

**Comment by keradus** [comment]
Thank you @ntzm.

**Comment by SpacePossum** [comment]
Thanks @ntzm solid fix!

**Pull request closed without merging**
