### PR TITLE
Adding new configuration option 'position_after_multiline_functions_and_oop_constructs' for classy constructs with the argument list is split across multiple lines

### LINKED ISSUE #3637: 'braces' with option 'position_after_functions_and_oop_constructs' = 'next' does not work for multi line methods
When reporting an issue (bug) please provide the following information:

#### The PHP version you are using (`$ php -v`):
=> php 7.1.13

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> .PHP CS Fixer 2.10.0

#### The command you use to run PHP CS Fixer:
=> fix

#### The configuration file you are using, if any:
```php
=>'braces' => [
                'allow_single_line_closure' => true,
                'position_after_anonymous_constructs' => 'same',
                'position_after_functions_and_oop_constructs' => 'next',
                'position_after_control_structures' => 'same',
            ],
```

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
=> private function __construct(
    argument 1,
    argument 2,
    argument 3,
    argument 4
) 
{
}
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
=> private function __construct(
    argument 1,
    argument 2,
    argument 3,
    argument 4
) {
}
```

 * with the changes you expected instead:
```php
=> private function __construct(
    argument 1,
    argument 2,
    argument 3,
    argument 4
) 
{
}
```

### PR DESCRIPTION
**Pull request by CMalvika**
Closes #3637.

### CODE REVIEW

**Comment by SpacePossum** [comment]
Thanks @CMalvika for this PR. I didn't review it (yet), just wanted to let you know not to worry about the failing `RunnerTest`, it will be fixed soon elsewhere.

**Comment by CMalvika** [comment]
@SpacePossum thanks and very kind of you to replying fast. Just for my knowledge, when do you think you will get time to review it and if it's valid then merge it? As, i really need this thing, otherwise i would need to patch it.

Thanks again..

**Comment by julienfalque** [comment]
Note: the `braces` rule is being splitted (#4884) and deprecated (#4885). I would suggest to wait for these PRs to be finished before working further on this one.

**Comment by lstrojny** [comment]
@julienfalque thanks for the heads up, will wait

**Comment by CMalvika** [comment]
> Note: the `braces` rule is being splitted (#4884) and deprecated (#4885). I would suggest to wait for these PRs to be finished before working further on this one.

@julienfalque Thanks a lot from heads up here. Do you still think that this PR makes sense, we will have this option in future? 
Thank you once again!

**Comment by julienfalque** [comment]
@CMalvika I think the PR still makes sense. Though refactoring `braces` takes time and won't be completed soon I'm afraid. Implementing the new option seems fairly simple so I don't think it will create a huge conflict if we merge this PR before refactoring `braces`. Maybe we don't need to wait after all.

**Comment by CMalvika** [comment]
> @CMalvika I think the PR still makes sense. Though refactoring `braces` takes time and won't be completed soon I'm afraid. Implementing the new option seems fairly simple so I don't think it will create a huge conflict if we merge this PR before refactoring `braces`. Maybe we don't need to wait after all.

Thank you very much, we will wait then.

**Pull request closed without merging**
