### PR TITLE
HeaderCommentFixer - Fix unexpected removal of regular comments

### LINKED ISSUE #4925: Header comment fixer regression
https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4870 seems to have broken `HeaderCommentFixer` in PHP-CS-Fixer ≥ 2.16.2. It is now removing other comments in the top scope.

When reporting an issue (bug) please provide the following information:

#### The PHP version you are using (`$ php -v`):
=> 7.4.4

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> 2.16.3

#### The command you use to run PHP CS Fixer:
=> vendor/bin/php-cs-fixer fix test.php

#### The configuration file you are using, if any:
```php
<?php

return PhpCsFixer\Config::create()
    ->setRules([
        'header_comment' => [
            'header' => 'header',
            'location' => 'after_open',
        ],
    ])
;
```

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
<?php

/*
 * header
 */

declare(strict_types=1);

// Do not allow this script to be used on web
if ('cli' !== PHP_SAPI) {
    http_response_code(500);
    exit(1);
}
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
<?php

/*
 * header
 */

declare(strict_types=1);
if ('cli' !== PHP_SAPI) {
    http_response_code(500);
    exit(1);
}
```

 * with the changes you expected instead:
```php
<?php

/*
 * header
 */

declare(strict_types=1);

// Do not allow this script to be used on web
if ('cli' !== PHP_SAPI) {
    http_response_code(500);
    exit(1);
}
```

### PR DESCRIPTION
**Pull request by julienfalque**
Fixes #4925.

### CODE REVIEW

**Comment by SpacePossum** [comment]
I think this will still remove the 2nd comment:

```php
<?php

/*
 * foo
 */

declare(strict_types=1);

/* 2 */
foo();
```

**Comment by julienfalque** [comment]
Indeed. Also this was a bad fix. I tried a different approach, I think it's more robust and reliable, but it's also a small behavior change: now the comments that are not in the expected location will not be removed unless they have the exact same content as the header.

**Review by cs278 — APPROVED** [review]
Resolves #4925 for me.

**Review by Jamesking56 — APPROVED** [review]

**Comment by SpacePossum** [comment]
Thank you @julienfalque.

**Pull request merged**
