### PR TITLE
EmptyReturnFixer - Make independent of LowercaseConstantsFixer

### PR DESCRIPTION
**Pull request by SpacePossum**

### CODE REVIEW

**Comment by keradus** [comment]
:+1:, but for 1.11.x

**Comment by SpacePossum** [comment]
> but for 1.11.x

do you want a new PR or can you retarget this when merging?

**Comment by keradus** [comment]
I will retarget it

**Comment by gharlan** [comment]
:+1:

**Comment by keradus** [comment]
Thank you @SpacePossum.

**Pull request merged**
