### PR TITLE
Exclude more tests in phar version

### PR DESCRIPTION
**Pull request by keradus**

### CODE REVIEW

**Comment by SpacePossum** [comment]
Won't this remove `src/Test/IntegrationCase.php` for example, that is a valid API/endpoint right?

**Comment by GrahamCampbell** [comment]
I guess that class should have been marked as `@internal`.

**Comment by SpacePossum** [comment]
don't think so, it a useful class for authors of 3rd party fixers

**Comment by keradus** [comment]
that's my goal @SpacePossum 
this class is still visible when one install package as library as dependency via composer, but when one install project as CLI app, he doesn't need to have it.

**Comment by SpacePossum** [comment]
alright than :)

**Pull request merged**
