### PR TITLE
Add a failing test for detection of lambdas returning by reference

### PR DESCRIPTION
**Pull request by stof**

### CODE REVIEW

**Comment by stof** [comment]
hmm, thinking about it, the bug should be fixed in 1.4 (but the test should go in a different location)

**Comment by stof** [comment]
Btw, the case of reference-returning functions should probably be checked for all places handling functions

**Comment by keradus** [comment]
@stof, could you take a look on #965 ? I have added some test cases for fixers too and a fix for Tokens::isLambda (1.4, so no TokensAnalyzer yet)

**Comment by keradus** [comment]
Fixed in #965, thank you @stof !

**Comment by stof** [comment]
great, thanks

**Pull request closed without merging**
