### PR TITLE
[WIP]Fix header comment & declare strict integration

### PR DESCRIPTION
**Pull request by BackEndTea**
This is a failing test case which 'proves' the bug in #3467

### CODE REVIEW

**Comment by kubawerlos** [comment]
The bug more of `DeclareStrictTypesFixer` itself than the combination of fixers, [this](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.10/tests/Fixer/Strict/DeclareStrictTypesFixerTest.php#L74) case exactly.

**Comment by BackEndTea** [comment]
Since that is part of the test case i'm wondering what the best solution here is

* Check if the **exact** same header is applied below declare strict if it is present, and if so, remove it and apply it again before declare strict (if configuration says after opening tag)
* Make declare strict apply below header comment if it is present (Probably a BC break)

ping @keradus

**Comment by SpacePossum** [comment]
for more background on this please see https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/2590
(there are links to other issues/PR's as well related to this)

(possibly https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/2363)

it would be awesome to this old issue resolved, it is a hard one though...

**Comment by BackEndTea** [comment]
@SpacePossum 

What do you think of this solution:
>Check if the exact same header is applied below declare strict if it is present, and if so, remove it and apply it again before declare strict (if configuration says after opening tag)

**Comment by julienfalque** [comment]
I think the solution proposed by @BackEndTea is the way to go. The fixer should check all possible positions of the header (`after_open` and `after_declare_strict` for now) and remove it from positions that are not the expected one.

This should prevent conflicts with `declare_strict_types` and fix an edge case: if one changes the configured position of the header, the fixer will duplicate the header even if the `declare` statement is already there, because currently the fixer only checks the configured position, not the other ones.

**Pull request closed without merging**
