### PR TITLE
Fixers - better comments handling

### PR DESCRIPTION
**Pull request by SpacePossum**
Add a bunch of tests, some passes but a lot don't, either break code or fixes wrongly (or not at all).

replaces https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2599

### CODE REVIEW

**Comment by SpacePossum** [comment]
PR should be ready.
Happy to take review findings on these bug fixes!

**Comment by julienfalque** [comment]
👍 great work :)

**Comment by keradus** [comment]
~40 files, ~800 lines, hard for careful review here... are you confident about this PR?

please rebase anyway

**Comment by SpacePossum** [comment]
Yeah I'm sure about this one, 
for the review please just focus on the changes of the Fixers. 
The other tests are nice, however if those pass than those pass and are of value to add to the repo.
Will rebase soon!

**Comment by keradus** [comment]
> Alternative I'm happy to open PR's for each fixer + its test and have one PR for all tests passing without changes to their fixers.

Nah, I agree that it wouldn't bring much value, just current PR is not sth that could be properly reviewed in 5 minutes ;)

**Comment by SpacePossum** [comment]
rebase :)
Yeah this won't a 5 minutes one, sorry about that.
However it is important as the Fixers touched do break valid code so need updating.

**Comment by keradus** [comment]
Thank you @SpacePossum.

**Comment by SpacePossum** [comment]
you're welcome @keradus , seems the script failed to close this PR though?

**Comment by keradus** [comment]
it would be autoclosed when I will merge 2.1 into master, as master is main branch currently.

**Comment by keradus** [comment]
merged into master

**Comment by SpacePossum** [comment]
thanks @keradus :D

**Pull request closed without merging**
