### PR TITLE
TESTING: FunctionTypehintSpaceFixerTest - add failing tests

### PR DESCRIPTION
**Pull request by xenmayer**
FunctionTypehintSpaceFixerTest does not remove useless spaces.

### CODE REVIEW

**Comment by SpacePossum** [comment]
indeed it doesn't, from the description I don't expect it either;

>Add missing space between function's argument and its typehint.

Would be nice to do the fixing as your test are suggesting, maybe it could be an option added to `method_argument_space` ? Like to here more opinions on.
(I would like to merge `FunctionTypehintSpaceFixerTest` into there as well some day, maybe for 3.x).

**Comment by xenmayer** [comment]
@SpacePossum ok, thanx) this feature will be great) I'm often finding useless spaces in methods arguments on my gitlab diffs(( which I need to fixing by hands((((

**Comment by kubawerlos** [comment]
The whitespaces before `&` were fixed in https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4421.

Should the whitespace after `&` be the responsibility of the `FunctionTypehintSpaceFixer`? In this code:
```php
function foo(? Bar \ Baz & ... $x) {}
```
how much is the type? Whole `? Bar \ Baz & ...`?

The space after `?` could be removed using `compact_nullable_typehint`.
The spaces after `&` could be removed using `unary_operator_spaces`.

**Comment by SpacePossum** [comment]
```
[02:47 PM]-[possum@aquarium]-[~/work/PHP-CS-Fixer]-[git master]
$ php php-cs-fixer fix test.php  -vvv --dry-run --diff
PHP CS Fixer 3.5.0 The Creation by Fabien Potencier and Dariusz Ruminski.
PHP runtime: 7.4.24
Loaded config default from "/home/possum/work/PHP-CS-Fixer/.php-cs-fixer.dist.php".
Paths from configuration file have been overridden by paths provided as command arguments.
F                                                                                                                                                                   1 / 1 (100%)
Legend: ?-unknown, I-invalid file syntax (file ignored), S-skipped (cached or empty file), .-no changes, F-fixed, E-error
1) PHP-CS-Fixer/test.php (function_declaration, function_typehint_space)
---------- begin diff ----------
--- /home/possum/work/PHP-CS-Fixer/test.php
+++ /home/possum/work/PHP-CS-Fixer/test.php
@@ -12,6 +12,6 @@
* with this source code in the file LICENSE.
*/

-function foo(  callable      $param   ): void
+function foo(callable $param): void
{
}
```

I think all functionality to fix as wanted has been added over time, let me know if not and than we can reopen based on up-to-date example, thanks :+1:

**Pull request closed without merging**
