### PR TITLE
[TrailingCommaInMultilineArrayFixer] simplify isMultilineArray condition

### PR DESCRIPTION
**Pull request by TomasVotruba**
Just a trial. This might speed up things a bit.

### CODE REVIEW

**Comment by keradus** [comment]
please prove its actually fasten anything.
nest scenario: 1 jump into function less, 1 trivial object (no work in constructor) instantation less
I wouldn't expect this PR to gain any visible performance improvement ,it's extra small microoptimization.

**Comment by TomasVotruba** [comment]
Sorry, I didn't mean speed up in performance, but in reading the code.

**Comment by julienfalque** [comment]
I also doubt the performance gain will ever be noticeable. But indeed this simplifies the code so 👍 .

This should target 2.2 though. @TomasVotruba if you have some time, could you please rebase onto 2.2?

**Comment by TomasVotruba** [comment]
@juliendufresne Thanks for reply. I've a little time so I've rather prepared standalone PR #2982

**Pull request closed without merging**
