### PR TITLE
IsNullFixerTest - set exception expectation on top

### PR DESCRIPTION
**Pull request by keradus**

### CODE REVIEW

**Comment by julienfalque** [comment]
I'm not in favor of standardizing such changes. Setting the exception expectation at the very beginning of the test means that anything in the test is allowed to throw said exception, including the fixer instanciation. Here it is quite unlikely to happen, but still.

**Comment by keradus** [comment]
on the same side, we test one method in one test method.
For that, it is not allowed in this project to set up exception expectation and call multiple methods ;)

**Comment by SpacePossum** [comment]
>For that, it is not allowed in this project to set up exception expectation and call multiple methods ;)

Agreed, however it cannot be helped in all cases. For example one might need to call a constructor to create an object where you want to call that one method on, the constructor might throw the exception as well while it shouldn't. 
I prefer setting the expected exception just before calling what is supposed to throw the exception.

**Comment by localheinz** [comment]
For reference, also see https://thephp.cc/news/2016/02/questioning-phpunit-best-practices.

**Comment by keradus** [comment]
Closing **without** merging due to discussion.
Thanks guys !

**Comment by SpacePossum** [comment]
:+1: please know it was not personal :)  thanks for PR'ing!

**Comment by keradus** [comment]
of course, reasoning was nice ;)

**Pull request closed without merging**
