### PR TITLE
DX: Add tests for type colon in backed enums

### PR DESCRIPTION
**Pull request by jrmajor**

### CODE REVIEW

**Comment by jrmajor** [comment]
Maybe `type_colon` option can be dropped from SingleSpaceAfterConstructFixer in favor of ReturnTypeDeclarationFixer in the next major version?

**Comment by SpacePossum** [comment]
:+1: for the new tests, nice addition :) 
for the new doc line, I think the current one is more like the others we got, so +0 for me on that

**Comment by julienfalque** [comment]
> Maybe `type_colon` option can be dropped from SingleSpaceAfterConstructFixer in favor of ReturnTypeDeclarationFixer in the next major version?

I would also prefer this syntax to be fixed by `return_type_declaration` rather than `single_space_after_construct` so I'm ok with deprecating `type_colon` option from `SingleSpaceAfterConstructFixer`. However, I think support for backed enum types in `ReturnTypeDeclarationFixer` was not initially intended and it works by accident. This is likely why the name only mentions return types. I think we should rename the fixer.

**Comment by jrmajor** [comment]
> I'm ok with deprecating type_colon option from `SingleSpaceAfterConstructFixer`.

I don't know how to make one of the allowed values deprecated.

> However, I think support for backed enum types in `ReturnTypeDeclarationFixer` was not initially intended and it works by accident. This is likely why the name only mentions return types. I think we should rename the fixer.

Sure, we can't do that in a minor version though, right?

**Comment by julienfalque** [comment]
> I don't know how to make one of the allowed values deprecated.

You can do it like the [`use_trait` value for option `tokens` of rule `no_extra_blank_lines`](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/src/Fixer/Whitespace/NoExtraBlankLinesFixer.php#L79=).

> Sure, we can't do that in a minor version though, right?

I meant only the first step for now: copying the current fixer to a new one with the new name and deprecating the current one (with `DeprecatedFixerInterface` and maybe `AbstractProxyFixer`).

We'll actually remove the deprecated fixer when we decide to work on a major release.

**Review by SpacePossum — APPROVED** [review]
I suggest merging this as-is and opening a new PR for the rename/deprecation.

**Review by julienfalque — APPROVED** [review]

**Comment by julienfalque** [comment]
Thank you @jrmajor.

**Pull request merged**
