### PR TITLE
Removed symfony23 finder

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by sstok** [comment]
Explain?

**Comment by GrahamCampbell** [comment]
Symfony use the default finder. Their config is committed in their code base...

**Comment by GrahamCampbell** [comment]
https://github.com/symfony/symfony/blob/2.3/.php_cs

**Comment by GrahamCampbell** [comment]
https://github.com/symfony/symfony/blob/2.7/.php_cs

**Comment by sstok** [comment]
Ah, ok :)

:+1: then.

**Comment by keradus** [comment]
What about Magento?
https://github.com/magento/magento2/blob/develop/.php_cs

**Comment by GrahamCampbell** [comment]
I'd rather keep that to a different PR. Infact, I think we should remove that extra namespace we have too.

**Comment by GrahamCampbell** [comment]
For config and finder.

**Comment by keradus** [comment]
> I'd rather keep that to a different PR

why?
Clearing old configs/finders and keeping universal one seems to be quite atomic ;)

**Comment by GrahamCampbell** [comment]
This probably needs a larger refactor. Someone else can take this if they want. If not, I'll get back to this when I have more time.

**Pull request closed without merging**
