### PR TITLE
Added a failing test to the unneeded control parentheses fixer

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by keradus** [comment]
It's all green?

**Comment by gharlan** [comment]
maybe it's failing only on 2.x?

**Comment by GrahamCampbell** [comment]
> It's all green?

lol, errr

**Comment by keradus** [comment]
so? what;s going on?

**Comment by GrahamCampbell** [comment]
D'no, lol. I'll make a test on 2.x later on and see if it's failing. Probably will make it an integration test.

**Comment by keradus** [comment]
ping @GrahamCampbell ;)

**Comment by keradus** [comment]
ping @GrahamCampbell

**Comment by gharlan** [comment]
@GrahamCampbell checked your test case with 2.0: no failures.

**Comment by keradus** [comment]
Thank you @gharlan

**Pull request closed without merging**
