### PR TITLE
AppVeyor - install dev deps as well

### PR DESCRIPTION
**Pull request by keradus**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
We need `--no-dev` still surely?

**Comment by GrahamCampbell** [comment]
Just saw the description. Why would we want to do this?

**Comment by keradus** [comment]
Backported from 2.x line. Without this tests won't run (we have fixtures for test as well, and without this PSR4 autoloader wont load things from tests dir)

**Comment by keradus** [comment]
Also, we install devs on Travis ;)

**Comment by GrahamCampbell** [comment]
> Also, we install devs on Travis ;)

That's because we actually use the dev-dependencies on travis. We do not use them on windows.

**Comment by keradus** [comment]
`--no-dev` not only disable dependencies, but also autoloader.

**Comment by GrahamCampbell** [comment]
Ah, of course. This PR is thus required for your PSR-4 changes to work.

**Pull request merged**
