### PR TITLE
DeclareEqualNormalizeFixer - Add config option

### PR DESCRIPTION
**Pull request by SpacePossum**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Should target 2.1 rather than 2.0?

**Comment by SpacePossum** [comment]
>Should target 2.1 rather than 2.0?

there is no 2.1 branch

**Comment by GrahamCampbell** [comment]
> there is no 2.1 branch

The branch for which the version is 2.1, ie, master.

**Comment by GrahamCampbell** [comment]
https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/composer.json#L48

**Comment by SpacePossum** [comment]
why not make 2.1 from 2.0 and use master for next major?

**Comment by GrahamCampbell** [comment]
> why not make 2.1 from 2.0 and use master for next major?

No point for now.

**Comment by SpacePossum** [comment]
>No point for now.

so no point for retarget, as master and 2.0 are the same

**Comment by keradus** [comment]
`master` is `2.1@dev`, `2.0` is 2.0 bugfixes and docs line, retargetted, please resolve conflicts

**Comment by SpacePossum** [comment]
done, please :shipit:

**Comment by keradus** [comment]
Thank you @SpacePossum.

**Pull request merged**
