### PR TITLE
[2.0] The plural of config is config

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by keradus** [comment]
Could you link some linguisting backup?

https://en.wiktionary.org/wiki/configs#English

**Comment by GrahamCampbell** [comment]
Hmmm, I've never seen anyone write configs before.

Is configs not a bit like monies then? Ie, used to describe the plural of a plural?

**Comment by GrahamCampbell** [comment]
Also, my in browser spellchecker says configs is wrong.

**Comment by GrahamCampbell** [comment]
Yeh, configs is wrong because config is already plural.

**Comment by jbrooksuk** [comment]
"configs" doesn't seem right.

**Comment by GrahamCampbell** [comment]
http://www.oxforddictionaries.com/definition/english/configuration

**Comment by GrahamCampbell** [comment]
No plural is mentioned here.

**Comment by keradus** [comment]
http://www.oxforddictionaries.com/definition/english/interface here too, yet we have interfaces.

`money` is uncountable, that is why in general you don't have monies etc.
`configuration` is countable and you have plural form `configurations`.

I always use `configs` - full words is countable, why shortcut not.
I do not know which form is better. But [google](https://www.google.pl/search?q=configs) founds 6 milions configs on pages, `configuration` is countable.
That why I ask what form is the grammar one - simply because I don't know.

**Comment by GrahamCampbell** [comment]
> that is why in general you don't have monies etc.

Monies does exist. When you do multiple transactions if money, you refer to monies.

**Comment by keradus** [comment]
yeah, that is that general part ;)

**Comment by GrahamCampbell** [comment]
Interfaces seems right as the plural of interface to me as an English speaker, but configs feels wrong.

**Comment by jbrooksuk** [comment]
Interfaces is correct. "Configs" is not :)

**Comment by keradus** [comment]
That is why I asked for grammar ref, not a feeling ;)

// btw https://github.com/symfony/symfony/search?utf8=✓&q=Configs

**Comment by GrahamCampbell** [comment]
Well symfony's made a massive mess of this then. Just because they've done it wrong, it doesn't mean we should too.

**Comment by SpacePossum** [comment]
isn't `config` short for configuration? `configurations` seems legit 
https://en.wiktionary.org/wiki/configuration

**Comment by GrahamCampbell** [comment]
I'm just telling you that no actual English person I know would ever say "configs". I can see this is getting nowhere and has been a complete waste of time.

**Comment by SpacePossum** [comment]
> I can see this is getting nowhere and has been a complete waste of time.

Sorry to hear you feel that way, it was not my intend with my comment.. :S

>I'm just telling you that no actual English person I know would ever say "configs"

I didn't know know "configs" is not common among English persons and I do not doubt it when you tell me. I find such language facts interesting. especially since it appears the Dutchies do use it although it is not a Dutch word at all ;) Maybe it is because we have a plural form for configurations in Dutch and we just started to use the non-valid plural "English" form "configs" as well.

The whole 'interesting` part aside; you and jbrooksuk are +1, keradus and I -1, so I think it still a valid PR to discuss.... :)

**Comment by keradus** [comment]
I'm not -1. I said I do not know if the form is incorrect or not and asked for some grammar reference which was not given, and to be honest I can't find one too.

I have an idea... to keep everything happy maybe we should just use full word, then `configurations` and `configuration` will not be controversial.

**Comment by GrahamCampbell** [comment]
Configurations is just as wrong as configs.

**Comment by jbrooksuk** [comment]
"Configurations" is fine? https://en.wiktionary.org/wiki/configurations#English

**Comment by GrahamCampbell** [comment]
If the full version is fine, then he short version is fine be definition.

**Comment by keradus** [comment]
Yeah, indeed.
Just try to look for sth to not have variables like `$c`...

**Comment by GrahamCampbell** [comment]
I've just worked out why configs sounds so wrong - it's because a "config" is the entire thing - each individual element of the config isn't config - that's why this sounds so wrong. All the elements together are what I would call "config".

**Comment by GrahamCampbell** [comment]
Configurations would describe multiple config files for example.

**Comment by keradus** [comment]
And in our case we have that `configurations` here - few independent configuration for different kind of project

**Comment by GrahamCampbell** [comment]
Wee seem to be calling an entire config file "configurations" in some places which is wrong IMO.

**Pull request closed without merging**
