### PR TITLE
SingleTraitInsertPerStatementFixer - Introduction

### PR DESCRIPTION
**Pull request by SpacePossum**
closes https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/2103

### CODE REVIEW

**Comment by ntzm** [comment]
Not sure about the name, `single_trait_import_per_statement` or `single_trait_use_per_statement` makes more sense imo

**Comment by SpacePossum** [comment]
I looked at the [docs](http://php.net/manual/en/language.oop5.traits.php) for the correct terminology but didn't found anything concluding, so all names are fine with me :)

**Comment by gharlan** [comment]
Please add some tests with `use` statements with `{ }`, like this (example from http://php.net/manual/de/language.oop5.traits.php#example-214):

```php
class Talker {
    use A, B {
        B::smallTalk insteadof A;
        A::bigTalk insteadof B;
    }
}
```

Do we want to change this one? 
It seems to work: https://3v4l.org/oGJJr, but I would prefer to not change it.

**Comment by SpacePossum** [comment]
Suggestions for adding this fixer to a set?

**Pull request merged**
