### PR TITLE
PhpdocTrimFixer - Fix handling of lines without leading asterisk

### LINKED ISSUE #3220: multi line annotation problem
For configuration or updating questions please read the README and UPGRADE documentation,
or visit: https://gitter.im/PHP-CS-Fixer

When reporting an issue (bug) please provide the following information:

The PHP version you are using:
$ php -v
`PHP 7.0.25 (cli) (built: Nov  4 2017 10:58:36) ( NTS )`

PHP CS Fixer version you are using:
$ php-cs-fixer -V
`PHP CS Fixer 2.8.0 Round Numbers by Fabien Potencier and Dariusz Ruminski`

The command you use to run the fixer (and the configuration file you are using if any).

`vendor/bin/php-cs-fixer fix`

with the following config:

*.php_cs*
```php
<?php

$finder = PhpCsFixer\Finder::create()
    ->in('src')
    ->in('tests')
;

return PhpCsFixer\Config::create()
    ->setRiskyAllowed(true)
    ->setRules([
        '@Symfony' => true,
        'ordered_class_elements' => true,
        'ordered_imports' => true,
        'no_unused_imports' => true,
        'psr4' => true,
    ])
    ->setFinder($finder)
;
```
A minimal sample of valid PHP code that is not fixed correctly (if applicable).

```php
<?php

namespace SupplierPortalBackendBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use SupplierPortalBackendBundle\Annotation\Filter;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity
 * @ORM\HasLifecycleCallbacks()
 * @ORM\Table(name="sp_purchase_order_item_history", indexes={
      @ORM\Index(name="idx_sp_item_history_pending", columns={"status_pending"}),
      @ORM\Index(name="idx_sp_item_history_created", columns={"created_at"}),
      @ORM\Index(name="idx_sp_item_history_status", columns={"status_new","status_old"}),
      @ORM\Index(name="idx_sp_item_history_po_id", columns={"order_id"}),
      @ORM\Index(name="idx_sp_item_history_co_id", columns={"sales_order_number"})
   })
 */
class PurchaseOrderItemHistory
{
```

The fixed version of that code after you run the fixer and the version you expected.

```diff
  * @ORM\Entity
  * @ORM\HasLifecycleCallbacks()
  * @ORM\Table(name="sp_purchase_order_item_history", indexes={
-      @ORM\Index(name="idx_sp_item_history_pending", columns={"status_pending"}),
-      @ORM\Index(name="idx_sp_item_history_created", columns={"created_at"}),
-      @ORM\Index(name="idx_sp_item_history_status", columns={"status_new","status_old"}),
-      @ORM\Index(name="idx_sp_item_history_po_id", columns={"order_id"}),
-      @ORM\Index(name="idx_sp_item_history_co_id", columns={"sales_order_number"})
-   })
  */
 class PurchaseOrderItemHistory
 {
```

**HINT:** this was the result by only applying the `@Symfony` ruleset

//cc @silasjoisten

### PR DESCRIPTION
**Pull request by julienfalque**
Fixes #3220.

### CODE REVIEW

**Comment by OskarStark** [comment]
@julienfalque now it looks like this and still wrong:

```diff
  * @ORM\Entity
  * @ORM\HasLifecycleCallbacks()
  * @ORM\Table(name="sp_purchase_order_item_history", indexes={
-      @ORM\Index(name="idx_sp_item_history_pending", columns={"status_pending"}),
-      @ORM\Index(name="idx_sp_item_history_created", columns={"created_at"}),
-      @ORM\Index(name="idx_sp_item_history_status", columns={"status_new","status_old"}),
-      @ORM\Index(name="idx_sp_item_history_po_id", columns={"order_id"}),
-      @ORM\Index(name="idx_sp_item_history_co_id", columns={"sales_order_number"})
-   })
+ @ORM\Index(name="idx_sp_item_history_pending", columns={"status_pending"}),
+ @ORM\Index(name="idx_sp_item_history_created", columns={"created_at"}),
+ @ORM\Index(name="idx_sp_item_history_status", columns={"status_new","status_old"}),
+ @ORM\Index(name="idx_sp_item_history_po_id", columns={"order_id"}),
+ @ORM\Index(name="idx_sp_item_history_co_id", columns={"sales_order_number"})
+ })
  */
```

**Comment by julienfalque** [comment]
Were those changes applied by `phpdoc_trim` **only**?

**Comment by SpacePossum** [comment]
@julienfalque I wonder if this related to https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/2983 as well, @OskarStark did only the `PhpdocTrim` fixer touch your code?

**Comment by julienfalque** [comment]
PR updated to fix another bug (in `phpdoc_indent` this time).

**Comment by OskarStark** [comment]
@julienfalque this version of the code behaves like expected, no diffs after running the command 👍

**Comment by julienfalque** [comment]
Great to hear, thanks for checking 👍

**Comment by OskarStark** [comment]
> Great to hear, thanks for checking 👍

Thanks for fixing it 👍 😄

**Comment by keradus** [comment]
Thank you @julienfalque.

**Pull request merged**
