### PR TITLE
PhpdocToCommentFixer - fix not properly fixing for block right after namespace

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by keradus** [comment]
Could you describe what has been improved?

**Comment by GrahamCampbell** [comment]
The tests describe that surely?

**Comment by keradus** [comment]
and the title of PR, which will be in changelog - does not

**Comment by GrahamCampbell** [comment]
D'no a way to put it succinctly, lol.

**Comment by sstok** [comment]
How about: Fix PhpdocToCommentFixer not properly fixing for block right after namespace.

Or something like that?

**Comment by SpacePossum** [comment]
:+1:

**Comment by keradus** [comment]
I'm wondering... Isn't it a bugfix?

**Comment by GrahamCampbell** [comment]
> I'm wondering... Isn't it a bugfix?

Yes. Feel free to merge to 1.10 if you want. :P

**Comment by keradus** [comment]
Thank you @GrahamCampbell.

**Pull request closed without merging**
