### PR TITLE
NoAliasFunctionsFixer - add imap aliases

### PR DESCRIPTION
**Pull request by Slamdunk**
This is not a bugfix nor a new complete feature: is `master` the right branch?

References:
1. [imap_create](https://secure.php.net/manual/en/function.imap-create.php)
1. [imap_fetchtext](https://secure.php.net/manual/en/function.imap-fetchtext.php)
1. [imap_header](https://secure.php.net/manual/en/function.imap-header.php)
1. [imap_listmailbox](https://secure.php.net/manual/en/function.imap-listmailbox.php)
1. [imap_listsubscribed](https://secure.php.net/manual/en/function.imap-listsubscribed.php)
1. [imap_rename](https://secure.php.net/manual/en/function.imap-rename.php)
1. [imap_scan](https://secure.php.net/manual/en/function.imap-scan.php)
1. [imap_scanmailbox](https://secure.php.net/manual/en/function.imap-scanmailbox.php)

### CODE REVIEW

**Comment by keradus** [comment]
> Actually I think we should create a configuration option for this

why? aliases are aliases, no need for using them.

**Comment by SpacePossum** [comment]
:+1: if a utest is added for at least subset of the added aliases.

**Comment by Slamdunk** [comment]
> 👍 if a utest is added for at least subset of the added aliases.

@SpacePossum `NoAliasFunctionFixerTest` is dynamic:
https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/5642a36a60c11cdd01488d192541a89bb44a4abf/tests/Fixer/Alias/NoAliasFunctionsFixerTest.php#L41

**Comment by keradus** [comment]
Thank you @Slamdunk.

**Pull request merged**
