### PR TITLE
PhpdocShortDescriptionFixer - add support for Japanese sentence-ending characters

### PR DESCRIPTION
**Pull request by fritz-c**

### CODE REVIEW

**Comment by keradus** [comment]
Please, could you add a test case with that characters to make sure that this won't stop working ?

**Comment by keradus** [comment]
:+1:

**Comment by GrahamCampbell** [comment]
:+1:

**Comment by SpacePossum** [comment]
:+1:

**Comment by keradus** [comment]
Thank you @fritz-c.

**Pull request closed without merging**
