### PR TITLE
Cleanup: remove useless constructor comment

### PR DESCRIPTION
**Pull request by kubawerlos**
It's the only one such comment in the repo.

### CODE REVIEW

**Comment by kubawerlos** [comment]
Do you mean something like [this](https://github.com/kubawerlos/php-cs-fixer-custom-fixers/blob/master/src/Fixer/NoUselessConstructorCommentFixer.php)?

**Comment by SpacePossum** [comment]
exactly, looks like a great start :)

**Comment by keradus** [comment]
agreeing here, fixer would be nice :+1:

**Comment by keradus** [comment]
Thank you @kubawerlos.

**Pull request merged**
