### PR TITLE
[1.5] Fixed Fixer Method Order

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Public methods should be declared before protected/private methods and should be declared in the same order they are in the interface the class is implementing.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
NB, this needs merging into 1.5, not 2.0. I sent it to the wrong branch.

**Comment by GrahamCampbell** [comment]
I've also made 1 or 2 other fixes while doing this.

**Comment by GrahamCampbell** [comment]
Merge conflicts.

**Comment by keradus** [comment]
Refs: #957

**Pull request closed without merging**
