### PR TITLE
OrderedUseFixer - fix namespace order for trailing digits

### PR DESCRIPTION
**Pull request by rusitschka**
Check the test case - this is also how IntelliJ IDEA sorts on "Organize Imports".

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Namespaces should never have backspaces in them.

**Comment by GrahamCampbell** [comment]
Imports should never have leading slashes in them.

**Comment by rusitschka** [comment]
Backslashes you mean? If so, that is not the issue. I'm talking about the examples given in the new test case I've written:

    use abc\Bar;
    use abc2\Bar;
    use xyz\abc\Bar;
    use xyz\abc2\Bar;
    use xyz\xyz\Bar;
    use xyz\xyz\Bar2;

Without my patch those were sorted wrong.

**Comment by GrahamCampbell** [comment]
Oh, my bad. I see what you mean now.

**Comment by keradus** [comment]
Thank you @rusitschka.

**Comment by keradus** [comment]
Merged into 1.5.x line

**Pull request closed without merging**
