### PR TITLE
RuleSet/FixerFactory - sort arrays content

### PR DESCRIPTION
**Pull request by keradus**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
> sort arrays content

Sounds like an idea of a fixer. :trollface:

**Comment by GrahamCampbell** [comment]
Would it be OCD to add a test to check the test arrays are sorted?

**Comment by keradus** [comment]
yes

**Comment by GrahamCampbell** [comment]
Well, if OCD needs must, it would be moved to a property. :D

**Pull request merged**
