### PR TITLE
FixCommandHelp - fix typo

### PR DESCRIPTION
**Pull request by keradus**

### CODE REVIEW

**Comment by SpacePossum** [comment]
:+1:
(but please regenerate the README, @ see contributing ;) ;)  wondering why this passes on 5.3 though :P)

**Comment by keradus** [comment]
i fixed the readme file directly, then i thought i should fix it in php generator, then i commited only later :D

**Comment by keradus** [comment]
because it's skipped:
> Unsupported symfony/console version, Symfony\Component\Console\Output\BufferedOutput was added in 2.4.

**Comment by SpacePossum** [comment]
>i fixed the readme file directly, then i thought i should fix it in php generator, then i commited only later :D

nice one : D

**Pull request closed without merging**
