### PR TITLE
ClassAttributesSeparationFixer - fixes & enhancements

### PR DESCRIPTION
**Pull request by keradus**
replaces #5871 due to https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5871#issuecomment-907839717

### CODE REVIEW

**Comment by keradus** [comment]
@SpacePossum due to new deprecations , this PR should be merge to `master` and not `3.0`.
can you pls help to solve conflicts ? they are mostly related to `only_if_meta` option

**Comment by SpacePossum** [comment]
Can we not take out the deprecation and merge the bug fixes to the lowest branch? Not sure why the target branch was changed and what happened with the other branch

**Comment by SpacePossum** [comment]
hmm the other "fixes" in the same class were merged as well, even in direct conflict with the PR open... why, what was the rush into all this?

**Comment by keradus** [comment]
tagging 3.2 due to new deprecations

**Pull request merged**
