### PR TITLE
NoUselessElseFixer - Fix detection of conditional block

### PR DESCRIPTION
**Pull request by SpacePossum**
closes https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/2802

I've modified the fixer to skip all `if`, `elseif`, `else` cases if these miss the `{}` body, this means we loose a bunch of opportunities. However these are edge cases and hard to fix.
So lets bug fix first and I've someone want to fix those edges as well than that can be done in another PR.

### CODE REVIEW

**Comment by shmax** [comment]
👍 for the quick PR!

**Comment by keradus** [comment]
did you drop or move some test cases ?

**Comment by SpacePossum** [comment]
yes, I moved these cases:
https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2807/files#diff-36575c3d3501696daa2da706f9912c92L297

as these are no longer fixed, these are no part of;
https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2807/files#diff-36575c3d3501696daa2da706f9912c92R776

**Comment by GrahamCampbell** [comment]
Looks pretty good. 👍

**Comment by keradus** [comment]
Thank you @SpacePossum.

**Pull request closed without merging**
