### PR TITLE
travis: run coverege just once

### PR DESCRIPTION
**Pull request by TomasVotruba**
Travis total runtime: ~50 mins => ~20 mins.
Unit test run 6 secs instead of 6 minutes.

To discuss:

- adding travis badge
- adding coverage badge

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
:-1:

**Comment by GrahamCampbell** [comment]
Different execution paths occur for each php version.

**Comment by TomasVotruba** [comment]
@GrahamCampbell Could you elaborate?

**Comment by GrahamCampbell** [comment]
Doctrine is a different project to php-cs-fixer.

**Comment by TomasVotruba** [comment]
@GrahamCampbell Could you elaborate then?

**Comment by keradus** [comment]
:-1: for badges

:-1: for removing code coverages for all but one version - we have many different paths for different versions like old PHP, new PHP, HHVM... and we really want to know if we test them

If we really want, we could allow one latest stable PHP to run in both ways (with and without corevage), but I dont see much point in it (I think everyone run phpunit before creating PR).

**Comment by TomasVotruba** [comment]
@keradus 

> ...and we really want to know if we test them

How do you work them now?

**Comment by keradus** [comment]
Test it on different envs and collect code coverage ?

**Comment by GrahamCampbell** [comment]
> Test it on different envs and collect code coverage ?

Scrutinizer supports multiple coverage reports being combined if coveralls doesn't. I've not used coveralls in a while so I d'no if it supports that yet, or if we've discussed this already.

**Comment by TomasVotruba** [comment]
Why there are no replies to my questions?

**Comment by GrahamCampbell** [comment]
:-1: for changing anything.

**Comment by TomasVotruba** [comment]
Nevermind, thanks for experience.

**Pull request closed without merging**
