### PR TITLE
AlignDoubleArrowFixer - fix new buggy case

### LINKED ISSUE #953: Unexpected character in input:  '' (ASCII=2)
When running the PHP-CS-Fixer from the phar version I get the following errors. I got some files with internal error's but how do I know what's wrong? 

```
PHP Warning:  Unexpected character in input:  '' (ASCII=2) state=0 in phar:///Users/me/repo/php-cs-fixer/Symfony/CS/Tokenizer/Tokens.php on line 134

Warning: Unexpected character in input:  '' (ASCII=2) state=0 in phar:///Users/me/repo/php-cs-fixer/Symfony/CS/Tokenizer/Tokens.php on line 134
PHP Warning:  Unexpected character in input:  '' (ASCII=3) state=0 in phar:///Users/me/repo/php-cs-fixer/Symfony/CS/Tokenizer/Tokens.php on line 134

Warning: Unexpected character in input:  '' (ASCII=3) state=0 in phar:///Users/me/repo/php-cs-fixer/Symfony/CS/Tokenizer/Tokens.php on line 134
PHP Warning:  Unexpected character in input:  '' (ASCII=2) state=0 in phar:///Users/me/repo/php-cs-fixer/Symfony/CS/Tokenizer/Tokens.php on line 134

Warning: Unexpected character in input:  '' (ASCII=2) state=0 in phar:///Users/me/repo/php-cs-fixer/Symfony/CS/Tokenizer/Tokens.php on line 134
PHP Warning:  Unexpected character in input:  '' (ASCII=3) state=0 in phar:///Users/me/repo/php-cs-fixer/Symfony/CS/Tokenizer/Tokens.php on line 134

Warning: Unexpected character in input:  '' (ASCII=3) state=0 in phar:///Users/me/repo/php-cs-fixer/Symfony/CS/Tokenizer/Tokens.php on line 134
```

```
./php-cs-fixer --version
PHP CS Fixer version 1.3 by Fabien Potencier (653cefb)
```

### PR DESCRIPTION
**Pull request by keradus**
fixes #953

### CODE REVIEW

**Comment by keradus** [comment]
Could you help with it @dericofilho , please ?

**Comment by keradus** [comment]
Is my solution correct @dericofilho ?

**Comment by dericofilho** [comment]
LGTM

**Comment by keradus** [comment]
merged

**Pull request merged**
