### PR TITLE
Upgraded xcode again

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by SpacePossum** [comment]
Thanks!
looks good to me, just lets see the CI green again after we fixed yet another issue with the CI tooling install....

**Comment by SpacePossum** [comment]
@GrahamCampbell can you rebase this PR, thanks!

**Comment by keradus** [comment]
I wonder, do we need to manually update every single version of xcode?
will we soon need another PR to use 11.6, and then 11.7?
also, CircleCI looks to be working on base branch anyway

**Comment by SpacePossum** [comment]
:+1:  lets only update when needed

**Pull request closed without merging**
