### PR TITLE
Changing composer install location

### LINKED ISSUE #2014: package name outdated in composer global install instructions?
I installed via composer on windows with the following command:

composer global require fabpot/php-cs-fixer

going off of the install instructions in the readme, but during the install I was presented with this message:

"Package fabpot/php-cs-fixer is abandoned, you should avoid using it. Use friendsofphp/php-cs-fixer instead." 

Should the package name be updated in the readme? I can submit a pull request to update the readme if so.

### PR DESCRIPTION
**Pull request by jaydiablo**
Fixes #2014

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Thanks, but this doesn't need changing on 1.x.

**Comment by jaydiablo** [comment]
Why not?  Composer does complain as the referenced ticket mentions, and 1.11 shows as the default branch when you hit https://github.com/FriendsOfPHP/PHP-CS-Fixer, so people will see the fabpot package location rather than friendsofphp.

**Comment by GrahamCampbell** [comment]
The old package is not deprecated yet. The packagist warning is too early.

**Comment by jaydiablo** [comment]
I see, the plan is to deprecate when 2.0 is released?

Should the referenced ticket be closed then with wontfix?

**Comment by GrahamCampbell** [comment]
There are over 10 tickets now.

**Pull request closed without merging**
