### PR TITLE
NoEmptyCommentFixer - fix middle line removal

### PR DESCRIPTION
**Pull request by keradus**
new case, not yet working

### CODE REVIEW

**Comment by keradus** [comment]
@SpacePossum do we want to take care of it ?

**Comment by SpacePossum** [comment]
:+1: 
We could, shouldn't be hard :)
Note to self to test the `#` version as well.

**Comment by keradus** [comment]
@SpacePossum 
Please, could you handle it? Also, maybe you have some more tests on your mind basing on my example.

**Comment by keradus** [comment]
Closing in favor of #1946

**Pull request closed without merging**
