### PR TITLE
Added more phpdoc tests

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by keradus** [comment]
Adding more tests are great!
But why removing some of current tests?
eg
```php
/**
 * @var string Hello!
 */
```
is not the same as
```php
/** @var string Hello! */
```


Also, in mosts tests we strongly use `dataProvider`s, why you remove them here?

**Comment by keradus** [comment]
ping @GrahamCampbell

**Comment by GrahamCampbell** [comment]
Removing the esiting tests was unintentional. Adding separate methods was meant to improve readability.

**Comment by GrahamCampbell** [comment]
I'll look at this at the weekend.

**Comment by keradus** [comment]
Having providers is more common for this project and it's worth keep it for consistency.
It the test case is really tricky we can always comment what/why we test ;)

**Comment by keradus** [comment]
ping @GrahamCampbell

**Pull request closed without merging**
