### PR TITLE
Update README.rst

### PR DESCRIPTION
**Pull request by chrjean**
Fix namespace

### CODE REVIEW

**Comment by keradus** [comment]
README on 1.12 branch (default one) is valid for v1.12.
If you are looking for readme for v1.11.x go for 1.11 branch

**Comment by GrahamCampbell** [comment]
Why is it that people always install "dev-master"?

**Comment by chrjean** [comment]
I do not install "dev-master" as you said.

I just run composer require fabpot/php-cs-fixer which install the 1.11 and I was expected to install the last one / the default one on github

**Comment by GrahamCampbell** [comment]
> (BTW, I'll love the breaking change of the minor update on the next composer up)

We don't have any breaking changes in minor releases?

**Comment by GrahamCampbell** [comment]
> I just run composer require fabpot/php-cs-fixer which install the 1.11 and I was expected to install the last one / the default one on github

It DOES do that?

**Comment by keradus** [comment]
v1.11 is 1.11 branch, which is not default
v1.12@dev (no stable yet) is 1.12 branch, which is default one
dev-master is master branch and is not related to the discussion.

1.12 will introduce new classes, which you can't use as you use 1.11. Introducing new things for next MINOR release is not BC break.

**Comment by chrjean** [comment]
I'll have to modify my .php_cs file because of the namespace change. If I don't make the change, I'll have a "Class Not Found" Exception.

I understand your "you just have to update the NS" but it's not expected on minor change

**Comment by keradus** [comment]
No, you dont understand. On your 1.11 you should use `DefaultFinder`. `Finder`, on which you got class not found error, has been introduced on dev-1.12. But you are using 1.11, so you should stick with `DefaultFinder` (which is still available on 1.12)

**Comment by chrjean** [comment]
Ok, I just saw that the 1.11 files stays here. My bad, sorry

**Pull request closed without merging**
