### PR TITLE
Bug MultilineCommentOpeningClosingFixer - do not remove PHPDoc

### PR DESCRIPTION
**Pull request by kubawerlos**
Ping @Slamdunk

### CODE REVIEW

**Comment by Slamdunk** [comment]
This PR goes against the purpose of the fixer: https://3v4l.org/nYudj

`/*** foo */` is **not** a `T_DOC_COMMENT`, is a simple `T_COMMENT`.

The fixer aims to have only two way of writing multiline comments: one for `T_DOC_COMMENT` and one for `T_COMMENT`.
It shouldn't be up to `MultilineCommentOpeningClosingFixer` to fix the human error you found.

**Comment by kubawerlos** [comment]
> it was never phpdoc

only in the meaning of PHP tokens, yet it is common mistake/practice to do [it](https://github.com/phingofficial/phing/blob/master/classes/phing/tasks/system/SwitchTask.php#L91) and PHPStorm also treats it as PHPDoc.

> turning comment into phpdoc is a serparated rule

which rule?

> It shouldn't be up to MultilineCommentOpeningClosingFixer to fix the human error you found

well, half of the fixers could be seen this way.

**Comment by Slamdunk** [comment]
> which rule?

Would be a new rule that if a `T_COMMENT` would have a meaning to be a `T_DOC_COMMENT`, it should be fixed to that type.

Such rules doesn't exists yet, you can PR it.

**Comment by kubawerlos** [comment]
Ok, that make sense.

**Pull request closed without merging**
