### PR TITLE
added missing keyword token

### PR DESCRIPTION
**Pull request by gharlan**

### CODE REVIEW

**Comment by gharlan** [comment]
Is `CT_CLASS_CONSTANT` (`::class`) a keyword?

**Comment by keradus** [comment]
Yes it is: http://php.net/manual/en/reserved.keywords.php

**Comment by keradus** [comment]
`CT_ARRAY_TYPEHINT` too ;)

**Comment by gharlan** [comment]
Ok, added them to the list.

**Comment by keradus** [comment]
:+1:

**Comment by keradus** [comment]
Thank you @gharlan.

**Pull request merged**
