### PR TITLE
Use official package name

### PR DESCRIPTION
**Pull request by mnabialek**
Use official package name instead of legacy one

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Thanks, but this isn't actually correct. This name is only for 2.x.

**Comment by mnabialek** [comment]
@GrahamCampbell  So I don't know why but when I've upgraded to 1.11.4 I'm getting:

> Package fabpot/php-cs-fixer is abandoned, you should avoid using it. Use friendsofphp/php-cs-fixer instead.

**Comment by GrahamCampbell** [comment]
Yeh, that message is correct. It's just saying that the name is changing when 2.x comes out, so be prepared.

**Comment by GrahamCampbell** [comment]
It should not have been marked as abandoned until 2.x is out IMO.

**Comment by Soullivaneuh** [comment]
Or maybe add a hint on the documentation just below the require example?

BTW, `composer require friendsofphp/php-cs-fixer:1.0.*` command actually works without any problem.

So maybe we can consider changing it?

**Pull request closed without merging**
