### PR TITLE
Move "single_space_after_construct" to Symfony ruleset

### PR DESCRIPTION
**Pull request by guilliamxavier**
Refs https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4435#issuecomment-714363283

### CODE REVIEW

**Comment by guilliamxavier** [comment]
(For CI failure see #5226)

**Comment by GrahamCampbell** [comment]
Has this been approved by the Symfony core team?

**Comment by guilliamxavier** [comment]
> Has this been approved by the Symfony core team?

I had asked @nicolas-grekas in https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4998#issuecomment-653889555, maybe they will want to confirm here?

**Comment by SpacePossum** [comment]
can you rebase on latest of master to see the tests?

**Comment by guilliamxavier** [comment]
Rebased, CI green now (thanks to Graham Campbell). Also I forgot to notify @localheinz (for information)

**Comment by keradus** [comment]
reworked to match new rulesets structure in #5252 
thanks for working on this, @guilliamxavier !

**Pull request closed without merging**
