### PR TITLE
PhpdocVarToTypeFixer - remove fixer

### PR DESCRIPTION
**Pull request by keradus**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
I think it's probably best to leave this here until psr5 gets finalized.

**Comment by keradus** [comment]
it won't be finalized for ages

**Comment by gharlan** [comment]
:+1: for removing

**Comment by GrahamCampbell** [comment]
What's the point in having either fixer if we don't have one for each direction?

**Comment by keradus** [comment]
It's violates PSR-5 proposal. If PSR change the annotation (I really doubt it) then we could change the fixer and still keep one fixer that follows PSR.

**Comment by GrahamCampbell** [comment]
> It's violates PSR-5 proposal.

So does the other fixer though. We say we only recognize valid PSR-5 annotations, so there is no such annotation type to even be fixed to var by that definition of strictly following PSR-5 only.

And, actually I disagree that we need to be so massively strict on being so connected to PSR-5 for the same reasons we have fixers that don't match up with symfony and/or PSR-2.

**Comment by gharlan** [comment]
refs #1521

**Comment by keradus** [comment]
good one @gharlan ;)

**Comment by GrahamCampbell** [comment]
> good one @gharlan ;)

Yes, I do want it removing eventually, but I think 2.x is just too early. ;)

**Comment by GrahamCampbell** [comment]
I think we should remove both fixers, and the definition of "type" from our phpdoc classes in 3.x, and keep them both in 2.x.

**Comment by keradus** [comment]
3.x won't be soon, as well as official PSR5. No need to wait for both.

**Comment by GrahamCampbell** [comment]
> 3.x won't be soon, as well as official PSR5. No need to wait for both.

I don't see the harm in leaving this fixer in the core for a year or two. It gives people the choice for what they want in their code base.

**Comment by keradus** [comment]
replaced by #1779

**Pull request closed without merging**
