### PR TITLE
FullOpeningTagFixer - Ensure opening PHP tag is lowercase

### PR DESCRIPTION
**Pull request by jtojnar**
Closes: #2503

### CODE REVIEW

**Comment by SpacePossum** [comment]
Hi,
can you add a test like 
```php
 array('<?php echo 1;', '<?PHP echo 1;'),
```

**Comment by jtojnar** [comment]
Now the code has to iterate through all the tokens every time. I could either change the regex to

**Comment by SpacePossum** [comment]
looking good,
please add this test:
```php
            array(
                '<?php
$a = <<<           "TEST"
<?Php <?
TEST;?>
TEST;

?>
<?php $a = <<<           \'TEST\'
<?PHP <?
TEST;?>
TEST;

?>
'
            ),
```

**Comment by SpacePossum** [comment]
Please add a empty line before the `continue;` (https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2509/files#diff-33adb6f1f275b90be6606f68146b502cR61)

The `foreach` @ https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2509/files#diff-33adb6f1f275b90be6606f68146b502cR70 can be changed to a `for` which remove the `if ($i !== $iLast) {` check within the loop.

**Comment by jtojnar** [comment]
@SpacePossum should refactorings really be part of feature pull requests?

**Comment by SpacePossum** [comment]
you can leave it out, I can PR it after yours :+1:

**Comment by keradus** [comment]
Thank you @jtojnar.

**Pull request closed without merging**
