### PR TITLE
Output details - Explain why a file was skipped

### PR DESCRIPTION
**Pull request by SpacePossum**
closes https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/4383

### CODE REVIEW

**Comment by julienfalque** [comment]
I think a file can also be skipped when it's empty, regardless of the cache.

**Comment by SpacePossum** [comment]
that is definitely true, but I decided to leave it out of the explanation because it is very rare case (who has empty `.php` files in their projects? ;) )

**Comment by julienfalque** [comment]
Well... it happens :p

Seing an "S" for an empty file can be confusing, especially when cache is enabled. It will be worse if the output says that "S" is only for files skipped because of the cache.

**Comment by SpacePossum** [comment]
@juliendufresne I will update :+1: 

@teohhanhui dont know why you throw that smiley at me, at least I tried and actually put time in your complaining, if you cannot be bothered to state what the issue is here now than maybe open a PR yourself? thanks

**Comment by teohhanhui** [comment]
Sorry. I just find it confusing. Your work is definitely appreciated.

See https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/4383#issuecomment-541212621

> As a matter of fact, PHPUnit does have a result cache now, and it didn't change the progress output (still just a dot), as far as I could tell.

**Comment by teohhanhui** [comment]
My suggestion:

 We should only use `S` for empty files and such. Use `.` as usual for successful files that are "skipped" because of the cache.

**Comment by GrahamCampbell** [comment]
This should probably target 2.16 or 3.x?

**Comment by keradus** [comment]
docs improvement can go to lowest supported branch.

**Comment by keradus** [comment]
Thank you @SpacePossum.

**Pull request merged**
