### PR TITLE
Fixed PhpdocShortDescriptionFixer for text ending by :

### LINKED ISSUE #1086: [DocBlock] Do not add a trailing dot after :
I'm using the last commit of 2.6 branch (6d4d5f9).
And here is the generated diff:
```diff
     /**
-     * Special arguments:
+     * Special arguments:.
      *
      *  * flags: if set, setFlags() will be called with its value
      *  * exchange: The exchange name to use (default exchange by default)
```

As you can see, php-cs-fixer added a `.` after the `:`. 

I wanted to make a PR; but I'm unable to find the correct fixer.

### PR DESCRIPTION
**Pull request by lyrixx**
fixes #1086

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Massive :-1: from me.

**Comment by GrahamCampbell** [comment]
Ending a short description in colon is NOT valid.

**Comment by GrahamCampbell** [comment]
Otherwise your long description starts from the things after the colon, which would be silly.

**Comment by keradus** [comment]
On the first look - yeah, `:` is not valid end of short descr.

On the second look - if `:` is invalid then we should not touch it...

**Comment by GrahamCampbell** [comment]
> On the second look - if : is invalid then we should not touch it...

No, this fixer is really useful because it highlights broken descriptions for people. It was really useful when I made that pull to symfony when I was regression testing this fixer originally, because it allowed me to manually rewrite some of their docblocks that were totally wrong.

**Comment by keradus** [comment]
That way we could also allow crashes and creating invalid syntax.
Purpose of this tool is to **fix** things without participation of user, not to **highlights** problems.

I remembed that we one day remove all warns etc that do not fix anything.

**Comment by GrahamCampbell** [comment]
> I remembed that we one day remove all warns etc that do not fix anything.

:(

People will just move to phpcs if we do that, that's not really what we want, because people will just use their autofixer too.

**Comment by keradus** [comment]
Not sure about that. phpcs has completely different approach.
Didn't we decided to drop warns after release of phpcbf ?
And to be honest... we are capable to fix almost 100% issues that we can detect so far...

**Comment by keradus** [comment]
Closing due to discussion

**Pull request closed without merging**
