### PR TITLE
Add branch alias for master branch

### PR DESCRIPTION
**Pull request by alexander-schranz**
allow usage of `^3.3@dev` to install master branch. Alternative default branch to 3.3 or what current version is.

### CODE REVIEW

**Comment by SpacePossum** [comment]
Thanks for suggesting,

I think we had something [this](https://github.com/FriendsOfPHP/PHP-CS-Fixer/commit/db59d08a4c3e9fc2d98d1f09aa0b32a8b7157221) , but since we only have the main branch left I wonder if there is still a need to have this? We don't really want to promote installing a non-release version as it might be unstable.

**Comment by kubawerlos** [comment]
If you want to use master branch, you don't need branch alias, you can go with `dev-master#checksum` (the checksum would be a good idea even with branch alias).

**Review by keradus — CHANGES_REQUESTED** [review]
Hey, thanks for your idea! I decided to _not_ follow it - we decided to simplify release flow and rely on single branch only. having the alias to is (in addition to existing dev-master) will not give much benefit, yet will require us to remember to update it with version bump

**Comment by julienfalque** [comment]
Maybe we could rename the branch `master` itself to `3.x`?

**Comment by keradus** [comment]
renaming root branch is always causing some issues
git refs, pr refs, fork refs, urls etc

**Comment by alexander-schranz** [comment]
`pr refs` and `url refs` are handled by github today correctly if you rename a branch you will be correctly redirected and pr target changed. They did fix there a lot of problems from the past.

**Pull request closed without merging**
