### PR TITLE
VoidReturnFixer - handle functions containing anonymous functions/classes

### PR DESCRIPTION
**Pull request by bendavies**
VoidReturnFixer does not work if the function contains a closure.
Not had the chance to look at fixing it yet, so here's a failing a test in case someone wants to tackle it.

cc @mrmark

### CODE REVIEW

**Comment by julienfalque** [comment]
What do you mean _it does not work_? Does it crash? Or does it make unexpected changes in your files? Could you provide more details like input code, your config, etc.?

**Comment by keradus** [comment]
Thanks for report @bendavies !
Any particular reason why to use not-released version ?

**Comment by bendavies** [comment]
@keradus no problem. because i wanted to use `VoidReturnFixer` in my project :)

**Comment by keradus** [comment]
@bendavies , as you allowed us to push to your branch, I pushed the fix directly to it.

**Comment by bendavies** [comment]
@keradus that appears to be the default 😃. Thanks for the fix

**Comment by keradus** [comment]
Thank you @bendavies.

**Comment by bendavies** [comment]
@keradus thank you!

**Pull request merged**
