### PR TITLE
SimpleLambdaCallFixer - introduction

### PR DESCRIPTION
**Pull request by keradus**
#4460

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
I wonder if this fixer should have a risky option that forces unpacking of arrays where we can't be sure they are not associative?

https://3v4l.org/KYknb

**Comment by keradus** [comment]
I love assoc arrays... good point :+1:

**Comment by drupol** [comment]
> I love assoc arrays... good point +1

Maybe prepend a `...array_values()` ?

https://3v4l.org/WUcFR

**Comment by GrahamCampbell** [comment]
Another case to be careful converting:

```php
call_user_func($foo, $foo = 'bar');
```

If you expand this, the order of evaluation changes...

**Comment by GrahamCampbell** [comment]
I note this example because it occurs in a real codebase: laravel/framework!

**Comment by drupol** [comment]
Ha, nicely spotted !

**Comment by SpacePossum** [comment]
Thank you @keradus.

**Comment by GrahamCampbell** [comment]
Is the following example not modified by this fixer: `call_user_func($foo, $foo = 'bar');`?

**Comment by SpacePossum** [comment]
you can test this by checking out the `master` branch

**Comment by GrahamCampbell** [comment]
If it is modified, then this is a bug.

**Comment by SpacePossum** [comment]
please let us know if you found a bug using the issue template :+1:

**Comment by GrahamCampbell** [comment]
Looks like it is broken. Why was this merged? I pointed out this case back in September...

```
There was 1 failure:

1) PhpCsFixer\Tests\Fixer\FunctionNotation\SimpleLambdaCallFixerTest::testFix with data set "unsafe repeated variable" ('<?php\n                call_u...bar');')
Code build on expected code must not change.
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
 '<?php
-                call_user_func($foo, $foo = 'bar');'
+                $foo($foo = 'bar');'

/data/tests/Test/AbstractFixerTestCase.php:167
/data/tests/Fixer/FunctionNotation/SimpleLambdaCallFixerTest.php:34
/data/vendor/phpunitgoodpractices/traits/src/ExpectationViaCodeOverAnnotationTrait7.php:39
```

**Comment by SpacePossum** [comment]
if you want it changed make a PR, don't act like you don't know how FOSS works or why things are merged, thanks

**Comment by SpacePossum** [comment]
again, please let us know if you found a bug using the issue template, I don't know why you don't

**Pull request merged**
