### PR TITLE
Remove non-default Config/Finder classes

### PR DESCRIPTION
**Pull request by keradus**
Replaces #1635

### CODE REVIEW

**Comment by keradus** [comment]
ping @GrahamCampbell, @sstok

**Comment by GrahamCampbell** [comment]
:+1:

**Comment by GrahamCampbell** [comment]
Do we even need the finder and config interfaces?

**Comment by keradus** [comment]
They are cool for tests

**Comment by gharlan** [comment]
:+1:

**Comment by keradus** [comment]
recreated after https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1670
please, could anyone take a look?

**Comment by GrahamCampbell** [comment]
:+1:

**Pull request merged**
