### PR TITLE
Support callable types in PHPDoc

### PR DESCRIPTION
**Pull request by kubawerlos**
Ping @GrahamCampbell (this is what you meant in https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4927#discussion_r451118785, right?) for review.

### CODE REVIEW

**Comment by kubawerlos** [comment]
The tests are passing on PHP 7.4, @julienfalque any idea why they are failing on PHP 7.0? I remember that there was some RegEx engine update (in PHP 7.3 I guess), but cannot find the info.

Reverting line 49/58 reduces numbers of failed tests, but I don't understand why.

**Comment by kubawerlos** [comment]
Also the switching position between `<simple>` and `<array>` did not break anything on PHP 7.4 (which makes sense as they are separated by `|`), but broke ` * @method gen<int,  string[]> method() <> a` case.

**Comment by GrahamCampbell** [comment]
Yes, and things like `callable(string, array<string, callable(): bool>): int[]`.

**Comment by GrahamCampbell** [comment]
This seems related to https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4914 too.

**Comment by julienfalque** [comment]
Ah I forgot about #4914, I thought it was merged already...

**Comment by julienfalque** [comment]
I have integrated these changes into #4914.

**Pull request closed without merging**
