### PR TITLE
Add ignore of PHP-CS-Fixer cache files

### PR DESCRIPTION
**Pull request by SpacePossum**

### CODE REVIEW

**Comment by keradus** [comment]
Why is that?
Cache is disabled when running fixing on project itself, so no cache file is generated.

**Comment by GrahamCampbell** [comment]
Can't people enable the cache on their local machines though, since .php_cs is ignored?

**Comment by keradus** [comment]
Cache can't be enabled for project fixing itself. Cache is enabled for version, which can be optained from composer installation or phar file. When working on cloned repo and fixing itself you don't have any version that can be used - because you can commit new things or even change code without commiting.

**Comment by GrahamCampbell** [comment]
This needs to be clearly documented then, and this can be closed, right?

**Comment by SpacePossum** [comment]
Fair point, I was just making a mess of my setup. I made a home brew phar of PHP-CS_Fixer 1.5 to run with a home brew Eclipse plugin. When trying to debug both the plugin and changes made to the PHP-CS_Fixer project the plugin version created the cache files so I made this commit.

**Pull request closed without merging**
