### PR TITLE
RunnerTest - workaround for failing Symfony v2.8.37

### PR DESCRIPTION
**Pull request by kubawerlos**
[This](https://github.com/symfony/symfony/pull/26337/files) change was released with Symfony v2.8.37 today.

### CODE REVIEW

**Comment by kubawerlos** [comment]
Failing build example: https://travis-ci.org/FriendsOfPHP/PHP-CS-Fixer/jobs/361316355

**Comment by keradus** [comment]
woooot :|

**Comment by keradus** [comment]
it's reverted on Sf, so if we would merge it, next release of Sf would make our tests to fail again...

**Comment by julienfalque** [comment]
Thought about it too but actually it should work anyway: what Symfony reverted is normalizing paths in its results. But if the given path is already normalized, normalizing it has no effect anyway, so if Symfony reverts the normalization on its side, it should have no effect on our side.

**Comment by keradus** [comment]
```diff
-/foo/.../bar
+/foo
```

that's the normalization we are talking about.
2.8.37 does it, 2.8.36 and 2.8.28`@dev` doesn't.
if we will do it on our side, it will fail on 2.8.28, won't it ?

**Comment by julienfalque** [comment]
No, because we normalize it *before* passing it to the finder, which will then use it as-is so the test will still pass.

**Comment by keradus** [comment]
didn't spot that. awesome !

**Comment by keradus** [comment]
Thank you @kubawerlos.

**Pull request merged**
