### PR TITLE
Travis - update matrix

### LINKED ISSUE #1582: Travis: symfony versions
At the moment we are using this matrix:

PHP | Symfony
--- | ---
5.3 | 2.x (lowest)
5.4 | 2.8
5.5 | 3.0
5.6 | 2.8 and 3.0
7.0 | 3.0
hhvm | 3.0

Why are we running PHP 5.6 with Symfony 2.8 and 3.0, but PHP 5.5 and 7.0 only with Symfony 3.0?
It does not make sense to me.

### PR DESCRIPTION
**Pull request by keradus**
Closes #1582

### CODE REVIEW

**Comment by gharlan** [comment]
:+1:

**Comment by GrahamCampbell** [comment]
What about testing php 5 with symfony 3?

**Comment by gharlan** [comment]
> What about testing php 5 with symfony 3?

This is what we are doing.
Only 5.3 and 5.4 are running symfony 2 because symfony 3 requires php >= 5.5.

**Comment by keradus** [comment]
PHP | Symfony
--- | ---
5.3 | 2.x (lowest)
5.4 | 2.8
5.5 | 3.0
5.6 | 3.0
7.0 | 2.8 and 3.0

**Comment by GrahamCampbell** [comment]
Ahh, yes. What about hhvm and both symfony versions. :P

**Comment by GrahamCampbell** [comment]
and, why does php 5.3 get the really old symfony version only?

**Comment by keradus** [comment]
hhvm - I can't see any point of it. Even hhvm is extra old on Travis.
5.3 - look at composer flags for 5.3, it is on purpose to check if the tool will work under the min version of deps we required.

**Comment by Soullivaneuh** [comment]
Maybe we can take profit to add SF 3.1 on allowed failures.

**Comment by GrahamCampbell** [comment]
Bit overkill imo.

**Pull request merged**
