### PR TITLE
DoctrineAnnotationFixer - Add template to ignored_tags

### PR DESCRIPTION
**Pull request by akalineskou**
Using `'doctrine_annotation_braces' => ['syntax' => 'with_braces']` it wants to add `()` to the `@template` tag, but then phpstorm doesn't recognize the template as valid `@template() T` so `@param T` and `@return T` would be marked as not found.  
This fixes it by adding the `template` keyword to the ignored list.

I saw that both phpstan https://phpstan.org/blog/generics-in-php-using-phpdocs and psalm https://psalm.dev/docs/annotating_code/templated_annotations/ use it without parentheses.

Did all the checks and updated the docs.

### CODE REVIEW

**Comment by akalineskou** [comment]
Any news on this? @keradus 

Also why change the branch to 3.0?
From contributing "If you are fixing a bug or typo, improving tests or for any small tweak: the lowest branch where the changes can be applied. Once your Pull Request is accepted, the changes will get merged up to highest branches."
Would this fix, if merged, be merged to 2.x too?

**Review by kubawerlos — APPROVED** [review]
Branch `2.9` was removed, so `3.0` is now lowest one.

**Comment by kubawerlos** [comment]
Or should it be considered a bug?

**Comment by akalineskou** [comment]
Probably a bug since this wasn't the desired effect?

**Comment by keradus** [comment]
Thank you @akalineskou.

**Comment by keradus** [comment]
Thank you @akalineskou.

**Pull request merged**
