### PR TITLE
PHP7.1 Integration test - Add features added in PHP7.1.

### PR DESCRIPTION
**Pull request by SpacePossum**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
What happens if we add a multicatch?

**Comment by SpacePossum** [comment]
>What happens if we add a multicatch?

https://github.com/SpacePossum/PHP-CS-Fixer/blob/640e37c5938f8e94a238a8baddb5144f6803155a/tests/Fixtures/Integration/misc/PHP7_1.test#L21

it is already part of the test (note that currently the main function of the test is to ensure the fixer doesn't break down or breaks code, not to prove it fixes all 7.1 features)

**Comment by GrahamCampbell** [comment]
great //0

**Comment by GrahamCampbell** [comment]
great :)

**Comment by keradus** [comment]
Thank you @SpacePossum.

**Pull request merged**
