### PR TITLE
PhpdocIndentFixer - fix error when there is a comment between docblock and next meaningful token

### PR DESCRIPTION
**Pull request by keradus**
Bug when between docs and documented code is a comment.

Could you take care of that @ceeram , please?

### CODE REVIEW

**Comment by ceeram** [comment]
Will take a look at it later when i am behind a computer again
Op 18 jan. 2015 22:30 schreef "Dariusz Rumiński" <notifications@github.com>:

**Comment by keradus** [comment]
Thanks !

**Comment by ceeram** [comment]
Why do you expect a newline to be removed here? this fixer is about indentation of docblocks, not removing newlines after them?

**Comment by keradus** [comment]
OK, then simply fix [this](https://travis-ci.org/FriendsOfPHP/PHP-CS-Fixer/jobs/47458340#L193)

**Comment by ceeram** [comment]
That is because T_COMMENT swallows the whitespace, will fix it here. Is there plans to split up T_COMMENT and newline char?

**Comment by ceeram** [comment]
See: https://github.com/keradus/PHP-CS-Fixer/pull/6

**Comment by keradus** [comment]
> That is because T_COMMENT swallows the whitespace, will fix it here. Is there plans to split up T_COMMENT and newline char?

https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/Symfony/CS/Tokenizer/Transformer/WhitespacyCommentTransformer.php

**Comment by ceeram** [comment]
Thats 2.x right? so no help here

**Comment by keradus** [comment]
Yeah, but you asked about plans for it, so here you go ;)

**Comment by ceeram** [comment]
So i did, so thanks for the heads up :)

**Comment by keradus** [comment]
Ready to merge?

**Comment by keradus** [comment]
Thank you @ceeram.

**Pull request closed without merging**
