### PR TITLE
NoShortBoolCastFixer - Missing doc

### PR DESCRIPTION
**Pull request by SpacePossum**
cc @keradus ;)

### CODE REVIEW

**Comment by SpacePossum** [comment]
oh it was meant as fix for a failing test in a PR of your, so you could pick it there, but nevermind

**Comment by keradus** [comment]
but here is any fix, right?
which failing test?

**Comment by SpacePossum** [comment]
https://travis-ci.org/FriendsOfPHP/PHP-CS-Fixer/jobs/184512482#L480

**Comment by keradus** [comment]
then bug of my code, not codebase

if you want to take authorship of this class go ahead and amend it to one of the PRs of yours ;)

**Pull request closed without merging**
