### PR TITLE
[single_space_after_construct] Remove multiple spaces between property type and variable

### LINKED ISSUE #5542: [single_space_after_construct] Remove multiple spaces between property type and variable
## Rule request

I'm using the [SingleSpaceAfterConstructFixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.18/src/Fixer/LanguageConstruct/SingleSpaceAfterConstructFixer.php) and notice that it doesn't remove multiple spaces between a property type and the variable.

## Questions

I would like to implement this, but have some questions:

1. Should this be a responsibility of the SingleSpaceAfterConstructFixer or a separate fixer?

2. ~I noticed that these properties are tokenized as `T_STRING (311)`. This makes sense. But it makes working with these types harder. Would it be OK to transform these to a new `CT::T_PROPERTY_TYPEHINT` token type? This is already done for the `array` typehint, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.18/src/Tokenizer/Transformer/ArrayTypehintTransformer.php. Having it as a separate token makes it easier to implement it in the `SingleSpaceAfterConstructFixer`.~ I guess this doesn't make any sense.

### Code snippet that shows how the rule would fix PHP code

```diff
 class Point
 {
-    public \DateTime    $x;
-    protected bool      $y = true;
-    private array       $z = [];
-    public int          $a = 0;
-    protected string    $b = '';
-    private float       $c = 0.0;
+    public \DateTime $x;
+    protected bool $y = true;
+    private array $z = [];
+    public int $a = 0;
+    protected string $b = '';
+    private float $c = 0.0;
 }
```

Same should apply for constructor property promotion in PHP 8.0.

### PR DESCRIPTION
**Pull request by ruudk**
Fixes #5542

```diff
 class Point
 {
-    public \DateTime    $x;
-    protected bool      $y = true;
-    private array       $z = [];
-    public int          $a = 0;
-    protected string    $b = '';
-    private float       $c = 0.0;
+    public \DateTime $x;
+    protected bool $y = true;
+    private array $z = [];
+    public int $a = 0;
+    protected string $b = '';
+    private float $c = 0.0;
 }
```

### CODE REVIEW

**Comment by ruudk** [comment]
PHPstan is failing because of https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5789
The PHP 7.4 tests on macOS are failing because of some other unrelated reason 🤷 

@kubawerlos @keradus @SpacePossum @julienfalque What do you think of this?

**Comment by julienfalque** [comment]
I'm :+1: for the new behavior but I don't think `single_space_after_construct` is the most suitable place for it. I would rather deprecate `function_typehint_space` in favor of a new `typehint_space` rule which also supports property types.

**Comment by mc0de** [comment]
what is the end of this feature? was this somewhere merged? how can we fix duplicate spaces after types?

**Comment by ruudk** [comment]
I didn't want to pursue this so therefore I closed the PR.

**Pull request closed without merging**
