### PR TITLE
DocBlock - The category tag should be together with package

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by keradus** [comment]
Could you add some reference for that change?

**Comment by GrahamCampbell** [comment]
Well, there's no reason for any of the grouping anyway. They're all totally arbitrary.

The category tag is directly related to the package tag though, so it would make sense to group it.

**Comment by keradus** [comment]
Thank you @GrahamCampbell.

**Comment by GrahamCampbell** [comment]
:)

**Pull request merged**
