### PR TITLE
BracesFixer - fix handling comment around control token

### LINKED ISSUE #1938: Test case that crashes php-cs-fixer
Latest 2.x. Enable the fixers: `braces` and `elseif` only.

**Input:**

```php
<?php

	if ($foo) {
		//
	}
	else
/*-- TROLOLOL --*/
	if ($bar) {}
```

### PR DESCRIPTION
**Pull request by keradus**
closes #1938

### CODE REVIEW

**Comment by keradus** [comment]
cc @GrahamCampbell

**Comment by GrahamCampbell** [comment]
:+1:

**Comment by GrahamCampbell** [comment]
Could we add my other test case as an integration test?

**Comment by keradus** [comment]
you know that it wasn't needed to use second fixer for this bug right ?

**Comment by GrahamCampbell** [comment]
1.11 didn't crash for me on my test case with both fixers enabled.

**Comment by keradus** [comment]
as it didn't crash for every possible code, i took the one that's causing the issues.

not sure if we want to go for every possible failing case and maintain it...

**Pull request closed without merging**
