### PR TITLE
Add deprecation notices tests

### PR DESCRIPTION
**Pull request by julienfalque**
~Requires #2500.~

### CODE REVIEW

**Comment by keradus** [comment]
I think you could easily extract bridge and new tests to be not dependent on referred PR.
If not (or it would require more work), let us freeze this PR until it's parent is merged, at least in terms of reviewing it.

**Comment by julienfalque** [comment]
Yeah, I've been a bit lazy here ;)
Rebasing.

**Comment by SpacePossum** [comment]
:+1:

**Comment by keradus** [comment]
Thank you @julienfalque.

**Pull request merged**
