### PR TITLE
ClassDefinitionFixer - Set configuration of the fixer in the RuleSet of SF.

### PR DESCRIPTION
**Pull request by SpacePossum**
These are the last things for the master branch after #2155 was merged to 1.12
@ see https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2155#issuecomment-257109271

### CODE REVIEW

**Comment by keradus** [comment]
does default configuration of fixer match PSR-2 ?

**Comment by SpacePossum** [comment]
>does default configuration of fixer match PSR-2 ?

yes, on a side note all other options of the fixer are PSR2 compliant. However the configuration options deals with parts of PSR-2 that state _may_ and not _must_ (which is what the Fixer does on default) :)

**Comment by keradus** [comment]
sure, but the default option must not  change PSR-2 valid into another PSR-2 valid syntax.
Great !

**Comment by keradus** [comment]
Thank you @SpacePossum.

**Pull request merged**
