### PR TITLE
[WIP] Make shell scripts POSIX-compatible

### LINKED ISSUE #3544: Make shell scripts POSIX-compatible
Some environments don't have Bash, and all PHP-CS-Fixer's shell scripts fail with

> env: can't execute 'bash': No such file or directory

It would be great if PHP-CS-Fixer's shell scripts were POSIX-compatible.

### PR DESCRIPTION
**Pull request by EvgenyOrekhov**
I used ShellCheck and checkbashisms to find and get rid of Bash-specific syntax and features in shell scripts.

This PR is not about refactoring or fixing the scripts. The intention of this PR is to make the scripts work in any POSIX-compliant shell.

This will allow developers to contribute to PHP-CS-Fixer using environments that don't have Bash, e. g. Alpine Linux.

Fixes #3544.

### CODE REVIEW

**Comment by EvgenyOrekhov** [comment]
Looks like I don't have enough expertise in POSIX to make ci-integration.sh POSIX-compatible.

**Comment by EvgenyOrekhov** [comment]
I can make ci-integration.sh POSIX-compatible after all, I just can't figure out how to test it in tests/Smoke/CiIntegrationTest.php.

**Comment by keradus** [comment]
how to test what in CiIntegrationTest?

**Comment by EvgenyOrekhov** [comment]
@keradus CiIntegrationTest tests the ci-integration.sh script, but the tests use Bash arrays to verify results. I think I can rewrite ci-integration.sh to use strings instead of Bash arrays, but I can't figure out how to rewrite tests in CiIntegrationTest.

**Comment by ntzm** [comment]
If this gets merged it might be worthwhile adding this check to the CI process

**Comment by EvgenyOrekhov** [comment]
@ntzm You mean ShellCheck and checkbashisms?

**Comment by keradus** [comment]
oh, i understood you already made changes in ci-integration.sh ;)
then my comment is not valid

**Comment by keradus** [comment]
note:
should target LTS 2.2 branch, not master

**Comment by EvgenyOrekhov** [comment]
Closed in favor of #3548.

**Comment by keradus** [comment]
for future, you could change target branch of PR without opening it as new PR

**Pull request closed without merging**
