### PR TITLE
Added missing types to the PhpdocTypesFixer

### PR DESCRIPTION
**Pull request by GrahamCampbell**
I've picked from https://github.com/phpDocumentor/TypeResolver/blob/0.5.0/src/TypeResolver.php#L47 the types that we missed. I'll also need to send back to them the types they missed.

### CODE REVIEW

**Comment by keradus** [comment]
tests are missing. I don't like features/bugfixes passing without touching tests

**Comment by GrahamCampbell** [comment]
Sure, can add more tests. I don't think our existing tests cover that whole array as is anyway, but sure, can add more tests.

**Comment by GrahamCampbell** [comment]
Will do tomorrow, will need to pull down the code to my laptop.

**Comment by SpacePossum** [comment]
:+1: for the idea, love to see to test :)

**Comment by keradus** [comment]
ping @GrahamCampbell

**Comment by keradus** [comment]
Thank you @GrahamCampbell.

**Pull request merged**
