### PR TITLE
Updated my email address

### PR DESCRIPTION
**Pull request by GrahamCampbell**
I requested this before, but now I don't even own the domain anymore, so this really does need changing.

### CODE REVIEW

**Comment by keradus** [comment]
not a bugfix.
why won't you use email address that you won't lose?

**Comment by GrahamCampbell** [comment]
I won't lose the alt-three one, and I don't release my personal gmail one to the internet like this.

**Comment by OskarStark** [comment]
This should be merged IMO

**Comment by GrahamCampbell** [comment]
Yeh, someone's parked the old domain now:

image

**Comment by ChipWolf** [comment]
My fault allowing it to expire; assumed domain was deprecated. Originally was used for a startup we collaborated on, no longer in use as you can see.

**Comment by GrahamCampbell** [comment]
@keradus Rebased, and ready for merge please. :)

**Pull request closed without merging**
