### PR TITLE
minor: ExplicitStringVariableFixer - Fix to PHP8.2 compat code

### PR DESCRIPTION
**Pull request by SpacePossum**
PHP8.2

see: https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/3488#issuecomment-1152809445

ping @dmvdbrugge as author of the rule, ping @iluuu1994 as author of the PHP language change, please have a look and let me know what you guys think, thanks! :+1: 

Stricktly this change could be considered a BC break, but fixing towards a PHP8.2 deprecated code style is more problematic and outweighs the minor BC thing IMHO.

### CODE REVIEW

**Comment by dmvdbrugge** [comment]
If I look at the linked comment, @Slamdunk is the author of ExplicitStringVariableFixer, I'm merely the author of SimpleToComplexVariableFixer (which should now be included in any "migrate to php 8.2+" sets).

It is correct the priority is no longer needed as the former will no longer produce the result the latter is fixing.

Anyway, the change looks good. Is this targeting a minor or a patch release? I wouldn't do patch because of the BC thing, but if you specify this as "8.2 compatibility feature" then minor sounds good to me 😄

**Comment by SpacePossum** [comment]
Thanks for your thoughts @dmvdbrugge , much appreciated :+1:  :)  we'll have to see when and how this gets shipped, but good points :+1:

**Comment by iluuu1994** [comment]
LGTM. This doesn't handle the deprecated var var syntax `"${expr}"` described in the [RFC](https://wiki.php.net/rfc/deprecate_dollar_brace_string_interpolation) but to be fair I couldn't find a single case of those in the wild with my script.

**Comment by SpacePossum** [comment]
Thanks @iluuu1994 :)
We have an additional rule to rewrite those cases here:
[simple_to_complex_string_variable](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/doc/rules/string_notation/simple_to_complex_string_variable.rst)
(additional [tests cases](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/tests/Fixer/StringNotation/SimpleToComplexStringVariableFixerTest.php)).
Thanks for making the change in PHP and for checking things out here, much appreciated :+1:

**Comment by iluuu1994** [comment]
Note that `"${var}"` is equivalent to `"{$var}"` (which is handled by `simple_to_complex_string_variable`), but `"${expr}"` is equivalent to `"{${expr}}"`. The distinction is very confusing (hence the deprecation). But this is probably negligible as I doubt anybody actually used that syntax non-accidentally.

**Pull request merged**
