### PR TITLE
PhpUnitNoExpectationAnnotationFixer - add case with backslashes

### PR DESCRIPTION
**Pull request by keradus**
Found in https://github.com/cakephp/cakephp/pull/11433/

Probably some experience from #3155 could be helpful

ref https://www.regular-expressions.info/characters.html , `"c:\\\\temp"` sample

### CODE REVIEW

**Comment by keradus** [comment]
for now, case is failing

**Comment by keradus** [comment]
@Slamdunk, could you please try to take a look here ?

**Comment by Slamdunk** [comment]
Sure, next week though

**Comment by Slamdunk** [comment]
https://github.com/keradus/PHP-CS-Fixer/pull/29

**Comment by keradus** [comment]
looks really great, thank you @Slamdunk ! your help is very appreciated ;)

**Comment by keradus** [comment]
Thank you @Slamdunk.

**Pull request merged**
