### PR TITLE
Always provide delimiter to `preg_quote` calls

### PR DESCRIPTION
**Pull request by ntzm**
These aren't needed and probably won't be needed, but it's good to have them just in case IMO

### CODE REVIEW

**Comment by SpacePossum** [comment]
good idea!

kindly note; duplicates https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3367 :)

**Comment by keradus** [comment]
So, I would say it other way.
Let us make a fixer for it.

**Comment by SpacePossum** [comment]
>Let us make a fixer for it.

That is going to be a highly risky one, as it is impossible to determine the delimiter that should be used.
Could be an autoreview/sniff though.

**Comment by keradus** [comment]
Thank you @ntzm.

**Pull request merged**
