### PR TITLE
Exclude Doctrine documents from final fixer

### PR DESCRIPTION
**Pull request by ossinkine**
Doctrine ORM entities already excluded from FinalClassFixer. I propose also to exclude Doctrine ODM documents.

### CODE REVIEW

**Comment by keradus** [comment]
would you mind to share reasoning for a person who is not using Doctrine daily?

**Comment by ossinkine** [comment]
Doctrine has two object mapping packages: ORM for relational DB and ODM document-oriented DB.
ORM works with entities, ODM works with documents.
Both can't be final because they can be proxied (will be created proxy classes extends them).
Since FinalClassFixer already excluded entities, I assumed it would be logical to also exclude documents.

**Review by kubawerlos — APPROVED** [review]
Is the list complete now for Doctrine? @Ocramius is there a place we can verify it is or not?

**Comment by Ocramius** [comment]
`@Document` seems a bit generic: shouldn't it be `@ODM\Document`?

**Comment by ossinkine** [comment]
Added `@ODM\Document`

**Comment by keradus** [comment]
Thank you @ossinkine.

**Pull request merged**
