### PR TITLE
Deprecate non-default Configs and Finders

### PR DESCRIPTION
**Pull request by keradus**
ref #1646

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
:+1:

**Comment by SpacePossum** [comment]
:+1:

**Comment by gharlan** [comment]
:+1:

**Comment by GrahamCampbell** [comment]
Surely we need to deprecate the other 2 class too?

**Comment by GrahamCampbell** [comment]
Since we're moving them?

**Comment by GrahamCampbell** [comment]
We should move them by extension, then deprecate the originals shouldn't we?

**Comment by keradus** [comment]
I was thinking about sth like that too, but I already have too many work in progress.
Could you send a PR ?

**Comment by GrahamCampbell** [comment]
Sorry, have no time at all this week. ;(

**Pull request merged**
