### PR TITLE
Added failing integration test

### PR DESCRIPTION
**Pull request by GrahamCampbell**
A change made since c4989f8ef45e6940222e9c4b57cd8dd8846b29a1 has broken fixing of string interpolation. Spaces are being erroneously added around `-` in a double quoted string. I am narrowing down the exact commit which broke this now...

---

```
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
     private function reverseBoolean($value = null, $theSwitch = false)
     {
         if (!$theSwitch) {
-            return "{$value}-{$theSwitch}";
+            return "{$value} - {$theSwitch}";
         }
 ```

### CODE REVIEW

**Comment by SpacePossum** [comment]
```
$ php php-cs-fixer fix test.php  -vvv --dry-run --diff
PHP CS Fixer 3.2.2-DEV by Fabien Potencier and Dariusz Ruminski
Runtime: PHP 7.4.24
Loaded config default from "/home/possum/work/PHP-CS-Fixer/.php-cs-fixer.dist.php".
Paths from configuration file have been overridden by paths provided as command arguments.
F                                                                                                                                                                                                      1 / 1 (100%)
Legend: ?-unknown, I-invalid file syntax (file ignored), S-skipped (cached or empty file), .-no changes, F-fixed, E-error
   1) PHP-CS-Fixer/test.php (binary_operator_spaces)
      ---------- begin diff ----------
--- /home/possum/work/PHP-CS-Fixer/test.php
+++ /home/possum/work/PHP-CS-Fixer/test.php
@@ -12,4 +12,4 @@
  * with this source code in the file LICENSE.
  */
 
-$a = "{$value}-{$theSwitch}";
+$a = "{$value} - {$theSwitch}";

      ----------- end diff -----------
```

**Comment by GrahamCampbell** [comment]
Yeh.

**Comment by SpacePossum** [comment]
if you can squash your commits into one clean commit with the updated test I can add it to https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6089 :+1:

**Comment by SpacePossum** [comment]
fixed in other PR, thanks for reporting :+1:

**Pull request closed without merging**
