### PR TITLE
DescribeCommand - use our Differ wrapper class, not external one directly

### PR DESCRIPTION
**Pull request by keradus**
Like we do on 2.2 line.

### CODE REVIEW

**Comment by keradus** [comment]
ah, accidentally already merged into 2.11, not 2.10. fixing the milestone.
good idea Julien, I was just too fast :(
in the end, no big deal, 2.10 is not LTS and gonna be dropped soon

**Comment by keradus** [comment]
Actually, I couldn't use 2.10. as 2.10 is using diff 1.2 and only master is using 1.3, so master was only possible choice :D

**Comment by julienfalque** [comment]
But the `UnifiedDiffer` class already exists on 2.10, so it should be possible anyway, as the diff dependency is wrapped in this class, no?

**Comment by keradus** [comment]
ha, good point ;)

**Comment by SpacePossum** [comment]
but it had different implementation, so 2.10 would be a BC break ;)

**Comment by keradus** [comment]
we don't have BC promise on txt output of any command.

**Pull request merged**
