### PR TITLE
[2.0] Cleanup the tags property in the abstract phpdoc types fixer

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by keradus** [comment]
Hurray :+1:

**Comment by GrahamCampbell** [comment]
Haha. ;)

**Comment by GrahamCampbell** [comment]
Is this good to merge then?

**Comment by keradus** [comment]
Thank you @GrahamCampbell.

**Comment by GrahamCampbell** [comment]
:)

**Pull request merged**
