### PR TITLE
Fix couple of typos

### PR DESCRIPTION
**Pull request by KKSzymanowski**
Follow up on #3059

Fixed three typos in the Readme.

### CODE REVIEW

**Comment by julienfalque** [comment]
Note that some of these changes can be applied to 2.2 as well. @keradus, do you want to handle this while merging? Or shall we open a separate PR?

**Comment by keradus** [comment]
I cannot downgrade sth during merging. If pr is for 2.2 line, i will catch it up to 2.6.
but if sth is for 2.6 line, i won't apply changes back to 2.2 during merging

**Comment by SpacePossum** [comment]
It would be nice to have some way to see on which version a rule was added so when you want fix multiple you don't need to go through all the release notes.

**Comment by keradus** [comment]
Thank you @KKSzymanowski.

**Pull request merged**
