### PR TITLE
Runner - always cache files, not only when something is changed

### LINKED ISSUE #1842: Latest 2.x cached performance very poor
After the latest changes, the performance when all files are cached is much worse than before. Easily 20x slower than it was before on a code base ~400 files.

### PR DESCRIPTION
**Pull request by gharlan**
I think, this should fix #1842.

/cc @GrahamCampbell

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Yes, along with https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1843, I think this should fix it.

**Comment by GrahamCampbell** [comment]
I'll try it out and see.

**Comment by GrahamCampbell** [comment]
Hmm, looking at your PR, it doesn't look right. dryRun doesn;t indicate if something was changed or not?

**Comment by GrahamCampbell** [comment]
Oh, wait, sorry. I've missread the diff. It does look good!

**Comment by GrahamCampbell** [comment]
Just tested this with my other imports patch, and they work.

:+1:

**Comment by keradus** [comment]
Question: why we want to remember that file is fixed when in fact we didn't fix it?
With this PR:
- first run, with dry-run, it found that file should be fixed, but didn't fix it, then mark in cache
- second run, without dry-run, it skipped the file, even while file needs fixing

**Comment by gharlan** [comment]
@keradus good point, updated the pr.

**Comment by keradus** [comment]
great ;)
@GrahamCampbell is that solves performance issue you have reported?

**Comment by GrahamCampbell** [comment]
With my import fix PR, yes it does.

**Comment by keradus** [comment]
Thank you @gharlan.

**Pull request merged**
