### PR TITLE
bug: BinaryOperatorSpacesFixer - Allow to align `=` inside array definitions

### PR DESCRIPTION
**Pull request by VincentLanglet**
Hi @SpacePossum, seems like you worked on the BinaryOperatorSpacesFixer.
I recently found a use-case where this is not working as expected.

Seems like removing a check you made fix my issue.
I added a test, and it seems it doesn't break any of the other tests.
Do you know why the check was here ?

### CODE REVIEW

**Review by julienfalque — APPROVED** [review]

**Comment by julienfalque** [comment]
I think the intention was to skip a portion of code that could not contain operators to align, but it turns out it can. Thanks for the fix @VincentLanglet.

**Comment by SpacePossum** [comment]
```php
<?php
$a = [$b = 1];
$ab = [$bc = 1];
$abc = [$bcd = 1];
$a = [$b];
$ab = [$bc];
$abc = [$bcd];
```

was fixed to:

```php
<?php
$a   = [$b = 1];
$ab  = [$bc = 1];
$abc = [$bcd = 1];
$a   = [$b];
$ab  = [$bc];
$abc = [$bcd];
```

with this PR it gets fixed to:
```php

'<?php
$a   = [$b   = 1];
$ab  = [$bc  = 1];
$abc = [$bcd = 1];
$a   = [$b];
$ab  = [$bc];
$abc = [$bcd];
```

if this is better or worse I don't know, but the code in place was there for this reason

**Comment by SpacePossum** [comment]
more of a problem
```php
<?php
$a = [$s = 5, $d => 5, $c => 9,];
$ab = [$bc = 1];
$someOtherArray = [$bcd = 1];
$a = [$b];
$ab = [$bc];
$abc = [$bcd];
```
before the PR fixed to:

```php
<?php
$a              = [$s = 5, $d => 5, $c => 9,];
$ab             = [$bc = 1];
$someOtherArray = [$bcd = 1];
$a              = [$b];
$ab             = [$bc];
$abc            = [$bcd];
```

after

```php
'<?php
$a              = [$s              = 5, $d => 5, $c => 9,];
$ab             = [$bc             = 1];
$someOtherArray = [$bcd = 1];
$a              = [$b];
$ab             = [$bc];
$abc            = [$bcd];
```

there is a bigger issue with this fixer, especially related to aligning stuff, I haven't got around to look into it, but not sure about this fix

**Comment by VincentLanglet** [comment]
I'll take a look.
There is a scope level notion to introduce maybe

**Comment by SpacePossum** [comment]
The bigger issue is the generated and injected placeholders, these should be inserted by level/depth and by operator. Than when doing the align based on these we should be going from most left per operator and depth and align others from the same depth and operator type, than continue based on that result with what is than the next most left operator, until all placeholders have been replaced. Figuring out the correct depth/scope is already hard, but than figuring out the most left placeholder over multiple lines is also a bit of puzzle. Doable, but will take a bunch of effort, testing, reviewing and what else :)

**Comment by VincentLanglet** [comment]
> The bigger issue is the generated and injected placeholders, these should be inserted by level/depth and by operator. Than when doing the align based on these we should be going from most left per operator and depth and align others from the same depth and operator type, than continue based on that result with what is than the next most left operator, until all placeholders have been replaced. Figuring out the correct depth/scope is already hard, but than figuring out the most left placeholder over multiple lines is also a bit of puzzle. Doable, but will take a bunch of effort, testing, reviewing and what else :)

Here, there are something simpler to do.
Just ignore the code inside `[]` when it's in the same line.

**Pull request merged**
