### PR TITLE
[git] Add .gitattributes to remove unneeded files

### PR DESCRIPTION
**Pull request by Slamdunk**

### CODE REVIEW

**Comment by keradus** [comment]
this should be sent to 1.x line

**Comment by Slamdunk** [comment]
I sent it to master on purpose because master has a clear `/tests` folder, on `1.x` instead I thought it would be strange to have a `./Symfony/CS/Tests export-ignore`.

**Comment by keradus** [comment]
Why strange ?
And it should solve a problem with too long paths in phar file right ? and that problem ocucrs on 1.x as wel..

**Comment by Slamdunk** [comment]
I'm not aware of the phar problem you are talking about, btw https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2128

**Comment by keradus** [comment]
ref: https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/2098
is it related?

**Comment by Slamdunk** [comment]
No: that bug may or may not emerge depending on how the source is retrieved.

By the way, as stated in #2098 `.gitattributes` only affects zip archive creation: no drawbacks as long as all the production code remains available within the zip

**Pull request closed without merging**
