### PR TITLE
[7.3] Test that "LITERAL instanceof X" is valid

### PR DESCRIPTION
**Pull request by guilliamxavier**
Refs #3697

### CODE REVIEW

**Comment by guilliamxavier** [comment]
@julienfalque @SpacePossum does it satisfy what you intended in https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/3697#issuecomment-450361627 and its reply? (i.e. is it enough to check the 3rd checkbox?)

**Comment by keradus** [comment]
It's perfect !
you will have my +1 after Travis will be green ;) (ignore first failing job).
Hopefully, nothing more for you on this PR. thanks!

**Comment by keradus** [comment]
Thank you @guilliamxavier.

**Comment by SpacePossum** [comment]
Great to have help with such a task as updating the codebase for PHP7.3, lot of people looking forward to it and all help to get it is done is much appreciated! 
Thanks so much @guilliamxavier :)

**Pull request merged**
