### PR TITLE
FullOpeningTagFixer - fix substr check for pre PHP8

### PR DESCRIPTION
**Pull request by SpacePossum**
closes https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/6372

### CODE REVIEW

**Review by GrahamCampbell — APPROVED** [review]

**Review by AndryG — APPROVED** [review]
Tested on a working project - works.

I do not agree with the change option. The code breaks the semantics for current PHP versions.

$possibleOpenContent = substr($content, $tokensOldContentLength, 5);

The result of the string function is used as a boolean value. At the heart of the code is not the usual meaning of the function, but a feature of the obsolete version.


The type cast patches exactly the feature of the old version. I find this to be the more natural option in this case.
if ('<?php' !== strtolower((string)substr($content, $tokensOldContentLength, 5))) {

**Comment by SpacePossum** [comment]
Thanks for testing :+1: 
The difference between casting and this solution seems like a preference/opinion one to me and I prefer not to cast here and as such leave the PR as is, thanks for the input.

**Comment by kubawerlos** [comment]
Let's wait for a code snippet reproduction a bug and add test for it to prevent regression.

**Comment by SpacePossum** [comment]
>Let's wait for a code snippet reproduction a bug and add test for it to prevent regression.

I won't change the PR, so either merge as is or maybe you open a PR here on the main repo and I'll take a piss on it for weeks on end without merging?

**Pull request closed without merging**
