### PR TITLE
NullableTypeDeclarationForDefaultNullValueFixer - fix for nullable with attribute

### PR DESCRIPTION
**Pull request by kubawerlos**
Fixes https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/5533

### CODE REVIEW

**Comment by kubawerlos** [comment]
@keradus @julienfalque @SpacePossum @localheinz should we extend `Tokens::getNextMeaningfulToken` to skip PHP 8 attributes as it this case `ArgumentsAnalyzer` includes it into the type and creates `<?php function foo(?#[AnAttribute] string $param = null) {}` which is invalid syntax?

**Comment by keradus** [comment]
attributes are meaningful.
we also fix their content, eg
```diff
-#[MyAttribute(array("key" => "value"))]
+#[MyAttribute(['key' => 'value'])]
```

**Review by keradus — APPROVED** [review]

**Comment by keradus** [comment]
Thank you @kubawerlos.

**Comment by OskarStark** [comment]
Thank you very much 🥰

**Pull request merged**
