### PR TITLE
Consider the php version when caching

### LINKED ISSUE #1619: Also included php version in cache
If someone updates from php 5.6 to 7.0, we probably want to consider the cache file stale.

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Closes #1619.

### CODE REVIEW

**Comment by keradus** [comment]
I don't like this.
I often store cache in CI cache and use it across all PHP versions.

**Comment by GrahamCampbell** [comment]
Well, that's surely incorrect, because the behaviour of fixing a file on php 7 in php-cs-fixer is not the same as fixing on php 5.3.

**Comment by keradus** [comment]
And 5.5.1 vs 5.5.2 is the same.
PHP7 is totally different case

**Comment by GrahamCampbell** [comment]
Well, php 5.5.2 vs 5.5.1 might be different if some of them had a bug affecting it.

**Comment by GrahamCampbell** [comment]
At the very least could we consider the major and minor versions, but not patch?

**Comment by keradus** [comment]
I'm not against it, just say don't like it in current form ;)

Let the other say their opinion ;)

**Comment by SpacePossum** [comment]
Like the idea :+1: 
Maybe use `PHP_VERSION_ID` over `PHP_VERSION`, it would take out out the extra bit (like RC etc.) I think?

**Comment by GrahamCampbell** [comment]
> Maybe use PHP_VERSION_ID over PHP_VERSION, it would take out out the extra bit (like RC etc.) I think?

We want that extra part though, because RC1 !== RC2.

**Comment by keradus** [comment]
BTW, having tests would be great ;)

**Comment by keradus** [comment]
Any other thoughts?

**Comment by keradus** [comment]
Any other thoughts?

**Comment by keradus** [comment]
Anyone ?

**Comment by GrahamCampbell** [comment]
Maybe a better way might be to select a cache file based on the php version?

**Comment by keradus** [comment]
one can already choose non-default filename for cache file

**Comment by GrahamCampbell** [comment]
I was meaning that php-cs-fixer could suffix that name with the php version.

**Comment by GrahamCampbell** [comment]
To allow easy cashing across different php versions automatically.

**Comment by keradus** [comment]
OK, sounds interesting

**Comment by GrahamCampbell** [comment]
Just rebased this, but don't have time to do much else with it, so if you don't like it as is, feel free to just close this. I'm not massively fussed.

**Comment by keradus** [comment]
Actually I was waiting for https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1649#issuecomment-177268279

**Comment by GrahamCampbell** [comment]
> Actually I was waiting for #1649 (comment)

**Comment by GrahamCampbell** [comment]
> Actually I was waiting for #1649 (comment)

Yeh, well, not sure people would actually want that because it means they can't control the filename if we're arbitrarily appending stuff to it.

**Comment by keradus** [comment]
Thank you @GrahamCampbell.

**Pull request merged**
