### PR TITLE
PHP8

### PR DESCRIPTION
**Pull request by SpacePossum**
https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/4702

some background on the transformers:

https://github.com/FriendsOfPHP/PHP-CS-Fixer/commit/d76397efde3caaf4d0fb5190a5c26f246cb5563e

### CODE REVIEW

**Comment by GPHemsley** [comment]
Should `@PHP8Migration` inherit from `@PHP73Migration`?

**Comment by SpacePossum** [comment]
yes indeed, good catch!

**Comment by GPHemsley** [comment]
Oops, another question: Shouldn't this be called `@PHP80Migration` to align with `@PHP70Migration`?

**Comment by SpacePossum** [comment]
yeah thanks, sounds good, I'll append it to https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5177 , let me know if you spot more :+1:  :)

**Pull request merged**
