### PR TITLE
[WIP] Async Fixing

### PR DESCRIPTION
**Pull request by GrahamCampbell**
I hope you can see where this is going. We can just have promises for the linting steps.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Let me know if you're interested in me continuing this.

**Comment by GrahamCampbell** [comment]
NB The fulfilled promises in the code atm are just placeholders for when it will actually be made async.

**Comment by keradus** [comment]
:+1: for using `proc_open` for linting
:-1: for using `proc_open` for fixing (we have heavy app start), other parallel mechanisms could be better here
:-1: for dropping 5.3.6 (I want the version 2 to support it)
:-1: for using not stable library

**Comment by GrahamCampbell** [comment]
> :-1: for using proc_open for fixing (we have heavy app start), other parallel mechanisms could be better 

I totally agree there, and I never planned to do that.

**Comment by GrahamCampbell** [comment]
> :-1: for using not stable library

I disagree that it's not stable.

**Comment by GrahamCampbell** [comment]
> for dropping 5.3.6 (I want the version 2 to support it)

I think that's a small price to pay if we can significantly increase the performance.

**Comment by GrahamCampbell** [comment]
This is a bit of a mess tbh, lol.

**Comment by Anahkiasen** [comment]
> for dropping 5.3.6 (I want the version 2 to support it)

Wouldn't version 2 actually be the perfect moment to drop support for EOL versions of PHP?

**Comment by keradus** [comment]
No. It is widely used (even in dev version).

**Comment by GrahamCampbell** [comment]
Meh.

**Comment by keradus** [comment]
It is pointless to say that 2.x is so awesome, works on 5.3.6 and then just drop it even if it could be used.
Changing interface to promises and async work is great, but it is a lot of work, more than it looks. Great thing for 3.x.

**Comment by GrahamCampbell** [comment]
Yeh, I'm inclined to agree. I also ran into an issue with exceptions and errors being silenced.

**Comment by GrahamCampbell** [comment]
It would be good to come back and review this situation again in a year or 2.

**Pull request closed without merging**
