### PR TITLE
[2.x] PhpUnitConstructFixerTest

### PR DESCRIPTION
**Pull request by SpacePossum**
Fix the following (`Not`) cases as well.

```php
<?php $this->assertNotSame(false));
<?php $this->assertNotFalse(false);
```

```php
<?php $this->assertNotSame(true);
<?php $this->assertNotTrue(true);
```

```php
<?php $this->assertNotSame(false, $a);
<?php $this->assertNotFalse($a);
```

```php
<?php $this->assertNotSame(true, $a);
<?php $this->assertNotTrue($a);
```

### CODE REVIEW

**Comment by SpacePossum** [comment]
fabbot fails because it wants to fix the tests cases themselves.

**Comment by keradus** [comment]
Somehow I missed that one.
Please @SpacePossum , could you send it again to 1.11 ?

**Comment by Soullivaneuh** [comment]
:+1:

**Comment by SpacePossum** [comment]
closing in fav. of https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1449

**Pull request closed without merging**
