### PR TITLE
GeneralPhpdocAnnotationRemoveFixer - remove PHPDoc if no content is left

### PR DESCRIPTION
**Pull request by SpacePossum**
closes https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/3570

### CODE REVIEW

**Comment by keradus** [comment]
@TomasVotruba , either that one or similar one you have also faced if I remember correctly.
just pinging you, maybe you will find it useful.

**Comment by keradus** [comment]
Thank you @SpacePossum.

**Comment by TomasVotruba** [comment]
@keradus Thanks for the ping. I'll wait for 3.0 release then verify.

**Comment by keradus** [comment]
well, it will be released under 2.2 ;)

**Comment by TomasVotruba** [comment]
Sure. I meant it in the chunk upgrade with other changes.   I put all my os time to Rector now

**Comment by TomasVotruba** [comment]
@keradus I just check it and this only applied when some annotations are removed by this fixer. Not to other empty doc blocks.

The fix is needed in `NoEmptyPhpdocFixer`

**Comment by keradus** [comment]
yep, this change affects only `GeneralPhpdocAnnotationRemoveFixer`
if you want to change `NoEmptyPhpdocFixer`, open a PR :+1:

**Comment by TomasVotruba** [comment]
Have you changed your view on this? IIRC you've declined it before

**Comment by keradus** [comment]
and then more ppl wanted it, you have proof of that here - this PR.
when it's one-vs-one, status quo is maintained, but if more ppl want some change, well, i don't need to agree with it to accept it.

**Comment by TomasVotruba** [comment]
Allright: https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3604

**Pull request merged**
