### PR TITLE
SelfAccessorFixer - mark as risky

### PR DESCRIPTION
**Pull request by Slamdunk**
https://3v4l.org/LrvSc

Behavoir present in [Yii2](https://github.com/yiisoft/yii2):
https://github.com/yiisoft/yii2/blob/4f80cda7130da5259ce93fe41eb681cbb70f30be/framework/base/BaseObject.php#L84-L87

S****y inheritance code, but still this fixer changes the user code behaviour.

### CODE REVIEW

**Comment by keradus** [comment]
I see that our AutoReview is doing great job :D

great catch, but extra sad for me :(

yet, IMO, we could try to fix it by not changing static method calls. WDYT ?

**Comment by Slamdunk** [comment]
> yet, IMO, we could try to fix it by not changing static method calls. WDYT ?

After years of usage of this Fixer, this is the first time I see it, and Yii2 is gonna remove that funcionality in the next release.

I'm not gonna spend time on this edge case: risky comment is enough for me.

**Comment by julienfalque** [comment]
:+1: for keeping the behavior as-is and mark it as risky.

**Comment by keradus** [comment]
Thank you @Slamdunk.

**Pull request closed without merging**
