### PR TITLE
no_whitespace_in_blank_lines -> no_whitespace_in_blank_line

### LINKED ISSUE #1797: no_trailing_whitespace_in_comment -> no_trailing_whitespace_in_comments
no_trailing_whitespace_in_comment -> no_trailing_whitespace_in_comment**s**

### PR DESCRIPTION
**Pull request by SpacePossum**
closes #1797

### CODE REVIEW

**Comment by SpacePossum** [comment]
fabbot is wrong, this rtm

**Comment by GrahamCampbell** [comment]
> fabbot is wrong

**Comment by keradus** [comment]
:+1:

**Comment by GrahamCampbell** [comment]
I prefer the plural. :-1:

**Comment by keradus** [comment]
consistency is good

**Comment by GrahamCampbell** [comment]
Yeh, we should consistently use the plural form imo.

**Comment by keradus** [comment]
it was half/half and community decided to go with singular form, no need to go around ;)

**Comment by GrahamCampbell** [comment]
sigh

**Comment by GrahamCampbell** [comment]
It doesn't fix it on one line. It fixes all lines.

**Comment by keradus** [comment]
Thank you @SpacePossum.

**Pull request merged**
