### PR TITLE
Convert PR/issue numbers to active links in CHANGELOG

### PR DESCRIPTION
**Pull request by miclf**
As the title says. Referenced pull requests and issues could then be reached directly from the change log file.

### CODE REVIEW

**Comment by keradus** [comment]
:-1: by me.
Want to keep readme file clean for using it offline, when using online there is a great milestones/releases list.

I would be glad to hear other opinions

**Comment by Anahkiasen** [comment]
Use Github releases in addition to the Changelog, they autolink to issues and stuff if I recall

**Comment by miclf** [comment]
I have to say that I was a bit surprised to see GitHub *not* autolinking issues in changelog files (even if that makes sense — they probably don’t want to accidentally break stuff). So I thought I would just propose this easy PR.

That said, GitHub releases are a great tool to use for that, so thanks to @Anahkiasen for the reminder.

**Comment by gharlan** [comment]
:+1: for using GitHub releases

**Comment by keradus** [comment]
Closing due to discussion.
Also our changelog is currently autogenerated from git history.
We should focus on describing releases in GH releases.

**Pull request closed without merging**
