### PR TITLE
[BinaryOperatorSpacesFixer] Fix align of `=` inside calls of methods

### PR DESCRIPTION
**Pull request by VincentLanglet**
Hi. I found a bug when using align/align_with_space_minimal for `=`.

Before, any time a `(` was found, the check was skipped until the `)`.

Now, I do this only for `(` for function definition and for/foreach/if/while/...

So 
```
$this->foo(function () {
$a = 1;
$aa = 2;
})
```
aligns the `=`.

It fix my personal issue (I added a test), and I think it will fix the issue #5667

### CODE REVIEW

**Comment by VincentLanglet** [comment]
@SpacePossum @keradus Hi, would you have time to take a look to this fix ? Does something need to be improved ?
Thanks :)

**Comment by VincentLanglet** [comment]
Friendly ping @keradus @SpacePossum. Is something wrong/missing with my PR ?

**Comment by VincentLanglet** [comment]
Friendly ping @keradus @SpacePossum ; would you mind taking a look at this bugfix ? :)

**Comment by VincentLanglet** [comment]
> Can you update the sample to the more simple one:

Sure, done.

> we also need a test with $fn1 = fn($x = 1) => $x + 3;

I don't understand what should be tested.

**Comment by SpacePossum** [comment]
Thanks for updating/simplify the sample, much appreciated :+1: 

I'm thinking along these lines,
lets say we have

```
<?php

fn ($x = 1) => $x + 3;
$f = 123;
```

it will get fixed to:

```diff
--- test.php
+++ test.php
@@ -13,4 +13,4 @@
  fn ($x = 1) => $x + 3;
-$f = 123;
+$f     = 123;
```

which I think is not correct

The change to `if ($token->isGivenKind(T_FUNCTION)) {` should be extended not to just test for function signatures but also for these cases, i.e. `if ($token->isGivenKind([T_FUNCTION, T_FN])) {`

**Comment by VincentLanglet** [comment]
> I'm thinking along these lines, lets say we have
> 
> ```
> <?php
> 
> fn ($x = 1) => $x + 3;
> $f = 123;
> ```
> 
> it will get fixed to:
> 
> ```diff
> --- test.php
> +++ test.php
> @@ -13,4 +13,4 @@
>   fn ($x = 1) => $x + 3;
> -$f = 123;
> +$f     = 123;
> ```
> 
> which I think is not correct
> 
> The change to `if ($token->isGivenKind(T_FUNCTION)) {` should be extended not to just test for function signatures but also for these cases, i.e. `if ($token->isGivenKind([T_FUNCTION, T_FN])) {`

You were right, it was fixing. I added the test and the fix.

**Comment by SpacePossum** [comment]
Thank you @VincentLanglet.

**Comment by VincentLanglet** [comment]
> Thank you @VincentLanglet , apologies for the long wait, PR is much appreciated 👍

No problem, I know it's not always easy to find time to maintain such a big project.
I'll be happy to provide some others PR ;)

**Comment by stayallive** [comment]
This seems to "break" (in my projects) on 2 fronts:

```diff
         if ($tenant !== null) {
-            $tenantUrl = $tenant->url;
+            $tenantUrl                     = $tenant->url;
         } elseif (!empty($sessionTenantUrl = session('tenant.url'))) {
-            $tenantUrl = $sessionTenantUrl;
+            $tenantUrl                     = $sessionTenantUrl;
         }
```

The above seems to be fixed by #6333, the other case is:

```diff
-    $parser = new QueryParser(
+    $parser    = new QueryParser(
         $query = 'modifier:single'
     );
```

So I think this was a good change but missed some edge cases it looks like.

Happy to help where I can but thought to report it here first 👍

**Comment by VincentLanglet** [comment]
@stayallive https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6333 and https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6334 are doing some fixes.

If the second PR is still not fixing your use case, please report it

**Pull request closed without merging**
