### PR TITLE
[WIP] Transform PHP 8 qualified names

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Two concerns here:

1. Does this code actually transform every occurrence? Does the foreach still get the tokens that were shifted right to make room after transformation?
2. Why does this not transform anything. :trollface: Can someone help? // cc @SpacePossum

### CODE REVIEW

**Comment by hamdrew** [comment]
When you say "Why does this not transform anything.", which exactly do you mean? Are your tests failing?

Are you running your code in PHP 8.0.0RC1? If so, I'm surprised you didn't run into the `Call to undefined method PhpCsFixer\Tokenizer\Tokens::rewind()` backwards-compatibility issue.

**Comment by GrahamCampbell** [comment]
> Are your tests failing?

Yes, see the travis build.

**Comment by hamdrew** [comment]
> Yes, see the travis build.

Oops, I should have clarified! I checked the Travis build and noticed that it failed the static code analysis (since it runs on PHP 7.4), so tests didn't run.  That's why I asked about your tests.

Managing the CI builds will be tricky as we introduce changes for PHP 8.  I've been pondering on that and might propose something.

**Comment by GrahamCampbell** [comment]
Oh. Forgot travis was configured in that way.

**Comment by SpacePossum** [comment]
Hi and sorry for not coming back on this earlier, struggled to find time to work on PHP8 support : (
Thanks for your WIP PR.

> Does this code actually transform every occurrence? Does the foreach still get the tokens that were shifted right to make room after transformation?

yeah, that will work fine

> Why does this not transform anything. :trollface: Can someone help? // cc

I went ahead and wrote a similar transformer and sure run into the same bug;
https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5166/files#diff-f0f05b598c6bff06cf727fc98b5d1191f18793eb4f9dce0c61b7d93ec8a7a334L980

The issue was that when inserting tokens of a different kind but with the same content the replace was not done :tada: 

Let me know if you spot anything off in my PR or if you've time to work on some other PHP8 issue here :)

**Comment by GrahamCampbell** [comment]
👍

**Pull request closed without merging**
