### PR TITLE
Escaped PHP executable path in Process' command line

### PR DESCRIPTION
**Pull request by mdecaffmeyer**
In response to issue #1364

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This doesn't seem to work on hhvm?

**Comment by sstok** [comment]
https://github.com/symfony/symfony/blob/05f3c3db7b6b46ba10a2b54178f97a21bf4161a8/src/Symfony/Component/Process/PhpExecutableFinder.php#L40

`hhvm --php` is a command with an argument, escaping this would make look a executable with a space in the name.

```php
            $executableFinder = new PhpExecutableFinder();
            $executable = ProcessUtils::escapeArgument($executableFinder->find()).$executableFinder->findArguments();
```

Should do the trick.

**Comment by keradus** [comment]
ping @mdecaffmeyer, it would be really great to see this!

**Comment by GrahamCampbell** [comment]
I can take over here if you like. The fix should be quite easy.

**Comment by keradus** [comment]
If anyone could do this it would be great ;)

**Comment by GrahamCampbell** [comment]
There we go: https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1403.

**Comment by mdecaffmeyer** [comment]
Thank you for taking over! I've a lack of time at the moment, sorry.

**Comment by keradus** [comment]
Closing due to merge of #1414

**Pull request closed without merging**
