### PR TITLE
Fixed bad ruleset merge

### PR DESCRIPTION
**Pull request by GrahamCampbell**
The ruleset refactor and merge upwards discarded all the differences in the rulesets between 2.15 and 2.16. This PR fixes this.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
// cc @SpacePossum

**Comment by SpacePossum** [comment]
Thanks, there were/are more issues with the sets and the tests, I've fixed a bunch, lets see what still needs to be done by looking @ Travis on the branches

**Comment by GrahamCampbell** [comment]
Looks good now.

**Comment by SpacePossum** [comment]
thanks, seems all is fixed :+1:

**Comment by GrahamCampbell** [comment]
@SpacePossum This PR is still needed to make that one remaining change?

**Pull request closed without merging**
