### PR TITLE
NoExtraConsecutiveBlankLinesFixer - SF rule set, add 'extra'

### PR DESCRIPTION
**Pull request by SpacePossum**
for ref. https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/1920

### CODE REVIEW

**Comment by keradus** [comment]
is it the full set that Symfony uses, or we could add more things to config of that rule ?

**Comment by SpacePossum** [comment]
I asked at SF, will see :)

**Comment by keradus** [comment]
:+1:

please rebase

**Comment by keradus** [comment]
Thank you @SpacePossum.

**Pull request closed without merging**
