### PR TITLE
PhpdocToParamTypeFixer - cover more cases

### PR DESCRIPTION
**Pull request by keradus**
ref #4583

@jg-development, @SpacePossum ,
can you pick it up, please?

### CODE REVIEW

**Comment by julienfalque** [comment]
If you don't mind, I'd like to add those to #4591.

**Comment by jg-development** [comment]
What about the string[]|int[] case?

**Comment by julienfalque** [comment]
It should already be covered by #4591.

**Comment by jg-development** [comment]
I am trying to look into that today

**Comment by keradus** [comment]
Thank you @julienfalque.

**Pull request merged**
