### PR TITLE
YodaStyleFixer - Fix variable detection for multidimensional arrays

### LINKED ISSUE #3335: Weird changes for the YodaStyleFixer
PHP: 7.2.0
PHP-CS-Fixer: 2.9.0
Command: `php-cs-fixer fix`
Configuration file:
```php
<?php

$finder = PhpCsFixer\Finder::create()
    ->in(__DIR__.'/src')
    ->in(__DIR__.'/tests')
    ->in(__DIR__.'/features/bootstrap')
    ->in(__DIR__.'/app')
    ->in(__DIR__.'/api')
    ->exclude('cache')
    ->exclude('logs')
    ->exclude('sessions')
    ->notName('bootstrap.php.cache')
;

return PhpCsFixer\Config::create()
    ->setRules(array(
        '@Symfony' => true,
        'array_syntax' => array('syntax' => 'long'),
        'doctrine_annotation_braces' => true,
        'doctrine_annotation_indentation' => true,
        'doctrine_annotation_spaces' => true,
        'heredoc_to_nowdoc' => true,
        'no_useless_else' => true,
        'ordered_class_elements' => true,
        'ordered_imports' => true,
    ))
    ->setFinder($finder)
    ->setCacheFile(__DIR__.'/build/.php_cs.cache')
;
```

Here is the diff produced by the tool:

```diff
             if (isset($referenceMessagesByDomainAndKey[$key])
-                && $messages['en'] === $referenceMessagesByDomainAndKey[$key]['en']
-                && $messages['fr'] === $referenceMessagesByDomainAndKey[$key]['fr']) {
+                && $referenceMessagesByDomainAndKey[$key]['en'] === $messages['en']
+                && $referenceMessagesByDomainAndKey[$key]['fr'] === $messages['fr']) {
                 continue;
             }
```

I expected no changes there, as I have variables on both sides.

### PR DESCRIPTION
**Pull request by julienfalque**
Fixes #3335 and replaces #3505.

### CODE REVIEW

**Comment by julienfalque** [comment]
PR scope reduced as discussed in https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/3153#issuecomment-379725393.

**Comment by SpacePossum** [comment]
Thanks for picking this up :)
I was struggling to get the possible repeated access detected correctly as well,
for example
```
$c2->a{a}{a}']
$c1->a{a}->a']
$a[1][2][3]/**/[4]
```

for more sample, please see this test; https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3505/files

I didn't test your solution yet, will do soon!

**Comment by julienfalque** [comment]
In the tests you added, which one are supposed to be swapped? All that should be detected as a variable (`$expected = true`)?

**Comment by SpacePossum** [comment]
I think;
```php
+            [true, '$a'],
+            [true, '$a+1'],
+            [true, '$b->a'],
+            [true, '$c->a[a]'],
+            [true, '$c1->a[a]->a'],
+            [true, '$c2->a[a][a]'],
+            [true, '$d->a[$a]'],
+            [true, '$c->a{a}'],
+            [true, '$c1->a{a}->a'],
+            [true, '$c2->a{a}{a}'],
+            [true, '$d->a{$a}'],
```
and these
```
$c2->a{a}{a}']
$c1->a{a}->a']
$a[1][2][3+5]/**/[4*2-1]
```
for sure

**Comment by julienfalque** [comment]
So `$a+1` should be detected as a variable but it's not. Does it mean you want me to add the following test case?

```php
['<?php return $b === $a+1;'],
```

**Comment by SpacePossum** [comment]
that looks like a mistake in my testset, sorry about that one. IIRC the bug is handling single level array access different than deeper levels. So $a[1] vs $a[1][2] and deeper. Also for $a->$A vs $a->$a->$a and combinations of that.

**Comment by julienfalque** [comment]
@SpacePossum I added more test cases from `provideFixCases()` in your PR. Most already pass (some with the changes in the fixer, some even without) so I didn't add them all. I'm still not sure how to proceed with test cases in `provideIsVariableCases()` to be honest. Could you show how those would look like if used in `provideFixCases()`?

**Comment by SpacePossum** [comment]
I've added more test in your branch to make it a bit more easy I hope. I'm fine with not having dedicated test for `provideIsVariableCases`-especially as the method name is misleading anyway ;)

So, after all the awesome work there is one case left I could find:

```php
<?php return $foo->$a === $foo->$b->$c;
```

IMHO this should not be fixed/touched, as both the left and right side of the `===` are the same type of access to something, WDYT?

**Comment by julienfalque** [comment]
Thanks, I'll have a look shortly!

> IMHO this should not be fixed/touched, as both the left and right side of the === are the same type of access to something, WDYT?

I agree it should not be changed though I think it's because both sides are assignable, not because they are of the same access type.

**Comment by julienfalque** [comment]
Green :)

**Comment by SpacePossum** [comment]
nice, thanks! looking good @julienfalque :)

**Comment by keradus** [comment]
Thank you @julienfalque.

**Pull request merged**
