### PR TITLE
ShortScalarCastFixer - Change binary cast to string cast as well

### PR DESCRIPTION
**Pull request by ntzm**
Not sure if this fixer is the best place for this

### CODE REVIEW

**Comment by keradus** [comment]
imo a feature, thus 2.12

**Comment by julienfalque** [comment]
The default behavior of the fixer is changing, shouldn't we add an option?

**Comment by ntzm** [comment]
Agreed, will update shortly

**Comment by keradus** [comment]
:-1: for option, but I agree it's always fuzzy
it's not that we now change possible behaviour, we simply fix more cases, imo it;s good without option
we simply fix more cases, "rule" remains the same, "fixer" that implements it implement it more completely.

@julienfalque , do you remember #3445 ? it was not just refactoring, it was refactoring to cover (detect & fix) more edge cases. but we didn't introduce any option shall newly detected cases be fixed or not, we just took it as good coin - we fix more.

**Comment by julienfalque** [comment]
#3445 is not a good example IMO as it was a bugfix (it didn't aim to cover more cases, it aimed to fix cases that didn't work as they should have). I think a better example would be #3478. But yes, it's really fuzzy. :+1: for tweaking the default behavior directly.

**Comment by keradus** [comment]
in #3445 we had to adjust existing unittests to follow new impelemntation, thus it was "behaviuor change", but ultimately not "rule change"

#3478 is good example as well ;)

**Comment by ntzm** [comment]
So keep this PR as-is?

**Comment by ntzm** [comment]
Nope I didn't no worries! Thanks

**Comment by SpacePossum** [comment]
The test failed because of a time out. It seems we run the unit tests twice on PHP7.2 because the toggle for coverage collection is off I think (https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/.travis.yml#L102 should test for `0` cc @keradus ) .

**Comment by keradus** [comment]
Thank you @ntzm.

**Pull request merged**
