### PR TITLE
Added failing integration test

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Also failing on the current 2.2 and 2.3 branches.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
If I add this on to the v2.3.2 code, then it **passes**.

**Comment by GrahamCampbell** [comment]
On the 2.3 branch, it is broken after edb500910845946200d0b273b12782167d87285e, but working at ae8f46b7f1e4678d48fba0676130339bf4488c54. Essentially looks like https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2817 broke things.

**Comment by GrahamCampbell** [comment]
Unhelpful that travis is broken for a different reason atm:

image

What we should see is:

```
There was 1 failure:

1) PhpCsFixer\Tests\IntegrationTest::testIntegration with data set #0 (PhpCsFixer\Test\IntegrationCase Object (...))
Errors reported during fixing of file "misc/braces,phpdoc_indent.test": 2: /Users/graham/GitHub/PHP-CS-Fixer/tests/Fixtures/Integration/.tmp.php

Failed asserting that an array is empty.

/Users/graham/GitHub/PHP-CS-Fixer/src/Test/AbstractIntegrationTestCase.php:218
/Users/graham/GitHub/PHP-CS-Fixer/src/Test/AbstractIntegrationTestCase.php:122
```

**Comment by keradus** [comment]
from failure, i would say it happens with simplified code sample and only one used rule. thus utest instead of itest
if happens on 2.2 as well, it shall target 2.2

**Comment by GrahamCampbell** [comment]
> from failure, i would say it happens with simplified code sample and only one used rule. thus utest instead of itest

Nope. It only happens when both fixers are enabled. It does not happen when only one is enabled.

**Comment by GrahamCampbell** [comment]
As I said in https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/2844.

**Comment by GrahamCampbell** [comment]
> if happens on 2.2 as well, it shall target 2.2

See https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2847.

**Pull request closed without merging**
