### PR TITLE
New ruleset "@PhpCsFixer"

### PR DESCRIPTION
**Pull request by gharlan**
I suggest to add new rulesets "@PhpCsFixer" and "@PhpCsFixer:risky".

Reason: I would like to use the standards recommended by this org.

I would only add fixers to these rulesets, that are really recommended by this org, not fixers you are using because of your min php version (like list_syntax=long).

### CODE REVIEW

**Comment by localheinz** [comment]
@gharlan 

I think it would be great if rulesets could be concrete classes, perhaps for 3.0?

**Comment by keradus** [comment]
sounds interesting and I see ppl like it.
(i didn't added it myself for a reason of what @localheinz is asking for)

yet, we have already some conflicts here,
@gharlan , can you target 2.12 branch, please ?
it would easier the maintainance

**Comment by gharlan** [comment]
> @gharlan , can you target 2.12 branch, please ?

done.

**Comment by keradus** [comment]
Thank you @gharlan.

**Comment by keradus** [comment]
Thank you @gharlan.

**Comment by keradus** [comment]
I propagated the idea up to 3.0, considering changes we done in config file on those branches

**Pull request merged**
