### PR TITLE
AbstractLinesBeforeNamespaceFixer - fix docs for fixLinesBeforeNamespace

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by keradus** [comment]
just a docs. set 1.7 line.
btw, few more fixers and we could kill 1.6 ;)

**Comment by GrahamCampbell** [comment]
:)

**Comment by keradus** [comment]
Thank you @GrahamCampbell.

**Comment by GrahamCampbell** [comment]
You merged into 1.6 anyway?

**Comment by keradus** [comment]
damn it, forgot to switch target :/
as I said no big deal, just the docs

**Pull request merged**
