### PR TITLE
Enhancement: Install ergebnis/composer-normalize via Phive

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] installs `ergebnis/composer-normalize` via Phive

Follows #4536.

### CODE REVIEW

**Comment by kubawerlos** [comment]
So each time a new version - even patch one - is released, `phive.xml` must be updated, right?

How is that better than having `"ergebnis/composer-normalize":"^2.1"` in `dev-tools/composer.json`?

**Comment by keradus** [comment]
@kubawerlos , it's a valid concern, but it affects other tools installed via phive already

**Comment by keradus** [comment]
Thank you @localheinz.

**Comment by localheinz** [comment]
Thank you, @keradus and @kubawerlos!

**Pull request merged**
