### PR TITLE
FunctionDeclarationFixer - fix more cases

### PR DESCRIPTION
**Pull request by keradus**
ref #1768

### CODE REVIEW

**Comment by glensc** [comment]
so, i removed those silly comments on lines 3&4 (of the gist on referenced issue), but it still gets internal error. what exactly is causing the error?

**Comment by glensc** [comment]
nevemind. mislooked

**Comment by keradus** [comment]
fixed

**Comment by SpacePossum** [comment]
Looks like a solid fix :+1: 
I guess 1.x only? (i.e. the line break being dealt with by the transformers on 2.x?)
Do you know any other fixer might be effected as well?

**Comment by keradus** [comment]
ref https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/1768#issuecomment-182594667

hard to guess

**Pull request closed without merging**
