### PR TITLE
`ISSUE_TEMPLATE` hints to check applied rules

### PR DESCRIPTION
**Pull request by goulashsoup**
To prevent further non-issues.

### CODE REVIEW

**Comment by SpacePossum** [comment]
Hi and thanks for the improvement suggestion through this PR,

The template already states that you should run the tool with `vvv`, so I'm not sure if this adds a lot. I think not everybody reads the complete template and follow all the steps, so I think adding more information might not yield the result that is wanted. Like to here more opinions on this though.

**Comment by goulashsoup** [comment]
> `provide technical details such as: ... the command used to run PHP CS Fixer (run with `-vvv`)`  

I understood the template as follows: "Provide the CS-Fixer command with `-vvv` so that devs can copy and use it." So asking for the command itself, not that the user runs it.

That i discovered that this command lists applied rules was a sheer coincidence, but of course my actions can be blamed of being lazy and/or minor intelligent.

I think a stronger hint to check `-vvv` can prevent time consuming false reports.

> The template already states that you should run the tool with `vvv`

**Where is that written clearly and unambiguously?**

**Comment by SpacePossum** [comment]
Any feedback on the doc's is welcome and if you feel that something is not `written clearly and unambiguously` than of course this is valuable feedback.
The template issue main goal is to provide as much detail so anyone can to start working on the reported issue. As such is it not intended to guide people through the working of the tool, for that we have the `usage` doc. Again, it is not about blaming or calling someone lazy, it just goes to show that the intended way of provide the doc and template might not be working, therefore, sure, improvements are welcome.

**Comment by keradus** [comment]
I believe that merging this could help in some cases, and does not harm in other. I'll merge. THanks!

**Pull request merged**
