### PR TITLE
Added PhpdocPropertyFixer, refactored Tag and Annotation

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Once branch merges have taken place I'll rebase this so that it works following my changes on 1.11.

**Comment by keradus** [comment]
wait a few more minutes please ;)

**Comment by GrahamCampbell** [comment]
> wait a few more minutes please ;)

That's fine. I'm only planning to rebase later this evening anyway. ;)

**Comment by keradus** [comment]
ready ;)

**Comment by GrahamCampbell** [comment]
Done. :)

**Comment by GrahamCampbell** [comment]
Just rebased again.

**Comment by keradus** [comment]
Thank you @GrahamCampbell.

**Pull request closed without merging**
