### PR TITLE
Linter - detect executable

### PR DESCRIPTION
**Pull request by keradus**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Should we allow the php executable to use to be overwritten with an optional constructor param?

**Comment by keradus** [comment]
This PR does not provide any new functionality.
It just protect us from situations, where there is no standard PHP executable (eg `php54-cli`).

If we want to add a feature to set php executable then it will be also nice to allow to specify it in config

**Comment by GrahamCampbell** [comment]
I was mainly thinking from the perspective of making the code reusable, rather than actually writing the whole config deal, though, I agree that might actually be a good idea.

**Comment by keradus** [comment]
It's cool when thinking about using PHP CS Fixer as library, but we also need to focus on using as a tool.

**Comment by GrahamCampbell** [comment]
:)

**Comment by GrahamCampbell** [comment]
It's a really awesome library. :)

**Comment by keradus** [comment]
Yeah, there are even such a great services built on it ;)

**Comment by keradus** [comment]
How about that?

**Comment by GrahamCampbell** [comment]
Looks good, yeh.

**Pull request closed without merging**
