### PR TITLE
[1.10] Fixed the var without name fixer for inline docs

### LINKED ISSUE #1352: phpdoc_var_without_name - removes @var from hash descriptions
```php
    /** 
     * Something about the method    
     * 
     * @return array {
     *     @var int|null $visibility T_PRIVATE, T_PROTECTED or T_PUBLIC
     *     @var bool     $static
     *     @var bool     $abstract
     *     @var bool     $final
     * }
     */
```

The fixer should not remove the `@var`.
References: 
https://github.com/phpDocumentor/fig-standards/blob/master/proposed/phpdoc.md#7-describing-hashes
https://github.com/php-fig/fig-standards/pull/169/files#diff-9a10a11696dc38209c125ea9c57a565fR689
discussed here https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1292#discussion_r36795601

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Let's fix this then. :)

--

Closes #1352. Replaces #1374.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Any news on this?

**Comment by keradus** [comment]
:+1:

**Comment by GrahamCampbell** [comment]
:ship:

**Comment by GrahamCampbell** [comment]
Ping @keradus. :)

**Comment by keradus** [comment]
This fix looks wrong, https://github.com/GrahamForks/PHP-CS-Fixer/pull/1

**Comment by GrahamCampbell** [comment]
Sure, easy fix. :)

**Comment by GrahamCampbell** [comment]
@keradus How does this look now?

**Comment by keradus** [comment]
https://github.com/GrahamForks/PHP-CS-Fixer/pull/2

**Comment by GrahamCampbell** [comment]
Thanks for the reviews @keradus. How does this looks now?

**Comment by keradus** [comment]
You ask me to found another bug?
If so, then please wait a bit ;) Must think of it ;)

**Comment by GrahamCampbell** [comment]
Haha.

**Comment by GrahamCampbell** [comment]
This algo is pretty heuristic because implementing nested annotation here would be way harder as far as I can see. ;)

**Comment by keradus** [comment]
IMO nested annotations should be handled on DocBlock level, not fixer level

**Comment by GrahamCampbell** [comment]
Yeh, that's what I was thinking, but I think that would be both hard, and unnecessary to implement. That's why I didn't take that approach. This one is good enough, because the thing we're dealing with here is so specific.

**Comment by GrahamCampbell** [comment]
I'd also assume this way is significantly faster to execute.

**Comment by keradus** [comment]
On the other hand, we do not support nested annotation in so many fixer, and now we should fix it in more fixers (not that one you had fixed in this PR). Handling it inside DocBlock will made us not need to fix all fixers separately

**Comment by GrahamCampbell** [comment]
All the other fixers work fine though?

**Comment by GrahamCampbell** [comment]
Nested annotations don't need special handling.

**Comment by GrahamCampbell** [comment]
That's why I think it would be a waste of time to implement.

**Comment by GrahamCampbell** [comment]
That said, I think it would be a very good idea to add tests to all the fixers to check I'm not talking crap. :P

**Comment by keradus** [comment]
Cool to hear

**Comment by keradus** [comment]
Yeah, too many fixers to guess ;)

**Comment by keradus** [comment]
:+1: for fix!
Could you squash commits of same author please?

**Comment by GrahamCampbell** [comment]
> Could you squash commits of same author please?

Ish, yeh. I'll probably just do a git reset then stage and commit twice. :P

**Comment by keradus** [comment]
will work ;)

**Comment by keradus** [comment]
Replaced by #1401

**Comment by GrahamCampbell** [comment]
Thanks. Sorry I didn't get around to doing the last bit.

**Comment by keradus** [comment]
No problem ;) Wanna take a look on #1383 ?

**Pull request closed without merging**
