### PR TITLE
added Atom package

### PR DESCRIPTION
**Pull request by pfefferle**
see https://atom.io/packages/php-cs-fixer

### CODE REVIEW

**Comment by pfefferle** [comment]
added new pull request: https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1175

hope this is ok now ;)

**Comment by SpacePossum** [comment]
:+1:

**Comment by keradus** [comment]
Is anyone here using atom and can confirm quality of that package?

**Comment by keradus** [comment]
Closed due to merge of #1202
PhpStorm info was updated too

**Pull request closed without merging**
