### PR TITLE
don't register self-update command when running non-phar distribution

### PR DESCRIPTION
**Pull request by remicollet**
Just because this may looks strange:

```
$ php-cs-fixer list
  ...
  self-update  Update php-cs-fixer.phar to the latest stable version.
  selfupdate   Update php-cs-fixer.phar to the latest stable version.

$ php-cs-fixer self-update
Self-update is available only for PHAR version.
```

### CODE REVIEW

**Comment by keradus** [comment]
From https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/710#issuecomment-62793466 :
> If one run self-update command on non-phar version he should get info that this action is allowed only with phar version.
Otherwise one who read README file and want to simply run self-update as described will get no command found.

Big :-1: for having different commands depending on installation type

**Comment by remicollet** [comment]
BTW, composer or PHPUnit already do this way.

**Comment by SpacePossum** [comment]
>Self-update is available only for PHAR version.

I like this message, it gives some info about what or why.

**Comment by keradus** [comment]
Closing due to discussion and lack of further communication

**Comment by GrahamCampbell** [comment]
I agree that conditional command registration seems like a hack.

**Pull request closed without merging**
