### PR TITLE
Psr0Fixer - disallow run on StdinFileInfo

### LINKED ISSUE #1355: Getting error wrong file name all time when I'm using stdin
PHP CS Fixer version 1.10
cat ./src/RM/Response.php | php ./bin/php-cs-fixer fix --diff -
````bash
   1) stdin.php
      ---------- begin diff ----------
      --- Original
      +++ New
      @@ @@
       
      -class Response extends RM\Response
      +class stdin extends RM\Response
````

### PR DESCRIPTION
**Pull request by keradus**
Fixes #1355

### CODE REVIEW

**Comment by SpacePossum** [comment]
:+1:

**Comment by gharlan** [comment]
:+1:

**Comment by maZahaca** [comment]
Merge it please

**Comment by keradus** [comment]
Closing

**Pull request merged**
