### PR TITLE
LowercaseConstantsFixer - Fix case where fixer would incorrectly chan…

### PR DESCRIPTION
**Pull request by srathbone**
…ge class properties after the object operator.

### CODE REVIEW

**Comment by SpacePossum** [comment]
Hi @srathbone ,

Thanks for this PR, looks like a good bug fix! Just wondering, is this bug also present on 2.12 that you know? If so it would be great to retarget this PR to that branch so we've the bug fix on the lowest support version of the project :)

**Comment by srathbone** [comment]
Hi @SpacePossum,

New PR is open, can I close this PR?

**Comment by ntzm** [comment]
FYI, you can change the target branch in the PR itself: https://help.github.com/articles/changing-the-base-branch-of-a-pull-request/

**Comment by julienfalque** [comment]
Closing as replaced by #4127.

**Pull request closed without merging**
