### PR TITLE
Fixers - no need to search for tokens of given kind in extra loop

### PR DESCRIPTION
**Pull request by keradus**
```bash
[keradus@keradus 00:10 ~/github/PHP-CS-Fixer]$ . benchmark.sh master 2.0-fix_find
master mean:2.9462 total:29.462 rounds:10
2.0-fix_find mean:2.9255 total:29.255 rounds:10
```

Proposed long time ago, not sure but perhaps by @ceeram 

~1 percent performance gain. One by one...

### CODE REVIEW

**Comment by stof** [comment]
:+1: (we should probably even do it in 1.5 btw)

**Comment by keradus** [comment]
Thanks!
Just want to forget about 1.x line as soon as possible ;)

**Comment by GrahamCampbell** [comment]
If only we could use generators. :(

**Comment by keradus** [comment]
They are cool. I agree. But they don't give you any extra cutting edge functionality which can't be done without them.
You remember we have a longer talk about min PHP version for 2.0 line, no need to do it again over and over.

**Comment by GrahamCampbell** [comment]
:)

**Pull request merged**
