### PR TITLE
Switch to PSR-4

### PR DESCRIPTION
**Pull request by keradus**

### CODE REVIEW

**Comment by gharlan** [comment]
:+1:

**Comment by GrahamCampbell** [comment]
YES. FINALLY! :rocket:

**Comment by gharlan** [comment]
What do you think about renaming the namespace?
`Symfon\CS\` -> `PhpCsFixer\`

**Comment by SpacePossum** [comment]
like the idea :)

>Symfony\CS\ -> PhpCsFixer\

:+1:

**Comment by keradus** [comment]
It is not the scope of this PR.

**Comment by SpacePossum** [comment]
fair enough :)

**Comment by keradus** [comment]
> Sorry, we could not display the entire diff because too many files (376) changed.

:D

**Comment by Soullivaneuh** [comment]
> > Sorry, we could not display the entire diff because too many files (376) changed.

> :D

Hoy hoy peggy diff! :pig: 

:+1: for PSR-4! ;-)

**Comment by keradus** [comment]
Help would be appreciated.
I cannot duplicate the errors on my local env :(

**Comment by GrahamCampbell** [comment]
@keradus I bet you it's due to line ending changes.

**Comment by keradus** [comment]
Where are they ?

**Comment by GrahamCampbell** [comment]
Not sure. GitHub's being lazy with showing all the diff, lol.

**Comment by keradus** [comment]
I can't see any line ending changes and errors didn't look like it is the reason...

**Comment by keradus** [comment]
Anyone?

**Comment by gharlan** [comment]
I can reproduce the failures on my mac.
The reason is [this line](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/0c290f4bf31727be69fd8ec65a1dfc08be528b10/Symfony/CS/Fixer/Symfony/UnusedUseFixer.php#L63).

**Comment by keradus** [comment]
Thank you @gharlan !
The Travis is now green!
The AppVeyor is still red.

**Comment by keradus** [comment]
This is the last PR I have merged this year. Now, the PSR-4 is here for all of you ;)
Let the next year be better for all of us!

**Pull request closed without merging**
