### PR TITLE
Fixer - fix rare situation when file was visited twice

### PR DESCRIPTION
**Pull request by keradus**
Closing #1706
Developed during #1666

### CODE REVIEW

**Comment by keradus** [comment]
cc @GrahamCampbell

**Comment by GrahamCampbell** [comment]
Surely this is slower than the alternative I suggested?

**Comment by keradus** [comment]
It shouldn't. Please measure and show.
We will need to do it that way on 2.x when we will have cachingIterator to lint files before fixing them, and we need to ommit some files before linting

**Comment by keradus** [comment]
I tried to measure real impact this has on running the tool. The difference in measurement error rate

**Pull request merged**
