### PR TITLE
Updated my email address

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by keradus** [comment]
That would be fun if someone vote :-1: ;)

**Comment by GrahamCampbell** [comment]
I'd:

image

**Comment by jbrooksuk** [comment]
:+1:

**Comment by GrahamCampbell** [comment]
image

**Comment by SpacePossum** [comment]
┬─┬ノ(ಠ_ಠノ)

:+1:

**Comment by keradus** [comment]
It would be really funny to have a changelog with position of changing some email... it's irrelevant.
Could you just merge it with some of your PR?

**Comment by GrahamCampbell** [comment]
Then they wouldn't be atomic. You don't HAVE to include this in the change log though?

**Comment by keradus** [comment]
All marges from PR are automatically in changelog

**Comment by GrahamCampbell** [comment]
So you joke about :-1:, then actually :-1: it. Brilliant.

**Comment by gharlan** [comment]
> All marges from PR are automatically in changelog

And automatically committed and pushed? Or can you change the changelog manually before?

**Comment by keradus** [comment]
> So you joke about :-1:, then actually :-1: it. Brilliant.

No, just said that change of mail is not relevant for end-user and it could be changed with some change that is relevant for user - don't you agree with that?

> And automatically committed and pushed? Or can you change the changelog manually before?

It can be stopped, manually changed and committed. But then it should be changed every time that changelog is generated. Is sth is automatic, it's nice to keep it that way ;)

**Comment by gharlan** [comment]
Maybe you can cherry pick the commit without merging this pr?

**Comment by keradus** [comment]
that can be a way ;)

**Comment by GrahamCampbell** [comment]
I'm actually going to hold off on this. My email might change again...

**Comment by keradus** [comment]
facepalm...

**Comment by GrahamCampbell** [comment]
yeh, i know

**Comment by keradus** [comment]
That is why I didn't want to merge it as regular PR

**Comment by GrahamCampbell** [comment]
lol - i'll probably send this again in 2 month's or so

**Pull request closed without merging**
