### PR TITLE
bug: Fix indentation of comment at end of switch case

### LINKED ISSUE #6491: braces: Incorrect closing brace for switch where last case contains only a comment
## Bug report

PHP-CS-Fixer incorrectly unindents the comment and indents the closing brace of a switch when the last case only contains a comment.

```
PHP CS Fixer 3.9.4 (093466b) Grand Awaiting by Fabien Potencier and Dariusz Ruminski.
PHP runtime: 8.0.21
Loaded config default.
Using cache file ".php-cs-fixer.cache".
F                                                                                                                                                                                                      1 / 1 (100%)
Legend: ?-unknown, I-invalid file syntax (file ignored), S-skipped (cached or empty file), .-no changes, F-fixed, E-error
```
```diff
   1) test.php (braces)
      ---------- begin diff ----------
--- /pwd/test.php
+++ /pwd/test.php
@@ -5,5 +5,5 @@
         echo "Okay", PHP_EOL;
         break;
     case 'baz':
-        // Nothing to do
-}
+    // Nothing to do
+    }

      ----------- end diff -----------


Checked all files in 0.011 seconds, 14.000 MB memory used
```

### Code snippet that reproduces the problem

```php
<?php

switch ($foo) {
    case 'bar':
        echo "Okay", PHP_EOL;
        break;
    case 'baz':
        // Nothing to do
}
```

### PR DESCRIPTION
**Pull request by julienfalque**
Fixes #6491.

### CODE REVIEW

**Comment by SpacePossum** [comment]
Hi,
I've done some testing with your branch on some projects.
Please have a look and feel free to ignore if you think these are not valid cases.

```diff
      ---------- begin diff ----------
--- /home/possum/work/ref/symfony/src/Symfony/Component/VarDumper/Cloner/VarCloner.php
+++ /home/possum/work/ref/symfony/src/Symfony/Component/VarDumper/Cloner/VarCloner.php
@@ -42,7 +42,7 @@
         $cookie = (object) [];          // Unique object used to detect hard references
         $a = null;                      // Array cast for nested structures
         $stub = null;                   // Stub capturing the main properties of an original item value
-                                        // or null if the original value is used directly
+        // or null if the original value is used directly
 
         if (!$gid = self::$gid) {
             $gid = self::$gid = md5(random_bytes(6)); // Unique string used to detect the special $GLOBALS variable

      ----------- end diff -----------
```

```diff
      ---------- begin diff ----------
--- /home/possum/work/ref/symfony/src/Symfony/Component/PropertyInfo/Util/PhpDocTypeHelper.php
+++ /home/possum/work/ref/symfony/src/Symfony/Component/PropertyInfo/Util/PhpDocTypeHelper.php
@@ -162,7 +162,7 @@
             case 'boolean':
                 return 'bool';
 
-            // real is not part of the PHPDoc standard, so we ignore it
+                // real is not part of the PHPDoc standard, so we ignore it
             case 'double':
                 return 'float';
 

      ----------- end diff -----------
```

```diff
      ---------- begin diff ----------
--- /home/possum/work/ref/composer/src/Composer/Config.php
+++ /home/possum/work/ref/composer/src/Composer/Config.php
@@ -308,7 +308,7 @@
 
                 return (($flags & self::RELATIVE_PATHS) == self::RELATIVE_PATHS) ? $val : $this->realpath($val);
 
-            // booleans with env var support
+                // booleans with env var support
             case 'cache-read-only':
             case 'htaccess-protect':
                 // convert foo-bar to COMPOSER_FOO_BAR and check if it exists since it overrides the local config
@@ -323,7 +323,7 @@
 
                 return $val !== 'false' && (bool) $val;
 
-            // booleans without env var support
+                // booleans without env var support
             case 'disable-tls':
             case 'secure-http':
             case 'use-github-api':
@@ -335,11 +335,11 @@
 
                 return $this->config[$key] !== 'false' && (bool) $this->config[$key];
 
-            // ints without env var support
+                // ints without env var support
             case 'cache-ttl':
                 return (int) $this->config[$key];
 
-            // numbers with kb/mb/gb support, without env var support
+                // numbers with kb/mb/gb support, without env var support
             case 'cache-files-maxsize':
                 if (!Preg::isMatch('/^\s*([0-9.]+)\s*(?:([kmg])(?:i?b)?)?\s*$/i', $this->config[$key], $matches)) {
                     throw new \RuntimeException(
@@ -365,7 +365,7 @@
 
                 return $size;
 
-            // special cases below
+                // special cases below
             case 'cache-files-ttl':
                 if (isset($this->config[$key])) {
                     return (int) $this->config[$key];

      ----------- end diff -----------
```

```diff
      ---------- begin diff ----------
--- /home/possum/work/ref/symfony/src/Symfony/Component/ErrorHandler/Resources/views/exception.html.php
+++ /home/possum/work/ref/symfony/src/Symfony/Component/ErrorHandler/Resources/views/exception.html.php
@@ -30,17 +30,17 @@
         <div class="tab">
             <?php
             $exceptionAsArray = $exception->toArray();
-            $exceptionWithUserCode = [];
-            $exceptionAsArrayCount = count($exceptionAsArray);
-            $last = $exceptionAsArrayCount - 1;
-            foreach ($exceptionAsArray as $i => $e) {
-                foreach ($e['trace'] as $trace) {
-                    if ($trace['file'] && false === mb_strpos($trace['file'], '/vendor/') && false === mb_strpos($trace['file'], '/var/cache/') && $i < $last) {
-                        $exceptionWithUserCode[] = $i;
-                    }
-                }
-            }
-            ?>
+$exceptionWithUserCode = [];
+$exceptionAsArrayCount = count($exceptionAsArray);
+$last = $exceptionAsArrayCount - 1;
+foreach ($exceptionAsArray as $i => $e) {
+    foreach ($e['trace'] as $trace) {
+        if ($trace['file'] && false === mb_strpos($trace['file'], '/vendor/') && false === mb_strpos($trace['file'], '/var/cache/') && $i < $last) {
+            $exceptionWithUserCode[] = $i;
+        }
+    }
+}
+?>
             <h3 class="tab-title">
                 <?php if ($exceptionAsArrayCount > 1) { ?>
                     Exceptions <span class="badge"><?= $exceptionAsArrayCount; ?></span>
@@ -51,14 +51,14 @@
 
             <div class="tab-content">
                 <?php
-                foreach ($exceptionAsArray as $i => $e) {
-                    echo $this->include('views/traces.html.php', [
-                        'exception' => $e,
-                        'index' => $i + 1,
-                        'expand' => in_array($i, $exceptionWithUserCode, true) || ([] === $exceptionWithUserCode && 0 === $i),
-                    ]);
-                }
-                ?>
+    foreach ($exceptionAsArray as $i => $e) {
+        echo $this->include('views/traces.html.php', [
+            'exception' => $e,
+            'index' => $i + 1,
+            'expand' => in_array($i, $exceptionWithUserCode, true) || ([] === $exceptionWithUserCode && 0 === $i),
+        ]);
+    }
+?>
             </div>
         </div>
 
@@ -92,14 +92,14 @@
 
             <div class="tab-content">
                 <?php
-                foreach ($exceptionAsArray as $i => $e) {
-                    echo $this->include('views/traces_text.html.php', [
-                        'exception' => $e,
-                        'index' => $i + 1,
-                        'numExceptions' => $exceptionAsArrayCount,
-                    ]);
-                }
-                ?>
+foreach ($exceptionAsArray as $i => $e) {
+    echo $this->include('views/traces_text.html.php', [
+        'exception' => $e,
+        'index' => $i + 1,
+        'numExceptions' => $exceptionAsArrayCount,
+    ]);
+}
+?>
             </div>
         </div>
 

      ----------- end diff -----------
```

**Comment by vadimonus** [comment]
@julienfalque ,  please add to your unit tests example from https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/6491#issuecomment-1204869741 to check it will be fixed two

**Comment by julienfalque** [comment]
@vadimonus I added a test, thanks.

@SpacePossum Those sample seem to be a bit out of the scope of this PR. They relate to different scenarios discussed elsewhere:
1. support for single lines comments part of multiline messages was dropped in `statement_indentation` so this is on purpose (see https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4884#discussion_r399457536)
2. comments above a switch case are discussed in #6490.
3. indentation issues in mixed PHP/HTML files have been reported in #6470 and #6519.

Hence I think the PR is ready.

**Comment by vadimonus** [comment]
@julienfalque , thanks. But it seems your test is covering only cases with single line comments. Are you sure that you test for
```php
    case_or_default:
        // Nothing to do
```
is enough to cover case
```php
    case_or_default:
        // comment
        code();
        // comment
```
?

**Comment by julienfalque** [comment]
Yep. The issue occurs when the `case`/`default` block ends with a comment, no matter the number of statements before it. I tested with your exact sample and the tests pass.

**Comment by vadimonus** [comment]
> I tested with your exact sample and the tests pass.

Great! Thanks again

**Pull request merged**
