### PR TITLE
PhpdocSeparationFixer - fix regression with lack of next line

### PR DESCRIPTION
**Pull request by keradus**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Desc should have included "Closes https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4869.".

**Comment by keradus** [comment]
sorry, didn't saw that PR.
damn, that means you spot the problem month ago but didn't go the path to fix it?

**Comment by GrahamCampbell** [comment]
I sent a PR which fixed the bug, but I wasn't sure of the exact case that reproduced it.

**Comment by GrahamCampbell** [comment]
I only had a non-isolated example, which was no good to use.

**Pull request merged**
