### PR TITLE
combine PhpdocTypeToVarFixer and PhpdocVarToTypeFixer

### PR DESCRIPTION
**Pull request by keradus**
The easiest way to handle to conflicting fixers is not to have them ;)

### CODE REVIEW

**Comment by keradus** [comment]
Could you take a look @GrahamCampbell ?

**Comment by keradus** [comment]
fabbot is failing as always (cc @fabpot)

**Comment by GrahamCampbell** [comment]
:-1:

**Comment by Soullivaneuh** [comment]
Oh, so you merged it with an option for `var` or `type`?

@GrahamCampbell How this would be handled by StyleCI?

**Comment by GrahamCampbell** [comment]
I'd rather we kept two fixers, BUT I think abstracting stuff to an abstract fixer class would be a good idea.

**Comment by keradus** [comment]
Could you elaborate @GrahamCampbell ?
Both fixer touch same rule but in different manner, the only difference is configuration.
We have so many fixers that cannot be run together (not all listed, but see #1033), and creation abstraction for them is pointless - no gain to have 10 lines moved into other class. And merging fixers that do same job in different way protect us against conflicts.

**Comment by keradus** [comment]
Any thoughts on that?
It could be a start on working on few more fixers that touch same rule but in different manner (eg how much whitespace should be before namespace)

**Comment by GrahamCampbell** [comment]
:-1: for actually removing one of the fixers.

**Comment by GrahamCampbell** [comment]
> Could you elaborate @GrahamCampbell ?

Like the other abstract fixers we have...

**Comment by GrahamCampbell** [comment]
Like https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/1.11/Symfony/CS/AbstractPhpdocTypesFixer.php.

**Comment by keradus** [comment]
Merging fixers together keep same code in one place and throw out the need of keeping list of conflicting fixers.
Creating abstraction for fixers but keeping two separated fixers doesn't give that.

**Comment by GrahamCampbell** [comment]
I think it's worth it. Having fixers with different names is much simpler and clearer.

**Comment by keradus** [comment]
Config vs inheritance - both are clear. If you only need an alias it may be done by `FixerFactory`.
But having multiple fixers that touch same rule isn't simpler if you think about handling conflicts. When you don't have multiple fixers for one rule there is no conflicts at all.

I hope your opinion isn't made due to that StyleCI doesn't support configuration yet.

Then we have a tie. Any other opinions?

**Comment by GrahamCampbell** [comment]
> I hope your opinion isn't made due to that StyleCI doesn't support configuration yet.

No, I just think it's really inconsistent with the rest of php-cs-fixer and I really like the way php-cs-fixer already does things.

**Comment by keradus** [comment]
It would be just a first step. All conflicting fixers would be merged. So no inconsistence.

And we already configure fixers, like telling which methods should be change. You would like a separate fixer for each method?

**Comment by GrahamCampbell** [comment]
:-1: All conflicting fixers would be merged.

I prefer to have different fixers.

**Comment by keradus** [comment]
Then, as I said...
Then we have a tie. Any other opinions?

**Comment by sstok** [comment]
:+1: but the name should be changed as `phpdoc_type_to_var` is no longer correct then.

**Comment by keradus** [comment]
maybe sth like `phpdoc_typehint_tag`, how do you think ?

**Comment by GrahamCampbell** [comment]
If we change this, we have to change all the others.

**Comment by keradus** [comment]
two fixers marged into new one as requested

**Comment by GrahamCampbell** [comment]
is it not confusing that fixer tagged a symfony can fix to non symfony compliant standards?

**Comment by keradus** [comment]
Fixer is not tagged as Symfony.
Rule (with it's fixer) is general, the group decides about used rules and how they are used.

`@Symfony` group contains `phpdoc_typehint_tag => [annotation=>type]`,
while some other group can contains `phpdoc_typehint_tag => [annotation=>var]`

**Comment by GrahamCampbell** [comment]
The readme is missleading then.

**Comment by keradus** [comment]
it shows that `phpdoc_typehint_tag` is used in `@Symfony` ruleset

**Comment by keradus** [comment]
Closing as we decided to remove fixer that violates PSR5

**Pull request closed without merging**
