### PR TITLE
Convert `strtolower` inside `strpos` to just `stripos`

### PR DESCRIPTION
**Pull request by ntzm**
Possibility for a new fixer as well?

### CODE REVIEW

**Comment by SpacePossum** [comment]
+0, is this really faster here?

**Comment by ntzm** [comment]
I haven't compared but it's 1 function call vs 2, so I assume it's faster?

**Comment by julienfalque** [comment]
Not sure it's faster but it's simpler so :+1: for me.

Though this an edge case, not sure it's worth creating a fixer.

**Comment by keradus** [comment]
Thank you @ntzm.

**Pull request merged**
