### PR TITLE
rename fixers

### PR DESCRIPTION
**Pull request by gharlan**
I propose some more renamings:

Old name | New name
--- | ---
double_arrow_no_multiline_whitespace | no_multiline_whitespace_around_double_arrow
spaces_cast | cast_spaces
strict | strict_comparison

### CODE REVIEW

**Comment by SpacePossum** [comment]
LGTM :+1:  :)

**Comment by keradus** [comment]
for some reason Travis hook didn't applied, please repush  your commit

**Comment by gharlan** [comment]
done

**Comment by keradus** [comment]
thanks ;)

:+1:

**Comment by keradus** [comment]
Thank you @gharlan.

**Pull request merged**
