### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by Bukashk0zzz**
Update sebastian/diff dependency version

### CODE REVIEW

**Comment by SpacePossum** [comment]
Thanks for reporting.
Please see https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/2993 and others.

**Comment by Bukashk0zzz** [comment]
@SpacePossum So close this PR? How I understand for now there are no any working solution. Maybe for now just merge this?

**Comment by SpacePossum** [comment]
sadly we cannot merge this, as the output between diff 2 and 1 slightly differs, beside diff 2 requires PHP7 and we ship with dependencies lower than that.

**Comment by Bukashk0zzz** [comment]
@SpacePossum But this not problem. You can choose what version you need. If you haven't php 7 then diff 1 will be installed.

Also tests are passed that's mean that there no any break problems.

**Comment by keradus** [comment]
v1 || v2 is not and issue for us for php5 vs php7 indeed.
issue is bc break of format produced by differ. yes, there is a bc break. yes, tests are not covering that.

**Comment by SpacePossum** [comment]
when you download the `phar` release you cannot change the `diff` version we shipped with it (in a sane way).

**Comment by Bukashk0zzz** [comment]
Thanks for explanation.

**Pull request closed without merging**
