### PR TITLE
Fix: Typos

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] fixes a few small typos

### CODE REVIEW

**Comment by SpacePossum** [comment]
:+1: 
please regenerate the readme file (`php php-cs-fixer readme > README.rst`) and this should be good :)

**Comment by localheinz** [comment]
Thank you, @SpacePossum!

**Comment by GrahamCampbell** [comment]
:+1:

**Comment by keradus** [comment]
Thank you @localheinz.

**Pull request merged**
