### PR TITLE
Fixed the import fixer priorities

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by keradus** [comment]
Please, add integration test for that

**Comment by GrahamCampbell** [comment]
Does the 1.10 branch have integration tests?

**Comment by keradus** [comment]
No, but doesn't mean we may ommit tests during fixing a bug.
Take a look at #1419 and #1420 (originally second contains first inside)

**Comment by GrahamCampbell** [comment]
Can we merge this then?

**Comment by GrahamCampbell** [comment]
And I'll send a second PR to 1.11 once you've merged 1.10->1.11, with an integration test.

**Comment by keradus** [comment]
Please send a PR to 1.11 with a fix and tests, and when tests prove the fix works - we will merge this PR into 1.10, and then the second PR to 1.11

**Comment by keradus** [comment]
ping @GrahamCampbell

**Comment by GrahamCampbell** [comment]
I'll sort this at the weekend with the psr4 fixer.

**Comment by GrahamCampbell** [comment]
Is appveyor working?

**Comment by keradus** [comment]
change PR commits (eg ammend empty changes to last commit and force push it) to recreate the build for AppVeyor

**Comment by GrahamCampbell** [comment]
I just did force push.

**Comment by GrahamCampbell** [comment]
And that broke it.

**Comment by keradus** [comment]
I did forced push on other PR and it restart AppVeyor

**Comment by GrahamCampbell** [comment]
Well, it was because of a force push that I noticed this broken. I'll deal with this at the weekend though, like I originally said. ;)

**Comment by keradus** [comment]
ping @GrahamCampbell ;P

**Comment by GrahamCampbell** [comment]
Just reset, re-commited, and force pushed.

**Comment by GrahamCampbell** [comment]
Still not working...

**Comment by keradus** [comment]
Then simply ignore AppVeyor and work on tests.

**Comment by GrahamCampbell** [comment]
Already doing that. PR incoming. :)

**Comment by GrahamCampbell** [comment]
How does this look now?

**Comment by GrahamCampbell** [comment]
Passing. :)

**Comment by keradus** [comment]
Thank you @GrahamCampbell.

**Pull request merged**
