### PR TITLE
Do not fix "alias" group in "phpdoc_types" rule by default in "Symfony" ruleset

### PR DESCRIPTION
**Pull request by mvorisek**
Aliased keywords come from old ages of phpdoc.

These keywords should be not fixed by default. Keyword like `Callback` is perfectly valid name for a class name it should be not fixed by any default ruleset.

### CODE REVIEW

**Comment by mvorisek** [comment]
Is the new/proposed default welcomed?

**Comment by kubawerlos** [comment]
> Is the new/proposed default welcomed?

With failing tests? Definitely no.

To branch `2.16`? No.

In general? Why would it?

> These keywords should be not fixed by default

Is this some general truth in PHP world that only I never heard of?

**Comment by mvorisek** [comment]
> > These keywords should be not fixed by default
> 
> Is this some general truth in PHP world that only I never heard of?

@kubawerlos because:
```
class Callback {
}

$cl = new Callback();
(function (callback $x) {})($cl);
```
keywords like `callback` (case insensitive) etc. are fully valid class/trait/interface names and they should never be fixed by CS fixer.

> In general? Why would it?

I changed target to `master` - it that right target for upcoming `2.17`?

Is this update welcomed? If yes, I will then update tests.

**Comment by kubawerlos** [comment]
The same applies to `mixed` or `scalar` which are in `meta` group.

> are fully valid class/trait/interface names and they should never be fixed by CS fixer by default.

This still is an opinion - some can claim it should not - after all, it is simply default value and anyone can not use it.

I don't see why any default value (especially one affecting Symfony ruleset) should be changed just because someone says so - except if we call this a bug and that change is approved by someone from Symfony project.

**Comment by mvorisek** [comment]
@kubawerlos please ping the right people from Symfony for this

**Comment by kubawerlos** [comment]
Ok then, @stof - is this change something to be done?

**Comment by SpacePossum** [comment]
The current PR aims to change the default of the fixer, not just the configuration of it in the SF set I think. 

While keywords can (now) be used as class/trait/interfaces names I don't think it very populair. If this requests comes from the SF community I think we can change it in the set, but otherwise I would recommend to configure by project at the fixer as is. 

For now i'm closing this request as not leave expectations open, however if Stof, Fabien or other members/maintainer/contributors of the SF community want this changed, please let us know and we can update their set.

Thanks for the suggestion!

**Pull request closed without merging**
