### PR TITLE
Linter - Prefer error output when throwing a linting exception

### PR DESCRIPTION
**Pull request by GrahamCampbell**
The error output provides information that's actually useful to debug the error.

### CODE REVIEW

**Comment by SpacePossum** [comment]
:+1:

**Comment by GrahamCampbell** [comment]
Ping @keradus. ;)

**Comment by keradus** [comment]
I replace `checkProcess` method with the following one:
```php
    private function checkProcess(Process $process)
    {
        if (!$process->isSuccessful()) {
            echo sprintf(">>>%s<<<\n>>>%s<<<", $process->getOutput(), $process->getErrorOutput());
            throw new LintingException($process->getOutput(), $process->getExitCode());
        }
    }
```
and run fixer on invalid file, what I got is:
```bash
>>>
Parse error: syntax error, unexpected 'namespace' (T_NAMESPACE) in D:\GIT\fork\PHP-CS-Fixer-upstream\test\test.php on line 12
Errors parsing D:\GIT\fork\PHP-CS-Fixer-upstream\test\test.php
<<<
>>><<<
```

`getOutput` provide me some info, `getErrorOutput` not.

Am I doing sth wrong @GrahamCampbell ?

**Comment by GrahamCampbell** [comment]
> Parse error: syntax error, unexpected 'namespace' (T_NAMESPACE) in D:\GIT\fork\PHP-CS-Fixer-upstream\test\test.php on line 12

That's from the error output, and is the only bit that's actually useful.

**Comment by keradus** [comment]
```php
    private function checkProcess(Process $process)
    {
        if (!$process->isSuccessful()) {
            echo sprintf(">>>%s<<<", $process->getErrorOutput());
            throw new LintingException($process->getOutput(), $process->getExitCode());
        }
    }
```

Gave me 
```
>>><<<
```

So no information at all.

-------------------------

Maybe there is a difference between OS?
```bash
λ php --version
PHP 5.6.8 (cli) (built: Apr 15 2015 15:07:09)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies

λ ver
Microsoft Windows [Version 10.0.10130]
```

**Comment by GrahamCampbell** [comment]
Maybe, yeh. I've only tested this on ubuntu 14.04.

**Comment by GrahamCampbell** [comment]
Does windows not have a standard error output?

**Comment by keradus** [comment]
It has.
Don't know why is the difference here.

**Comment by GrahamCampbell** [comment]
Maybe a php bug?

**Comment by GrahamCampbell** [comment]
@keradus How does this look now?

**Comment by keradus** [comment]
LGTM, I would just add a comment why we are doing that fallback.

---------------------------

Tiny curiosity below...

```bash
D:\GIT\fork\PHP-CS-Fixer ((detached from GrahamForks/linting))
λ php -v
PHP 5.6.8 (cli) (built: Apr 15 2015 15:07:09)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies

D:\GIT\fork\PHP-CS-Fixer ((detached from GrahamForks/linting))
λ php php-cs-fixer fix 1 -vvv
array(2) {
  ["errorOutput"]=>
  NULL
  ["output"]=>
  string(145) "
Parse error: syntax error, unexpected end of file in D:\GIT\fork\PHP-CS-Fixer\1\a.php on line 3
Errors parsing D:\GIT\fork\PHP-CS-Fixer\1\a.php
"
}
```

```bash
λ php -v
PHP 7.0.0-dev (cli) (built: May 28 2015 08:20:23)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v3.0.0-dev, Copyright (c) 1998-2015 Zend Technologies

D:\GIT\fork\PHP-CS-Fixer ((detached from GrahamForks/linting))
λ php php-cs-fixer fix 1 -vvv
array(2) {
  ["errorOutput"]=>
  string(101) "PHP Parse error:  syntax error, unexpected end of file in D:\GIT\fork\PHP-CS-Fixer\1\a.php on line 3
"
  ["output"]=>
  string(145) "
Parse error: syntax error, unexpected end of file in D:\GIT\fork\PHP-CS-Fixer\1\a.php on line 3
Errors parsing D:\GIT\fork\PHP-CS-Fixer\1\a.php
"
}
```

**Comment by GrahamCampbell** [comment]
Hmm. Can you try on a newer 5.6.x release?

**Comment by keradus** [comment]
```bash
D:\GIT\fork\PHP-CS-Fixer ((detached from GrahamForks/linting))
λ php -v
PHP 5.6.13 (cli) (built: Sep  3 2015 15:14:40)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies

D:\GIT\fork\PHP-CS-Fixer ((detached from GrahamForks/linting))
λ php php-cs-fixer fix 1 -vvv
array(2) {
  ["errorOutput"]=>
  NULL
  ["output"]=>
  string(145) "
Parse error: syntax error, unexpected end of file in D:\GIT\fork\PHP-CS-Fixer\1\a.php on line 3
Errors parsing D:\GIT\fork\PHP-CS-Fixer\1\a.php
"
}
```

**Comment by GrahamCampbell** [comment]
Hmmm, strange.

**Comment by GrahamCampbell** [comment]
Must just be the windows implementation in php being inconsistent with that of linux.

**Comment by GrahamCampbell** [comment]
Is this ok now?

**Comment by keradus** [comment]
:+1:, after Travis successful build I will merge this PR, thank you ;)

**Comment by keradus** [comment]
Thank you @GrahamCampbell.

**Comment by SpacePossum** [comment]
:+1:   thanks both :)

**Comment by keradus** [comment]
Almost a month :(
But sometimes one need to be picky to have it work on both unix and NT ;)

**Pull request closed without merging**
