### PR TITLE
GitlabReporter - fix report output

### PR DESCRIPTION
**Pull request by mjanser**
According to the [documentation](https://docs.gitlab.com/ee/user/project/merge_requests/code_quality.html#implementing-a-custom-tool) the location in the report should be a nested object.

### CODE REVIEW

**Comment by SpacePossum** [comment]
Hi and thanks for the PR!

Could you add `@see https://github.com/codeclimate/spec/blob/master/SPEC.md#data-types` to the header so it becomes:

```
/**
 * Generates a report according to gitlabs subset of codeclimate json files.
 *
 * @see https://github.com/codeclimate/spec/blob/master/SPEC.md#data-types
 *
 * @author Hans-Christian Otto <c.otto@suora.com>
 *
 * @internal
 */
```

after that I'm :+1:  for merging in this

**Comment by mjanser** [comment]
Sure, I added the reference to the documentation.

**Comment by keradus** [comment]
please, can you solve https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/4430 inside this PR?

**Comment by mjanser** [comment]
What should I do to solve #4430 inside this PR?

**Comment by SpacePossum** [comment]
Thank you @mjanser.

**Comment by keradus** [comment]
I really don't like that we are doing some unspecified changes to reporter, that is supposed to be under BC promise, but we don't specify what the promise is - we have reporter without spec :/

cc @SpacePossum @mjanser

**Comment by SpacePossum** [comment]
We've added a link to the spec: 
https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4563#issuecomment-539068372

This PR fixes a bug so the tool generates the report following that spec, I think that is inline with BC?

**Comment by keradus** [comment]
Link to a spec does not ensure that our implementation is following this spec.
validating outcome of our implementation with spec file (eg xsd) would.

**Comment by SpacePossum** [comment]
Good idea, let me know when you've time to help out with that :)   

Till than I will merge bug fixes because I think these are more important than test case completeness.

**Pull request merged**
