### PR TITLE
LinefeedFixer - Fix in a safe way

### PR DESCRIPTION
**Pull request by SpacePossum**
The fixer should not touch all line breaks.

### CODE REVIEW

**Comment by keradus** [comment]
then we need a second fixer (risky one) that will fix all the rest...

**Comment by SpacePossum** [comment]
>then we need a second fixer (risky one) that will fix all the rest...

I think this is a bug fix, so do not need such a fixer for BC reasons. Do you think someone really wants it?

**Comment by gharlan** [comment]
> Do you think someone really wants it?

I know at least one: me!

**Comment by keradus** [comment]
me too .actually most of community. the only thing is that it's risky.

we have exactly the same problem with trailing spaces. PSR requires to not have them in non-empty lines - even if it's part of string var. but then it modifies a content, so it's risky. but still, most of us wanna follow that.

**Comment by keradus** [comment]
It's bugfix but also shrinking functionality. Now one cannot fix linefeed inside var content. could you prepare the new fixer as well please? it's really important for us ! :)

**Comment by SpacePossum** [comment]
alrighty, would a config flag work as well or you really want a diff. fixer?

**Comment by keradus** [comment]
I was thinking about the config as well, but then you need to dynamically say if the fixer is risky or not depends on config.

**Comment by SpacePossum** [comment]
I'm kind of happy with this PR as is, but if we need another fixer please provide names for both fixers and I'll update this PR :)

**Comment by keradus** [comment]
as discussed it could be an option. the only thing to keep in mind is risky vs not risky... depends on used options

**Comment by keradus** [comment]
OK, I treat it as bugfix after thinking about it. Missing functionality is raised here: #2224

**Comment by keradus** [comment]
:+1:

**Comment by keradus** [comment]
Thank you @SpacePossum.

**Pull request merged**
