### PR TITLE
Add custom fixers documentation

### PR DESCRIPTION
**Pull request by julienfalque**

### CODE REVIEW

**Comment by SpacePossum** [comment]
I would prefer updating `doc/COOKBOOK-FIXERS.md` than the README, as the README is already very long and to detailed IMHO.

**Comment by julienfalque** [comment]
That's what I wanted at first but this guide is specific to contributing a new rule to PHP CS Fixer repository itself. I would keep both distinct.

Regarding the README being too long, maybe we can move forward with #3475?

**Comment by SpacePossum** [comment]
Having this in 3475 would be great!

I think 3475 is one of the PR's like the one about listing which rules are not in your current config, pretty good ideas and PR's but kind of stuck in the decision process in this project. Given that we go for months without releases I would suggest merging these in and tweak where needed later.

**Comment by julienfalque** [comment]
You mean to include the changes here into #3475 then merge it as-is?

**Comment by luiz-brandao-jr** [comment]
This is great, I was wondering if there was a way to create custom fixers locally. This is the answer.

**Comment by julienfalque** [comment]
Included in #3475.

**Pull request closed without merging**
