### PR TITLE
[2.5] Bugfix braces

### PR DESCRIPTION
**Pull request by mnabialek**
In new 2.5 version is problem (comparing to 2.3 version, maybe same was in 2.4) - when we have PHP file with content:

```
<?php

function test()
{
//    $closure = function ($callback) use ($query) {
//        doSomething();
//
//        return true;
//    };

    $a = 3;
}

```

BracesFixer will add indentation to line between **doSomething();** and **return true;** like this:

```
//        doSomething();
    //
//        return true;
```

what doesn't make sense in my opinion

### CODE REVIEW

**Comment by mnabialek** [comment]
I see the build failed, but those additional spaces were added just to make sure in case of additional spaces everything will work the same

**Comment by keradus** [comment]
affected line: 2.2
ref #2987

ping @rob006 , please take a look here

**Comment by rob006** [comment]
Fix looks valid to me.

@mnabialek Try put `'.'` after these trailing whitespaces.

**Comment by mnabialek** [comment]
@rob006 It's done

**Comment by rob006** [comment]
@mnabialek 
Like this:

```php
//    $closure = function ($callback) use ($query) {
//        doSomething();
//        '.'
//        return true;
//    };
```

This also needs to be merged into 2.2 line.

**Comment by mnabialek** [comment]
@rob006 So you want me to create one more PR into 2.2 branch?

**Comment by SpacePossum** [comment]
@mnabialek can retarget this PR to 2.2? If this change applies to 2.2 nicely it can be done during merging.

**Comment by keradus** [comment]
no it cant. 
@mnabialek target 2.2 please

**Comment by julienfalque** [comment]
Closing as replaced by #3002.

**Pull request closed without merging**
