### PR TITLE
Add TwoEmptyLinesFixer

### PR DESCRIPTION
**Pull request by denplatov**

### CODE REVIEW

**Comment by keradus** [comment]
question to community - would anyone use this rule ?

**Comment by GrahamCampbell** [comment]
👎  here

**Comment by SpacePossum** [comment]
sorry no interest, @denplatov do you know of a community which uses this style?

**Comment by denplatov** [comment]
This codestyle would be usefull for OWOX company

**Comment by keradus** [comment]
what is OWOX ?
if it's only company-related and nobody else would use it - it should be your company fixer. We call it custom fixer. just register it in your config file and that's all ;)

As there is no interest of community into this fixer for one month - closing.

If you would have any problems using custom fixers feel free to ask on our gitter chat !

**Pull request closed without merging**
