### PR TITLE
DuplicateSemicolonFixer - Remove duplicate semicolons even if there are comments between those

### PR DESCRIPTION
**Pull request by SpacePossum**
With this PR duplicate semicolons will be removed even if there are comment between the semicolons. 

~~WIP because it seems there might be a priority issue with the multiple empty/blank and trailing whitespace on empty line fixers.~~ added

### CODE REVIEW

**Comment by SpacePossum** [comment]
I've a hard time trying to figure out why the coverage is reported as being down.

**Comment by keradus** [comment]
> Coverage decreased (-0.01%) to 88.587%

This one? Ignore it, it's a measurement error.

**Comment by SpacePossum** [comment]
I see, the test first failed but now its green :)
Btw. I'm planning to add more logic to this fixer on the master line to remove semicolons after close braces of control structures as well. I think it would be better to rename it to UseSemiColonFixer than, any thoughts?

**Comment by keradus** [comment]
`;;` and `if (1) {};` are 2 different cases.
Add new fixer on 1.x line

**Comment by gharlan** [comment]
IMO it should be one fixer, that removes empty statements (`/*nothing*/;`).
It does not matter what kind of statement is before the empty statement (ending with `;` or `}`).
So I would name it `NoEmptyStatementFixer`.

**Comment by gharlan** [comment]
So I would also fix this case with the fixer:

```php
function foo() 
{
    ;
}

**Comment by keradus** [comment]
:+1: for @gharlan 
Please, create complex fixer for 1.x line and send PR to remove trivial one for 2.x line.

**Comment by keradus** [comment]
Thank you @SpacePossum.

**Pull request closed without merging**
