### PR TITLE
SingleLineCommentStyleFixer - fix 'strpos() expects parameter 1 to be string, boolean given'

### PR DESCRIPTION
**Pull request by keradus**
broken since #3318

### CODE REVIEW

**Comment by keradus** [comment]
cc @kubawerlos

**Comment by keradus** [comment]
I will keep your added test @SpacePossum , but keep in mind that we already did have this test in codebase - I caught this error as Travis nightly build crashed on it (nightly is not stable, different workers will bring different nightly version, that's why we don't see this crash usually)

**Comment by keradus** [comment]
Thank you @SpacePossum.

**Comment by SpacePossum** [comment]
oh I completely missed we already had an unstable test for the case! :)
thanks for the fix!

**Pull request closed without merging**
