### PR TITLE
FunctionDeclarationFixer - breaks code for comment cases

### PR DESCRIPTION
**Pull request by SpacePossum**

### CODE REVIEW

**Comment by keradus** [comment]
ufff, it's not on 2.1 line

**Comment by SpacePossum** [comment]
sadly this also effects the 2.x line, lets go debugging! :D

**Comment by keradus** [comment]
this is affecting 2.1? really ?

**Comment by SpacePossum** [comment]
https://travis-ci.org/FriendsOfPHP/PHP-CS-Fixer/jobs/212072776#L549  yes :(

**Comment by keradus** [comment]
so, if the bug is there, why closing this PR ?

**Comment by SpacePossum** [comment]
bug should be solved on 2.x line?

**Comment by keradus** [comment]
supported version:
2.1 for bugs
2.2 for non-bugs and bugs avilable only on 2.2

**Comment by SpacePossum** [comment]
it will do no harm to bug fix this on lowest maintained branch does it?

**Comment by keradus** [comment]
sure, but now the only bug report about it is... closed

**Comment by SpacePossum** [comment]
no worries, we've https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2607 now that proves the same bug but on lower line

**Comment by keradus** [comment]
cool :D

**Pull request closed without merging**
