### PR TITLE
[NewFixer] Introduction

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] extracts a configurable `NewFixer` from the existing `NewWithBracesFixer`

💁‍♂️ This can be useful for people who prefer to instantiate objects without braces when an object can be instantiated without arguments.

### CODE REVIEW

**Comment by keradus** [comment]
it increases the complexity. is there any well-recognized standard that this new rule would support?

**Comment by keradus** [comment]
(wrong button clicked)

**Comment by localheinz** [comment]
@keradus 

> it increases the complexity. is there any well-recognized standard that this new rule would support?

Not that I am aware of (but I haven't done the research). The idea stems from working on `phpunit/phpunit`: @sebastianbergmann likes to instantiate objects without braces when the constructor can be invoked without passing arguments to it.

**Comment by localheinz** [comment]
@keradus 

The "requirement" was added in https://github.com/php-fig/fig-standards/pull/675, in https://github.com/php-fig/fig-standards/commit/589b267f92224c81e9a2f84dcad668b73ac0a1f6 - but without explanation. I have not found corresponding research. 

It's arguable whether PSR-12 is relevant at all, but allowing to configure the fixer at least allows for different preferences - similar to the [`BracesFixer`](https://github.com/php-fig/fig-standards/commit/589b267f92224c81e9a2f84dcad668b73ac0a1f6), which also allows configuring the position of opening and closing braces in different places.

I understand that it adds more maintenance work, perhaps it's still worth adding (extracting)?

**Comment by localheinz** [comment]
For reference, see https://twitter.com/michaelcullumuk/status/1343636878893981700.

**Comment by keradus** [comment]
> I understand that it adds more maintenance work, perhaps it's still worth adding (extracting)?

To be honest I saw not using of parenthesis for `new Sth` *only* in PHPUnit. I would rather suggest PHPUnit to move towards ecosystem standard than making a tool to support that not-common rule.

We do not aim to have every possible rule. We aim to have rules that makes sense for community. If plenty of folks will be using sth, it's good to have it. If only single repo would use the rule, plus rule would be in opposition to PSR, we were rejecting such requests so far. Why to make different move here?

**Comment by localheinz** [comment]
@keradus 

According to https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-12-extended-coding-style-guide-meta.md#441-php-fig-representative-results, at least @bretterer and @Seldaek also voted against the requirement **`new` keyword usage, parenthesis required** .

Also, according to https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-12-extended-coding-style-guide-meta.md#442-general-non-representative-voters, 8.62% of non-representative voters voted agains the requirement.

CleanShot 2020-12-29 at 10 55 11

Of course, I accept your decision on the matter, though!

🤓

**Comment by keradus** [comment]
A standard is always a compromise. not everyone likes every single rule, but in general, decides to follow the overall standard for the unification of code produced by many developers in the same repo. And 90% is damn high when we talk abut compromises.

If there is a community that would follow the rule, I'm happy to welcome it, as always. But making the rule for one repo purpose is overkill for me - for that, we done custom tokens mechanism.

After saying that, I'm happy to be overvoted by @SpacePossum @localheinz @julienfalque @kubawerlos , your call folks

**Comment by keradus** [comment]
Or, maybe you want to introduce whole PHPUnit ruleset? that can be another argument for this change

**Comment by localheinz** [comment]
@keradus 

> Or, maybe you want to introduce whole PHPUnit ruleset? that can be another argument for this change

Sure, why not! 

👍

**Comment by localheinz** [comment]
@keradus 

I think we are good here, closing!

**Pull request closed without merging**
