### PR TITLE
NativeFunctionInvocationFixer: added sccp optimized functions

### PR DESCRIPTION
**Pull request by brainexe**
There are bunch of global function which can be replaced at compile time by their fix return value (if the input is stable/const) -> in the end this can remove function calls and jumps/dead code at runtime. 

[See this opcache optimizer code](https://github.com/php/php-src/blob/dd9b5c8/ext/opcache/Optimizer/sccp.c#L782)

**Example:**
```
function isSupported(): bool
{
    return \ini_get('opcache.enable_cli')
        && \version_compare('7.3.0', \phpversion(), '<=')
        && (\strpos(\php_uname('a'), 'Ubuntu') !== false)
    ;
}
```
-> 
```
T\isSupported: ; (lines=2, args=0, vars=0, tmps=1)
    ; (after optimizer)
L0 (15):    T0 = QM_ASSIGN bool(true)
L1 (15):    RETURN T0

```

This whole function will be optimized in one true/false already at compile time (even with or without preloader)....and the whole isSupported() call can also get inlined/replaced in some cases.

Other examples from running it on this repo: `return 'phar://' === \substr(__DIR__, 0, 7);` 

And additionally the first method call on a non imported global function needs one lookup - even it's then cached, still slight overhead which can be replaced on compile time already

### CODE REVIEW

**Comment by kubawerlos** [comment]
Hi @brainexe,

this looks promising, can you target `master` branch?

**Comment by SpacePossum** [comment]
Thanks for suggesting these improvements. Up till now we decided against these because of the performance gain did not outweigh the maintenance cost (especially the expected conflicts over the maintained branches).
We can reconsider though, but till than maybe not spend to much time on it.
cc @kubawerlos @keradus @julienfalque

**Comment by brainexe** [comment]
no problem, I don't rely on this PR - we can close this PR if there are too many nasty merge conflicts 
-> just find it now a bit inconsistent because many native optimized functions are important and others not...any with PHP 8 there are some new ones in the opcache-optimizer list anyway.

But we're still able to import *all* global function/consts (and even with "use function XXX" which might be cleaner) -> this gave us a small (but visible!) impact on our high traffic project.

**Comment by kubawerlos** [comment]
Are there any benchmarks to support this PR? What about creating a separate set of functions?

**Pull request closed without merging**
