### PR TITLE
Fix typo in ShortArraySyntaxFixer

### PR DESCRIPTION
**Pull request by tommygnr**

### CODE REVIEW

**Comment by tommygnr** [comment]
I'm not sure whether I need to recompile the readme. I haven't but can easily update the PR to do so.

**Comment by sstok** [comment]
If the description is changed you need recompile the readme :)
This is also pointed-out by Travis https://travis-ci.org/FriendsOfPHP/PHP-CS-Fixer/jobs/52056529#L178

**Comment by keradus** [comment]
Or by [CONTRIBUTING.md](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/1.5/CONTRIBUTING.md).
Please do it.

**Comment by keradus** [comment]
Thank you @tommygnr.

**Comment by keradus** [comment]
Regenerate it manually in d2355e2

**Pull request merged**
