### PR TITLE
fix 2 bugs in phpdoc_line_span

### LINKED ISSUE #4818: phpdoc_line_span breaks annotations containing slashes
#### The PHP version you are using (`$ php -v`):
PHP 7.2.19

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
PHP CS Fixer 2.16.1

#### The command you use to run PHP CS Fixer:
bin/php-cs-fixer fix MyClass.php

#### The configuration file you are using, if any:
```php
<?php

return PhpCsFixer\Config::create()
    ->setRules([
        '@PhpCsFixer' => true,
        'phpdoc_line_span' => ['property' => 'single'],
    ])
;
```

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
<?php

namespace App\MyNamespace;

use Symfony\Component\Validator\Constraints as Assert;

class MyClass
{
    /**
     * @Assert\File(mimeTypes={ "image/jpeg", "image/png" })
     */
    public $logoFileObject;
}
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
<?php

namespace App\MyNamespace;

class MyClass
{
    /** ng" }) */
    public $logoFileObject;
}
```

 * with the changes you expected instead:
```php
<?php

namespace App\MyNamespace;

use Symfony\Component\Validator\Constraints as Assert;

class MyClass
{
    /** @Assert\File(mimeTypes={ "image/jpeg", "image/png" }) */
    public $logoFileObject;
}
```

### LINKED ISSUE #4820: phpdoc_line_span breaks 2 line doc blocks
#### The PHP version you are using (`$ php -v`):
PHP 7.2.19

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
PHP CS Fixer 2.16.1

#### The command you use to run PHP CS Fixer:
bin/php-cs-fixer fix MyClass.php

#### The configuration file you are using, if any:
```php
<?php

return PhpCsFixer\Config::create()
    ->setRules([
        '@PhpCsFixer' => true,
        'phpdoc_line_span' => ['property' => 'single'],
    ])
;
```

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
<?php

class MyClass
{
    /** @var bool
     */
    public $variable1;

    /**
     * @var bool */
    public $variable2;
}
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
<?php

class MyClass
{
    /**  */
    public $variable1;

    /**  */
    public $variable2;
}
```

 * with the changes you expected instead:
```php
<?php

class MyClass
{
    /** @var bool */
    public $variable1;

    /** @var bool */
    public $variable2;
}
```

### PR DESCRIPTION
**Pull request by lmichelin**
Fixes #4818
Fixes #4820

### CODE REVIEW

**Comment by SpacePossum** [comment]
Good catch, thanks @lmichelin.

**Comment by SpacePossum** [comment]
btw., do we need the bug in `Line.php` on 2.15 as well?

**Comment by julienfalque** [comment]
I guess we could backport the changes into 2.15.x but, unless it actually fixes a bug there, it's not important IMO.

**Comment by SpacePossum** [comment]
thanks!

**Pull request merged**
