### PR TITLE
Added SingleLineClassDeclarationFixer

### LINKED ISSUE #1976: Single line class and method declaration fixers
Those fixers should be on the Symfony group according to the [coding standards](http://symfony.com/doc/current/contributing/code/standards.html#structure):

> * Declare the class inheritance and all the implemented interfaces on the same line as the class name;
> * Declare all the arguments on the same line as the method/function name, no matter how many arguments there are;

- [x] Class declaration: #1979 
- [x] Method declaration: #1980

### PR DESCRIPTION
**Pull request by Soullivaneuh**
Partially closes #1976

Question: Shall I add `trait` here too?

cc @javiereguiluz, you wrote the coding standard about that, what do you think?

I add some test cases. If you want to add more, please tell me! :+1:

### CODE REVIEW

**Comment by SpacePossum** [comment]
>Question: Shall I add trait here too?

:+1:  and why not interfaces as well?

maybe as configuration option of the `class_definition`-fixer?

**Comment by keradus** [comment]
and interfaces extending other interfaces?

**Comment by javiereguiluz** [comment]
@Soullivaneuh it looks very nice 👍  Thanks for working on this.

**Comment by Soullivaneuh** [comment]
> maybe as configuration option of the class_definition-fixer?

AFAIK, fixer options is only possible on 2.x.

Plus, I think it should not be on option.

It would be very weird to force inline declaration for classes, but not for traits, right?

@javiereguiluz Do we agree that this Symfony rules also applies for traits?

> and interfaces extending other interfaces?

Good catch! Will work on it. :+1:

**Comment by javiereguiluz** [comment]
@Soullivaneuh I guess it applies to traits too to be consistent.

**Comment by SpacePossum** [comment]
>AFAIK, fixer options is only possible on 2.x.

correct

>Plus, I think it should not be on option.

fair enough :)

>It would be very weird to force inline declaration for classes, but not for traits, right?

class_definition handles classes, interfaces and traits, would be great if your new would do that as well

**Comment by Soullivaneuh** [comment]
> class_definition handles classes, interfaces and traits, would be great if your new would do that as well

Oh, so rename the fixer. Sounds good. :+1:

**Comment by keradus** [comment]
> > AFAIK, fixer options is only possible on 2.x.
>
> correct

BTW, it was introduces to 2.x line as part of interface.
On 1.x line we already have configurations for few fixers, but not in part of interface and called statically, like header fixer

**Comment by Soullivaneuh** [comment]
All fixed, please review! :+1:

**Comment by Soullivaneuh** [comment]
@keradus Could you please explain this failing travis job? https://travis-ci.org/FriendsOfPHP/PHP-CS-Fixer/jobs/136717844

**Comment by SpacePossum** [comment]
that is because of typo in your test;
https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1979/files#diff-2cac64058aaace5a8ec0b1128005b97cR39
`implement` should be `implements`

On PHP7 (the version that is failing on Travis) the tests are linted. You can lint the test case on your machine as well if you want to prevent this from happening.

**Comment by Soullivaneuh** [comment]
Thanks @SpacePossum, should be OK now.

**Comment by SpacePossum** [comment]
I would still like to see the tests made in this PR moved to the `ClassDefinitionFixerTest`,
and based on config call a diff method here;
https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/1.12/Symfony/CS/Fixer/PSR2/ClassDefinitionFixer.php#L143

The reason is basic DRY, the new fixer proposal has a lot in common with the current;
- finding candidates (should be the same)
- fixing white space before the classy token (should be the same)
- fixing white space after the classy token for `extends` (should be the same) and;
- fixing white space after the classy token for `implements` (should be the same)

So the only diff. is removing line breaks if there are any in a list of implementing interfaces.

**Comment by keradus** [comment]
@SpacePossum you say that test classes are similar, are Fixer classes too ?

**Comment by keradus** [comment]
Also, I still (https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1979#issuecomment-225193893) think it should be one fixer...

**Comment by Soullivaneuh** [comment]
@SpacePossum @keradus So if I understand well, the fixer should be merge onto `class_definition`

Is that right?

And what about #1980 in this case?

**Comment by SpacePossum** [comment]
> So if I understand well, the fixer should be merge onto class_definition

I would prefer that yes :)
The link I provided shows where to hook:
```php
 $index = $this->ensureOnNewLine($tokens, $index);
```
->
```php
if (some config) {
     $index = $this->ensureOnSameine($tokens, $index); // new
} else {
     $index = $this->ensureOnNewLine($tokens, $index);
}

```

>And what about #1980 in this case?

lets discuss 1980 over there ;)

**Comment by keradus** [comment]
ping @Soullivaneuh

**Comment by Soullivaneuh** [comment]
Same opinion as https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1980#issuecomment-230393449 ATM.

**Comment by keradus** [comment]
any news here ?

**Comment by keradus** [comment]
Closing due to merge of #2155

**Pull request closed without merging**
