### PR TITLE
AbstractIntegratationTest - fix linting test cases

### PR DESCRIPTION
**Pull request by gharlan**
https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1538#issuecomment-166161928

### CODE REVIEW

**Comment by keradus** [comment]
:+1:

**Comment by GrahamCampbell** [comment]
:+1:

**Comment by SpacePossum** [comment]
:+1:

**Comment by keradus** [comment]
I want to merge it at night but I fell asleep waiting for Travis..

**Comment by SpacePossum** [comment]
>I want to merge it at night but I fell asleep waiting for Travis..

ha, oh man just a few more days until the holidays, hold in there!

**Comment by keradus** [comment]
Yes, holidays, finally... finally I will be able to push few things for CS Fixer!

**Comment by keradus** [comment]
Thank you @gharlan.

**Comment by SpacePossum** [comment]
thanks @gharlan & @keradus  : D

**Pull request merged**
