### PR TITLE
ClassKeywordRemoveFixer: Add support of namespaces

### LINKED ISSUE #4555: class_keyword_remove doesn't convert to fully qualified class names
#### The PHP version you are using (`$ php -v`):
=> `7.2.11`

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> `2.15.3 Europe Round`

#### The command you use to run PHP CS Fixer:
=> `php-cs-fixer fix test.php --rules=class_keyword_remove`

#### The configuration file you are using, if any:
=>  None in this reduced test case.

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
<?php

namespace TestNamespace;

class TestClass
{
    public function test($object)
    {
        if (is_a($object, AnotherTestClass::class)) {
            return 'something';
        } else {
            return 'something else';
        }
    }
}
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
<?php

namespace TestNamespace;

class TestClass
{
    public function test($object)
    {
        if (is_a($object, 'AnotherTestClass')) {
            return 'something';
        } else {
            return 'something else';
        }
    }
}
```

 * with the changes you expected instead:
```php
<?php

namespace TestNamespace;

class TestClass
{
    public function test($object)
    {
        if (is_a($object, 'TestNamespace\AnotherTestClass')) {
            return 'something';
        } else {
            return 'something else';
        }
    }
}
```

### PR DESCRIPTION
**Pull request by yassine-ah**
Fixes #4555

The modification is about validating 2 test cases:

**Case 1**:
Before:
```php
<?php
namespace Foo\Bar;
var_dump(Baz::class);
```

After:
```php
<?php
namespace Foo\Bar;
var_dump('Foo\Bar\Baz');
```

**Case 2**:

Before:
```php
<?php
namespace Space1 {
  var_dump(Baz::class);
}

namespace Space2 {
  var_dump(Baz::class);
}
```
After:
```php
<?php
namespace Space1 {
  var_dump('Space1\Baz');
}

namespace Space2 {
  var_dump('Space2\Baz');
}
```

### CODE REVIEW

**Comment by kubawerlos** [comment]
https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4601 covers more cases.

**Comment by yassine-ah** [comment]
@kubawerlos I didn't know that you are working on it until I prepared the PR

I tested your PR and didn't find a cases where it fail 👍 
An example:
```php
[
  '<?php
  namespace Quux {
    use Baz\\Qux;
    var_dump(\'Baz\\Qux\');
  }
  namespace Qux2 {
    use Baz\\Quux;
    var_dump(\'Baz\\Quux\');
  }
  ',
  '<?php
  namespace Quux {
    use Baz\\Qux;
    var_dump(Qux::class);
  }
  namespace Qux2 {
    use Baz\\Quux;
    var_dump(Quux::class);
  }
  ',
]
```

But I couldn't find a case where my commit fail, could you point it out so I can learn from my mistakes 😄

**Comment by kubawerlos** [comment]
@yassine-ah this one:
```
            [
                "<?php
                namespace Foo;
                var_dump('Foo\\Bar\\Baz');
                ",
                '<?php
                namespace Foo;
                var_dump(Bar\\Baz::class);
                ',
            ],
```

and also the long one I've extended in my PR

**Comment by yassine-ah** [comment]
> 
> 
> @yassine-ah this one:
> 
> ```
>             [
>                 "<?php
>                 namespace Foo;
>                 var_dump('Foo\\Bar\\Baz');
>                 ",
>                 '<?php
>                 namespace Foo;
>                 var_dump(Bar\\Baz::class);
>                 ',
>             ],
> ```
> 
> and also the long one I've extended in my PR

Thank you for pointing them, I added the test cases mentionned to my PR 👍 and now everything is working fine :)

**Comment by keradus** [comment]
@yassine-ah , @kubawerlos 
i got lost folks. which PR is supposed to be merged, #4604 or #4601 ? can you please prepare common solution together and close one of the PRs ?

**Comment by kubawerlos** [comment]
@keradus me too, but got it sorted out.

#4601 contains a test case - the bottom one added there - that is failing on #4604

For the class `ClassKeywordRemoveFixer`:

| PR | changes | Cyclomatic complexity (original 31) |
|----|----|----|
| #4601 | -14 lines (26 additions & 40 deletions) | 28 |
| #4604 | +16 lines (16 additions) | 36 |

**Comment by yassine-ah** [comment]
@kubawerlos this already updated and added all the testcases, but yes you can merge anyone of them.
> #4601 contains a test case - the bottom one added there - that is failing on #4604

in #4604, only adding the below code solve the problem, and we can impliment it to a private function as an improvement :

```php
        if (false === $classImport) {
            $namespaces = (new NamespacesAnalyzer())->getDeclarations($tokens);
            foreach ($namespaces as $namespace) {
                if ('' === $namespace->getFullName()) {
                    continue;
                }
                if ($classIndex < $namespace->getScopeStartIndex() || $classIndex > $namespace->getScopeEndIndex()) {
                    continue;
                }
                $classString = $namespace->getFullName().'\\'.$classString;
            }
        }
```

**Comment by kubawerlos** [comment]
@yassine-ah 
> this already updated and added all the testcases

no, last test added in #4601 still fails

**Comment by SpacePossum** [comment]
Hope you don't mind @yassine-ah but as you stated `we can merge anyone of them` I assume you don't, closing in favor of https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4601 , mainly as the CI is happy there.

Thanks both @yassine-ah and @kubawerlos for all the work, much appreciated! :+1:

**Pull request closed without merging**
