### PR TITLE
[2.15] Switched to non-deprecated composer normalize and updated dev-tools

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Fixes a bunch of warnings in the CI.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Hmmm. It's still running old code...

image

**Comment by GrahamCampbell** [comment]
Ready to merge now. 🚀

**Comment by GrahamCampbell** [comment]
Test failure is unrelated.

**Comment by GrahamCampbell** [comment]
The test failure is unrelated, and I have submitted a separate PR to address the failing test: https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4857.

**Comment by keradus** [comment]
Thank you for your effort on working on this.
I have decided to merge #4715 instead, which brings very similar change and was raised earlier

**Comment by GrahamCampbell** [comment]
That other PR doesn't actually fix all the warnings though?

**Pull request closed without merging**
