### PR TITLE
Fixing example and description for GeneralPhpdocAnnotationRemoveFixer

### PR DESCRIPTION
**Pull request by kubawerlos**
The working version is [without](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/.php_cs.dist#L22) "@" sign.

### CODE REVIEW

**Comment by julienfalque** [comment]
Changes are good but should be done in 2.2, please rebase your branch onto 2.2 and update the PR.

**Comment by kubawerlos** [comment]
I don't know how to change source branch from master to 2.2 so I made new PR: https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2743

**Comment by keradus** [comment]
for future:
git rebase + https://github.com/blog/2224-change-the-base-branch-of-a-pull-request

**Comment by kubawerlos** [comment]
@keradus I know how to change target branch, don't know how to change source one, though.

**Comment by julienfalque** [comment]
You can do that with a rebase:

```
$ git rebase --interactive --onto 2.2 <your-first-commit>
```

**Comment by julienfalque** [comment]
You can do that with a rebase:

```
$ git fetch --all
$ git rebase --interactive --onto origin/2.2 HEAD~#
```

This will replay the last `#` commits on top of `origin/2.2` branch.

See [Github article about rebase](https://help.github.com/articles/about-git-rebase/) for details.

**Pull request closed without merging**
