### PR TITLE
NoEmptyCommentFixer - Fix typo

### PR DESCRIPTION
**Pull request by fritz-c**

### CODE REVIEW

**Comment by SpacePossum** [comment]
Thanks for PR'ing this typo!
The README.rst is generated so the fix should be done within the fixer itself as well.
https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/src/Fixer/Comment/NoEmptyCommentFixer.php#L70
Let me know if you've the time to do this, otherwise I can pick it up later.

**Comment by fritz-c** [comment]
Yeah, I can get that spot tomorrow (Japan time).

**Comment by fritz-c** [comment]
Updated.

**Comment by SpacePossum** [comment]
:+1: thanks :)

**Comment by keradus** [comment]
Thank you @fritz-c.

**Pull request closed without merging**
