### PR TITLE
Fixer - do not lint invalid files over and over again

### LINKED ISSUE #1290: Cache Files That Failed Linting
Would it not make sense to skip linting files that haven't changed since the last run and failed linting the last time?

### PR DESCRIPTION
**Pull request by keradus**
Fixes #1290

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
We still want to show that it failed linting though.

**Comment by GrahamCampbell** [comment]
Doing this suppresses that error, and we need that error.

**Comment by keradus** [comment]
Do we?

> We still want to show that it failed linting though.

If we want to cache it then we will show that info on first linting and do not show that info again - because we cache that file and not lint it again, so no linting failor occurs again.

**Comment by GrahamCampbell** [comment]
I really don't want that behaviour. I want php-cs-fixer to point out bad files each time so I can fix them.

**Comment by GrahamCampbell** [comment]
Someone might not notice the first time and then php-cs-fixer would just hide their error.

**Comment by GrahamCampbell** [comment]
If this change went through, I'd have to fork the project and revert it.

**Comment by keradus** [comment]
First, please just send one post instead of posting one post per each sentence ;)
Second, you could always do some fork when you want.
Finally, I was just sending a PR for change that was wanted by... you.

I do not need this change myself - I simply do not have invalid files on my repos.
And I can totally agree with your argumentation, but then see this change pointless.
Closing this PR.

**Pull request closed without merging**
