### PR TITLE
Disallow to disable linter

### PR DESCRIPTION
**Pull request by keradus**
Disallow to disable linter, as it's required by 2.x tokenizer and transformer

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
It would be cool to have a way to disable the fast linting though. :)

**Comment by GrahamCampbell** [comment]
I mean, it would make no difference for me, just thinking about other people using the tool. :)

**Comment by keradus** [comment]
it's outside of scope of this PR

**Comment by SpacePossum** [comment]
please fix the project itself :)

:+1: for the idea

**Pull request closed without merging**
