### PR TITLE
Fix Circle CI build

### PR DESCRIPTION
**Pull request by julienfalque**

### CODE REVIEW

**Comment by kubawerlos** [comment]
Can we bump PHP version?

**Comment by julienfalque** [comment]
Sure thing :)

**Comment by kubawerlos** [comment]
One more thing: can we bump [xcode](https://circleci.com/docs/2.0/testing-ios/#supported-xcode-versions), so maybe Python 3 will be installed with it, so we don't have to remove Python 2 and have Python 3 installed with PHP?

**Comment by julienfalque** [comment]
Done. Version `11.3.0` still includes Python 2. It also includes PHP 7.2 and 7.3 but not PHP 7.4 so we still need to install it manually.

**Comment by kubawerlos** [comment]
Thank you @julienfalque.

**Pull request merged**
