### PR TITLE
Support PHPUnit 7

### PR DESCRIPTION
**Pull request by keradus**

### CODE REVIEW

**Comment by SpacePossum** [comment]
rebased, conflict resolved and forced pushed
this should also trigger the CI again

**Comment by keradus** [comment]
not sure why fabbot is asking to use long array syntax... cc @julienfalque

**Comment by julienfalque** [comment]
I'm getting a blank page when trying to see fabbot reports for your latest commits.

**Comment by keradus** [comment]
:|

**Pull request closed without merging**
