### PR TITLE
Rename namespace "Symfony\CS" to "PhpCsFixer"

### PR DESCRIPTION
**Pull request by gharlan**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Cs is incorrect spelling thoug?

**Comment by gharlan** [comment]
Then `Php` is incorrect, too.
Isn't it a matter of taste?

**Comment by GrahamCampbell** [comment]
> Then Php is incorrect, too.

Yes, it is.

**Comment by gharlan** [comment]
But it is not the symfony style, see `HttpKernel`..

**Comment by GrahamCampbell** [comment]
> But it is not the symfony style, see HttpKernel..

So? Isn't the point of the PR to remove the symfonyness?

**Comment by gharlan** [comment]
No, the project will still follow symfony coding standards..

**Comment by SpacePossum** [comment]
LGTM :)
:+1:

**Comment by gharlan** [comment]
Any other thoughts?

**Comment by keradus** [comment]
Please rebase and good to go

**Comment by gharlan** [comment]
done

**Comment by SpacePossum** [comment]
:+1:  :package:

**Comment by keradus** [comment]
:+1:

**Comment by GrahamCampbell** [comment]
You know I'm :-1:, lol.

**Comment by keradus** [comment]
it's good to have consistent naming between package name and namespace ;)

**Comment by GrahamCampbell** [comment]
Yes, and this name isn't consistent due to the capitalization.

**Comment by keradus** [comment]
It is. `php-cs-fixer` is `PhpCsFixer`.
About shorthands - HTTP in camel case is Http, like `getHttpResponse` etc.

**Comment by GrahamCampbell** [comment]
How come the repo is named PHP-CS-Fixer and not Php-Cs-Fixer then?

**Comment by keradus** [comment]
repo name is case insensitive ;)

**Comment by keradus** [comment]
Thank you @gharlan.

**Pull request merged**
