### PR TITLE
Update LICENSE

### PR DESCRIPTION
**Pull request by exussum12**

### CODE REVIEW

**Comment by SpacePossum** [comment]
Hi and thanks for you PR!

It seems the current listing layout was done on purpose by @keradus so I don't think we need to change it :)

**Comment by exussum12** [comment]
The spacing makes this not get picked up correctly. I re made the PR as I targeted 3. If you merge this pr github will correctly identify the licence

**Comment by exussum12** [comment]
See https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5716

**Comment by SpacePossum** [comment]
sorry just saw it :+1:

**Comment by SpacePossum** [comment]
Thank you @exussum12.

**Pull request merged**
